### ISSUE TITLE
Moto G 4G LTE kernel source

### ISSUE THREAD

**Issue by rabih** [MotorolaMobilityLLC/kernel-msm#1]
Where exactly is the kernel source for the Peregrine variant of the moto G?

**Comment by savoca** [comment]
If it's not here or on sourceforge then they just haven't pushed it yet. :)

http://sourceforge.net/projects/motog.motorola/files/

**Comment by gu1dry** [comment]
The issue is the Moto G LTE has been available since June 3 (in the US, and I've have had two of them since June 11) and with their lack of releasing the kernel source for it thus far is a direct violation of the GPL.

**Comment by savoca** [comment]
Eh, much worse has been done by others.

**Comment by dhacker29** [comment]
I spoke with the moto employee that is handing it and he said he has been on vacation for 2 weeks but it should be available soon.

**Comment by rabih** [comment]
Thanks for the info.

**Comment by faux123** [comment]
Moto has been very good with kernel source releases. Things sometimes happen. I'm sure good things will come to those who wait.

**Comment by tags07** [comment]
Thank you @dhacker29 and @faux123 for posting responses. Really appreciate it.

As you know we are posting the entire branch and all commits leading up to the latest shipping release. I don't think any OEM post their development tree on github or on any other version control platform. 

The good thing(for developers) is that you get all the intermediate commits and history to make the porting/integration work easy.  We have posted all commits leading upto 4.4.2 on all our products. Many of them share the same kernel/OSS components. We are slacking behind a bit on applying dummy labels on commits for all the shipping release tags. We probably need to do a better job in communicating which tag corresponds to which product release to avoid confusion.

We are getting ready to post all the commits thru :
KXA21.12-L1.22
KXB21.14-L1.32

This should bring all the products up to 4.4.3.. I am following up with teams to make sure it also covers Moto G LTE/Moto E. If there are differences, we'll post the delta. 

We'll start working on 4.4.4 after all the rollouts are complete starting next week.

thanks,
Gopi

**Comment by nothize** [comment]
Thanks Gopi, I'm looking forward to the kernel source of Moto G for the 4.4.4 update. I'm eager to see whether the battery abrupt drop fix is being included and how.

**Comment by DooMLoRD** [comment]
Sony Developers (@sonyxperiadev) do post all kernel sources with commit
history:

https://github.com/sonyxperiadev/kernel-copyleft

**Comment by hurtsky** [comment]
so @tags07 moto G falcon also gonna got update of 4.4.4?

**Comment by PRJosh** [comment]
@DooMLoRD although sony started to push to github, they release each release as a squashed commit with no real history. Although this is much easier then the old zip's they provided it isn't like motorola that actually provides a detailed history of commits that people can follow easily

**Comment by Black-Light** [comment]
@hurtsky Yep I also believe they are both getting 5.0 (L) nice to see you here after i moved from the galaxy W

Source on 4.4.4: https://forums.motorola.com/posts/817e1b24cb
Don't think there is an 'official' confirmation on 5.0 however someone from motorola support supposedly confirmed it.

**Comment by hurtsky** [comment]
@Black-Light  yeah.. i hope so... moto G so smooth for my usage.. if getting L, that really awesome

**Comment by Black-Light** [comment]
@tags07 My Moto G 4G/LTE (XT1039) is KXB21.14-L1.31 not KXB21.14-L1.32 is their going to be 4.4.4 source for this as well? Looking forward to the SD card fix

**Comment by tags07** [comment]
@Black-Light since we are posting all commits leading to L1.32 ...you will get L1.31.

**Comment by iyedb** [comment]
Hi all, it's probably not the best place to ask about so sorry for the inconvenience:
I have a moto G device falcon with the following information
![2014-12-05 00 37 13](https://cloud.githubusercontent.com/assets/643030/5309094/95f332b8-7c1f-11e4-88c4-9647e536b7c5.png)
I have tried to lookup the commit hash **b89c9dd** of my above kernel version string but it does not exist in the commit log. Is this normal?
How can I retrieve the exact kernel tree that was used to build the kernel that ships with my device.
Thanks a lot.

**Comment by savoca** [comment]
That's probably internal only - as I'm pretty sure they doctor up the tree they push to GitHub - isn't necessarily a bad thing, (for example high brightness mode exists here but not on any official kernel from Moto on titan) but still can be a bit confusing.

**Comment by iyedb** [comment]
Oh that's unfortunate. Thank you for the reply.
Anyway I have noticed that the build number matches a tag on the repo. Can I use that tag to checkout the kernel instead of the hash?

**Comment by iyedb** [comment]
Oh that's unfortunate. Thank you for the reply.
Anyway I have noticed that the build number matches a tag on the repo. Can I use that tag to checkout the kernel instead of the hash?

**Comment by tags07** [comment]
I'll check and let you know..busy at the moment.. What we post is what we ship..sometimes we apply filters on the log comments but nothing changes in the source.. use the tag.

**Comment by iyedb** [comment]
Ok I will use the tag- thanks - But it would nice to know what happened to the hash.

**Comment by jhrycay** [comment]
The filters strip out internal meta-data from the commit message which will alter the sha1. The source code is the same.

That commit you are referencing is indeed the same commit pointed to by KXB21.14-L1.40: https://github.com/MotorolaMobilityLLC/kernel-msm/commit/27b1ece76d1f234079d7016cae50a6422b72beb1

**Comment by savoca** [comment]
In that case, can you at least tag KXB21.85-17 for titan? It would be great as a point of reference since XT1064 never got that OTA with high brightness mode - unless it's just me and my phone's derped out.

**Comment by ccfries** [comment]
I don't see that tag on github, but KXB21.85-17 lines up with a commit a
few away from KXB21.85-24 (and is missing HBM)

Looking at:
https://github.com/MotorolaMobilityLLC/kernel-msm/commits/MMI-KXB21.85-24

KXB21.85-17 is 6ebf73a2c07307581407be94a36ce048541b6499
"arm/dts: batterydata: 0C for ED30 Sony"

hope that helps.

**Comment by savoca** [comment]
Perfect, thank you!

**Comment by iyedb** [comment]
Got it. Thank you all for the replies.
