### ISSUE TITLE
Missing F2FS source

### ISSUE THREAD

**Issue by luk1337** [MotorolaMobilityLLC/kernel-msm#10]
The "fs/f2fs" folder is linked to "../../motorola/kernel/fs/f2fs" which isn't pushed to git, can someone from Moto push it?

**Comment by luk1337** [comment]
it got pushed

**Comment by luca020400** [comment]
Thanks ;)

**Comment by antdking** [comment]
MotorolaMobilityLLC/motorola-kernel#1
