### ISSUE TITLE
Moto Z Play (addison) kernel source, NPN25.137-15-2

### ISSUE THREAD

**Issue by Stark2x** [MotorolaMobilityLLC/kernel-msm#100]
Could you please release the kernel source code for the Nougat release NPN25.137-15-2 of the Moto Z Play (addison)? 

Thanks in advance @charleseb.

**Comment by charleseb** [comment]
Hi @Stark2x,

This version is in our pipeline and will be released in a few days.

Thanks,
Charles

**Comment by flashallthetime** [comment]
a few days, it's been 5 days!!!!!!

**Comment by charleseb** [comment]
Hi @flashallthetime,

We have a process to follow before to release a version to Github.
I'm still working to release this version.

Thanks,
Charles

**Comment by charleseb** [comment]
MMI-NPN25.137-15 released.

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPN25.137-15

**Comment by Stark2x** [comment]
Thanks for the quick release @charleseb
