### ISSUE TITLE
Moto G4 Plus compile error : 'dsi_otm1906c_1080p_cmd', not found

### ISSUE THREAD

**Issue by saurabhsamanta** [MotorolaMobilityLLC/kernel-msm#105]
I am getting the following error when I am trying to compile the MOTO G4 Plus source code:

 DTC     arch/arm/boot/dts/qcom/../msm8936-mtp.dtb
  DTC     arch/arm/boot/dts/qcom/../msm8936-mtp-smb1360.dtb
  DTC     arch/arm/boot/dts/qcom/../msm8936-mtp-wcd9306.dtb
  DTC     arch/arm/boot/dts/qcom/../msm8952-sim.dtb
  DTC     arch/arm/boot/dts/qcom/../msm8952-rumi.dtb
  DTC     arch/arm/boot/dts/qcom/../msm8952-qrd-skum.dtb
Error: arch/arm/boot/dts/qcom/msm8952-qrd-skum.dtsi:358.2-3 label or path, 'dsi_otm1906c_1080p_cmd', not found
FATAL ERROR: Syntax error parsing input tree
/home/trustzone/and/kernel-msm-MMI-MPJ24.139/arch/arm/boot/dts/qcom/Makefile:346: recipe for target 'arch/arm/boot/dts/qcom/../msm8952-qrd-skum.dtb' failed
make[1]: *** [arch/arm/boot/dts/qcom/../msm8952-qrd-skum.dtb] Error 1
/home/trustzone/and/kernel-msm-MMI-MPJ24.139/arch/arm/Makefile:305: recipe for target 'dtbs' failed

Source Code Compilation of MOTO G4 Plus.
Code: MMI-MPJ24.139
Toolchain: arm-eabi-4.8 (https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/)
Config: msm8916_defconfig

**Comment by Vachounet** [comment]
Seems you forget to append the content of arch/arm/configs/ext_config/moto-msm8916.config to msm8916_defconfig.
(so missing this flag : CONFIG_MMI_DEVICE_DTBS=y)

**Comment by saurabhsamanta** [comment]
Thanks alot @Vachounet ... It worked for me.
