### ISSUE TITLE
Kernel Source Code for Moto G5 Plus (India)

### ISSUE THREAD

**Issue by HostZero** [MotorolaMobilityLLC/kernel-msm#107]
Codename: Potter
Build.No: NPN25.137-15
Android Version: 7.0

Hope you will release kernel source as soon as possible. @charleseb @tags07

**Comment by tags07** [comment]
Fyi, I am no longer with Mot :)

**Comment by HostZero** [comment]
Sad to hear. Moto and developers will miss you.

**Comment by chenyt9** [comment]
Hi all,

I've just released version MMI-NPN25.137-33 related to Potter (Nougat).
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPN25.137-33

Thanks.
Yuting
