### ISSUE TITLE
Error while compiling wlan driver for MMI-MPJ24.139-23.4 For Moto G4

### ISSUE THREAD

**Issue by dhanush-raj** [MotorolaMobilityLLC/kernel-msm#110]
@charleseb @chenyt9 
build instructions used from the following link.
[https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-MPJ24.139-23.4.txt](url)
Compiling my wlan driver from vendor-qcom-opensource-wlan-prima from the following link.
[https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-wlan-prima/](url)

/my_top_dir/vendor/qcom/opensource/wlan/prima/CORE/HDD/src/wlan_hdd_main.c: In function 'hdd_request_firmware':
/my_top_dir/vendor/qcom/opensource/wlan/prima/CORE/HDD/src/wlan_hdd_main.c:5931:9: error: implicit declaration of function 'wcnss_get_wlan_nv_name' [-Werror=implicit-function-declaration]
         if (wcnss_get_wlan_nv_name(sysfs_fname) != 0) {
         ^
cc1: some warnings being treated as errors
/my_top_dir/kernel/scripts/Makefile.build:308: recipe for target '/my_top_dir/vendor/qcom/opensource/wlan/prima/CORE/HDD/src/wlan_hdd_main.o' failed
make[3]: *** [/my_top_dir/vendor/qcom/opensource/wlan/prima/CORE/HDD/src/wlan_hdd_main.o] Error 1
/my_top_dir/kernel/Makefile:1260: recipe for target '_module_/my_top_dir/vendor/qcom/opensource/wlan/prima' failed
make[2]: *** [_module_/my_top_dir/vendor/qcom/opensource/wlan/prima] Error 2
Makefile:135: recipe for target 'sub-make' failed
make[1]: *** [sub-make] Error 2
Makefile:26: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/my_top_dir/out/target/product/generic/obj/kernel'

Thanks in advance,sir...

**Comment by charleseb** [comment]
Hi @dhanush-raj,

I've just reproduced this 'how to' in a environment completely without dependencies.

Make sure you are getting all variables set correctly ($my_top_dir and  $kernel_out_dir for example) 
and the code in perl is ok when executing:
cat kernel/arch/arm/configs/msm8916-perf_defconfig > $kernel_out_dir/mapphone_defconfig; cat kernel/arch/arm/configs/ext_config/moto-msm8916.config >> $kernel_out_dir/mapphone_defconfig

And before to compile [wlan/prima]([https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-wlan-prima/releases/tag/MMI-MPJ24.139-23.4]), make sure to get the code, unzip and rename that folder and move it to the right place ($my_top_dir/vendor/qcom/opensource/wlan/prima).

----
Thanks,
Charles
