### ISSUE TITLE
GPL source request for clark NPH25.200-15

### ISSUE THREAD

**Issue by HashBang173** [MotorolaMobilityLLC/kernel-msm#111]
There is currently no GPL source available for clark on Nougat, build number NPH25.200-15

**Comment by invisiblek** [comment]
http://i.imgur.com/8ARsWpJ.gifv

**Comment by charleseb** [comment]
Hi all,
Version released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPH25.200-15
