### ISSUE TITLE
Moto Z2 Play (albus) - NPS26.74-16 Kernel Sources 

### ISSUE THREAD

**Issue by Vachounet** [MotorolaMobilityLLC/kernel-msm#114]
Any chance to get this released ?
As well as the corresponding dtbTool if needed. (Would be great if this could be open source too)

Codename: albus
Build.No: NPS26.74-16-1
Android Version: 7.1.1

@charleseb :)

**Comment by Vachounet** [comment]
Maybe we could have more luck with NPS26.74-36 one ? :D

**Comment by erfanoabdi** [comment]
NPS26.74-41 and NPS26.118-19 OTA released BTW :)

**Comment by Vachounet** [comment]
Don't expect too much :p, if at least we could have initial sources....

**Comment by eexit** [comment]
Hello, 

I'm also looking for NPS26.74-36/NPS26.74-38.

Any update on this?

Thanks!

**Comment by charleseb** [comment]
Version MMI-NPS26.74-43 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPS26.74-43
