### ISSUE TITLE
Moto Z Play (Addison) NPN26.107 Android 7.1.1 Kernel Sources

### ISSUE THREAD

**Issue by sameer** [MotorolaMobilityLLC/kernel-msm#118]
Hi @charleseb ,

Could you please push the 7.1.1 kernel source for Addison used under RETUS?

Thank you

**Comment by charleseb** [comment]
Version MMI-NPN26.107 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPN26.107
