### ISSUE TITLE
Moto X Force (kinzie) NPK25.200-12 kernel sources

### ISSUE THREAD

**Issue by betaxab** [MotorolaMobilityLLC/kernel-msm#119]
Could you please release this kernel sources?

Model: Moto X Force
Android version: 7.0
Build number: NPK25.200-12

@charleseb

Thank you. 😄

**Comment by charleseb** [comment]
Hi @betaxab,

I'm working to release this version soon.

Thanks,
Charles

**Comment by charleseb** [comment]
Version MMI-NPN26.107 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPN26.107

**Comment by charleseb** [comment]
Version MMI-NPK25.200-12 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPK25.200-12
