### ISSUE TITLE
Kernel source for falcon?

### ISSUE THREAD

**Issue by ShiroiKarasu6991** [MotorolaMobilityLLC/kernel-msm#12]
When will you release the kernel source for the Moto G 2013 (falcon) running Android Lollipop?

Firmware build versions are LXB22.46-xx

**Comment by rabih** [comment]
My guess is that they are here: https://github.com/MotorolaMobilityLLC/kernel-msm/tree/lollipop%E2%80%945.0.2-release

**Comment by ShiroiKarasu6991** [comment]
Maybe? The device isn't specified. The only device-specific kernel released here is for victara (Moto X 2014).

**Comment by rabih** [comment]
They are all unified (condor/falcon/peregrine/titan/victara) inside of the
kernel. They have a different tracking branch for the victara though.
Motorola delays the source pushes for quite a while now, maybe they'll
eventually push it with the L rollout.

**Comment by tags07** [comment]
Sources for Moto G, Moto E and Moto G(2nd Gen) are all posted on branch: lollipop—5.0.2-release   and TAG : MMI-LXB22.46-28

Sources for Moto X(2nd Gen) is posted on branch:  lollipop-5.0.2-release-victara
TAG: MMI-LXE22.46-25

**Comment by ShiroiKarasu6991** [comment]
Ah, okay then. Thanks @tags07!

**Comment by antdking** [comment]
@tags07 I'm messing with the moto e 2nd gen atm. found the dump commands in fastboot, but it requires the moto version of fastboot (located here http://goo.gl/Qyzg2L )

```
$ sudo fastboot oem partition dump recovery
(bootloader) Latest Motorola fastboot required, download from: 
(bootloader) http://goo.gl/Qyzg2L
(bootloader) 
FAILED (remote failure)
```

would you be able to provide it please?

**Comment by antdking** [comment]
Scratch that. I've got one that supports it, though it's limited (probably due to the "allow unlock" flag not being set [it resets after every reboot]). 

Would you be able to send the complete boot image please? Dm-verity means I can no longer boot

**Comment by ccfries** [comment]
For future reference you can get windows/darwin/linux fastboot.exe from a recovery image.
https://motorola-global-portal.custhelp.com/app/standalone/bootloader/recovery-images

That being said, I don't see a falcon recovery image posted.

-Chris
