### ISSUE TITLE
Moto E4 (perry) kernel source

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#120]
Will the Moto E4 perry kernel source be released any time soon?

**Comment by ghost** [comment]
I know you guys are busy trying to release kernels for numerous devices and I really don't want to pester you, but it's been a while and I haven't even got a we're working on it or anything. Any word on the release of the Perry 7.1.1  NCQ.26.69-48/51 kernel source would be nice. Thank you.

**Comment by chenyt9** [comment]
Hi，aaronmarch，
    We are trying to release the code, perry the code has been in the workflow priority, please give us some time, we will be released before October 1. Thanks for understanding.
BRs.
chenyt9

**Comment by chenyt9** [comment]
Hi，@aaronmarch,
    Version MMI-NCQ26.69-48 is released:
    https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NCQ26.69-48
