### ISSUE TITLE
Kernel source for Moto G Turbo (Merlin)

### ISSUE THREAD

**Issue by dchatterjee172** [MotorolaMobilityLLC/kernel-msm#121]
Hi,
Can you please release the kernel sources for Moto G Turbo (Merlin)
Android Version: 6.0.1
Build Number: MPDS24.107-56-1-17
SKU: XT1557
@charleseb
@chenyt9 
http://www.gnu.org/licenses/gpl-violation.html

**Comment by EduardMcfly** [comment]
PLEASE MOTOROLA ...

**Comment by dchatterjee172** [comment]
@chenyt9  @charleseb
Can you please respond and clarify this?

**Comment by EduardMcfly** [comment]
here is the answer:

https://github.com/MotorolaMobilityLLC/kernel-msm/issues/75

**Comment by charleseb** [comment]
Tag already released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-MPD24.107-56

Thanks,
Charles
