### ISSUE TITLE
Moto xt1789

### ISSUE THREAD

**Issue by jbats** [MotorolaMobilityLLC/kernel-msm#122]
Codename: nash
Build.No:NCX26.2
Android Version: 7.1.1

Could you please release source

**Comment by thatcharacter** [comment]
I would also like to see the kernel source code released for this device. We would sure appreciate it. :)

**Comment by charleseb** [comment]
Version MMI-NCX26.2 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NCX26.2
