### ISSUE TITLE
GPL Source Request for Moto G5s Plus (sanders) - (NPS26.116-26)

### ISSUE THREAD

**Issue by therootlord** [MotorolaMobilityLLC/kernel-msm#123]
Hi, could you provide the corresponding sources ?

@charleseb @chenyt9

Many Thanks!

**Comment by chenyt9** [comment]
Hi , therootlord ，

We have a process to follow before to release a version to Github. We are working to release Moto Z code, it will be available in a few days.

Thanks,

**Comment by therootlord** [comment]
Great! 

Many thanks @chenyt9

**Comment by CheckYourScreen** [comment]
@charleseb @chenyt9 any plans of releasing fastboot flashable imgs of stock retail firmware being shipped with the device?

**Comment by therootlord** [comment]
Hi @chenyt9 ,  i really need this, to fix a f2fs mount issue, the sources from potter worked, but not camera/flash light/rear proximity sensor as its missing ltr559 driver,  ive imported this driver from another kernel source but not worked, can you provide a patch including the correct/missing camera/sensors drivers for sanders?

**Comment by charleseb** [comment]
Hi @therootlord,

We are working to release this version.

Charles

**Comment by charleseb** [comment]
Version MMI-NPS26.116-45 released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPS26.116-45

**Comment by CheckYourScreen** [comment]
Thanks @charleseb !
Edit: seems like you released for a newer tag too! Great!

**Comment by therootlord** [comment]
Many many thanks @charleseb  !

**Comment by CheckYourScreen** [comment]
Hi @charleseb , can you please push the NPSS26.116-26-4 tag of sanders?
