### ISSUE TITLE
Moto Z2 Force Kernel Source NCX26.122-59

### ISSUE THREAD

**Issue by XirXes** [MotorolaMobilityLLC/kernel-msm#124]
Can you please share kernel sources for Motorola Z2 Force (NASH) build NCX26.122-59?

http://www.gnu.org/licenses/gpl-violation.html

**Comment by chenyt9** [comment]
Hi , XirXes,

We have a process to follow before to release a version to Github. We are working to release Moto Z code, it will be available in a few days.

Thanks,

**Comment by XirXes** [comment]
Thanks for the clarification chenyt9. Glad to hear it.

**Comment by thatcharacter** [comment]
Can we please get this source code now? It's been more than a few days.

**Comment by ghost** [comment]
+1, can we please have the kernel source code?

Thought it was supposed to be released last week. Moto Z2 Force NCX 26.5

**Comment by ghost** [comment]
Hello?
This thing on? LOL

I thought HTC was bad, this is ridiculous. Work WITH your customers Motorola. Dont be that guy, we as consumers spend alot of money with you guys.

**Comment by charleseb** [comment]
Hi all,

We are working to release this version soon.

Thanks,
Charles

**Comment by ghost** [comment]
Right. Empty promises as this same thing was said a couple weeks back to shut us up.

**Comment by slipkn0t2012** [comment]
How soon, is soon Charles? What's an ETA?

**Comment by charleseb** [comment]
Hi @slipkn0t2012,

I'll release this version by next Friday.

Thanks,
Charles

**Comment by Uzephi** [comment]
So if I am reading the broken English correctly, (not blaming you, your native language might not be English and it is the translator error) you will have the kernel released NLT (No later than) 06/10/2017 dd/mm/yyyy? 

I.E. Next Friday the code will be released?

**Comment by charleseb** [comment]
Hi @Uzephi,

"by Friday"

Ch.

**Comment by charleseb** [comment]
Version MMI-NCX26.122-59-8 is released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NCX26.122-59-8

**Comment by XirXes** [comment]
Awesome! Feeling more confident in my choice to switch to Moto now.
