### ISSUE TITLE
Please release the kernel source for Moto X Force (kinzie) NPK25.200-12

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#125]
I do not understand why you delayed the release of the source code, it's violated the GPL.

**Comment by charleseb** [comment]
Hi @kevinzh1,

Sorry we've not replied before. We have a lot of versions to release in parallel. I'm working to release this version soon.

Charles

**Comment by charleseb** [comment]
Version MMI-NPK25.200-12 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPK25.200-12

**Comment by PRIHLOP** [comment]
Thanks for share. But after build and flashing kernel smartphone gone in bootloop. 
Maybe problem with mounting userdata partition.
Can you share f2fs sources especially for kinzie?
