### ISSUE TITLE
Kernel sources for Moto X Play (lux) - NPD26.48-24-1

### ISSUE THREAD

**Issue by ilusaoautosustentada** [MotorolaMobilityLLC/kernel-msm#128]
Hey, could you provide the kernel sources for Moto X Play 
Android version: 7.1.1
Build number: NPD26.48-24-1
@charleseb 
@chenyt9 

Thanks and great work !

**Comment by charleseb** [comment]
Hi @smsportoo,

We're working to release this version soon.

Thanks,
Charles

**Comment by archon810** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPD26.48-24-1

**Comment by charleseb** [comment]
Version released.
