### ISSUE TITLE
Kernel source for Moto X4 NPW26.83-34-0-1

### ISSUE THREAD

**Issue by mightysween** [MotorolaMobilityLLC/kernel-msm#129]
I know it is REALLY soon, but any timeframe on the X4 sources?  Thanks, you rock. :)

**Comment by chenyt9** [comment]
Hi，@mightysween，
We are trying to release the code, the code has been in the workflow priority, please give us some time,  it may take 1 or 2 weeks... Thanks for understanding.
BRs.
chenyt9

**Comment by chenyt9** [comment]
@mightysween ，
Version MMI-NPW26.83-18-2 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPW26.83-18-2

Thanks,
Chenyt9
