### ISSUE TITLE
e4 Plus kernel

### ISSUE THREAD

**Issue by jaduncan** [MotorolaMobilityLLC/kernel-msm#131]
Do you have a timescale for release of the e4 plus/XT17xx/nicklaus kernel source?

For the avoidance of doubt I'm using the device, and this is a formal GPL request for a source link.

**Comment by samstone86** [comment]
https://github.com/MotorolaMobilityLLC/kernel-mtk/tree/nougat-7.1.1-release-nicklaus ?

**Comment by archon810** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NCR26.58-26
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPR26.58-25
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NDR26.58-21

**Comment by hangfan1** [comment]
Moto E Plus
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NCR26.58-26
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPR26.58-25
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NDR26.58-21
