### ISSUE TITLE
blank flash for Moto g2

### ISSUE THREAD

**Issue by iamDmon** [MotorolaMobilityLLC/kernel-msm#132]
Please upload files for the blank flash(programmer and singlefile.bin

**Comment by awheeler-mmi** [comment]
Hey @iamDmon, sorry for the delay.  We don't release the blankflash images for our devices.  If your phone is stuck in blankflash mode then I recommend contacting [support](https://support.motorola.com). 
I hope you have already gotten past this issue!!
