### ISSUE TITLE
Kernel Source Request for Moto G4 Plus NPJS25.93-14-10

### ISSUE THREAD

**Issue by Plususer** [MotorolaMobilityLLC/kernel-msm#133]
Hello,

Please could you provide the kernel sources for the Moto G4 Plus (codenamed Athene), with tag NPJS25.93-14-10.

Many thanks, and I hope you are well.

**Comment by charleseb** [comment]
Hi @Plususer,

We are working to release this version. It will be released by Friday.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi @Plususer,

Version MMI-NPJS25.93-14-10 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPJS25.93-14-10

Thanks,
Charles

**Comment by Plususer** [comment]
Thanks :)
