### ISSUE TITLE
Which "defconfig" is used for Moto G5 Plus Kernel Compilation?

### ISSUE THREAD

**Issue by sunmughan** [MotorolaMobilityLLC/kernel-msm#136]
Hello, please tell me the "defconfig" that can be used for compiling the kernel for Moto G5 Plus. There are lots of defconfigs available in /arch/arm/* and i want to know the appropriate one used for Moto G5 plus. Thankyou

**Comment by chenyt9** [comment]
Please refer to https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-NPS26.116-45.txt.
Thanks.

**Comment by awheeler-mmi** [comment]
Thanks @chenyt9 !
