### ISSUE TITLE
Kernel source for Moto x4 oreo

### ISSUE THREAD

**Issue by kraatus90** [MotorolaMobilityLLC/kernel-msm#140]
Version: MMI-OPW27.57-40
Device: payton
Branch: 8.0

can we have kernel source  for it ? thanks
  
@charleseb

**Comment by charleseb** [comment]
Hi @kraatus90,

This version is in our pipeline and will be released soon. This version will be available by the next week.

Thanks,
Charles

**Comment by hangfan1** [comment]
Hi @kraatus90,
Version MMI-OPW27.57-40 has published in 2018/01/22.
link is https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPW27.57-40.

Thanks
Hangfan
