### ISSUE TITLE
Request for NPSS26.118-19-18 tag source update for Albus (Moto Z2 Play)

### ISSUE THREAD

**Issue by rahulsnair** [MotorolaMobilityLLC/kernel-msm#142]
Please release the kernel source for tag NPSS26.118-19-18 for Moto Z2 Play (albus)

**Comment by rahulsnair** [comment]
@charleseb @chenyt9

**Comment by charleseb** [comment]
Hi @rahulsnair,

I'm working to release this version by Friday.

Thanks,
Charles

**Comment by faiyazsheth** [comment]
+1, please release asap. :)

**Comment by charleseb** [comment]
We are almost there.

- Charles

**Comment by charleseb** [comment]
Version released
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPSS26.118-19-18
