### ISSUE TITLE
Source code release

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#146]
Is there any chance we can get the latest kenel source code released for Owens and Perry? Please, and thank you!

**Comment by luk1337** [comment]
You need to provide the exact versions otherwise you'll get ignored.

**Comment by charleseb** [comment]
Hi @Goose03,

Could you describe the version you need, please?

Thanks,
Charles

**Comment by ghost** [comment]
MMI-NPR26.58-45 for Owens
MMI-NCQ26.69-56 for Perry
Thank you very much!

**Comment by chenyt9** [comment]
@Goose03 ，since we have a series of approval processes prior to the release of the code, we need a little time and we expect to release the code before next Friday (16th). Thank you for your patience. Once the code is updated, I will inform you immediately.

**Comment by ghost** [comment]
Not a problem, I know you guys have a lot to deal with. That was expected. Thank you very much for your quick response.

**Comment by chenyt9** [comment]
@Goose03 , Versions have been released.
MMI-NPR26.58-45 for Owens:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPR26.58-45
MMI-NCQ26.69-56 for Perry:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NCQ26.69-56
Thanks.
