### ISSUE TITLE
Kernel source for march security update moto x4.

### ISSUE THREAD

**Issue by kraatus90** [MotorolaMobilityLLC/kernel-msm#149]
build - OPWS27.57-25-6-10
device- payton

when can we expect it ?

**Comment by kraatus90** [comment]
@chenyt9 @hangfan1

**Comment by chenyt9** [comment]
Hi，@kraatus90
We have a process to follow before to release a version to Github. We are working to release this version code, it will be available in a few days.

Thanks,

**Comment by chenyt9** [comment]
Hi @kraatus90

Version released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPWS27.57-25-6-10

Thanks,
chenyt9
