### ISSUE TITLE
Kernel Source Request for Moto G4 Plus NPJS25.93-14-15

### ISSUE THREAD

**Issue by Plususer** [MotorolaMobilityLLC/kernel-msm#150]
Hello,

Please could you provide the kernel sources for the Moto G4 Plus (codenamed Athene), with tag NPJS25.93-14-15.

Many thanks, and I hope you are well.

**Comment by Plususer** [comment]
@charleseb @chenyt9 @awheeler-mmi @hangfan1

**Comment by charleseb** [comment]
Hi @Plususer,

I'm working to release this version.
It will be available by Tuesday.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPJS25.93-14-15
