### ISSUE TITLE
Moto G6 Plus "Evert" - OPW27.113-45 Kernel Sources

### ISSUE THREAD

**Issue by ahmedalbayati** [MotorolaMobilityLLC/kernel-msm#153]
Hi, @charleseb @chenyt9 @awheeler-mmi @hangfan1 

**Blur Version:** Blur_Version.27.11.53.evert.retail.en.US
**Build Fingerprint:** motorola/evert/evert:8.0.0/OPW27.113-45/53:user/release-keys
**Android Version:** 8.0.0

Can you provide the corresponding sources?
Thanks in advance!

**Comment by creasingmass** [comment]
+1

**Comment by chenyt9** [comment]
@ahmedalbayati， @creasingmass ，
Because we have some necessary processes, so we need a little time. We will release OPW27.113-45 ASAP. It will be released within two weeks.
Thanks for understanding
BRs.
chenyt9

**Comment by charleseb** [comment]
Hi guys,

We are working to release this version. It will be available by Friday.

Thanks,
Charles

**Comment by chenyt9** [comment]
@creasingmass ，@ahmedalbayati,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPW27.113-45
thanks.
