### ISSUE TITLE
Moto Z Play OPN27.76-12-22 / OPNS27.76-12-22-3 kernel sources

### ISSUE THREAD

**Issue by TimoRoth** [MotorolaMobilityLLC/kernel-msm#157]
I'm looking for the Kernel of one of the following two addison oreo releases:

Build Fingerprint: motorola/addison/addison:8.0.0/OPNS27.76-12-22-3/3:user/release-keys
Blur Version: Blur_Version.27.201.3.addison.retail.en.US
Android Version: 8.0.0

or:

Build Fingerprint: motorola/addison/addison:8.0.0/OPN27.76-12-22/24:user/release-keys
Blur Version: Blur_Version.27.21.24.addison.retail.en.US
Android Version: 8.0.0

Pretty much the latest Kernel available for addison Oreo

**Comment by BtbN** [comment]
@charleseb @chenyt9 @awheeler-mmi @hangfan1

**Comment by charleseb** [comment]
Hi @TimoRoth, @BtbN,

We are working to release this version. It will be released by Friday.

Thanks,
Charles

**Comment by chenyt9** [comment]
@TimoRoth @BtbN
Version released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPNS27.76-12-22-24-3
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPN27.76-12-22
Thanks.
