### ISSUE TITLE
Please release kernel source for kinzie NPKS25.200-12-9

### ISSUE THREAD

**Issue by belegdol** [MotorolaMobilityLLC/kernel-msm#158]
Please may you release the kernel source for kinzie NPKS25.200-12-9? It is the latest kernel available for reteu model. Thank you!

**Comment by charleseb** [comment]
Hi @belegdol,

We are working to release this version. It will be released by Friday.

Thanks,
Charles

**Comment by belegdol** [comment]
Hi @charleseb, would you happen to have any updates regarding the release? Thank you!

**Comment by charleseb** [comment]
Hi @belegdol,

We are almost there.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPKS25.200-12-9

Thanks,
Charles
