### ISSUE TITLE
Request for OPS28.85-13 source of Potter

### ISSUE THREAD

**Issue by GtrCraft** [MotorolaMobilityLLC/kernel-msm#159]
Can you please release the kernel source of OPS28.85-13 for potter?

**Comment by fernandobouchet** [comment]
@charleseb @chenyt9 @awheeler-mmi @hangfan1

**Comment by fernandobouchet** [comment]
Any update on this @charleseb @chenyt9 @awheeler-mmi @hangfan1 ? Thanks in advance

**Comment by charleseb** [comment]
Hi all,

I'm starting the process to release this version. It will be released by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPS28.85-13
