### ISSUE TITLE
release for MMI-NPLS26.118-20-5-11

### ISSUE THREAD

**Issue by hermesthecat** [MotorolaMobilityLLC/kernel-msm#162]
can you add for release for MMI-NPLS26.118-20-5-11?

**Comment by charleseb** [comment]
Hi @abazad,

We are working to release this version. It will be released by Friday.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPLS26.118-20-5-11

Thanks,
Charles

**Comment by hermesthecat** [comment]
hi @charleseb

can you release same version for  vendor-qcom-opensource-wlan-qcacld-2.0, motorola-external-greybus  and motorola-external-v4l2_hal?

thanks in advance.

**Comment by hermesthecat** [comment]
hi @charleseb 

oohh  i saw.   you released it. 

thank you much.
