### ISSUE TITLE
Moto g4/g4 plus "athene" - NPJS25.93-14-18 kernel source

### ISSUE THREAD

**Issue by loonycrd** [MotorolaMobilityLLC/kernel-msm#166]
Hi @charleseb @chenyt9 could you please update the source for athene.
Build no. NPJS25.93-14-18. Thanks in advance.

**Comment by charleseb** [comment]
Hi @loonycrd,

We are working to release this version. It will be released by Tuesday.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi @loonycrd,

Version released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPJS25.93-14-18

Thanks,
Charles

**Comment by loonycrd** [comment]
Thanks Charles.

Corresponding branch for this tag is "nougat-7.0.0-release-smr" just in case to avoid any confusion as the branch name doesn't include device codename.

**Comment by charleseb** [comment]
Hi @loonycrd,

Yes, nougat-7.0.0-release-smr is the upstream to this version tag. Please use the tag as reference. That's possible to an existing branch be used just for an update in future versions.

Thanks,
Charles
