### ISSUE TITLE
OPSS27.104-15-10-4 kernel source - Moto G6 (ali)

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#167]
Hey @charleseb @chenyt9 

When you get a chance, could you please release the kernel source for **OPSS27.104-15-10-4**, I'd greatly appreciate it.

Thank you

**Comment by chenyt9** [comment]
@Jleeblanch ,
I have triggered the release process and may finish the release before next Friday. Please be patient, thank you!

**Comment by Jleeblanch** [comment]
@chenyt9 ,
Thanks for the reply, I will be patiently waiting

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPSS27.104-15-10-4
Thanks.
