### ISSUE TITLE
OPXS27.109-34-13 Kernel source

### ISSUE THREAD

**Issue by Uzephi** [MotorolaMobilityLLC/kernel-msm#168]
Hello, for our Nash, after July Security patches my custom kernel will not have wifi work. (it runs off OPXS27.109-48-6 which is May security patch) Can you please release the source for this release number so I can merge it and have wifi working again? thank you.

**Comment by charleseb** [comment]
Hi @Uzephi,

I'm starting the process to release this version.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPXS27.109-34-13
