### ISSUE TITLE
XT1079 source code please.

### ISSUE THREAD

**Issue by victortan1972** [MotorolaMobilityLLC/kernel-msm#17]
Please update kernel source code for XT1079 and tag it, please.

**Comment by luca020400** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/tree/lollipop%E2%80%945.0.2-release
It uses the same branch as Moto G/Moto G LTE/MOTO G 2014
& ext_config is titan one

**Comment by gtx1049** [comment]
@luca020400  I compiled this kernel branch "lolipop 5.0.2 release" and flash it into XT1079
But the wifi module and SIM don't work, also, I cant get baseband info
The log said "qmi" module has some problem. 
like "E/QC-QMI  (  331): qmi_client [331]: unable to connect to server"
I dont know how to fix it.
By the way, XT1079's default build version is "LXB22.99-7.1"

**Comment by lucasauditoree** [comment]
como faz pre instalar : o  kernel no moto G

**Comment by luk1337** [comment]
@lucasauditoree English?

**Comment by lucasauditoree** [comment]
How does pre installed: the kernel in moto G

**Comment by luk1337** [comment]
@lucasauditoree I don't really understand your question

**Comment by lucasauditoree** [comment]
how will I do to install the kernel to revive Moto G xt1033 have to create the kernel that the link aii

**Comment by efgowacki** [comment]
We are looking for the MBM-CI 5.0 file for MOTOROLA MOTO G 2013 devices (XT1032 / XT1033) HARDBRICKED. With these files will be possible to get it? May indicate how or who to?

**Comment by lucasauditoree** [comment]
it also wonder

**Comment by victortan1972** [comment]
MMI-LXB22.99-24 is ready now. It work on my XT1079 (Moto G 2014 Chinese version).

**Comment by lucasauditoree** [comment]
will be to work on my bike g 2013 that hardbrick
