### ISSUE TITLE
Request for OPG28.54-19 pettyl kernel sources

### ISSUE THREAD

**Issue by Dark98** [MotorolaMobilityLLC/kernel-msm#170]
Would you be able to release these sources? & is there anyway to get to firmware packages for this device?

**Comment by Dark98** [comment]
@chenyt9 @charleseb @awheeler-mmi

**Comment by charleseb** [comment]
Hi all,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by Dark98** [comment]
@charleseb thank you! Is there anyway to download stock firmware packages for this device?

**Comment by pmwray** [comment]
Is this available yet?

**Comment by charleseb** [comment]
Hi all,

I'm still working on this version. Sorry about the delay. I think it will  be released this week,\.

Charles

**Comment by chenyt9** [comment]
@Dark98 @pmwray ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPG28.54-19
Thanks.
