### ISSUE TITLE
Request kernel source of tag OPW27.113-89 for Moto G6 Plus (evert)

### ISSUE THREAD

**Issue by rahulsnair** [MotorolaMobilityLLC/kernel-msm#173]
Hi @charleseb @chenyt9 ,

Could you please release the kernel source for moto g6 plus (Evert) with tag OPW27.113-89?

Regards,
Rahul

**Comment by chenyt9** [comment]
@rahulsnair ，
I am preparing for the release of this version, but it will take some time because the process we have to do is not yet complete. Please wait patiently, I will release it ASAP. Thank you!
BRs.
chenyt9

**Comment by chenyt9** [comment]
@rahulsnair ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPW27.113-89
Thanks.
