### ISSUE TITLE
Request for OPP.28-85-16 Cedric Kernel sources

### ISSUE THREAD

**Issue by ezxpro** [MotorolaMobilityLLC/kernel-msm#174]
It would be very nice if we had the kernel source code for the stable Oreo.
Thanks

**Comment by ezxpro** [comment]
@chenyt9 @awheeler-mmi @charleseb

**Comment by chenyt9** [comment]
@ezxpro ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPP28.85-16
Thanks.

**Comment by ezxpro** [comment]
Many a thanks
