### ISSUE TITLE
Kernel source release for chef_sprout build OPT28.81-39

### ISSUE THREAD

**Issue by faiyazsheth** [MotorolaMobilityLLC/kernel-msm#175]
Hi,

Can we have a kernel source release for Motorola one power code named as chef_sprout for OPT28.81-39 build please? @charleseb

Thanks.

**Comment by shamith16** [comment]
Wew

**Comment by faiyazsheth** [comment]
Any update please? @chenyt9 @charleseb

**Comment by charleseb** [comment]
Hi all,

We are working to release this version. It will be released by next week.

**Comment by spookykat** [comment]
@charleseb Kernel reminder. Just in case you guys forgot, like you did with the October security patch.

**Comment by charleseb** [comment]
Hi @spookykat,

I'm still working on this version. It will be released asap.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
 https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPT28.81-39
