### ISSUE TITLE
Request for OPWS28.46-21-12   PAYTON_FI (moto x4)  kernel sources

### ISSUE THREAD

**Issue by kraatus90** [MotorolaMobilityLLC/kernel-msm#176]
Can we have monthly kernel updates according to security patches please ?

**Comment by kraatus90** [comment]
@charleseb

**Comment by awheeler-mmi** [comment]
Hey @kraatus90, we're getting the releases out as soon as possible.   A number of open-source-release reviews just want across my (virtual) desk.  I don't recall if this payton release was one of them, but @charlesb will respond with an ETA next week.  

FYI, we prioritize the tags that developers are asking for, so your formal requests here on Github help!!!

**Comment by charleseb** [comment]
Hi @kraatus90,

This version will be released by Tuesday.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPWS28.46-21-12
