### ISSUE TITLE
Request for OPPS27.91-35-3 (Moto G6 Play) kernel source

### ISSUE THREAD

**Issue by SyNtheticNightmar3** [MotorolaMobilityLLC/kernel-msm#177]
May you release this?

Thanks!

**Comment by charleseb** [comment]
Hi @SyNtheticNightmar3,

We are working to release this version. It will be released by next week.

**Comment by charleseb** [comment]
Version released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPPS27.91-35-3
