### ISSUE TITLE
Moto E5 (source)

### ISSUE THREAD

**Issue by TheStrechh** [MotorolaMobilityLLC/kernel-msm#178]
any news about source for nora? actually use ali kernel with defconfig taked from stock boot.img but not boot... need push some changes on dts?

**Comment by ghost** [comment]
This request is of extreme necessity for developers!

**Comment by charleseb** [comment]
Hi @TheStrechh,

Could you describe the version you need, please?

Thanks

**Comment by TheStrechh** [comment]
@charleseb OPS27.91-72 if you can I do not know if there is a more recent

**Comment by ghost** [comment]
@charleseb update OPP27.91-146, compilation without errors, however, device does not start.

**Comment by charleseb** [comment]
We are working to release OPP27.91-146.
It will be released by next week.

Thanks,
Charles

**Comment by ghost** [comment]
@charleseb Thanks.

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPP27.91-146
