### ISSUE TITLE
NPPS25.137-93-2-5 Cedric Kernel Sources request 

### ISSUE THREAD

**Issue by ezxpro** [MotorolaMobilityLLC/kernel-msm#179]
it'd be very nice if we could have the source code for the latest nougat build.
Thanks in advance.

@charleseb @chenyt9

**Comment by charleseb** [comment]
Hi @ezxpro,

We are working to release this version. It will be released by next week.

**Comment by ezxpro** [comment]
@charleseb any progress?

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPPS25.137-93-2-5
