### ISSUE TITLE
Request for OPP27.91-122 ahannah (Moto E5 Plus Indian) Kernel source

### ISSUE THREAD

**Issue by chrisvrose** [MotorolaMobilityLLC/kernel-msm#180]
Is it possible to release this version?

**Comment by TheStrechh** [comment]
use kernel ali, only follow instruccions motorola for get defconfig ahannah

**Comment by charleseb** [comment]
Hi @chrisvrose,

We are working to release this version. It will be released by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPP27.91-122
