### ISSUE TITLE
Moto G6 kernel source for tag OPS27.104-92

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#181]
Hey @charleseb and @chenyt9

Could you release the kernel source for Moto G6 (XT1925-6) with tag OPS27.104-92?

I would greatly appreciate it, thank you.

**Comment by charleseb** [comment]
Hi @Jleeblanch,

We are working to release this version.
It will be released by next week.

Thanks,
Charles

**Comment by Jleeblanch** [comment]
> Hi @Jleeblanch,
> 
> We are working to release this version.
> It will be released by next week.
> 
> Thanks,
> Charles

@charleseb Thank you for the heads up 👍

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPS27.104-92
