### ISSUE TITLE
Messi kernel source: ODX28.66-18

### ISSUE THREAD

**Issue by Uzephi** [MotorolaMobilityLLC/kernel-msm#183]
Can we please get kernel source for the Z3 - Messi? ODX28.66-18

**Comment by charleseb** [comment]
Hi @Uzephi,

We are working to release this version. It will be released by Tuesday.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-ODX28.66-18
