### ISSUE TITLE
Kernel source Z3 OCX28.39-28 

### ISSUE THREAD

**Issue by matiascx89** [MotorolaMobilityLLC/kernel-msm#184]
Good day, is it possible to have kernel source for Moto Z3 (messi) OCX28.39-28?  

It's chinese version of Z3 (XT1929-15)

Thanks!

**Comment by charleseb** [comment]
Hi @matiascx89 ,

We are working to release this version.
It will be released by Tuesday.

Thanks,
Charles

**Comment by matiascx89** [comment]
Many thanks @charleseb !

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OCX28.39-28
