### ISSUE TITLE
release for MOTO Z   OPL27.76-71-2-3

### ISSUE THREAD

**Issue by hermesthecat** [MotorolaMobilityLLC/kernel-msm#185]
can you release OPL27.76-71-2-3 for 
kernel source,
vendor-qcom-opensource-wlan-qcacld-2.0, 
motorola-external-greybus,
motorola-external-v4l2_hal ?

thanks in advance.

**Comment by charleseb** [comment]
Hi @abazad,

We are working to release this version.
It will be available by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPL27.76-71-2-3
