### ISSUE TITLE
Kernel source release for chef_sprout build PPT29.74-25

### ISSUE THREAD

**Issue by faiyazsheth** [MotorolaMobilityLLC/kernel-msm#186]
Hi,

Can we have a kernel source release for Motorola one power code named as chef_sprout for PPT29.74-25 build please? @charleseb

Thanks.

**Comment by charleseb** [comment]
Hi @faiyazsheth,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by erfanoabdi** [comment]
Blur Version: Blur_Version.29.11.26.chef.retail.en.US

just in case ;)

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPT29.74-25
