### ISSUE TITLE
Kernel source for OPPS28.85-16-2 Cedric

### ISSUE THREAD

**Issue by ezxpro** [MotorolaMobilityLLC/kernel-msm#187]
We'd be very glad if the source code for this version and the readme were released.

Thanks in advance 
@charleseb

**Comment by charleseb** [comment]
HI @ezxpro,

We are working to release this version.
It will be released by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPPS28.85-16-2
