### ISSUE TITLE
Moto Z3 Play kernel source for tag OPWS28.70-31-2

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#188]
Hey @charleseb and @chenyt9, 

When you get a chance, can you please release the kernel source for tag **OPWS28.70-31-2** for the Moto Z3 Play (beckham)?

Thank you, 
Joshua

**Comment by charleseb** [comment]
Hi @Jleeblanch,

We are working to release this version. It will be released by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPWS28.70-31-2
