### ISSUE TITLE
Kernel source for montana on build OPPS28.65-37-2-2

### ISSUE THREAD

**Issue by wiktorek140** [MotorolaMobilityLLC/kernel-msm#189]
As in title, we will appreciate if source and readme for montana will be published.
Best regards
Wiktor

@charleseb

**Comment by charleseb** [comment]
Hi @wiktorek140,

We are working to release this version. This will be available by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPPS28.65-37-2
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-OPPS28.65-37-2.txt
