### ISSUE TITLE
motorola one "deen" - PPK29.68-16-8 Kernel Sources

### ISSUE THREAD

**Issue by erfanoabdi** [MotorolaMobilityLLC/kernel-msm#190]
Hi @charleseb @chenyt9 @awheeler-mmi

Blur Version: Blur_Version.29.21.11.deen.retail.en.US

Could you provide the corresponding source ?

Thanks in advance!

**Comment by charleseb** [comment]
Hi @erfanoabdi,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPK29.68-16-8
