### ISSUE TITLE
Moto X4 "payton" - PPW29.69-26 Kernel Sources

### ISSUE THREAD

**Issue by erfanoabdi** [MotorolaMobilityLLC/kernel-msm#191]
Hi @charleseb @chenyt9 @awheeler-mmi

Blur Version: Blur_Version.29.11.36.payton.retail.en.US

Could you provide the corresponding source ?

Thanks in advance!

**Comment by charleseb** [comment]
Hi @erfanoabdi,

We are working to release this version. It will be available by next week.

Thanks,
Charkes

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPW29.69-26
