### ISSUE TITLE
USB SoundCard Failing to Turn on

### ISSUE THREAD

**Issue by Schuby** [MotorolaMobilityLLC/kernel-msm#192]
Same as #134 and #160

I've got the following DAC and it's exhibiting the same behaviour, as previously outlined by Loader006, on my Moto Z (XT1650-03).
https://hifimediy.com/DACs/ready-made-dacs/Sabre-9018-DAC

A fix was mentioned in #134 but has still not been delivered.

I've attached a dmesg output which was recorded when the DAC failed to turn on upon plugging it in.
[fail.txt](https://github.com/MotorolaMobilityLLC/kernel-msm/files/2659621/fail.txt)

Edit: To add further information, I observed that if the phone battery is below 25%, the soundcard connects flawlessly and doesn't encounter the "OTG Overcurrent" error. Charging the phone up even as little as 30% results in the original OTG Overcurrent error occurring again.

**Comment by awheeler-mmi** [comment]
Hey there, I recommend pinging the Motorola support forums [here](https://support.motorola.com/us/en).   We just deal with the OSS releases on Github. Thanks!
