### ISSUE TITLE
Kernel source for Moto G6 play XT1922-7

### ISSUE THREAD

**Issue by madbat99** [MotorolaMobilityLLC/kernel-msm#197]
Can you post kernel source for Moto g6 play xt1922-7 Jeter
OCPS27.91-150-2

**Comment by anoraktrend** [comment]
Also, the currently available kernel is in an unacceptably unbuildable state.

**Comment by charleseb** [comment]
Hi @madbat99 and @anoraktrend,

We are working to release this version. It will be released by Friday.

Could you inform the version without conditions to build, please?

Thanks,
Charles

**Comment by madbat99** [comment]
Moto g6 play xt1922-7 Jeter
OCPS27.91-150-2

**Comment by anoraktrend** [comment]
MMI-OPPS27.91-35-3 according to user Space Miner on XDA.

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OCPS27.91-150-2
