### ISSUE TITLE
Moto G6 Plus (evert) - Kernel source for tag PPW29.116-11

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#198]
Hey @awheeler-mmi, @charleseb, and @chenyt9,

When you get a chance, can you release the kernel source for tag **PPW29.116-11** for the Moto G6 Plus (evert)?

Thank you,
Joshua

**Comment by charleseb** [comment]
Hi @Jleeblanch,

We are working to release this version. It will be released by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version Released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPW29.116-11
