### ISSUE TITLE
Non-ASCII character in branch name

### ISSUE THREAD

**Issue by stucki** [MotorolaMobilityLLC/kernel-msm#20]
The branch https://github.com/MotorolaMobilityLLC/kernel-msm/tree/lollipop%E2%80%945.0.2-release does not contain a plain ASCII dash but some special character instead.

This breaks "repo sync" on my system (and probably on others, too). Can you rename it?

**Comment by luca020400** [comment]
I don't get your problem , anyway https://github.com/MotorolaMobilityLLC/kernel-msm/tree/lollipop—5.0.2-release works

**Comment by stucki** [comment]
It's not a dash and I wanted to report that. If it works for you then fine, but it failed on my system and it was hard to find the cause for it.

```
➜  msm8226 $ git:(upstream) git remote -v
MotorolaMobilityLLC https://github.com/MotorolaMobilityLLC/kernel-msm.git (fetch)
MotorolaMobilityLLC https://github.com/MotorolaMobilityLLC/kernel-msm.git (push)
➜  msm8226 $ git:(upstream) find .git/refs/ | egrep -v "^.git/refs/[/A-Za-z0-9_\.-]*$"
.git/refs/remotes/MotorolaMobilityLLC/lollipop—5.0.2-release
```

**Comment by luk1337** [comment]
@stucki you can clone with MMI-LXB22.99-24 instead.

**Comment by stucki** [comment]
Thanks for the sugggestion, but I can work around this of course (just delete the ref manually). I'm reporting it here so that it will hopefully be fixed and in the future nobody will run into the same problem again...

**Comment by luk1337** [comment]
anyway MMI-LXB22.99-24 is a bit newer than lollipop—5.0.2-release.

**Comment by stucki** [comment]
Right. I didn't use it anyway. However, when you run `git fetch` then it will create references for all branches, including the old broken one. So I don't need it, that's also why I could delete it as a workaround.
Still, the problem is that it will be added again on next fetch...

**Comment by ccfries** [comment]
Yes, it's a valid bug, it'll get cleaned up.
