### ISSUE TITLE
Kernel source release for chef_sprout build PPT29.74-29-2

### ISSUE THREAD

**Issue by archie9211** [MotorolaMobilityLLC/kernel-msm#200]
Hi,

Can we have a kernel source release for Motorola one power code named as chef_sprout for PPTS29.74-29-2 build please? @charleseb

Thanks.

**Comment by charleseb** [comment]
HI @archie9211,

We are working to release this version. It will be released by next week.

Thanks,
Charles

**Comment by kkmfincorp** [comment]
Hi @charleseb

Waiting more than a week sir

Thanks.

**Comment by charleseb** [comment]
Hi @kkmfincorp,

We are completing the process to this version. I'll release this tag in a few days. 

Thanks,
Charles

**Comment by kkmfincorp** [comment]
Hi @charleseb,

Does the process has been finished for chef_sprout build PPT29.74-29-2 #200 .
We are expecting your kind response and release tag.

Thanks,
kkmfincorp

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPT29.74-29
