### ISSUE TITLE
Moto G7 Plus (lake) - Kernel source for tag PPW29.98-28

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#202]
Hey, @charleseb, @chenyt9, @awheeler-mmi 

When you guys get a chance, can you release the kernel source for tag **PPW29.98-28** for the Moto G7 Plus (lake). 

Thank you,
Joshua.

**Comment by charleseb** [comment]
HI @Jleeblanch,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by Jleeblanch** [comment]
@charleseb just checking in on how things are looking.

**Comment by charleseb** [comment]
Hi @Jleeblanch,

Sorry about the delay. It was needed to get some processes concluded before to release. I'm going to push this today.

Thanks,
Charles

**Comment by Jleeblanch** [comment]
No worries @charleseb, 

Thank you for the heads up

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPW29.98-28
