### ISSUE TITLE
Kernel Source for Moto G⁴ Plus (athene) - OPJ28.111-22

### ISSUE THREAD

**Issue by DarkGrillz** [MotorolaMobilityLLC/kernel-msm#203]
Now that this device is being updated to Android Oreo (Final) to the public, release the linux kernel source to start the development and improve our device.
I hope you can read me.

Beforehand thank you very much.

Device: Moto G⁴ Plus
Build Number: OPJ28.111-22

@awheeler-mmi @charleseb @chenyt9

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPJ28.111-22

**Comment by lucaasteixeira** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPJ28.111-22
