### ISSUE TITLE
Moto G6 Play (aljeter) PPP29.55-25 - kernel source code

### ISSUE THREAD

**Issue by JarlPenguin** [MotorolaMobilityLLC/kernel-msm#206]
Can you guys release the kernel source code for the Moto G6 Play Pie update? @charleseb

**Comment by charleseb** [comment]
Hi @JarlPenguin,

We are working to release this version. It will be available in a few days.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPP29.55-25
