### ISSUE TITLE
Moto G4 Plus (athene) - Kernel source OPJ28.111-22

### ISSUE THREAD

**Issue by loonycrd** [MotorolaMobilityLLC/kernel-msm#207]
Hey @awheeler-mmi, @charleseb, and @chenyt9,

Can you update the kernel source tag for current OPJ28.111-22 official release as well as dtv module sources in vendor-fci-dtvdriver repo for the Moto G4 Plus (athene)?

Thank you,
Rohit

**Comment by charleseb** [comment]
Hi @loonycrd,

We are working to release this version for both projects.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi @loonycrd,

You can find vendor-fci-dtvdriver artifacts here: https://github.com/MotorolaMobilityLLC/vendor-fci-dtvdriver/releases/tag/MMI-OPJ28.111-12

Thanks,
Charles

**Comment by charleseb** [comment]
We are working to release the version OPJ28.111-22. It will be released in a few days.

Thanks,
Charles

**Comment by loonycrd** [comment]
@charleseb any update on this?

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPJ28.111-22
