### ISSUE TITLE
Moto Z3 Play (beckham) - Kernel source for tag PPW29.131-27-1

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#208]
Hey @charleseb 

When you get a chance, can you release the kernel source for tag PPW29.131-27-1 for the Moto Z3 Play (beckham)?

Thank you, 
Joshua

**Comment by charleseb** [comment]
Hi @Jleeblanch,

We are working to release this version. It will be released by next week.

Thanks,
Charles

**Comment by Jleeblanch** [comment]
@charleseb any updates?

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPW29.131-27-1
