### ISSUE TITLE
Moto G6 (ali) - Kernel source for tag PPS29.55-24

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#209]
Hey @charleseb 

When you get a chance, can you release the kernel source for tag PPS29.55-24 for the Moto G6 (ali)?

Thank you, 
Joshua

**Comment by charleseb** [comment]
HI @Jleeblanch,

We are working to release this version. It will be released by next week.

Thanks,
Charles

**Comment by Jleeblanch** [comment]
@charleseb any updates on the kernel source?

**Comment by awheeler-mmi** [comment]
Hi @Jleeblanch, @charleseb is on this.  He's on holiday right now, but will get to them released as soon as he is back, next week.

**Comment by Jleeblanch** [comment]
@awheeler-mmi, ok no worries. Thank you for the heads up

**Comment by wh0dat** [comment]
@awheeler-mmi @charleseb , any chance yall can release source for stock timeweather widget? I'd like to get this working in custom ROM on the lockscreen.
Thanks in advance!! & Sorry to ask here

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPS29.55-24
