### ISSUE TITLE
Moto E5 PLUS - [RHannah/xt1924-4] kernel source 

### ISSUE THREAD

**Issue by wh0dat** [MotorolaMobilityLLC/kernel-msm#210]
Ignore

**Comment by yourordinarycat** [comment]
Hi there! Can Motorola publish a Kernel for Rhannah? (Obviously working) The one provided didn't boot on Rhannah, but it worked fine on other variants (like hannah_t and ahannah).

Thanks in advance for your help.
By: GodcraftPlata.

**Comment by charleseb** [comment]
Hi @GodcraftPlata,

Could you describe the version tag, please?

Thanks,
Charles

**Comment by wh0dat** [comment]
> Hi @GodcraftPlata,
> 
> Could you describe the version tag, please?
> 
> Thanks,
> Charles

No longer needed , thanks anyway Charles.
