### ISSUE TITLE
Moto G5S - OPPS28.65-37-7 tag source request

### ISSUE THREAD

**Issue by wiktorek140** [MotorolaMobilityLLC/kernel-msm#212]
Hi @charleseb,

As per title we waiting for source code of kernel to help community grow and to use latest security's patches.

Thanks,
Wiktor

**Comment by charleseb** [comment]
Hi @wiktorek140,

We are working to release this version. It will be released by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPPS28.65-37-7-2
