### ISSUE TITLE
G7  Plus Issues with voice sound on calls and poor line

### ISSUE THREAD

**Issue by RoscioZ** [MotorolaMobilityLLC/kernel-msm#213]
Audio of interlocutor disturbed with rustling and metallic voice, tried
reset, safe mode, no result.
Phone already replaced once by amazon, in addition problems of very poor line, perfect in other phones, SIM Vodafone Italia.
![Screenshot_20190429-131946](https://user-images.githubusercontent.com/18037921/56893223-3d678d00-6a82-11e9-9083-e9bdb35dac30.png)

**Comment by Ristovski** [comment]
This is not a support forum. Please close this issue.

**Comment by RoscioZ** [comment]
Hi, I know but nobody from motorola / lenovo answers on the forum, and the telephone support doesn't know how to give me indications, except to carry out the tests that I have already done!
