### ISSUE TITLE
Please release latest moto z force droid kernel (OCL27.76-69-6-3)

### ISSUE THREAD

**Issue by belegdol** [MotorolaMobilityLLC/kernel-msm#214]
Please may you release the kernel source for moto z force OCL27.76-69-6-3? Thank you!

**Comment by charleseb** [comment]
Hi @belegdol,

We are working to release this version. It will be released by next week.

**Comment by charleseb** [comment]
Version released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OCL27.76-69-6-3
