### ISSUE TITLE
Moto G7 Play (channel) - Kernel source for tag PPY29.68-28

### ISSUE THREAD

**Issue by scritch007** [MotorolaMobilityLLC/kernel-msm#215]
Hello,

Can you please release the sources for the Moto G7 Play tag **PPY29.68-28.**

Regards

Benjamin

**Comment by charleseb** [comment]
Hi @scritch007,

We are working to release this version. It will be released by the next week.

Thanks,
Charles

**Comment by jrtberlin** [comment]
Hi @charleseb any news on this or an ETA? I want to build TWRP for the G7 play. Thanks in advance.;D

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPY29.68-28

**Comment by scritch007** [comment]
Thanks @charleseb
