### ISSUE TITLE
Motorola One Vision (kane) - Kernel source for tag PSA29.97-13-9

### ISSUE THREAD

**Issue by GtrCraft** [MotorolaMobilityLLC/kernel-msm#216]
Hi,

Can you please release kernel source of Motorola One Vision tag PSA29.97-13-9?

**Comment by awheeler-mmi** [comment]
Hey @GtrCraft, the Moto One Vision is a Samsung Exynos-based device, so we're going to create "kernel-slsi" and probably a few other new projects for this release.  I'll leave this issue open until we get the projects created, and then will re-open your request under kernel-slsi.

Give us a bit of time for this release.  We should get the new projects (at least kernel-slsi) created today, but it will likely take some additional time to get make our first SLSI release.

**Comment by awheeler-mmi** [comment]
Moving to https://github.com/MotorolaMobilityLLC/kernel-slsi/issues/1 .
