### ISSUE TITLE
Moto G5 Plus (Potter) - Kernel source for tag OPS28.85-17-6-2

### ISSUE THREAD

**Issue by GtrCraft** [MotorolaMobilityLLC/kernel-msm#217]
Sorry to bother you again but can you also release the kernel source of Moto G5 Plus's tag OPS28.85-17-6-2?

**Comment by charleseb** [comment]
Hi @GtrCraft,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPS28.85-17-6-2
