### ISSUE TITLE
G7 (River) Kernel Source request

### ISSUE THREAD

**Issue by Yossarian75** [MotorolaMobilityLLC/kernel-msm#218]
Please provide the kernel source for the G7 (River). Thanks!

**Comment by charleseb** [comment]
Hi @Yossarian75,

Could you describe the version you need, please?

Thanks,
Charles

**Comment by curbthepain** [comment]
I won't open another request to be a bother but I also would like the kernel source code for the Moto g7 (river). If you want to know which kernel version to provide then go with the one from PPOS29.114-16-5-2 (that's the build number)
