### ISSUE TITLE
Moto G7 Plus (lake) - Kernel source for tag PPWS29.98-66-2

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#219]
@charleseb 

Can you please release the kernel source (and relevant sources) for tag **PPWS29.98-66-2**? 

Thank you,
Joshua

**Comment by charleseb** [comment]
Hi @Jleeblanch,

We are working to release this version. It will available by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPWS29.98-66-2
