### ISSUE TITLE
Kernel Nash PPX29.159-19 kernel source request

### ISSUE THREAD

**Issue by Uzephi** [MotorolaMobilityLLC/kernel-msm#220]
Since it is rolling out, can we get Kernel sources for Nash. Build PPX29.159-10?

**Comment by jbats** [comment]
Still waiting on a response for this.

**Comment by npjohnson** [comment]
@charleseb @chenyt9 
Hate to tag, but you all were very helpful in attaining source when Oreo dropped, just thought I'd look y'all in on the discussion (:

**Comment by Uzephi** [comment]
I assume it is because they haven't finalized the kernel. We got a -19 build distributed recently. If you are fixing the kernel. Please fix the way your kernel handles rendering. com.android.test.uibench program looks horrid currently on any release of the Z2F. Below is the results on pie. It should be consistently below 0.5. I'll wait patiently if it would assist in making the kernel release better.

https://cdn.discordapp.com/attachments/397594172149727234/592744548174659586/Screenshot_20190624-125444.png

**Comment by Uzephi** [comment]
PPX29.159-19 officially went out as an OTA per our friends in Brazil. Can we please be compliant with this release since it is public and follow GPL? 

This request was originally for -10 but that seems it was a soak test, so please at least give us sources for the public Pie release for Nash so we can fix the jitter issue ourselves since the device will be EOL shortly.

**Comment by Uzephi** [comment]
@charleseb @chenyt9 could we get a monthly update on this request now that Pie is rolling out officially and publicly?

**Comment by awheeler-mmi** [comment]
Hey @Uzephi and others, @charleseb is on vacation for the next two weeks.  In the meantime we are trying to figure out how to get this release out, given the interest in a nash P kernel. I'll keep y'all posted!

**Comment by Uzephi** [comment]
Any update on this? PPX-29.159-19 released in Brazil and India. We have firmware as well via LMSA tool. Can we please get the kernel sources? 

License reminder
https://www.gnu.org/licenses/gpl-violation.en.html

**Comment by charleseb** [comment]
Hi @Uzephi,

I'm working to release this. This version will be available by the next week.

Thanks,
Charles

**Comment by Uzephi** [comment]
Thank you

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPX29.159-19
