### ISSUE TITLE
Moto Z3 Play (beckham) - Kernel source for tag PPW29.183-29-1

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#221]
@charleseb 

Can you release the kernel source (and relevant sources) for tag **PPW29.183-29-1**? 

Thank you,
Joshua

**Comment by charleseb** [comment]
Hi @Jleeblanch,

This version is in our pipeline. It will be released by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPW29.183-29-1

**Comment by heynando** [comment]
Hey @charleseb do you think Beckham will get Android 10? I only ask because the answer will impact in my decision to keep it or buy a new one.. thank you
