### ISSUE TITLE
Request from the Motorola Nora kernel source

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#222]
Hello, I was compiling the MMI-OPP27.91-146 (https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPP27.91-146) source from the Nora motorola, but this source is already very outdated and when it is compiled and installed it lags and instability. The software version is already in OPP27.91-176-8.

Thank you very much in advance ;)

**Comment by chenyt9** [comment]
@amaterasushen 
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPP27.91-176-8
Thanks.
