### ISSUE TITLE
Moto G7 XT1962-1 River Kernel

### ISSUE THREAD

**Issue by curbthepain** [MotorolaMobilityLLC/kernel-msm#224]
Requesting the kernel source code for the Moto G7 River (XT1962-1). Preferably from the build PPOS29.114-16-5-2.

**Comment by charleseb** [comment]
Hi @curbthepain,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by Vachounet** [comment]
@charleseb Any news for the release ?

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPOS29.114-16-5-2
