### ISSUE TITLE
G6 (Ali) PPSS29.55-34-1 kernel source request

### ISSUE THREAD

**Issue by Yossarian75** [MotorolaMobilityLLC/kernel-msm#226]
Can you please supply the PPSS29.55-34-1 kernel source? Thanks a lot.

**Comment by charleseb** [comment]
Hi @Yossarian75,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPSS29.55-34-1
