### ISSUE TITLE
Moto G4 Plus (athene) - Source updates for OPJ28.111-22-1

### ISSUE THREAD

**Issue by loonycrd** [MotorolaMobilityLLC/kernel-msm#227]
Hey @awheeler-mmi, @charleseb, and @chenyt9,

Can you update the necessary sources for kernel, dtv, prima and f2fs for current OPJ28.111-22-1 official release for the Moto G4 Plus (athene)

Thank you,
Rohit

**Comment by charleseb** [comment]
Hi @loonycrd,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by chenyt9** [comment]
@loonycrd 
loonycrdVersion released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPJ28.111-22-1
Thanks.
