### ISSUE TITLE
Moto G5S (montana) OPPS28.65-37-7-6 source

### ISSUE THREAD

**Issue by JarlPenguin** [MotorolaMobilityLLC/kernel-msm#228]
Thanks!

**Comment by charleseb** [comment]
Hi @JarlPenguin,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by chenyt9** [comment]
@JarlPenguin 
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPPS28.65-37-7-7-6
Thanks.
