### ISSUE TITLE
Moto G6 Play (aljeter) PPPS29.55-25-2 kernel source

### ISSUE THREAD

**Issue by JarlPenguin** [MotorolaMobilityLLC/kernel-msm#229]
Thanks beforehand.

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPPS29.55-25-2

**Comment by Sota4Ever** [comment]
> Versión publicada: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPPS29.55-25-2

Does not show aljeter.defconfig file
