### ISSUE TITLE
G6 play Jeter source request PCP29.118-41

### ISSUE THREAD

**Issue by madbat99** [MotorolaMobilityLLC/kernel-msm#230]
Please post Pie kernel source for the XT1922-7 G6 play Jeter. Build number PCP29.118-41

**Comment by madbat99** [comment]
Going to need a reply here. GPL requires it. 
@charleseb

**Comment by loonycrd** [comment]
@madbat99 I am not a member of MotorolaMobilityLLC. If PCP29.118-41 is an official public release then Motorola will release kernel sources. It takes time.

**Comment by charleseb** [comment]
Hi @madbat99,

This version is in our pipeline. It will be released in two weeks.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PCP29.118-41
