### ISSUE TITLE
GPL Source Request for Moto Z4 (foles) - (PPF29.105-25-13)

### ISSUE THREAD

**Issue by AliceGrey** [MotorolaMobilityLLC/kernel-msm#233]
Hello,
Could you please provide the source code for the RETAIL version of the Moto Z4. Specifically version PPF29.105-25-13. @charleseb 

Thank You

**Comment by charleseb** [comment]
Hi @AliceGrey,

We are working to release this version.
It will be released by next week.

Thanks,
Charles

**Comment by AliceGrey** [comment]
@charleseb
It looks like 
PPF29.105-25-13-2 got pushed out today. Could you release that version as well? I take it there's a small bugfix in there.

**Comment by AliceGrey** [comment]
@charleseb Any updates on releasing the source?

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPF29.105-25-13
