### ISSUE TITLE
 GPL Source Request for Moto G7 (river) (PPOS29.114-134-2) + Moto G7 Power (ocean) - (PPO29.114-134-2)

### ISSUE THREAD

**Issue by wh0dat** [MotorolaMobilityLLC/kernel-msm#235]
Please include techpack also this time.
Thanks
~Barry Allen

**Comment by luizdores** [comment]
Release the kernel Motorola please.

**Comment by wh0dat** [comment]
On River ... In stock , if listening to BT and get incoming call and accept it , BT completely dies after the call and cannot listen to music unless reboot. @charleseb @awheeler-mmi please give techpack for river?? I was planning to buy a ocean but been waiting for techpack for it aswell. PLEASE??!
Thanks in advance

~Barry Allen

**Comment by electimon** [comment]
Please we need techpack

**Comment by Geofferey** [comment]
Hi, the techpack is one of the last things we need for functional audio on our custom roms. It would be very much appreciated if you could also include that source as well. Thank you for your consideration and for cohering to the GPL.

**Comment by charleseb** [comment]
Version released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPO29.114-134
techpack: https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-audio-kernel/releases/tag/MMI-PPO29.114-134

**Comment by motog7** [comment]
Thanks Charles , this is only for ocean? What about river?

**Comment by charleseb** [comment]
Hi @motog7,

Working on it. It will be available by next week.

Thanks,
Charles

**Comment by rajatgupta1998** [comment]
> Hi @motog7,
> 
> Working on it. It will be available by next week.
> 
> Thanks,
> Charles

Hi @charleseb . Please consider releasing the kernel and the techpack sources for the build PPOS29.114-134-4 for Moto G7 (River) if possible, as it is the most recent one. :)

**Comment by charleseb** [comment]
Versions released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPOS29.114-134-2
https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-audio-kernel/releases/tag/MMI-PPOS29.114-134-2
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPOS29.114-134-2_RIVER
https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-audio-kernel/releases/tag/MMI-PPOS29.114-134-2_RIVER

**Comment by wh0dat** [comment]
thanks @charleseb
