### ISSUE TITLE
GPL Source Request for Moto E5 (codename Nora) (OPPS27.91-176-11-5)

### ISSUE THREAD

**Issue by IMPERADOR-MENDIGO** [MotorolaMobilityLLC/kernel-msm#236]
please release the recent version of the Nora kernel OPPS27.91-176-11-5.

thanks.

**Comment by Play4NoobWin** [comment]
Soon, maybe

**Comment by ghost** [comment]
I want it too.

**Comment by charleseb** [comment]
Hi @IMPERADOR-MENDIGO, @Play4NoobWin, @amaterasushen,

We are starting the process to release this version. It will be available in two weeks.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi @IMPERADOR-MENDIGO,

I'm still working on this. It will be released this week. Sorry about the delay.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPPS27.91-176-11-5

**Comment by ghost** [comment]
> Version released:
> https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPPS27.91-176-11-5

it didn't take long hahahahah. Thanks for releasing.
