### ISSUE TITLE
GPL Source Request for Moto E6 (surfna - PPB29.73-81)

### ISSUE THREAD

**Issue by moldimolt** [MotorolaMobilityLLC/kernel-msm#238]
Hello, 

Please release the source code for the surfna kernel, build PPB29.73-81. As the Motorola E6 is available for sale for sale and ships with a binary/executable form of the kernel, under the terms of the GPLv2 section 3 the source code must be made available upon request in a timely manner.

Thank you.

**Comment by charleseb** [comment]
HI @suppai,

This version is in our pipeline. It will be released by next week.

Thanks,
Charles

**Comment by chenyt9** [comment]
@suppai ，
Version release：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPB29.73-81
Thanks.
Chenyt9
