### ISSUE TITLE
Source request for PPO29.80-61

### ISSUE THREAD

**Issue by asprakash** [MotorolaMobilityLLC/kernel-msm#242]
Hi. I request the kernel source for MOTO G7, PPO29.80-61, Model : XT1962-6

TIA

**Comment by charleseb** [comment]
Hi @asprakash,

We are working to release this version. It will be released by next week.

Thanks,
Charles

**Comment by asprakash** [comment]
Hi Charles. Thanks for the prompt reply and considering my request. Looking forward your further update.

May I know what are differences b/w these various kernel version though the Moto G7 Play/Power are having the same processor?. I found a nearest version MMI-PPO29.80-27. Is this different from my requested version PPO29.80-61?.

TIA.

**Comment by asprakash** [comment]
Hi. Any updates on the kernel source?

**Comment by charleseb** [comment]
Hi @asprakash,

Sorry about the delay. I'm still working to process this version before to push.
We'll release both versions MMI-PPO29.80-27 and MMI-PPO29.80-61.
These versions will be released by next week.

Thanks,
Charles

**Comment by asprakash** [comment]
@charleseb Still waiting for your release.

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPO29.80-61

**Comment by asprakash** [comment]
Thanks @charleseb 
It will be very helpful if there is any document/steps to compile this source.
TIA

**Comment by charleseb** [comment]
Version released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPO29.80-27-RIVER
Readme: https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-PPO29.80-27_RIVER.txt
