### ISSUE TITLE
Moto One Power (Chef) Kernel source request QPT30.61-18

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#243]
Hey , with Stable Q rolling out for Chef, I request you to release the kernel source for it, version QPT30.61-18 has a kernel build date of 3rd December.
It will be nice of you all to release it as soon as possible.

Rohan.

**Comment by archie9211** [comment]
Any updates? ETA?

**Comment by therootlord** [comment]
Up @charleseb

**Comment by Hasaber8** [comment]
@charleseb any update?

**Comment by charleseb** [comment]
Hi all,

I'm starting the process to release this version.
It will be released by next week.

Thanks,
Charles

**Comment by Hasaber8** [comment]
1/x weeks down.

**Comment by Hasaber8** [comment]
> Hi all,
> 
> I'm starting the process to release this version.
> It will be released by next week.
> 
> Thanks,
> Charles

2/x weeks down.

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPT30.61-18
