### ISSUE TITLE
[Request] Moto One Hyper (def) QPF30.103-21-1

### ISSUE THREAD

**Issue by Vachounet** [MotorolaMobilityLLC/kernel-msm#244]
Hi,

Could you release kernel sources for that new phone ?

Thanks

**Comment by Vachounet** [comment]
Bump @charleseb :)

**Comment by charleseb** [comment]
Hi @Vachounet,

I'm starting the process to release this version.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPF30.103-21-1
