### ISSUE TITLE
Request for PSS29.113-30 tag source update for Albus (Moto Z2 Play)

### ISSUE THREAD

**Issue by lynxis** [MotorolaMobilityLLC/kernel-msm#245]
Could you please release the sources for build PSS29.113-30 (Albus / Moto Z2 Play, Android 9 Pie) ?

**Comment by charleseb** [comment]
I think you meant PPS29.133-30. Could you confirm, please? 
I'm working to release this version.

Thanks,
Charles

**Comment by lynxis** [comment]
Hi @charleseb, correct, it's PPS29.133-30.

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPS29.133-30

**Comment by lynxis** [comment]
Thanks a lot!
