### ISSUE TITLE
[REQUEST] Kernel source release for PPIS29.65-21-2 moto g8+ (doha)

### ISSUE THREAD

**Issue by mauro235** [MotorolaMobilityLLC/kernel-msm#246]
Kernel source release for moto g8+ (doha) please, tag version PPIS29.65-21-2.

**Comment by charleseb** [comment]
Hi @mauro235,

Could you describe the tag version you need, please?

Thanks,
Charles

**Comment by mauro235** [comment]
Thanks for your fast response @charleseb !

I'm updating the comment with the tag version which is PPIS29.65-21-2

**Comment by charleseb** [comment]
Hi @mauro235,

I'm starting the process to release this version.

Thanks,
Charles

**Comment by borislavba** [comment]
@mauro235, I've just "received" OTA version PPIS29.65-24-2. According to the changelog the android version is update to the 1 November 2019 Security Patch. 
Isn't it better to update the request to the latest one or open a second issue for it?

N. B. I'm new around these requests and stuff, sorry if I'm asking obvious things :)

**Comment by mauro235** [comment]
That's the latest one from Motorola, how do I request something that does not exist yet? Besides most kernel changes are only security patch updates.

**Comment by borislavba** [comment]
Let's say that my intention was to notify you that there is an official newer version and to see if it's better to request that instead. Maybe @charleseb can tell us if there are important changes in the kernel so that we should request PPIS29.65-24-2?

**Comment by mauro235** [comment]
Seems that it's virtually the same as PPIS29.65-21-2 (which is also November 2019 patch), but a build for India which came later that's why a higher number.

**Comment by borislavba** [comment]
OK, thanks for the info. Actually I'm in Bulgaria and the "channel" is reteu, so this version might be available in Europe too. I'll try to use (or to build myself if I have the time) a custom kernel based on whatever is released by Moto as soon as possible, as I'm missing some things like e.g. Wireguard.

**Comment by mauro235** [comment]
Yeah, or at least a newer security patch. I'm looking forward to improve audio processing latency which is around 165ms (unbelievably high for today standards) and should be less than 30ms.

**Comment by charleseb** [comment]
Hi @mauro235 and @borislavba,

We'll release both versions PPIS29.65-21-2 and PPIS29.65-24-2.

Thanks,
Charles

**Comment by mauro235** [comment]
Any update or ETA? Thanks!

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPIS29.65-24-2

Thanks.

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPIS29.65-21-2
Thanks.

**Comment by mauro235** [comment]
I have seen several projects updated with those releases. Are there any steps to integrate everything and compile the kernel? Like the readme file for other devices.

**Comment by chenyt9** [comment]
@mauro235 ,please refer to: https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-PPIS29.65-21-2.txt
Thanks
