### ISSUE TITLE
GPL Source Request for Moto G6 (ali) - PPSS29.55-37-7-2

### ISSUE THREAD

**Issue by d0vine** [MotorolaMobilityLLC/kernel-msm#247]
I would like to kindly request source code (update) for build/version PPSS29.55-37-7-2 of the MSM kernel for Motorola Moto G6. As mentioned in https://github.com/MotorolaMobilityLLC/kernel-msm/issues/231 , I would like the source to be buildable so it can be used on the device.

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPSS29.55-37-7-2
