### ISSUE TITLE
Moto G7 Plus (lake) Kernel source for tag QPW30.61-21

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#249]
@charleseb 

Can you please release the kernel source and other relevant sources for tag **QPW30.61-21**?

Thank you
Joshua

**Comment by charleseb** [comment]
Hi @Jleeblanch,

I'm working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPW30.61-21
