### ISSUE TITLE
Moto G7 Play (channel) Kernel source for PPY29.105-134-7

### ISSUE THREAD

**Issue by Dizzzlectic** [MotorolaMobilityLLC/kernel-msm#250]
@charleseb 

I've got a XT1952-1 running PPY29.105-134-7 and have a project where I need to enable UVC\V4L support. Is the kernel source and\or other relevant sources for this released? If they're already released I'd appreciate a poke in the right direction.

Thank you,
Arnt

**Comment by charleseb** [comment]
Hi @SpellCraft,
I'm starting the process to release PPYS29.105-134-7.
It will be available by the next week.

**Comment by Dizzzlectic** [comment]
Thanks a lot. You're a saint.

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPYS29.105-134-7
