### ISSUE TITLE
[Request] Moto G8 Power (sofiar) kernel sources - QPE30.79-41

### ISSUE THREAD

**Issue by Vachounet** [MotorolaMobilityLLC/kernel-msm#251]
Hey,

Could you release kernel sources for this version ?

Thanks

**Comment by chenyt9** [comment]
Hi， Vacheounet，
I have started to prepare for the release of this version. Due to some processes, it will take about two weeks. Please be patient, thank you!

**Comment by Vachounet** [comment]
> Hi， Vacheounet，
> I have started to prepare for the release of this version. Due to some processes, it will take about two weeks. Please be patient, thank you!

Hi,

No problem, thank you.

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPE30.79-41
Thanks.

**Comment by Dark98** [comment]
@chenyt9 @charleseb would you be able to release the build guide for this release? I've managed a successful build, but just get reeboted to fastboot when trying to boot
