### ISSUE TITLE
Moto one "Deen" - QPK30.54-22 Kernel Sources

### ISSUE THREAD

**Issue by erfanoabdi** [MotorolaMobilityLLC/kernel-msm#252]
Hi @charleseb @chenyt9 
Could you provide the corresponding kernel source?

Thanks in advance!

**Comment by charleseb** [comment]
Hi @erfanoabdi,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPK30.54-22
