### ISSUE TITLE
Request River source release for  QPU30.52-16-2 - please include kernel-modules and techpack

### ISSUE THREAD

**Issue by Tailanbr** [MotorolaMobilityLLC/kernel-msm#253]
I would be very grateful

**Comment by wh0dat** [comment]
We all would be very grateful :)

**Comment by JuampiCarosi** [comment]
We would appreciate it please!

**Comment by charleseb** [comment]
Hi @Tailanbr,

I'm working to release this version. It will be released by Friday.

Thanks,
Charles

**Comment by wh0dat** [comment]
Thanks @charleseb

**Comment by charleseb** [comment]
Hi @Tailanbr,

Sorry about the delay. I need more a couple days to conclude this. 
This version will be released by Monday.

Thanks,
Charles

**Comment by Tailanbr** [comment]
> Hi @Tailanbr,
> 
> Sorry about the delay. I need more a couple days to conclude this.
> This version will be released by Monday.
> 
> Thanks,
> Charles

ok charles, thanks

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPU30.52-16-2
