### ISSUE TITLE
Request sources

### ISSUE THREAD

**Issue by wh0dat** [MotorolaMobilityLLC/kernel-msm#254]
OPPS27.91-179-9-11 - rhannah
PPBS29.73-81-5-8 - surfna

please :)
thanks

**Comment by chenyt9** [comment]
@wh0dat ，
Could you pls tell us the specific project name, then we will start preparing for the release. Thank you!

**Comment by chenyt9** [comment]
Hi， @wh0dat ，
We are preparing to release work, but it will take about two weeks, please be patient, thank you!

**Comment by wh0dat** [comment]
Hi and thanks for your reply
I was interested in trying to get Hannah a working 4.9 kernel so i thought
maybe can try to add to surfna's

~Barry Allen

**Comment by chenyt9** [comment]
@wh0dat ,
Version released:
PPBS29.73-81-5-8 - surfna
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPBS29.73-81-5-8
OPPS27.91-179-9-11 - rhannah
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPPS27.91-179-9-11
Thanks.
