### ISSUE TITLE
Sofiar QPE Build Guide Request

### ISSUE THREAD

**Issue by Dark98** [MotorolaMobilityLLC/kernel-msm#255]
@chenyt9 @charleseb would you be able to release the kernel & modules build guide for this release?

Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPE30.79-41
Thanks.

_Originally posted by @chenyt9 in https://github.com/MotorolaMobilityLLC/kernel-msm/issues/251#issuecomment-601508818_

**Comment by Dark98** [comment]
@charleseb @chenyt9 @awheeler-mmi

**Comment by chenyt9** [comment]
@Dark98,
Please refer to：https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QPE30.79-41.txt
Thanks.
