### ISSUE TITLE
Which defconfig should I use for moto g6 (ali)

### ISSUE THREAD

**Issue by NexelOfficial** [MotorolaMobilityLLC/kernel-msm#256]
Been looking for it for a while now. Though I might aswell ask. Which defconfig should I use for building? There are quite alot and I've been googling for ages and yet no answer.. Thanks alot!

**Comment by charleseb** [comment]
Hi @nathandiepeveen,

Could you describe the version you are building, please?

Thanks,
Charles

**Comment by NexelOfficial** [comment]
Hi there! Thanks for your response @charleseb.
I'm building version 'kernel-msm-pie-9.0.0-release-ali'

Thanks again,
Nathan

**Comment by charleseb** [comment]
Hi @nathandiepeveen,

Could you refer to a tag, please? Sometimes we use the same branch to more than one tag. Then there is better to get a tag to build.

Thanks,
Charles

**Comment by NexelOfficial** [comment]
Hi @charleseb,

I'm building:

kernel-msm-MMI-PPS29.55-24.

Thanks!

**Comment by NexelOfficial** [comment]
Hi @charleseb!

Already found something? If not, sorry for the interuption. I'm just very excited. Anyway, thanks for helping.

Nathan

**Comment by charleseb** [comment]
Hi @nathandiepeveen,

I need some time to prepare the readme file to this version.
It will be available by Friday.

Thanks,
Charles

**Comment by NexelOfficial** [comment]
Alright @charleseb 

Sounds good to me!

I appriciate it alot. Thanks!

Nathan

**Comment by NexelOfficial** [comment]
Hi @charleseb,

How are you? I was wondering how things are going with the readme file since Friday has passed already. Would love to hear from you,

Nathan

**Comment by charleseb** [comment]
Readme file released:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-PPS29.55-24.txt
