### ISSUE TITLE
[REQUEST KERNEL]

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#257]
Hello friends, I'm looking for the kernel of two devices:

Pokerp (Moto E6 Plus 2/32)
Pokerp_64 (Moto E6 Plus 4/64)

For study purposes, compilations and maintaining the famous custom rom's. Everything is ready, but I urgently need the kernel source.

**Comment by chenyt9** [comment]
Hi，@theczeman , 
Could you tell me which version do you need? Thanks.
We have released two versions: MMI-PTA29.401-18(https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-PTA29.401-18) and MMI-PTB29.401-18(https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-PTB29.401-18).
I don’t know if it can meet your needs?
The branch of the kernel code is https://github.com/MotorolaMobilityLLC/kernel-mtk/tree/pie-9.0.0-release-poker

**Comment by ItsKartik1169** [comment]
Hi I am new to this kernel building thing and etc. and I need a custom kernel  , can someone build the kernel using source code and provide the download link for that kernel or tell me how to make a custom kernel for my phone, my phone is pokerp_64 (Moto E6 Plus) (4/64) and currently I am using the pixel experience + ( plus ) 12.1 GSI right now. Please support me as soon as possible

**Comment by Krush206** [comment]
What exactly do you need help with, @ItsKartik1169? I can build and instruct you. Mail me at tateusg@protonmail.com.
