### ISSUE TITLE
[Request] Moto G5S (montana) OPPS28.65-37-7-12 kernel source

### ISSUE THREAD

**Issue by JarlPenguin** [MotorolaMobilityLLC/kernel-msm#258]
Please release the kernel source for this tag. Thank you.

**Comment by charleseb** [comment]
Hi @JarlPenguin,

We are working to release this version, it will be released by next week.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-OPPS28.65-37-7-12
