### ISSUE TITLE
[request] buildable Kernel Source for E6

### ISSUE THREAD

**Issue by anoraktrend** [MotorolaMobilityLLC/kernel-msm#259]
Not necessary if the branch is buildable. Would be nice to have, however, for various reasons.

**Comment by chenyt9** [comment]
Hi, @anoraktrend 
Could you specify which project and version? Thanks.

**Comment by anoraktrend** [comment]
ah, nevermind, didn't see the already existing surfna kernel source issue that was already closed. thanks anyway for your response.
