### ISSUE TITLE
Requesting HID driver for RZ100 for upstream inclusion

### ISSUE THREAD

**Issue by hzulla** [MotorolaMobilityLLC/kernel-msm#26]
Hi,

the RZ100 Smart Controller is a bluetooth accessory sold by Motorola. It combines a headset and a multitouch trackpad.

It works out of the box on Motorola Android phones, but [not on other manufacturers' Android devices](https://code.google.com/p/android/issues/detail?id=180029). It also does not work on [Linux desktops](http://thread.gmane.org/gmane.linux.kernel.input/44720).

Obviously, the HID driver needed to use the RZ100 comes pre-installed with Motorola products and nowhere else.

Can the Motorola Mobility team please provide this driver so that it can be included upstream with Linux desktops and stock Android?

Thank you.

**Comment by awheeler-mmi** [comment]
As far back as Marshmallow we don't have any specific driver code for the RZ100.  It looks like the device just identifies itself as 2-3 different BT devices, including a full keyboard.

**Comment by hzulla** [comment]
@awheeler-mmi There appears to be RZ100 specific code needed. I have tried pairing it with a multitude of devices, but the touchpad specific part wasn't supported.

**Comment by awheeler-mmi** [comment]
I can't find anyone here that worked on the RZ100.  After some spelunking around I found [this driver](https://github.com/MotorolaMobilityLLC/kernel-msm/blob/kitkat-4.4.4-release-titan/drivers/hid/hid-motorola.c).  This is "the" Motorola HID driver that we used for lapdock and other multitouch devices, but I can't be 100% certain that it supports RZ100. If I can find more info then I'll update this page.

**Comment by luca020400** [comment]
@awheeler-mmi pretty sure it does support it by looking at the HID in his dmesg
drivers/hid/hid-ids.h:
#define USB_VENDOR_ID_MOTOROLA		0x22b8
#define USB_DEVICE_ID_MOT_KB_1G		0x093d

dmesg:
0005:22B8:093D.0004

**Comment by awheeler-mmi** [comment]
Ah, great!

**Comment by hzulla** [comment]
Wow, thanks. I'll try it out.

**Comment by hzulla** [comment]
@awheeler-mmi I would very very much love to have the RZ100 support included in mainline. Is there any plan  on your team for adding hid-motorola to mainline?
