### ISSUE TITLE
[Request] Moto Edge (racer) kernel sources - QPD30.70-43-2

### ISSUE THREAD

**Issue by Vachounet** [MotorolaMobilityLLC/kernel-msm#260]
Hey,

Could you release kernel sources for this version ?

Thanks

**Comment by chenyt9** [comment]
Hi， @Vachounet  
We are preparing to release work, but it will take about two weeks, please be patient, thank you!

**Comment by Vachounet** [comment]
Bump :)

Maybe we could have the newer QPD30.70-58 ?

**Comment by chenyt9** [comment]
@Vachounet ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPD30.70-43-2
QPD30.70-58 is in another workflow, we are preparing.
Thanks.

**Comment by chenyt9** [comment]
@Vachounet ，
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPD30.70-58
Thanks.
