### ISSUE TITLE
[Request] Moto One Fusion + (liber) kernel sources - XT2067-2_LIBER_RETUS_10_QPIS30.73-23-1-3

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#261]
Hey,
Could you release kernel sources for this version ?
Thanks

**Comment by chenyt9** [comment]
@Hasaber8 ，
We are preparing to release work, but it will take about two weeks, please be patient, thank you!
BRs.
Chenyt9

**Comment by Hasaber8** [comment]
> @Hasaber8 ，
> We are preparing to release work, but it will take about two weeks, please be patient, thank you!
> BRs.
> Chenyt9

There is a confusion regarding exactly which chipset this device has, in India its marketed as 730G but in Europe its 730, can you clarify exactly which chipset its having?
-Rohan

**Comment by Hasaber8** [comment]
> @Hasaber8 ，
> We are preparing to release work, but it will take about two weeks, please be patient, thank you!
> BRs.
> Chenyt9

Just received an update! It will be nice if you can release QPI30.73-16-5-2.
Rohan

**Comment by chenyt9** [comment]
@Hasaber8 ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPI30.73-16-5
QPI30.73-16-5-2 is in another workflow, we are preparing.
Thanks.

**Comment by Hasaber8** [comment]
> https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPI30.73-16-5

Thank you for the release

**Comment by chenyt9** [comment]
@Hasaber8 ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPI30.73-16-5-2
Thanks.
