### ISSUE TITLE
[Request] Moto X4 (payton) - PPWS29.69-40-3-1 Kernel Source

### ISSUE THREAD

**Issue by knuxyl** [MotorolaMobilityLLC/kernel-msm#262]
Can you please release the kernel source for the latest retail Moto X4 (payton) device, thanks!
`Firmware File - PAYTON_RETAIL_9.0_PPWS29.69-40-3-1_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml.zip`
`Android Version - 9`
`Kernel version - PPWS29.69-40-3-1`

**Comment by charleseb** [comment]
Hi @knuxyl,

We are starting the process to release this version.
It will be available by Friday.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPWS29.69-40-3-1

**Comment by knuxyl** [comment]
Thank you!
