### ISSUE TITLE
diag_notify_md_client wrongly clears the md_support flag

### ISSUE THREAD

**Issue by balika011** [MotorolaMobilityLLC/kernel-msm#263]
More details: [https://github.com/MotorolaMobilityLLC/kernel-msm/commit/6947c341ef076cf5ca0af4ebb9636ba1bdb0fa03#r40575236](https://github.com/MotorolaMobilityLLC/kernel-msm/commit/6947c341ef076cf5ca0af4ebb9636ba1bdb0fa03#r40575236)

**Comment by awheeler-mmi** [comment]
Thanks, I opened an internal bug for this.
