### ISSUE TITLE
[Request] Moto G7 Play (channel) - QPYS30.52-22-2 Kernel Sources 

### ISSUE THREAD

**Issue by Deivid21** [MotorolaMobilityLLC/kernel-msm#265]
Hey,
Could you release kernel sources for this version?
Thanks :)

**Comment by charleseb** [comment]
Hi @Deivid21,

We are working to release this version. It will be available by Friday.

Thanks,
Charles

**Comment by 00p513-dev** [comment]
Any update on the source code? I am trying to build postmarketOS and would like the newer kernel sources

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPYS30.52-22-2
