### ISSUE TITLE
[REQUEST] Missing QPVS30.106-27-2 source

### ISSUE THREAD

**Issue by balika011** [MotorolaMobilityLLC/kernel-msm#266]
The QPVS30.106-27-2 source nowhere to be found and qpv30.106-27 is not compatible.

**Comment by charleseb** [comment]
Hi @balika011,

We are starting the process to release this version. It will be released by Friday.

Thanks,
Charles

**Comment by balika011** [comment]
Awesome, thanks

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPVS30.106-27-2
