### ISSUE TITLE
[Request] Moto G7 Power (ocean) - QPOS30.52-29-2 Kernel Sources

### ISSUE THREAD

**Issue by Fraaxius** [MotorolaMobilityLLC/kernel-msm#267]
Hey,
Could you release kernel sources for this version?
Thanks :)

**Comment by charleseb** [comment]
Hi @Fraaxius,

We are starting the process to release this version. It will be available by Friday.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPOS30.52-29-2
