### ISSUE TITLE
[Request] Moto G8 Plus (doha) - PPIS29.65-51-5 Kernel Sources

### ISSUE THREAD

**Issue by kytoaq** [MotorolaMobilityLLC/kernel-msm#268]
Hey,
Could you release kernel sources for this version?
Thanks :)

**Comment by charleseb** [comment]
Hi @kytoaq,

We are starting the process to release this version. It will be available by Friday.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPIS29.65-51-5
