### ISSUE TITLE
Request kernel source for sofiap 

### ISSUE THREAD

**Issue by amarc78** [MotorolaMobilityLLC/kernel-msm#269]
Can you guys please release the kernel source for sofiap QPRS30.80-58-3? Or will the source for sofiar work for sofiap (US retail)?

**Comment by amarc78** [comment]
Actually, I see sofiar source wasn't actually released.

**Comment by chenyt9** [comment]
Hi， @amarc78 
Here is a version for sofiar：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPE30.79-41
I have started to prepare for the release of this version（sofiap QPRS30.80-58-3）. Due to some processes, it will take about two weeks. Please be patient, thank you!

**Comment by amarc78** [comment]
That's ok. It's all good bro. The sofiar kernel source been working fine. Thanks!

**Comment by chenyt9** [comment]
Hi， @amarc78
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPRS30.80-58-3
Thanks.
