### ISSUE TITLE
Moto G GPE (Falcon) 5.1 Kernel Sources release request

### ISSUE THREAD

**Issue by jame25** [MotorolaMobilityLLC/kernel-msm#27]
Could the sources for this Kernel be made available please?

Kernel Version: 3.4.42-ga838857
ro.build.id=LMY47M.M001
ro.build.description=falcon_gpe-user 5.1 LMY47M.M001 6 release-keys

Thanks

**Comment by charleseb** [comment]
Hi jame25,
We will work to release this version in a few days.

Thanks,
Charles

**Comment by jame25** [comment]
Thanks Charles, I really appreciate your quick response.

**Comment by charleseb** [comment]
Hi jame25,

Tag MMI-LMY47M.M001 released.

Thanks,
Charles

**Comment by jame25** [comment]
Great! Thanks for doing that, Charles
