### ISSUE TITLE
[REQUEST] Missing branch Moto G⁷ Power (ocean) QPOS30.52-29-2 Kernel

### ISSUE THREAD

**Issue by Fraaxius** [MotorolaMobilityLLC/kernel-msm#270]
Hello! 

I can't find branch of kernel QPOS30.52-29-2 for Moto G⁷ Power (ocean)

¿You're can solve it? Thanks! :)

**Comment by charleseb** [comment]
Hi @Fraaxius,

Please refer to the tag https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPOS30.52-29-2
Sometimes we use the same branch for more than one version.

Thanks,
Charles
