### ISSUE TITLE
[Request] Moto G(8) (rav) kernel sources - QPJS30.63-35-1-9

### ISSUE THREAD

**Issue by Vachounet** [MotorolaMobilityLLC/kernel-msm#271]
Hey,

Could you release kernel sources for this device ?

Thanks

**Comment by chenyt9** [comment]
Hi,@Vachounet ,
We are preparing to release work, but it will take about two weeks, please be patient, thank you!

**Comment by chenyt9** [comment]
Hi,@Vachounet ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPJS30.63-35-1-9
Thanks.
