### ISSUE TITLE
[Request] Moto G Power (sofia) kernel sources - QPMS30.80-51-5

### ISSUE THREAD

**Issue by Vachounet** [MotorolaMobilityLLC/kernel-msm#272]
Hey,

Could you release kernel sources for this version ?

Thanks

**Comment by chenyt9** [comment]
Hi,@Vachounet ,
We are preparing to release work, but it will take about two weeks, please be patient, thank you!

**Comment by chenyt9** [comment]
Hi，@Vachounet ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPMS30.80-51-5
Thanks.
