### ISSUE TITLE
Moto Z3 Play (beckham) i need One Commit

### ISSUE THREAD

**Issue by dopaemon** [MotorolaMobilityLLC/kernel-msm#273]
# Thanks For Team Motorola
I Need Commit Adreno 509 830Mhz 
I Can't Find With This Source 
Pls Tell Me 
Thanks

**Comment by dopaemon** [comment]
U Don't Have This ?

**Comment by awheeler-mmi** [comment]
Hey @dopaemon. I'm not sure what you are requesting.  Can you be more specific? Thanks!

**Comment by dopaemon** [comment]
> Hey @dopaemon. I'm not sure what you are requesting. Can you be more specific? Thanks!

^^
Thanks Reply Me
https://support.motorola.com/us/en/documents/MS130460/

GPU Adreno 509 850Mhz

I Need Commit GPU 850Mhz For Adreno 509

But i can't find this with Source

**Comment by awheeler-mmi** [comment]
Hey @dopaemon, the Adreno runs custom firmware.  We don't open-source it.

-andrew

**Comment by dopaemon** [comment]
> Hey @dopaemon, the Adreno runs custom firmware. We don't open-source it.
> 
> -andrew

oh okay thanks u
