### ISSUE TITLE
[Request] Moto G 5G Plus - QPN30.33-40

### ISSUE THREAD

**Issue by Vachounet** [MotorolaMobilityLLC/kernel-msm#275]
Hey,

Could you release kernel sources for this version ?

Thanks.

**Comment by Vachounet** [comment]
Bump @charleseb @awheeler-mmi

**Comment by charleseb** [comment]
Hi @Vachounet,

We are working to release this version. It will be available by next week.

Thanks,
Charles

**Comment by chenyt9** [comment]
Hi, @Vachounet ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPN30.33-40
Thanks.

**Comment by Vachounet** [comment]
Could we get a readme for this release ?
Can't get it to boot, same as with racer.

**Comment by Vachounet** [comment]
Bump, @charleseb @awheeler-mmi

**Comment by chenyt9** [comment]
@Vachounet ,
Please refer to this file:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QPN30.33-40.txt
Thanks.
