### ISSUE TITLE
[Request] Moto G5S (montana_retcn/XT1799-2) NZS26.68-117-10 kernel source

### ISSUE THREAD

**Issue by JarlPenguin** [MotorolaMobilityLLC/kernel-msm#276]
Can you please release the kernel sources for this tag? Thank you.

**Comment by xiongkg1** [comment]
> Can you please release the kernel sources for this tag? Thank you.

Dear JarlPenguin, Can you confirm the version information again? 
The steps are as follows: Settings ---> About ----> ZUI Vsersion
Here is a version release of montana _retail:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NPP26.102-41
montana _retail and montana _retcn the code is basically the same. Please see if it will help you.

**Comment by JarlPenguin** [comment]
Hi,
The ZUI version is 3.1.86-128 ST. With the provided kernel source unfortunately front camera does not work.

**Comment by xiongkg1** [comment]
> Hi,
> The ZUI version is 3.1.86-128 ST. With the provided kernel source unfortunately front camera does not work.

Dear JarlPenguin
      Nzs26.68-117-10 and 3.1.86-128 st are not officially released by us. How do you get this version? Is your mobile phone purchased in the market or customized through channels?

**Comment by JarlPenguin** [comment]
I infact do not have the device itself, but I know some people have it. If the kernel source is the same for both variants, I will try to look for a solution. Thank you for your help.
