### ISSUE TITLE
[Request] Motorola One Zoom - QPH30.29-Q3-28-13

### ISSUE THREAD

**Issue by betaxab** [MotorolaMobilityLLC/kernel-msm#277]
Hi,

Could you release kernel sources for this version?

Thanks.

**Comment by charleseb** [comment]
Hi @betaxab,

We are starting the process to release this version. It will be available by Tuesday.

Thanks,
Charles

**Comment by betaxab** [comment]
@charleseb hi, could you upload this kernel's build readme? Thanks!

**Comment by charleseb** [comment]
Hi @betaxab,

I'm working to release the readme file. It will be available by Monday.

Thanks,
Charles

**Comment by betaxab** [comment]
hi, @charleseb ,

Could you release Motorola E7 ginNA's readme?

Thanks! 👍

**Comment by alexenferman** [comment]
Please release the Readme for Moto E 2020 Ginna!

**Comment by chenyt9** [comment]
@betaxab @alexenferman ,
For Motorola E7 ginNA's readme:
Pls refer to :https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QPG30.82-95.txt
Thanks.
