### ISSUE TITLE
 [Request] Moto Edge+ (burton) kernel sources - QPB30.188-58

### ISSUE THREAD

**Issue by PixlOne** [MotorolaMobilityLLC/kernel-msm#278]
I see that the kernel sources for QPB30.188-26-4 on burton are released. Can you release the updated QPB30.188-58 kernel sources?

Thanks.

**Comment by charleseb** [comment]
Hi @PixlOne,

We are starting the process to release this version. It will be released by Friday.

Thanks,
Charles

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPB30.188-58
