### ISSUE TITLE
[Request] Moto One Fusion + (liber) kernel sources - XT2067-2_LIBER_RETUS_10_QPIS30.73-23-1-3

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#279]

**Comment by chenyt9** [comment]
Hi, @Hasaber8 ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPIS30.73-23-1-3
Thanks.
