### ISSUE TITLE
[Request] Moto G8 Plus (doha) - QPI30.28-Q3-28-26 Kernel Sources

### ISSUE THREAD

**Issue by Fraaxius** [MotorolaMobilityLLC/kernel-msm#283]
Hey,
Could you release kernel sources for this version?
Thanks :)

**Comment by charleseb** [comment]
Hi @Fraaxius,

We are starting the process to release this version. It will be available by next week.

Thanks,
Charles

**Comment by Vachounet** [comment]
Bump @charleseb :)

**Comment by charleseb** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPI30.28-Q3-28-26
