### ISSUE TITLE
[Request] QCS30.58-Q3-30 source

### ISSUE THREAD

**Issue by balika011** [MotorolaMobilityLLC/kernel-msm#284]
Hello Moto!
I'm looking for the kernel source for QCS30.58-Q3-30.
Can you please provide that?

**Comment by charleseb** [comment]
Hi @balika011,

I think this is not an official release. Please check I've released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QCS30.58-Q3-44-9-11-2

Please check if this version is enough.

Thanks,
Charles
