### ISSUE TITLE
Moto G9 ( india )

### ISSUE THREAD

**Issue by vvknd** [MotorolaMobilityLLC/kernel-msm#285]
Recently purchased moto g9 ( india ) having Snapdragon 662 according to website but in about phone baseband version is shown as  M4250_XX.XXX.XX.XXR which is for Snapdragon 460.

For Snapdragon 662  baseband version should be  M6115_XX.XXX.XX.XXR.

**Comment by charleseb** [comment]
Hi @vvknd,

Could you describe the version tag(s) you need, please?

Thanks,
Charles

**Comment by vvknd** [comment]
(. Issue )
Hi @charleseb 
Here is the screenshot.
![Screenshot_20200912-163940](https://user-images.githubusercontent.com/71217846/93166997-491e2700-f73d-11ea-983e-2cc1ff4ca48e.png)

Why SD 662 phne showing baseband of sd460 ?
is Motorola cheating ?

**Comment by badmaan** [comment]
Those chipsets has a unified BSP from Qualcomm. This is not related to Motorola.

**Comment by PythonLimited** [comment]
> Those chipsets has a unified BSP from Qualcomm. This is not related to Motorola.


I looked up the modem versions at qcom, but all sdm662 have M6115 or SDM6XX.GEN.PACK.1 as unified modem version.
In fact the sdm460 isnt even included in the sdm662 BSP.

**Comment by badmaan** [comment]
No.
![20200916_122616](https://user-images.githubusercontent.com/13089901/93318898-e6e62480-f817-11ea-9f24-45be51550e25.jpg)

**Comment by PythonLimited** [comment]
> No.
> ![20200916_122616](https://user-images.githubusercontent.com/13089901/93318898-e6e62480-f817-11ea-9f24-45be51550e25.jpg)

I'm talking about the BSP.
Not the design guidelines or docs.
Send the about.html that includes both.

**Comment by badmaan** [comment]
> > No.
> > ![20200916_122616](https://user-images.githubusercontent.com/13089901/93318898-e6e62480-f817-11ea-9f24-45be51550e25.jpg)
> 
> I'm talking about the BSP.
> Not the design guidelines or docs.
> Send the about.html that includes both.

![20200916_144155](https://user-images.githubusercontent.com/13089901/93332679-dd19ec80-f82a-11ea-8ebe-876d15648023.jpg)

**Comment by PythonLimited** [comment]
> > > No.
> > > ![20200916_122616](https://user-images.githubusercontent.com/13089901/93318898-e6e62480-f817-11ea-9f24-45be51550e25.jpg)
> > 
> > 
> > I'm talking about the BSP.
> > Not the design guidelines or docs.
> > Send the about.html that includes both.
> 
> ![20200916_144155](https://user-images.githubusercontent.com/13089901/93332679-dd19ec80-f82a-11ea-8ebe-876d15648023.jpg)

What is that repo name?
I have them separated and only for R...
![Screenshot_2020-09-16-13-48-29-737_com android chrome](https://user-images.githubusercontent.com/16454674/93333326-73e2ab00-f823-11ea-92af-954ffe09ecd6.jpg)

**Comment by badmaan** [comment]
> > > > No.
> > > > ![20200916_122616](https://user-images.githubusercontent.com/13089901/93318898-e6e62480-f817-11ea-9f24-45be51550e25.jpg)
> > > 
> > > 
> > > I'm talking about the BSP.
> > > Not the design guidelines or docs.
> > > Send the about.html that includes both.
> > 
> > 
> > ![20200916_144155](https://user-images.githubusercontent.com/13089901/93332679-dd19ec80-f82a-11ea-8ebe-876d15648023.jpg)
> 
> What is that repo name?
> I have them separated and only for R...
> ![Screenshot_2020-09-16-13-48-29-737_com android chrome](https://user-images.githubusercontent.com/16454674/93333326-73e2ab00-f823-11ea-92af-954ffe09ecd6.jpg)

snapdragon-mid-2020-spf-1-0_hlos_dev revision 00018.

**Comment by chenyt9** [comment]
Hi,@vvknd ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPX30.30-Q3-38-20
Thanks

**Comment by vvknd** [comment]
> Hi,@vvknd ,
> Version released:
> https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPX30.30-Q3-38-20
> Thanks

thanks , but my concern is for baseband version.

**Comment by vvknd** [comment]
@chenyt9 my concern is for baseband version.
and thank for code.

**Comment by awheeler-mmi** [comment]
Hey @vvknd,

SM4250 and SM6115 both have a Snapdragon X11 LTE modem, and share the same modem binary.  The version number, M4250_XX.XXX.XX.XXR, is our own versioning scheme, and we tend to put the chipset number of the first chipset that the release supports, rather than all of the chipsets that the release supports.

**Comment by vvknd** [comment]
@awheeler-mmi please change string to M6115 to remove confusion.

thank you.

**Comment by awheeler-mmi** [comment]
@vvknd Oh if it were only that easy!
