### ISSUE TITLE
Android 9 OTA update for z2 play

### ISSUE THREAD

**Issue by ajaikumarnadar** [MotorolaMobilityLLC/kernel-msm#287]
Why the Indian variants of Moto z2 play haven't received Android 9 update yet ?

An year ago, we saw people receiving the update in Brazil and that too a 32-bit OS, where-in the chip is capable of 64-bit software, For ex: Moto one has sd625 and it got 64 bit os but our z2 play got 32 bit os :(.

My question is, why not in India ?

**Why are you guys doing these things? Its really annoying for us...**

**Comment by awheeler-mmi** [comment]
Hey @ajaikumarnadar. This is a great question for the [support forums](https://forums.lenovo.com/t5/Motorola-Community/ct-p/MotorolaCommunity)!  The team monitoring Github work on open-source releases.  But the team on the support forum give feedback directly to the upgrade planning teams. So ping them and let them know you are interested!
