### ISSUE TITLE
[Request]: Odessa QPA30.19-Q3-32 Kernel Sources

### ISSUE THREAD

**Issue by kytoaq** [MotorolaMobilityLLC/kernel-msm#288]
<h1> Hi Moto!  👋 </h1>
<h3> Please, could you release kernel sources for this version? </h3>
<h2> Thanks 🤨 <h2>

**Comment by chenyt9** [comment]
Hi，@kytoaq 
We have released multiple versions starting with QPA30.19-Q3-32. Could you describe the version tag(s) you need, please?
Thanks.

**Comment by kytoaq** [comment]
Well, could you provide the source code:

**ODESSA**     **BRLA_CUST**       **QPA30.19-Q3-32-21**
**ODESSA**     **BRLA_CUST**       **QPA30.19-Q3-32-39**

...and as a question, is there release of LATAM_CUST?

Thank you.

**Comment by chenyt9** [comment]
Hi,@kytoaq ,
I am starting to trigger the release process, which will take about two weeks. Please wait patiently, Thank you!
Chenyt9

**Comment by Hasaber8** [comment]
> Hi,@kytoaq ,
> I am starting to trigger the release process, which will take about two weeks. Please wait patiently, Thank you!
> Chenyt9

Hey @chenyt9 any updates on this?

**Comment by chenyt9** [comment]
@kytoaq , 
There is a problem in process.
Could you pls help reconfirm the version number？I only found this version：QPA30.19-Q3-32-39-1. Thanks.

**Comment by kytoaq** [comment]
@chenyt9 Of course, I need that version. In the same way I need you to please provide the README file to generate the correct kernel defconfig, Thanks.

**Comment by chenyt9** [comment]
@kytoaq ，
What I need to confirm is, we only have a release record for QPA30.19-Q3-32-39-1，I will release QPA30.19-Q3-32-39-1 today. Will it meet your needs?

**Comment by Hasaber8** [comment]
> @kytoaq ，
> What I need to confirm is, we only have a release record for QPA30.19-Q3-32-39-1，I will release QPA30.19-Q3-32-39-1 today. Will it meet your needs?

Definitely works!

**Comment by kytoaq** [comment]
Yes, I need this release QPA30.19-Q3-32-39-1 as you mentioned. I also request that you provide the README file to generate the correct kernel configuration (defconfig) please, thanks

**Comment by chenyt9** [comment]
Okay, no problem, I am preparing to push. The reame file will also be provided, please be patient. Thank you!

**Comment by kytoaq** [comment]
Thanks for the support 👍

**Comment by chenyt9** [comment]
@kytoaq @Hasaber8 ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPA30.19-Q3-32-21
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPA30.19-Q3-32-39-1
Readme file:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QPA30.19-Q3-32-39-1.txt

Thanks.
