### ISSUE TITLE
[request] Add support for NavIC navigation

### ISSUE THREAD

**Issue by vvknd** [MotorolaMobilityLLC/kernel-msm#291]
Moto g9 first lauched in india by saying india first...and still dont support indian navigation system..SD 662 is first Qualcomm chip to add support for NavIC... what a irony this is.
please add support of it.

![image](https://user-images.githubusercontent.com/71217846/94523190-747d3780-024e-11eb-95db-59c530472470.png)

**Comment by Hasaber8** [comment]
Hey @vvknd , I have been looking at the previous comments you made, there are certain limitation on a device stack, if you feel you want certain things added take the kernel source code and work on it yourself, and stop commenting and annoying people over here.
:-)
