### ISSUE TITLE
[Request] Full techpack drivers for 4.19 kernel (kona/lito)

### ISSUE THREAD

**Issue by erfanoabdi** [MotorolaMobilityLLC/kernel-msm#292]
Please release source code of techpack drivers for 4.19 devices
Example device tags: QCS30.58-Q3-44-9-11-2 or QPD30.70-58
Techpack includes: 

- camera
- dataipa
- display
- video
- audio

audio already available at https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-audio-kernel but other drivers missing

Thanks
cc @charleseb @awheeler-mmi @chenyt9

**Comment by erfanoabdi** [comment]
@charleseb any updates on this?
we need moto changes on below qcom repos:
https://source.codeaurora.org/quic/la/platform/vendor/opensource/camera-kernel/
https://source.codeaurora.org/quic/la/platform/vendor/opensource/display-drivers/
https://source.codeaurora.org/quic/la/platform/vendor/opensource/video-driver/
https://source.codeaurora.org/quic/la/platform/vendor/qcom-opensource/data-kernel/

(All repos licensed GPL-2.0)

Moto edge (racer) have glitchy screen on source built kernel using display driver from CAF: 
![2020-11-10 20 38 52](https://user-images.githubusercontent.com/7512922/98707024-d2945300-2394-11eb-8c6f-7ab97cfa1df7.jpg)

**Comment by erfanoabdi** [comment]
Bump @charleseb @awheeler-mmi @chenyt9

**Comment by betaxab** [comment]
hi @charleseb @awheeler-mmi @chenyt9 any updates???

**Comment by awheeler-mmi** [comment]
Hey @betaxab. Yes, sorry for delay.  We are working on the release of the techpack drivers.  We should be getting them out shortly - hopefully an early Xmas present.

**Comment by betaxab** [comment]
oh, good luck! @awheeler-mmi

**Comment by charleseb** [comment]
Hi @betaxab and @erfanoabdi,

Please find the techpack drivers listed below:
QPD30.70-58:
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-video/releases/tag/MMI-QPD30.70-58
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-camera/releases/tag/MMI-QPD30.70-58
https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-data-kernel/releases/tag/MMI-QPD30.70-58
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-display/releases/tag/MMI-QPD30.70-58

QCS30.58-Q3-44-9-11-2:
https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-data-kernel/releases/tag/MMI-QCS30.58-Q3-44-9-11-2
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-video/releases/tag/MMI-QCS30.58-Q3-44-9-11-2
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-display/releases/tag/MMI-QCS30.58-Q3-44-9-11-2
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-camera/releases/tag/MMI-QCS30.58-Q3-44-9-11-2

Sorry about the delay.

Thanks,
Charles
