### ISSUE TITLE
[Request] Moto G7 (river) QPUS30.52-33-7 kernel source

### ISSUE THREAD

**Issue by JarlPenguin** [MotorolaMobilityLLC/kernel-msm#294]
Releasing the kernel source would be much appreciated. Thank you beforehand!

**Comment by mbissaromoto** [comment]
Hi @JarlPenguin 

Version is now released: 
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPUS30.52-33-7

Att,
Marcelo
