### ISSUE TITLE
Moto E 2020 (Ginna) and sdm632 defconfig missing

### ISSUE THREAD

**Issue by alexenferman** [MotorolaMobilityLLC/kernel-msm#295]
It looks like the kernel source is not fully complete for QPG30.82-95 Moto E 2020 (Ginna). It is missing ginna_defconfig or sdm632_defconfig.
Can someone provide me the right defconfig or upload the complete kernel source?

**Comment by chenyt9** [comment]
@alexenferman ,
Pls refer to :https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QPG30.82-95.txt
Thanks.
