### ISSUE TITLE
[GPL] Release the Motorola Evolve kernel source

### ISSUE THREAD

**Issue by PythonLimited** [MotorolaMobilityLLC/kernel-msm#296]
As stated above, the kernel source for the newly launched Motorola Evolve hasn't been uploaded.
Please do so!

**Comment by Hasaber8** [comment]
> As stated above, the kernel source for the newly launched Motorola Evolve hasn't been uploaded.
> Please do so!

That device isn't handled by motorola mobility.

**Comment by mbissaromoto** [comment]
Hi @PythonLimited  
Motorola Evolve is handled by Motorola Solutions, not Motorola Mobility. Please, see here: https://github.com/MotorolaSolutions

**Comment by PythonLimited** [comment]
> Hi @PythonLimited
> Motorola Evolve is handled by Motorola Solutions, not Motorola Mobility. Please, see here: https://github.com/MotorolaSolutions

I don't see any kernel repos there either.

Can you suggest me a repo where I could open the issue?

**Comment by mbissaromoto** [comment]
> > Hi @PythonLimited
> > Motorola Evolve is handled by Motorola Solutions, not Motorola Mobility. Please, see here: https://github.com/MotorolaSolutions
> 
> I don't see any kernel repos there either.
> 
> Can you suggest me a repo where I could open the issue?

Hi @PythonLimited 
Sorry, unfortunately I can't help you with this. Motorola Solutions is a different company, and we have no internal contacts to talk about it. You can maybe try to find a project that has more issues (even if not related to kernel) and open a new one.

**Comment by awheeler-mmi** [comment]
Closing this issue, since the OS request is for a Motorola Solutions product.
