### ISSUE TITLE
[Request] Moto G8 Plus (doha) - QPIS30.28-Q3-28-26-1 Kernel Sources

### ISSUE THREAD

**Issue by Deivid21** [MotorolaMobilityLLC/kernel-msm#297]
Hey,
Could you release kernel sources for this version?
Thanks :)

**Comment by charleseb** [comment]
Hi @Deivid21,

We are working to release this version. It will be released by Monday.

Thanks,
Charles

**Comment by kytoaq** [comment]
Hi @charleseb any updates for this?

**Comment by methuselahin** [comment]
@charleseb
 +1

**Comment by charleseb** [comment]
Hi @Deivid21, @methuselahin , @kytoaq,

Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPIS30.28-Q3-28-26-1

Sorry about the delay.

Thanks,
Charles
