### ISSUE TITLE
Motorola Edge (racer) - Kernel source for tag QPD30.114-80

### ISSUE THREAD

**Issue by Jleeblanch** [MotorolaMobilityLLC/kernel-msm#298]
@charleseb @awheeler-mmi

Can you please release the kernel source and other relevant sources for tag **QPD30.114-80**?

Thank you,
Joshua

**Comment by chenyt9** [comment]
Hi，@Jleeblanch ，We are preparing to release work, but it will take about two weeks, please be patient, thank you!

**Comment by chenyt9** [comment]
@Jleeblanch ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPD30.114-80
Thanks.

**Comment by erfanoabdi** [comment]
@chenyt9 this release is missing techpack drivers (display, camera, ..)
please check https://github.com/MotorolaMobilityLLC/kernel-msm/issues/292

**Comment by erfanoabdi** [comment]
Please push this reversion for the following repos:

https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-camera
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-display
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-video
https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-data-kernel

**Comment by charleseb** [comment]
Hi @erfanoabdi,

We are working to release the techpack drivers.

Thanks,
Charles

**Comment by Jleeblanch** [comment]
@charleseb We thank you!

**Comment by mbissaromoto** [comment]
Hi @erfanoabdi 

Techpack drivers available at:
https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-data-kernel/releases/tag/MMI-QPD30.114-80
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-video/releases/tag/MMI-QPD30.114-80
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-display/releases/tag/MMI-QPD30.114-80
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-camera/releases/tag/MMI-QPD30.114-80

**Comment by erfanoabdi** [comment]
Thanks 
sorry i forgot to ask in previous comment
please push racer tag for "motorola-kernel-modules" repo

**Comment by mbissaromoto** [comment]
Hi @erfanoabdi 

It is done. Check here: https://github.com/MotorolaMobilityLLC/motorola-kernel-modules/releases/tag/MMI-QPD30.114-80

Att,
Marcelo

**Comment by erfanoabdi** [comment]
Thanks 🙏
