### ISSUE TITLE
[Request] Moto G7 Power (ocean) - QPOS30.52-29-9 Kernel Sources

### ISSUE THREAD

**Issue by Naxo79** [MotorolaMobilityLLC/kernel-msm#299]
Hi,
Could you release kernel sources for this version (QPOS30.52-29-9)?
Thanks!

**Comment by charleseb** [comment]
Hi @Naxo79,

We are starting the process to release this version. It will be released by Monday.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi @Naxo79,

Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPOS30.52-29-9
