### ISSUE TITLE
Moto G non-GPE (Falcon) 5.1 kernel sources request

### ISSUE THREAD

**Issue by ShiroiKarasu6991** [MotorolaMobilityLLC/kernel-msm#30]
Hi,

Can you please release the sources for the kernel used on this build here?
Build: Stock 5.1 for xt1032 (Brazilian Retail)
Build ID: LPB23.13-56
Build description: falcon_retbr-user 5.1 LPB23.13-56 57 release-keys

**Comment by charleseb** [comment]
Hi KingKaminari,
We will work to release this version in a few days.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi KingKaminari,

The tag MMI-LPB23.13-56 has been released.

Thanks,
Charles

**Comment by ShiroiKarasu6991** [comment]
Thanks a lot, Charles! 

Regards,
Kami
