### ISSUE TITLE
Request source kernel Motorola g7 river xt1962-4

### ISSUE THREAD

**Issue by Mcalle25** [MotorolaMobilityLLC/kernel-msm#300]
Please i need this source code
I need the kernel
preferably PPOS29.114-134-14
Pleaseeeeee

**Comment by mcirsta** [comment]
I'm in no way related to Motorola but it seems to be available here:

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPUS30.52-33-7

**Comment by Mcalle25** [comment]
Muchas gracias amigo, intentaré compilar mi kernel personalizado con esto.

**Comment by mbissaromoto** [comment]
Hi @Mcalle25 

Here it is: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPOS29.114-134-14

Att,
Marcelo

**Comment by Mcalle25** [comment]
> Hi @Mcalle25 
> 
> Here it is: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPOS29.114-134-14
> 
> Att,
> Marcelo

Thanks you, very much
