### ISSUE TITLE
[Request] Release Techpack for Moto G9 (guamp) MMI-QPX30.30-Q3-38-20

### ISSUE THREAD

**Issue by DelightReza** [MotorolaMobilityLLC/kernel-msm#302]
Kindly Release Techpack for MMI-QPX30.30-Q3-38-20 tag there is not available

**Comment by charleseb** [comment]
Hi @raza231198,

Versions released:
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-display/releases/tag/MMI-QPX30.30-Q3-38-20
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-video/releases/tag/MMI-QPX30.30-Q3-38-20
https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-data-kernel/releases/tag/MMI-QPX30.30-Q3-38-20
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-camera/releases/tag/MMI-QPX30.30-Q3-38-20

Sorry about the delay.

Thanks,
Charles
