### ISSUE TITLE
[REQUEST] Release techpack for Moto e6 (surfna) MMI-PPB29.73-81

### ISSUE THREAD

**Issue by klabit87** [MotorolaMobilityLLC/kernel-msm#305]
I formally request kernel source , techpack / vendor/qcom/audio , wifi and motorola-modules release for the MMI-PPB29.73-81 tag for surfna.
Thank you for your time.

**Comment by wh0dat** [comment]
Please @awheeler-mmi @charleseb 

Thanks

**Comment by awheeler-mmi** [comment]
They're coming very shortly!  Sorry for the delay!!

**Comment by charleseb** [comment]
Hi @wh0dat,

Please check these are the projects you are asking for:

https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-audio-kernel/releases/tag/MMI-PPB29.73-81
https://github.com/MotorolaMobilityLLC/motorola-kernel-modules/releases/tag/MMI-PPB29.73-81
https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-wlan-prima/releases/tag/MMI-PPB29.73-81
