### ISSUE TITLE
[request kernel] moto e6 play

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#306]
hello and thanks for reading.
I need the kernel of the moto e6 play bali XT2029-1 2/32 to be able to make studies of the operation of the system and the creation of the well-known custom ROMS.

**Comment by mbissaromoto** [comment]
Hi @GKart 
For exactly which tag do you need it? Example: POAS29.475-62-26-7

**Comment by ghost** [comment]
Thank you for reading.

I need POA29.550-132 please.
by the way, being the legal owner of the device I want to know what is running in the background and for that I need to be told, if possible, how to unlock the bootloader of this device.

**Comment by awheeler-mmi** [comment]
Hey @GKart,

We are working on the Bali release.  Give us a week to get it prepped and released. 

Many of our device are unloackable, and the steps are [here](https://motorola-global-portal.custhelp.com/app/standalone/bootloader/unlock-your-device-a).  I don't see Bali on the list, though.  But you should be able to check the background processes w/out unlocking the bootloader.  Are you able to adb-shell into the device?  (Sorry, my team doesn't work much with the MTK-based products so I'm not 100% sure what developer options are enabled.)

**Comment by ghost** [comment]
Hi @awheeler-mmi 
thanks
The device is totally solid and although it does not help me, your work on this device is incredible. I cannot find a way to unlock the bootloader since it detects it as unknown to all commands. It has the most limited fastboot menu I've ever seen: fastboot devices and fastboot reboot, nothing more. I think that to develop next time I will buy one with snapdragon.

**Comment by awheeler-mmi** [comment]
Yeah, I believe that MTK products use a different flashing tool than fastboot. I have never actually used it, since my team deals more with the QCOM (and SLSI)-based products.

**Comment by GKart** [comment]
> Yeah, I believe that MTK products use a different flashing tool than fastboot. I have never actually used it, since my team deals more with the QCOM (and SLSI)-based products.
Thranks

**Comment by ghost** [comment]
> Yeah, I believe that MTK products use a different flashing tool than fastboot. I have never actually used it, since my team deals more with the QCOM (and SLSI)-based products.


Thranks

**Comment by ghost** [comment]
So there is no solution for the bootloader?

**Comment by awheeler-mmi** [comment]
Yeah, there is no supported method for unlocking the Bali bootloader.

**Comment by ghost** [comment]
@awheeler-mmi thranks

**Comment by kytoaq** [comment]
Hi @awheeler-mmi any update on this? Release would be greatly appreciated, please provide ETA. Thanks.

**Comment by awheeler-mmi** [comment]
I'm moving this to [kernel-mtk](https://github.com/MotorolaMobilityLLC/kernel-mtk/issues/39) .
