### ISSUE TITLE
[request kernel] Lenovo Z6 ( L78121 )

### ISSUE THREAD

**Issue by mcirsta** [MotorolaMobilityLLC/kernel-msm#307]
I bought a Lenovo Z6 ( not pro or lite ) which was sold only in China but I'd like to get the kernel sources to develop new ROMs for it.
 I know this is mostly for Motorola devices but I have no idea where to ask for the Lenovo kernel for this one. On the support page I only found the Z6 Pro.
 Any help would be appreciated.

@charleseb @awheeler-mmi @chenyt9
  
Thank you.

**Comment by mbissaromoto** [comment]
Hi @mcirsta 

I would like to help you with this, but Lenovo phones are out of my jurisdiction. Really sorry :(

The only suggestion I can give to you is to try asking for help on [Lenovo profile in github](https://github.com/lenovo).

Att,
Marcelo
