### ISSUE TITLE
[Request] Moto G7 Plus (lake) - QPWS30.61-21-18-5 Kernel Sources

### ISSUE THREAD

**Issue by kytoaq** [MotorolaMobilityLLC/kernel-msm#308]
Hi Moto;
Could you release kernel source for this version?
Thanks :)

**Comment by mbissaromoto** [comment]
Hi @kytoaq , @Deivid21 and @GarfieldFernando

Ok, I'm working on it.

Att,
Marcelo

**Comment by kytoaq** [comment]
hi, any updates on this?

**Comment by mbissaromoto** [comment]
Hi @kytoaq 

It is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPWS30.61-21-18-5

Sorry for the delay. We are working on some improvements in our internal process to speed up this delivery for next tags.

Att,
Marcelo

**Comment by kytoaq** [comment]
Seem right. thanks for the attention and the release.
