### ISSUE TITLE
[Request] Moto G7 Power (ocean) - QPOS30.52-29-11 Kernel Sources

### ISSUE THREAD

**Issue by Deivid21** [MotorolaMobilityLLC/kernel-msm#309]
Hi, can you release kernel sources for this version?
Thanks!

**Comment by mbissaromoto** [comment]
Hi @Deivid21  and @kytoaq,

Ok, working on it.

**Comment by mbissaromoto** [comment]
Hi @Deivid21  and @kytoaq

Release is published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPOS30.52-29-11

Att,
Marcelo

**Comment by Deivid21** [comment]
> Hi @Deivid21 and @kytoaq
> 
> Release is published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPOS30.52-29-11
> 
> Att,
> Marcelo

Many thanks :)
