### ISSUE TITLE
Kernel Source Request for Moto X Pure Edition (XT1575)

### ISSUE THREAD

**Issue by HashBang173** [MotorolaMobilityLLC/kernel-msm#31]
Hi,

Can you please release the Kernel source for the new Moto X Pure Edition (XT1575).

Thanks

**Comment by charleseb** [comment]
Hi,

This product is on pre order phase, so we not able to release this version
yet.
Once we are able to release this version I'll inform to you.

Thanks,
Charles

**Comment by Shawn5162** [comment]
I see on the Motorola website that the phone is through the pre-order phase, does that mean to source will be released soon? 

Thanks,
Shawn

**Comment by charleseb** [comment]
Yes.
Once we are able to release this version I'll start this code push.

Thanks,
Charles

**Comment by Shawn5162** [comment]
Any update on the code push. One of my favorite parts of Motorola devices is quick source code releases.

**Comment by charleseb** [comment]
Hi Shawn,

We are working to release this version in a few days.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi Shawn,

The tag MMI-LPH23.116-18.1 has been released.

Thanks,
Charles

**Comment by HashBang173** [comment]
Thank you very much!

**Comment by Shawn5162** [comment]
Thanks so much
