### ISSUE TITLE
[Request] Moto G7 Play (channel) - QPYS30.52-22-12 Kernel Sources

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#311]
Hellooo guys!!
Can you release kernel sources for this version? Please, thanks! :)

**Comment by mbissaromoto** [comment]
Hi @GarfieldFernando 

I'm working on it

Att,
Marcelo

**Comment by mbissaromoto** [comment]
It is now released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPYS30.52-22-12

Att,
Marcelo

**Comment by ghost** [comment]
thank you
