### ISSUE TITLE
[Request] Moto G7 (river) - QPUS30.52-16-2-12 Kernel Sources

### ISSUE THREAD

**Issue by Naxo79** [MotorolaMobilityLLC/kernel-msm#313]
Hi!!
Can you release kernel sources for this version?
Thanks! :)

**Comment by mbissaromoto** [comment]
It is now released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPUS30.52-16-2-12

Att,
Marcelo
