### ISSUE TITLE
[Request] Moto G8 Plus (doha) - QPIS30.28-Q3-28-26-3 Kernel Sources 

### ISSUE THREAD

**Issue by Deivid21** [MotorolaMobilityLLC/kernel-msm#314]
Hi!
Can you release kernel sources for this version?
Thanks! :D

**Comment by mbissaromoto** [comment]
It is now released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPIS30.28-Q3-28-26-3

Att, 
Marcelo

**Comment by Deivid21** [comment]
> It is now released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPIS30.28-Q3-28-26-3
> 
> Att,
> Marcelo

Thanks again! :D
