### ISSUE TITLE
[Request] Moto G 5G (kiev) - QZK30.Q4-40-32 Kernel Sources

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#315]
Hello!
Can you release kernel sources for this version? Please, thx. :DD

**Comment by kytoaq** [comment]
If possible also release dtsi for kernel 4.19 please, being broad importance the device tree of kiev and drivers. Thanks.

**Comment by Deivid21** [comment]
Can release the kernel source from QZK30.Q4-40-52 and full techpack, please?
Thx!

**Comment by ghost** [comment]
sorry, I was forgetting, release for techpack too, please

**Comment by mbissaromoto** [comment]
Hi @GarfieldFernando , @Deivid21  and @kytoaq 

For a better tracking, can you please open a new issue to request this QZK30.Q4-40-52 tag?

As 40-32 is the first Kiev tag we gonna release, our internal process will take some time. After it is done and first tag is released, all next tags can be released right after. 

Att,
Marcelo

**Comment by ghost** [comment]
Ok, i will do

**Comment by mbissaromoto** [comment]
Reopening. This issue will be used to track the 40-32.

**Comment by alexguna1** [comment]
> Hi @GarfieldFernando , @Deivid21 and @kytoaq
> 
> For a better tracking, can you please open a new issue to request this QZK30.Q4-40-52 tag?
> 
> As 40-32 is the first Kiev tag we gonna release, our internal process will take some time. After it is done and first tag is released, all next tags can be released right after.
> 
> Att,
> Marcelo

Could you pls update, its been more then 2months now

**Comment by ghost** [comment]
Oh, yeah i will update

**Comment by alexguna1** [comment]
> Hi @GarfieldFernando , @Deivid21 and @kytoaq
> 
> For a better tracking, can you please open a new issue to request this QZK30.Q4-40-52 tag?
> 
> As 40-32 is the first Kiev tag we gonna release, our internal process will take some time. After it is done and first tag is released, all next tags can be released right after.
> 
> Att,
> Marcelo

The other vendor has already Released, the Kernel Sources for the same chipset. What is the issue with Motorola?.

https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/gauguin-q-oss

**Comment by mbissaromoto** [comment]
Hi guys,
 
Really sorry for the delay to reply here. Since Charles has left the company, we are in lack of human resource to take care of OSS publications. And as it is the first tag of a product, it takes even more time. We are working in the automation of this process so it doesn't require too much human effort, but it will take time. One more time: Sorry for this and please bear with us :) 

Att,
Marcelo

**Comment by Hasaber8** [comment]
Close this issue, as everything needed has been released

**Comment by mbissaromoto** [comment]
Released: https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-QZK30.Q4-40-32
