### ISSUE TITLE
[Request] Moto G 5G (kiev) - QZK30.Q4-40-52 Kernel Sources

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#316]
Hello!
Can you release kernel sources and full techpack for this version? please, thx! :)

**Comment by kytoaq** [comment]
@mbissaromoto Any updates for this? 🤔

**Comment by alexguna1** [comment]
Forum moderators could you please atleast reply with some words atleast,

**Comment by Hasaber8** [comment]
Close this issue, as everything needed has been released

**Comment by mbissaromoto** [comment]
Released: https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-QZK30.Q4-40-52
