### ISSUE TITLE
[Request] Moto G⁷ Play (Channel) - QPYS30.52-22-12 Kernel Sources

### ISSUE THREAD

**Issue by Katsumi-Minami** [MotorolaMobilityLLC/kernel-msm#317]
Hello, hello... Could you release 32bits kernel sources for this version? If u can, thank you, greetings lol

**Comment by mbissaromoto** [comment]
It is already released here, isn't?
https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-QPYS30.52-22-12
