### ISSUE TITLE
[Request] Motorola Edge S (nio) RRN31.Q1-20-17-1 kernel sources

### ISSUE THREAD

**Issue by betaxab** [MotorolaMobilityLLC/kernel-msm#318]
Hi,

Can you please release the kernel source and other relevant sources for tag RRN31.Q1-20-17-1?

I hope you could also release techpack and dts too.

Thanks a lot. 😄 

@awheeler-mmi @mbissaromoto

**Comment by chenyt9** [comment]
Hi, @betaxab ,
We are starting the process to release this version. We will release release techpack.
It may be need about two week. Please wait patiently, Thank you!

**Comment by betaxab** [comment]
@chenyt9 Thank you! Have a nice day!

**Comment by chenyt9** [comment]
Hi,@betaxab ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRN31.Q1-20-17-1
Thanks.
