### ISSUE TITLE
[Request] Motorola E7 Plus (guam) QPZS30.30-Q3-38-42-3 kernel sources

### ISSUE THREAD

**Issue by kauan-wg** [MotorolaMobilityLLC/kernel-msm#319]
Hi,

Can you please release the kernel source and other relevant sources for tag QPZS30.30-Q3-38-42-3?

I hope you could also release techpack and dts too.

Thanks a lot. smile

**Comment by chenyt9** [comment]
Hi，@kauan-wg 
We are starting the process to release this version. We will release release techpack.
It will be released within two week. Please wait patiently, Thank you!

**Comment by chenyt9** [comment]
Hi，@kauan-wg
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPZS30.30-Q3-38-42-3
Thanks.

Yuting.Chen

**Comment by yiesko** [comment]
Nice!
