### ISSUE TITLE
Moto G GPE (Falcon) 4.4.4 Kernel Sources release request

### ISSUE THREAD

**Issue by jasonst** [MotorolaMobilityLLC/kernel-msm#32]
Hi, i tried to search this tag/release but i couldn't find it, it's the latest 4.4.4 GPE available.

So, can you please release the sources for the kernel used on this build?
Build: GPE 4.4.4 for XT1032 (falcon)
Build ID: KTU84P.M003
Build description: falcon_gpe-user 4.4.4 KTU84P.M003 18 release-keys

Thank you.

**Comment by charleseb** [comment]
Hi jasonst,

We will work to release this version in a few days.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi jasonst,

The tag MMI-KTU84P.M003 has been released.

Thanks,
Charles

**Comment by jasonst** [comment]
Thank you charles, have a good day!
