### ISSUE TITLE
[Request] Moto E 2020 (GinNA) QPG30.82-132 Kernel Source

### ISSUE THREAD

**Issue by electimon** [MotorolaMobilityLLC/kernel-msm#321]
Can I get tag MMI-QPG30.82-132 ? Thanks

**Comment by chenyt9** [comment]
@electimon , we will release this version: QPG30.82-135,, will it meet your need？

**Comment by electimon** [comment]
> @electimon , we will release this version: QPG30.82-135,, will it meet your need？

Yes, thank you.

**Comment by chenyt9** [comment]
@electimon ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPG30.82-135
Thanks for your patience.
