### ISSUE TITLE
[Request] moto g pro (sofiap_sprout) - RPR31.Q4U-20-26-2

### ISSUE THREAD

**Issue by Vachounet** [MotorolaMobilityLLC/kernel-msm#323]
Hi,

Could you realease kernel sources from the R update please ?

**Comment by Vachounet** [comment]
Bump @chenyt9 @mbissaromoto :)

**Comment by kytoaq** [comment]
@mbissaromoto @chenyt9 @ccfries release when? Two months have passed and there has been no reply, please indicate when you could do it. Without the urge to interrupt, thank you

**Comment by kytoaq** [comment]
If they could upload a newer tag like RPRS31.Q4U-20-30 it would be better. Please include everything you need like drivers and techpack

**Comment by kytoaq** [comment]
@chenyt9 any update?? 🤔

**Comment by kytoaq** [comment]
Release when? @mbissaromoto @chenyt9 @awheeler-mmi

**Comment by mbissaromoto** [comment]
Hi all,

It is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPR31.Q4U-20-26-2

Regards,
Marcelo
