### ISSUE TITLE
[Request] Motorola moto g 5G plus kernel source (Android 11)

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#325]
Hi, could you please release the source code of this device?
Glowing regards.

**Comment by ghost** [comment]
The version that I would like is QPNS30.37-Q3-42-62-1 :)

**Comment by ghost** [comment]
Would it be possible to get the source code for the latest RPN31.Q4U-39-27-5 (Android 11)?

**Comment by mbissaromoto** [comment]
Same as #370
