### ISSUE TITLE
[Request] Motorola Edge Plus MMI-QPB30.188-58 Techpack sources

### ISSUE THREAD

**Issue by electimon** [MotorolaMobilityLLC/kernel-msm#326]
Although kernel tag was released, techpack tags were not. Can you release them?

**Comment by betaxab** [comment]
@awheeler-mmi @mbissaromoto please

**Comment by mbissaromoto** [comment]
Done:

https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-video/tree/MMI-QPB30.188-58
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-camera/tree/MMI-QPB30.188-58
https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-display/tree/MMI-QPB30.188-58
