### ISSUE TITLE
[Reques] Kernel Source from Motorola Moto E7 Plus (guam)

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#328]
I need the Motorola Moto E7 Plus kernel source (guam).

**Comment by RainbowCookie32** [comment]
There's #319 already

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPZS30.30-Q3-38-42-3

**Comment by yiesko** [comment]
> There's #319 already
> 
> https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPZS30.30-Q3-38-42-3

Old version, I guess

**Comment by chenyt9** [comment]
@unc0ver-debug ，Can you specify the version you need? Thanks.

**Comment by chenyt9** [comment]
Hi，@riansouzasantos 
Could you specify which version do you want? Thanks.
The current version we have released is here:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPZS30.30-Q3-38-42-3
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPZS30.30-Q3-38-66-2

**Comment by chenyt9** [comment]
Hi，@all，
Close the issue first, if there are still version requirements, please re-open this issue and specify which version you need.
Thanks.
