### ISSUE TITLE
MMI-KXC20.82-13

### ISSUE THREAD

**Issue by percy-g2** [MotorolaMobilityLLC/kernel-msm#33]
better get someone who can maintain , 5.0.2 for condor now? really go home

**Comment by dhacker29** [comment]
How are comments like this helpful in the least? It definitely does not foster communication and future cooperation with the OEM.

**Comment by fonz93** [comment]
That should be just a typo, KX it's kitkat coding.. also if you look at the commits, it is clear that is a kitkat based kernel

**Comment by charleseb** [comment]
Hi all,

You are right it was a typo. As is described on the branch this tag is
related to kitkat.
I'm checking how I can fix it.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi all,

I just fixed the typo on the tag message.

Thanks,
Charles
