### ISSUE TITLE
[Request] Please Release Kernel Source for Moto G 5g (kiev) - QZK30.Q4-40-5

### ISSUE THREAD

**Issue by someone-in-existence** [MotorolaMobilityLLC/kernel-msm#330]
Release Kernel Source for Moto G 5g, please.

**Comment by Hasaber8** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-QZK30.Q4-40-62
already released , please close the issue.

**Comment by someone-in-existence** [comment]
> https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-QZK30.Q4-40-62
> already released , please close the issue.

Thanks.
