### ISSUE TITLE
[Request] Motorola G8 Power (Sofiar) RPE31.Q4U-47-35

### ISSUE THREAD

**Issue by seba3567** [MotorolaMobilityLLC/kernel-msm#334]
Hi

Could you realease kernel sources from the R update, please ?
 thank you very much in advance @mbissaromoto

**Comment by nsherbina1999** [comment]
@chenyt9 @jwylder1 @ccfries no updates?

**Comment by nsherbina1999** [comment]
Bump @chenyt9 @jwylder1 @ccfries

Are there some issues or just an EOL?

**Comment by mbissaromoto** [comment]
Hi @nsherbina1999  and @seba3567 
It is now released: https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-RPE31.Q4U-47-35

Att,
Marcelo
