### ISSUE TITLE
[Request] Motorola Edge S Device Tree and Kernel Sources (RRN31.Q1-20-31-3)

### ISSUE THREAD

**Issue by electimon** [MotorolaMobilityLLC/kernel-msm#335]
Hello!, Can you please release kernel sources (kernel, techpacks, and devicetree) for nio RRN31.Q1-20-31-3? Thank you 😊

**Comment by betaxab** [comment]
Please please @chenyt9

**Comment by Hasaber8** [comment]
Bump @awheeler-mmi

**Comment by Hasaber8** [comment]
bump @mbissaromoto

**Comment by betaxab** [comment]
Requst Motorola Edge S Device Tree and Kernel Sources (RRN31.Q1-20-52-3)

@chenyt9 

I really need PWM related kernel updates, thank you

thanks.

**Comment by chenyt9** [comment]
Sorry for delay. Which version?RRN31.Q1-20-52-3 or RRN31.Q1-20-31-3？

**Comment by chenyt9** [comment]
Hi，@betaxab ，Which version?RRN31.Q1-20-52-3 or RRN31.Q1-20-31-3？

**Comment by Hasaber8** [comment]
RRN31.Q1-20-52-3

**Comment by chenyt9** [comment]
@Hasaber8 ，thank.
Sorry for delay, since a large number of versions pending release in our process. RRN31.Q1-20-52-3 will be released first. Under normal circumstances, it is probably within1-2 weeks. Thank you!
Yuting.Chen

**Comment by Hasaber8** [comment]
> @Hasaber8 ，thank.
> Sorry for delay, since a large number of versions pending release in our process. RRN31.Q1-20-52-3 will be released first. Under normal circumstances, it is probably within1-2 weeks. Thank you!
> Yuting.Chen

@chenyt9 first of all thank you, please do release the device trees too

**Comment by chenyt9** [comment]
Hi,@all,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRN31.Q1-20-52-3
Thanks.

**Comment by SyberHexen** [comment]
@chenyt9 
Appreciate the push of this tag but it appears the kernel-devicetree and a few others was missed:

- https://github.com/MotorolaMobilityLLC/kernel-devicetree/tags
- https://github.com/MotorolaMobilityLLC/kernel-display-devicetree/tags
- https://github.com/MotorolaMobilityLLC/kernel-camera-devicetree/tags

**Comment by electimon** [comment]
@chenyt9 bump

**Comment by chenyt9** [comment]
@SyberHexen @electimon ,Thanks for the feedback, I will re-trigger the supplementary related files.

**Comment by SyberHexen** [comment]
> @SyberHexen @electimon ,Thanks for the feedback, I will re-trigger the supplementary related files.

Any update on this?
Thanks in advance.

**Comment by electimon** [comment]
@chenyt9 @mbissaromoto Please, release DTS sources for MMI-RRN31.Q1-20-52-3, its been a few months now..

**Comment by ilia3367** [comment]
Hi! Can you please release kernel sources (Kernel, techpacks, DeviceTree) for Moto G100/Edge S? Thank you!

**Comment by electimon** [comment]
@chenyt9 :(

**Comment by ilia3367** [comment]
> @chenyt9 :(

I get the impression that these people just give standard, meaningless answers...

**Comment by chenyt9** [comment]
For the tag RRN31.Q1-20-52-3， device tree is here：
https://github.com/MotorolaMobilityLLC/kernel-display-devicetree/releases/tag/MMI-RRN31.Q1-20-52-3
https://github.com/MotorolaMobilityLLC/kernel-camera-devicetree/releases/tag/MMI-RRN31.Q1-20-52-3
https://github.com/MotorolaMobilityLLC/kernel-devicetree/releases/tag/MMI-RRN31.Q1-20-52-3
