### ISSUE TITLE
[Request] Motorola G 10 Power (capri) Device Tree and Kernel Sources (RRB31.Q1-3-34-1)

### ISSUE THREAD

**Issue by sultanahamer** [MotorolaMobilityLLC/kernel-msm#338]
Could you please publish the device tree, kernel and sources required to build AOSP for Motorola G 10 Power (capri)

**Comment by chenyt9** [comment]
@sultanahamer ,
Sorry for the delay, this version is already in our process and will be released as soon as possible. Under normal circumstances, it is probably within two weeks. Thank you!

**Comment by chenyt9** [comment]
@sultanahamer ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRB31.Q1-3-34-1
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRB31.Q1-3-34-3
Thanks.

**Comment by sultanahamer** [comment]
@chenyt9 Thanks for the links and releases. Have a good day.
