### ISSUE TITLE
Screen flickering with kitkat kernel and lollipop bootloader (41.19) on falcon

### ISSUE THREAD

**Issue by jasonst** [MotorolaMobilityLLC/kernel-msm#34]
Hi, i own a gpe falcon and i recently switched to an older kitkat GPE (latest 4.4.4) build and i am also trying to fix the screen flickering at startup (easily fixable by locking and unlocking the screen), i believe there is a commit on lollipop kernel branch that fixes this behavior, because compiling lollipop kernel and using it on kitkat GPE fixes the screen flickering. Because i want to use kitkat kernel i would like to know the single commit that adresses the issue.

Thanks in advance for your help.

**Comment by awheeler-mmi** [comment]
Ooh, sorry, we aren't in a good position to narrow down this commit.  But we do give the complete commit history so you can see what we changed, and why.  I recommend looking at the new display driver commits.
