### ISSUE TITLE
[REQUEST]: Kernel release for RPF31.Q1-21-20 - Defender aka Def

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#340]
RPF31.Q1-21-20 was pushed a few days ago, would really appreciate the kernel source being released
Bump @awheeler-mmi @mbissaromoto

**Comment by chenyt9** [comment]
@Hasaber8 ，
Sorry for delay，this version is already in our process and will be released as soon as possible. Under normal circumstances, it is probably within two weeks. Thank you!

**Comment by Hasaber8** [comment]
Bump @chenyt9 
Any updates on this?

**Comment by chenyt9** [comment]
@Hasaber8 ，Sorry, I am urging the approval process . Once approved, release the version as soon as possible.

**Comment by chenyt9** [comment]
Version released：

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPF31.Q1-21-20

Thanks

**Comment by Hasaber8** [comment]
Thank you @chenyt9 
Please look into this :- https://github.com/MotorolaMobilityLLC/kernel-msm/issues/350
