### ISSUE TITLE
[REQUEST] Kernel Release for QPX30.30-Q3-38-69 - gaump

### ISSUE THREAD

**Issue by DelightReza** [MotorolaMobilityLLC/kernel-msm#341]
QPX30.30-Q3-38-69 has been published few days ago, kindly upload kernel source as soon you can.
Bump @awheeler-mmi

**Comment by mbissaromoto** [comment]
Released: https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-QPX30.30-Q3-38-69

**Comment by Hasaber8** [comment]
@mbissaromoto you missed https://github.com/MotorolaMobilityLLC/kernel-devicetree

**Comment by mbissaromoto** [comment]
Opps, my bad. Sorry!
Check again, please

**Comment by Hasaber8** [comment]
> Opps, my bad. Sorry!
> Check again, please

thank you!

**Comment by DelightReza** [comment]
> > Opps, my bad. Sorry!
> > Check again, please
> 
> thank you!

Device Tree Released For Guamp 👀

**Comment by Hasaber8** [comment]
> > > Opps, my bad. Sorry!
> > > Check again, please
> > 
> > 
> > thank you!
> 
> Device Tree Released For Guamp 👀

https://github.com/MotorolaMobilityLLC/kernel-devicetree/blob/android-10-release-qpx30.30-q3-38-69/qcom/bengal-guamp-common-overlay.dtsi
they are there
