### ISSUE TITLE
Build errors out with [-Wformat=] error while building for cebu QZC30.Q4-22-57

### ISSUE THREAD

**Issue by mistersmee** [MotorolaMobilityLLC/kernel-msm#342]
>In file included from /home/andbuild/Downloads/and/kernel/motorola/cebu/kernel/sched/core.c:23:0:
>/home/andbuild/Downloads/and/kernel/motorola/cebu/kernel/sched/walt.h: In function 'walt_task_dump':
>/home/andbuild/Downloads/and/kernel/motorola/cebu/kernel/sched/walt.h:351:2: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'pid_t' [-Wformat=]
>error, forbidden warning: walt.h:351
>make[3]: *** [/home/andbuild/Downloads/and/kernel/motorola/cebu/scripts/Makefile.build:338: kernel/sched/core.o] Error 1
>make[2]: *** [/home/andbuild/Downloads/and/kernel/motorola/cebu/scripts/Makefile.build:643: kernel/sched] Error 2
>make[1]: *** [/home/andbuild/Downloads/and/kernel/motorola/cebu/Makefile:1143: kernel] Error 2

is the error log. I tried building on multiple systems, multiple Linux distros, multiple times, searched online to no avail. I'm not a C expert, so I couldn't figure it out. Can anyone please help, or point me in the right direction?

**Comment by napolegend** [comment]
Whats the solve??
