### ISSUE TITLE
[Request] Motorola G 30 (caprip) Kernel Sources (RRCS31.Q1-3-34-1-2)

### ISSUE THREAD

**Issue by Venkat3620** [MotorolaMobilityLLC/kernel-msm#343]
please publish  kernel ,dts,techpack drivers  for Motorola G 30 (caprip) @chenyt9 @awheeler-mmi @mbissaromoto

**Comment by chenyt9** [comment]
@Venkat3620 
Sorry for miss this msg，this version is already in our process and will be released as soon as possible. Under normal circumstances, it is probably within
two weeks. Thank you!

**Comment by Venkat3620** [comment]
Thanks for response

**Comment by ghost** [comment]
@chenyt9 any update about caprip?

**Comment by Kuntitled** [comment]
Hoping this comes out soon

**Comment by Venkat3620** [comment]
> @chenyt9 any update about caprip?

Source is already out but there are no device tree files.

https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-RRB31.Q1-3-34-3

**Comment by Kuntitled** [comment]
> > @chenyt9 any update about caprip?
> 
> Source is already out but there are no device tree files.
> 
> https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-RRB31.Q1-3-34-3

Isn't that for capri specifically?

**Comment by Venkat3620** [comment]
> > > @chenyt9 any update about caprip?
> > 
> > 
> > Source is already out but there are no device tree files.
> > https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-RRB31.Q1-3-34-3
> 
> Isn't that for capri specifically?

there is another tag MMI-RRB31.Q1-3-34-1(caprip) too that exactly has same code as this

**Comment by chenyt9** [comment]
Hi， @Venkat3620 
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRCS31.Q1-3-34-1-2
Thanks for your patient！

**Comment by chenyt9** [comment]
@Venkat3620 ,
Thanks for the feedback, I will check the device tree files and confirm the related files.
