### ISSUE TITLE
[Request] Moto G10 - RRB31.Q1-3-34-3 kernel sources

### ISSUE THREAD

**Issue by rustycl0ck** [MotorolaMobilityLLC/kernel-msm#344]
Can you please publish kernel sources for this device. Thanks!

**Comment by rustycl0ck** [comment]
@motorolamobility any updates or ETA?

**Comment by rustycl0ck** [comment]
bump @mbissaromoto

**Comment by chenyt9** [comment]
@rustycl0ck ，Sorry for the delay, this version is already in our process and will be released as soon as possible. Under normal circumstances, it is probably within two weeks. Thank you!

**Comment by rustycl0ck** [comment]
Thanks a lot for the info @chenyt9. Good to know that it is in pipeline. No worries about the delay. Prioritize safety and well-being of the staff first. Thanks!

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRB31.Q1-3-34-3

**Comment by Hasaber8** [comment]
@chenyt9 kernel-device-trees repo wasn't pushed . Please do so for caprip and nio

**Comment by rustycl0ck** [comment]
Thanks a lot for the kernel sources @chenyt9. Just waiting for the device tree now.
