### ISSUE TITLE
[Request] Moto E7 Plus [guam] - QPZS30.30-Q3-38-66-2 (Kernel Source)

### ISSUE THREAD

**Issue by yiesko** [MotorolaMobilityLLC/kernel-msm#345]
Is it possible to release the source code of kernel of Moto E7 Plus? If possible too, release the DTS/DTSI (with `techpacks` and `devicetree` too) files of Bengal platform/device please, thanks!

(Bump @chenyt9)

**Comment by chenyt9** [comment]
@Velosh ，
Sorry for miss this msg，this version is already in our process and will be released as soon as possible. Under normal circumstances, it is probably within
two weeks. Thank you!

**Comment by yiesko** [comment]
Nice, thanks! I'll be waiting.

**Comment by yiesko** [comment]
Okay so, any updates? @chenyt9

**Comment by chenyt9** [comment]
@Velosh ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPZS30.30-Q3-38-66-2
Thank you for patient！
