### ISSUE TITLE
[Request] G9+ (Odessa ) QPAS30.19-Q3-32-50-5: Kernel Source

### ISSUE THREAD

**Issue by YSpoof** [MotorolaMobilityLLC/kernel-msm#347]
Can you guys please push this source updated?

**Comment by chenyt9** [comment]
@YSpoof,
this version is already in our process and will be released as soon as possible. Under normal circumstances, it is probably within 
two weeks. Thank you!

**Comment by chenyt9** [comment]
@YSpoof ，
Version released：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPAS30.19-Q3-32-50-5
Thank you for your patient.
