### ISSUE TITLE
[REQUEST](Moto G60/G40 fusion)(Hanoip/Hanoi) RRI31.Q1-42-24-4 Kernel source

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#348]
Please release the Kernel source as soon as possible.
- Thanks, Rohan.
- bump @awheeler-mmi @mbissaromoto

**Comment by chenyt9** [comment]
Hi, @Hasaber8 ,this version is already in our process and will be released as soon as possible. Under normal circumstances, it is probably within two weeks. Thank you!

**Comment by Hasaber8** [comment]
Great work today @chenyt9 , Thank you for all the updates!

**Comment by Hasaber8** [comment]
> Hi, @Hasaber8 ,this version is already in our process and will be released as soon as possible. Under normal circumstances, it is probably within two weeks. Thank you!

Any updates @chenyt9 ?

**Comment by chenyt9** [comment]
@Hasaber8 ，
Version released：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRI31.Q1-42-24-4
Thanks for your patient.

**Comment by Hasaber8** [comment]
@chenyt9 Seems like with RRI31.Q1-42-42-3 a touch lag fix was shipped, can you please release this version?
thank you
