### ISSUE TITLE
GPL | Source request for Motorola Moto Edge (racer) (RPD31.Q4U-39-26-4)

### ISSUE THREAD

**Issue by SyberHexen** [MotorolaMobilityLLC/kernel-msm#349]
Kindly requesting source for the following repos for this tag "RPD31.Q4U-39-26-4"
- kernel-msm
- kernel-devicetree
- kernel-camera-devicetree
- kernel-display-devicetree
- kernel-msm-4.19-techpack-camera
- kernel-msm-4.19-techpack-display
- kernel-msm-4.19-techpack-video
- vendor-qcom-opensource-audio-kernel
- vendor-qcom-opensource-wlan-qcacld-3.0
- vendor-qcom-opensource-wlan-fw-api
- vendor-qcom-opensource-wlan-qca-wifi-host-cmn

Thanks in advance!
~Andrew

**Comment by SyberHexen** [comment]
bump @awheeler-mmi @mbissaromoto @chenyt9

**Comment by SyberHexen** [comment]
@chenyt9 sorry to bump again, any idea if this request has made any progress yet?

**Comment by SyberHexen** [comment]
Well this is just ridiculous...
I'll be seeking legal action over the poor display on this device plus  the violation of releasing open source in timely matter...

 I feel like I've been patient, polite and been ignored over the months while I've watched countless edge users displays go out..

Totally users did thier part but you guys too busy flooding the market with devices rather than working on the shortfalls of current issues...

**Comment by mbissaromoto** [comment]
Hi all,

It is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPD31.Q4U-39-26-4

Att,
Marcelo

**Comment by SyberHexen** [comment]
> Hi all,
> 
> It is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPD31.Q4U-39-26-4
> 
> Att, Marcelo

Thank you!
