### ISSUE TITLE
quark 5.1 release

### ISSUE THREAD

**Issue by SkrilaxCZ** [MotorolaMobilityLLC/kernel-msm#35]
@tags07  Can you make the 5.1 source release for Motorola Droid Turbo XT1254 (quark), that was pushed to phones two month ago? Thanks

**Comment by tags07** [comment]
It might be in our pipeline. I'll check.

**Comment by tags07** [comment]
SU3TL-39 & SU4TL-44 are in the pipeline. They should be posted in the next few weeks.

**Comment by SkrilaxCZ** [comment]
Thanks

**Comment by z2z** [comment]
@tags07 .. Any updates on this?

**Comment by tags07** [comment]
Its already posted..

**Comment by tags07** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-SU4TL-44

**Comment by tags07** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-SU3TL-39 is also up now
