### ISSUE TITLE
GPL | Source Request Moto G(50) (Ibiza) XT2137-1_IBIZA_RRF31.Q1-59-33

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#350]
Kindly requesting source for the following repos for this tag:-
kernel-msm
kernel-devicetree
kernel-msm-5.4-techpack-{display,video,camera}
vendor-qcom-opensource-*
motorola-kernel-modules

**Comment by Hasaber8** [comment]
Bump @awheeler-mmi @mbissaromoto @chenyt9

**Comment by PeterCxy** [comment]
Also including the following repos for the kernel modules:

-  kernel-msm-5.4-techpack-{display,video,camera}
- vendor-qcom-opensource-*
- motorola-kernel-modules

**Comment by chenyt9** [comment]
@Hasaber8 @PeterCxy ，
This version is already in our process and will be released as soon as possible. Under normal circumstances, it is probably within two weeks. Thank you!

**Comment by Hasaber8** [comment]
Bump @chenyt9 
Any updates on this?

**Comment by chenyt9** [comment]
Version released:

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRF31.Q1-59-33

Thanks.

**Comment by Hasaber8** [comment]
@chenyt9 techpack and device trees aren't pushed. Please check and release them please

**Comment by mbissaromoto** [comment]
Hi @Hasaber8  @decaduto

Missing repos are now released. Please, let me known if something else is missing.
