### ISSUE TITLE
[REQUEST] Moto G Power 2021 (Borneo) QZBS30.Q4-43-43-2 sources

### ISSUE THREAD

**Issue by iprouteth0** [MotorolaMobilityLLC/kernel-msm#351]
Please release sources for moto g power 2021 codename Borneo
Build QZBS30.Q4-43-43-2.  Thank you

**Comment by chenyt9** [comment]
@iprouteth0 ，
This version is already in our process and will be released as soon as possible. Under normal circumstances, it is probably within two weeks. Thank you!

**Comment by iprouteth0** [comment]
Still waiting on this.  I do not yet see it in the releases tags.

**Comment by lojgmyrht** [comment]
When will these sources be released?

**Comment by iprouteth0** [comment]
This is starting to get rediculous.  It has been a month and a half since I submitted this request.  If these are not released soon, I will begin prices of reporting Motorola for GPL violations to FSF (license-violation@gnu.org)

**Comment by chenyt9** [comment]
Sorry for delay. This version is already in our process, we will release both QZB30.Q4-43-130 and QZBS30.Q4-43-43-2 first. May release in these two days.

**Comment by iprouteth0** [comment]
Thank you for the update

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QZBS30.Q4-43-43-2
Thanks for your patient
