### ISSUE TITLE
[Request] Moto G Pro (sofiap) - RPRS31.Q4U-20-35 Kernel Sources [GPL]

### ISSUE THREAD

**Issue by Naxo79** [MotorolaMobilityLLC/kernel-msm#353]
Hi!!
Can you release kernel and full techpack sources for this version?
Thanks guys :D

**Comment by kytoaq** [comment]
Also requested at #323  🔢

**Comment by Naxo79** [comment]
Bump pls @chenyt9

**Comment by kytoaq** [comment]
please Moto, lunch TAG if possible as soon as possible 🤗 Don't forget to launch the necessary repositories for the sm6125 platform (trinket)

**Comment by kytoaq** [comment]
Never release? Bump @chenyt9 please 😢🙌

**Comment by kytoaq** [comment]
Hello good afternoon!!

We are very puzzled with you, we have waited for more than 7 months for this version and our request is not being taken, the developers are waiting for this tag forcing us to use a prebuilt kernel. Please give us an answer on what is happening internally, we cannot wait any longer.

Thanks you for your time

@mbissaromoto @chenyt9 @ccfries @jwylder1 @awheeler-mmi @motorolamobility

**Comment by damnthefall** [comment]
@mbissaromoto @chenyt9 @ccfries @jwylder1 @awheeler-mmi @motorolamobility 

Can we please get an update on where we stand as far as getting  the kernel and full techpack sources for sofiap RPRS31.Q4U-20-35. The lack of communication in regards to this particular issue is beginning to feel like all out neglect on behalf of Motorola.

**Comment by mbissaromoto** [comment]
Hi all,

Version released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPRS31.Q4U-20-35

Att,
Marcelo
