### ISSUE TITLE
[REQUEST] Moto G Stylus 2021 (minsk) QPCS30.Q4-31-26-1-7 sources

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#354]
Please release sources for moto g stylus 2021 codename minsk
Build QPCS30.Q4-31-26-1-7 Thank you

**Comment by chenyt9** [comment]
Hi，@animeking9901，
this version is already in our process and will be released as soon as possible. Under normal circumstances, itusually takes two weeks. Thank you!

**Comment by ghost** [comment]
Anytime! thanks for the response!

**Comment by chenyt9** [comment]
@animeking9901 ,Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPCS30.Q4-31-26-1-7
Thanks.
