### ISSUE TITLE
[Question] Branch: marshmallow-6.0.1-release-smelt, Help changing the maximum sample rate for the accelerometer in the kernel.

### ISSUE THREAD

**Issue by ntvthuyen** [MotorolaMobilityLLC/kernel-msm#356]
I'm trying to change the maximum sample rate for the accelerometer in marshmallow-6.0.1-release-smelt. 
The sample rate currently has maximum value = 50Hz when I ran "dumpsys senserservice".
I've read the source code and found a m4sensorhub driver which containing m4sensorhub-accelerometer driver.
However, I've never worked on a device with sensorhub before, I don't know how it must be done in the right way.
Can you please tell me how do I do that?

**Comment by vinimed** [comment]
Hello @lightkeima, sorry for late response. Do you still have doubts regarding the change?

**Comment by ntvthuyen** [comment]
Yeah I'm still trying to search for the solution. @vinimed Do you know something?

**Comment by asbraga-motorola** [comment]
Hi @ntvthuyen,
This forum is primarily for requesting open source code publication or questions related to it.
Please use the Moto Community Forum for all other questions:
https://forums.lenovo.com/t5/Motorola-Community/ct-p/MotorolaCommunity
