### ISSUE TITLE
[REQUEST] Motorola Moto G30 (Caprip) (RRCS31.Q1-3-34-1-4) [GPL]

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#357]
Hi everyone!
Could u release **kernel, full techpack and kernel-devicetree sources** for this tag **RRCS31.Q1-3-34-1-4**? Please!

Best regards, thank you! =)
 ~ Fernando

**Comment by ghost** [comment]
bump @chenyt9

**Comment by chenyt9** [comment]
@ferhzzoma ，this version is already in our process and will be released as soon as possible. Under normal circumstances, itusually takes two weeks. Thank you!

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRCS31.Q1-3-34-1-4
Thanks

**Comment by mikeNG** [comment]
@chenyt9 It looks like you forgot to push `MMI-RRCS31.Q1-3-34-1-4` for https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-data-kernel , can you please take a look?
