### ISSUE TITLE
[REQUEST] Kernel Release for RPX31.Q2-58-16 - guamp

### ISSUE THREAD

**Issue by DelightReza** [MotorolaMobilityLLC/kernel-msm#358]
RPX31.Q2-58-16 has been published few days ago, kindly upload kernel source as soon you can.

**Comment by DelightReza** [comment]
@mbissaromoto @awheeler-mmi

**Comment by leole0leoleo** [comment]
when will it be posted?

**Comment by leole0leoleo** [comment]
@chenyt9 @mbissaromoto @awheeler-mmi

**Comment by leole0leoleo** [comment]
@mbissaromoto pls

**Comment by mbissaromoto** [comment]
Hi @leole0leoleo 
Really sorry for the delay. It is now released.

**Comment by DelightReza** [comment]
@mbissaromoto https://github.com/MotorolaMobilityLLC/kernel-msm-4.19-techpack-display techpack is not pushed

**Comment by mbissaromoto** [comment]
@RazaDroid  as I replied on the other repo (and just to keep it in track here): it should be fine now.

Please, note that the tag was applied on top of wrong commits before, for some repos. It should be fine now, so please fetch the update. And sorry about that :(
