### ISSUE TITLE
[Request] Moto G8 Plus (doha) - QPIS30.28-Q3-28-26-4-1-4 Kernel Sources [GPL]

### ISSUE THREAD

**Issue by Deivid21** [MotorolaMobilityLLC/kernel-msm#359]
Hi!
Can you release kernel sources for this version?
Thanks! :D

**Comment by ghost** [comment]
bump @chenyt9 @awheeler-mmi @mbissaromoto

**Comment by Fraaxius** [comment]
bump @chenyt9

**Comment by Katsumi-Minami** [comment]
bump @chenyt9 @awheeler-mmi

**Comment by mbissaromoto** [comment]
Hi all,

It is now released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPIS30.28-Q3-28-26-4-1-4

Sorry for the delay. We've made some improvements in our internal process, and we hope to be faster publishing next tags.

Att,
Marcelo/@vinimed  and team
