### ISSUE TITLE
Build instructions for MMI-LPH23.116-18.1

### ISSUE THREAD

**Issue by vadimtk** [MotorolaMobilityLLC/kernel-msm#36]
Can you provide Build instructions for MMI-LPH23.116-18.1 kernel, Moto X Pure Edition ?

**Comment by tags07** [comment]
ok will check with the team and post.

**Comment by ramsudharsan** [comment]
@tags07 If possible, do update the instructions for all devices here: https://github.com/MotorolaMobilityLLC/readme

**Comment by tags07** [comment]
@ramsudharsan Sure will do.

**Comment by tags07** [comment]
https://raw.githubusercontent.com/MotorolaMobilityLLC/readme/master/MMI-LPH23.116-18.1.txt  
I made this up looking at the build logs. I have not tested it. Feel free to try it. I'll have someone test it here and fix it if it has bugs..

We'll try to update for other products that have different instructions..if you need something immediate, Let me know..i can prioritize that.

**Comment by vadimtk** [comment]
@tags07 great, thanks!

I wonder if you can post command line how to build boot.img after this.
That would be greatly appreciated.

**Comment by tags07** [comment]
Well boot.img is out of scope for me.. Long ago I have used mkbootimg to pack it. I am not sure if things have changed. Its been a while I built my own custom boot image. I'll ask around to see if they can post an easy instruction..

May be our friends in XDA can help: http://forum.xda-developers.com/showthread.php?t=2319018

**Comment by aloknnikhil** [comment]
@tags07 So first off, the build instructions seem a bit off. The dtb generated is only for the "bunkerhill" family and none for clark. This means the system won't go past the bootloader. I fixed this by building the dtbs for clark. But now, this brings it back to the same old issue of instant reboot at the unlocked bootloader warning screen

**Comment by gokart2** [comment]
Have the "clark" MMI-LPH23.116-18.1 kernel build instructions been created/updated/posted yet? Cannot get it to build, mostly because I have little background on kernel building. Build instructions would be greatly appreciated

**Comment by vadimtk** [comment]
@gokart2 build instructions are here
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-LPH23.116-18.1.txt

and you can check my build script:
https://github.com/vadimtk/moto-x-kernel/blob/master/build-uber.sh
