### ISSUE TITLE
[Request] Moto G9 Power (cebu) - RZCS31.Q2-57-12-2 kernel sources

### ISSUE THREAD

**Issue by mistersmee** [MotorolaMobilityLLC/kernel-msm#360]
Kindly requesting source for the following repos for this tag "RZCS31.Q2-57-12-1"

    kernel-msm
    kernel-devicetree
    motorola-kernel-modules
    kernel-camera-devicetree
    kernel-display-devicetree
    kernel-msm-4.19-techpack-camera
    kernel-msm-4.19-techpack-display
    kernel-msm-4.19-techpack-video
    vendor-qcom-opensource-audio-kernel
    vendor-qcom-opensource-wlan-qcacld-3.0
    vendor-qcom-opensource-wlan-fw-api
    vendor-qcom-opensource-wlan-qca-wifi-host-cmn

Thanks in advance!

**Comment by mistersmee** [comment]
Bump @awheeler-mmi @chenyt9 @mbissaromoto

**Comment by mistersmee** [comment]
Bump @chenyt9

**Comment by mistersmee** [comment]
Bump @chenyt9

**Comment by mistersmee** [comment]
Bump @chenyt9 @awheeler-mmi @mbissaromoto

**Comment by mistersmee** [comment]
Bump @chenyt9 @awheeler-mmi @mbissaromoto

**Comment by mistersmee** [comment]
If there were any changes between the newer tags, having those would be great as well.

**Comment by mistersmee** [comment]
Bump @chenyt9 @awheeler-mmi @mbissaromoto 
It's been 1.5 months, any updates as to when it's going to be released?

**Comment by mistersmee** [comment]
Bump @chenyt9 @mbissaromoto @awheeler-mmi 

With the recent releases for guamp and nio, I hoped that this would be released too. It's been 2 months since I opened the issue.

**Comment by mistersmee** [comment]
@chenyt9 @mbissaromoto @awheeler-mmi 

The second security update since the update to Android 11 has even dropped, and still kernel source for cebu have not been released.
It will almost be 3 months since opening the issue soon. When will cebu sources be released?

**Comment by mistersmee** [comment]
Bump @chenyt9 @mbissaromoto @motorolamobility @vinimed 

It has been just about 4 months since I opened the issue, when are Cebu sources going to be released? With the recent releases for a few devices, I had hoped that cebu would be one of them.

**Comment by vinimed** [comment]
Hello, all!
Version Released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RZCS31.Q2-57-12-1

Note: We had already started the process when you updated the request from 12-1 suffix to a superior. If you still need the informed releases above, please consider to open a new issue.

Thank you for your patience and comprehension.
