### ISSUE TITLE
[REQUEST] Moto G Power 2021 (Borneo) - MMI-QZBS30.Q4-43-43-2 - all device tree/dts sources

### ISSUE THREAD

**Issue by iprouteth0** [MotorolaMobilityLLC/kernel-msm#362]
Kindly release the following sources (all device tree/dts) for borneo(moto g power 2021).  Tag MMI-QZBS30.Q4-43-43-2 

kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree

Other sources have already been released.
Thanks
James

**Comment by ghost** [comment]
bump @chenyt9 pls

**Comment by chenyt9** [comment]
@ferhzzoma @iprouteth0 ,pls refer to 'MMI-QZBS30.Q4-43-43-2' tag on devicetree repo.
like:
https://github.com/MotorolaMobilityLLC/kernel-devicetree/releases/tag/MMI-QZBS30.Q4-43-43-2
https://github.com/MotorolaMobilityLLC/kernel-display-devicetree/releases/tag/MMI-QZBS30.Q4-43-43-2
https://github.com/MotorolaMobilityLLC/kernel-camera-devicetree/releases/tag/MMI-QZBS30.Q4-43-43-2
