### ISSUE TITLE
[Request] Moto One Fusion (astro) RPLS31.Q2-63-10-2-2 Sources

### ISSUE THREAD

**Issue by uotlaf** [MotorolaMobilityLLC/kernel-msm#364]
Hi! I will wait you release the kernel source, device tree and tech pack. Thanks!

**Comment by uotlaf** [comment]
Android 11 update: RPL -> RPLS

**Comment by vinimed** [comment]
Hello @uotlaf,
Version released:
https://github.com/MotorolaMobilityLLC/external-libcxx/releases/tag/MMI-RPLS31.Q2-63-10-2-2

Thank you for your patience.

**Comment by uotlaf** [comment]
> Hello @uotlaf, Version released: https://github.com/MotorolaMobilityLLC/external-libcxx/releases/tag/MMI-RPLS31.Q2-63-10-2-2
> 
> Thank you for your patience.

Thanks!
