### ISSUE TITLE
[REQUEST] Moto g20 (java) RTA31.42-5-5 sources

### ISSUE THREAD

**Issue by Mashopy** [MotorolaMobilityLLC/kernel-msm#365]
Hello, could you release the kernel and kernel modules source for the Motorola g20 (java) from RTA31.42-5-5 please ?

That's a Unisoc Tiger T700 powered device however

**Comment by Mashopy** [comment]
@awheeler-mmi @chenyt9 @mbissaromoto

**Comment by Hasaber8** [comment]
bump @chenyt9

**Comment by Mashopy** [comment]
Bump @chenyt9

**Comment by DavidDeath21** [comment]
kernel source error... please share Source

**Comment by Pipump** [comment]
Please share the source...

**Comment by Tokoteke** [comment]
could you release the kernel and kernel modules source for the Motorola g20 (java) from RTA31.68-29
please ?

**Comment by Zonik94** [comment]
Please take our request into consideration, a new kernel update has just come out if possible to source this thousands of users and devs will be grateful @awheeler-mmi @chenyt9 @mbissaromoto 🙏

**Comment by zmoky2468** [comment]
Hello, could you release the kernel and kernel modules source for the Motorola g20 (java) from RTA31.42-5-5 please ?

That's a Unisoc Tiger T700 powered device however
Hail UwU.

**Comment by SantiiAgoo5121** [comment]
@awheeler-mmi @chenyt9 @mbissaromoto 🙏🏻🙏🏻🙏🏻

**Comment by Claravallac** [comment]
Hello moto???
Source??? 

@chenyt9

**Comment by Claravallac** [comment]
@chenyt9
@awheeler-mmi
@TinnoOSS
@asbraga-motorola
@mbissaromoto

Bump it, please

**Comment by asbraga-motorola** [comment]
A more recent version has been published on #413: 
https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-RTAS31.68-34-2

**Comment by Mashopy** [comment]
The source for building the kernel modules present on socko partition are still not released for all Motorola unisoc devices
