### ISSUE TITLE
[REQUEST] Moto Edge S - RRN31.Q2-12-14-7 - all device tree/dts sources

### ISSUE THREAD

**Issue by gyfx** [MotorolaMobilityLLC/kernel-msm#367]
Kindly release the following sources (all device tree/dts) for nio(moto edge s). Tag  RRN31.Q2-12-14-7

kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree

Thanks

**Comment by gyfx** [comment]
bump @chenyt9  pls

**Comment by chenyt9** [comment]
@gyfx ，this version is already in our process and will be released as soon as possible. Under normal circumstances, itusually takes two weeks. Thank you!

**Comment by SGCMarkus** [comment]
I suppose those sources will then work fine too for the G100 (nio, RRTS31.Q1-84-21-1-2), as the devices are basically the same, and just marketed for different regions?

**Comment by mukul2259** [comment]
Bump, would love to see sources so that developers can work on it.

**Comment by chenyt9** [comment]
@gyfx ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRN31.Q2-12-14-7
Thanks

**Comment by Hasaber8** [comment]
@chenyt9 again, device tree weren't pushed 😥

**Comment by electimon** [comment]
@chenyt9 since may we've been waiting for these sources...

https://github.com/MotorolaMobilityLLC/kernel-msm/issues/335#issuecomment-839707469

**Comment by Hasaber8** [comment]
@awheeler-mmi you promised us proper kernel release with device trees, but again and again kernels are getting released without them ಠ︵ಠ

**Comment by Hasaber8** [comment]
Also consistently false timelines are given, making the whole matter worse, seems like you guys haven't recovered from https://github.com/charleseb leaving the team

**Comment by SGCMarkus** [comment]
yep, kinda a shame, these are such nice devices
I dont get why you wouldnt release the kernel devicetrees, other manufacturers manage to do that too

**Comment by chenyt9** [comment]
@SGCMarkus ，@Hasaber8 ，
Sorry for the missing device-tree code, I have re-triggered a new release process. Will release as soon as possible. Thanks for your patience.

**Comment by chenyt9** [comment]
@Hasaber8 ,I'm sorry I don't quite understand what you mean of the "false timelines", what problem are you referring to? The code is released as is, there should be no errors.

**Comment by Hasaber8** [comment]
> @Hasaber8 ,I'm sorry I don't quite understand what you mean of the "false timelines", what problem are you referring to? The code is released as is, there should be no errors.

I was referring to, when you say in under normal circumstances it will release in 2 weeks but it takes 4-5 weeks. I understand nothing is normal of the current circumstances.

Also please add device trees to the new process, the delay just forces us to prebuild the kernel.
Also please look into https://github.com/MotorolaMobilityLLC/kernel-msm/issues/323
Its been pending for 7 months now. Again forcing us to prebuild the kernel.

**Comment by Hasaber8** [comment]
Also @chenyt9 please don't take it in the wrong way, the kernel release has been very slow lately compared to last few years.

**Comment by chenyt9** [comment]
@SGCMarkus ，@Hasaber8 ， 
For kernel device tree, pls refer to:
https://github.com/MotorolaMobilityLLC/kernel-display-devicetree/releases/tag/MMI-RRN31.Q2-12-14-7
https://github.com/MotorolaMobilityLLC/kernel-camera-devicetree/releases/tag/MMI-RRN31.Q2-12-14-7
https://github.com/MotorolaMobilityLLC/kernel-devicetree/releases/tag/MMI-RRN31.Q2-12-14-7

**Comment by Hasaber8** [comment]
Thank you @chenyt9

**Comment by SGCMarkus** [comment]
Thanks @chenyt9
