### ISSUE TITLE
GPL | Source request for Motorola Moto Edge 20 (Berlin) RRG31.Q3-23-12 (XT2143-1)

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#368]
Kindly requesting sources for the following repos for this tag "RRG31.Q3-23-12"

kernel-msm
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-5.4-techpack-camera
kernel-msm-5.4-techpack-display
kernel-msm-5.4-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn
Thanks in advance!
~Rohan

**Comment by Hasaber8** [comment]
I know there are a lot of pending backlogs of device source releases. But if Motorola has decided to release devices at the rate Xiaomi releases devices then they should also be ready to release device sources as fast as Xiaomi.
Bump @awheeler-mmi @chenyt9

**Comment by SGCMarkus** [comment]
I'll second this. 
Would like to have the sources for this.

**Comment by mukul2259** [comment]
Bump, would love to see sources so that developers can work on it.

**Comment by Pulkit077** [comment]
Bump
![Alt Text](https://media.giphy.com/media/tXL4FHPSnVJ0A/giphy.gif)

**Comment by chenyt9** [comment]
@Hasaber8 ，Can you specify the required version? I cannot find out that RRG31.Q3-23-12 has been released. If I choose to release version RRG31.Q3-23-25-1, will it meet your needs?

**Comment by Hasaber8** [comment]
Sure @chenyt9 RRG31.Q3-23-25-1 works

**Comment by Hasaber8** [comment]
> Sure @chenyt9 RRG31.Q3-23-25-1 works

**Comment by Hasaber8** [comment]
@chenyt9 please also release the device tree for kernel 5.4 and all the relevant things, already listed above

**Comment by chenyt9** [comment]
Hi, @Pulkit077 @SGCMarkus @Hasaber8 @mukul2259 
Will release RRG31.Q3-23-25-1 version. The release process of the version has been triggered and it may be need take about two weeks. We will release it as soon as possible, will include device tree gits. Please wait patiently, thanks!

**Comment by Hasaber8** [comment]
Thank you @chenyt9

**Comment by Hasaber8** [comment]
bump @chenyt9 almost approaching 3 weeks now

**Comment by Hasaber8** [comment]
> Hi, @Pulkit077 @SGCMarkus @Hasaber8 @mukul2259
> Will release RRG31.Q3-23-25-1 version. The release process of the version has been triggered and it may be need take about two weeks. We will release it as soon as possible, will include device tree gits. Please wait patiently, thanks!

It been a month now -_- @chenyt9

**Comment by SGCMarkus** [comment]
Not like i have much time atm to work with this, but i agree with @Hasaber8 
Its been a loooong time since the launch of these devices, its time you provide proper sources...

**Comment by chenyt9** [comment]
Hi, @Pulkit077 @SGCMarkus @Hasaber8 @mukul2259,

Sorry for delay.Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRG31.Q3-23-25-1

Thanks.
