### ISSUE TITLE
GPL | Source request for Motorola Moto Edge 20 Pro (pstar) RRA31.Q3-19-19 (XT2153-1) 

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#369]
Kindly requesting sources for the following repos for this tag "RRA31.Q3-19-19"

kernel-msm
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-4.19-techpack-camera
kernel-msm-4.19-techpack-display
kernel-msm-4.19-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn
Thanks in advance!
~Rohan

**Comment by Hasaber8** [comment]
I know there are a lot of pending backlogs of device source releases. But if Motorola has decided to release devices at the rate Xiaomi releases devices then they should also be ready to release device sources as fast as Xiaomi.
Bump @awheeler-mmi @chenyt9 @mbissaromoto

**Comment by SGCMarkus** [comment]
I'll second this. 
Would like to have the sources for this aswell.

**Comment by mukul2259** [comment]
Bump, would love to see sources so that developers can work on it.

**Comment by electimon** [comment]
Smol bump

**Comment by chenyt9** [comment]
Hi, @electimon @SGCMarkus  @Hasaber8 
The release process of the version has been triggered and it may be need take about two weeks. We will release it as soon as possible,  will include device tree gits. Please wait patiently, thanks!

**Comment by Hasaber8** [comment]
Thank you @chenyt9 we will be patiently waiting.

**Comment by ilia3367** [comment]
https://dumps.tadiphone.dev/dumps/motorola/pstar/-/tree/msi_prc-user-11-RRAA31.Q3-19-33-1-d699dd-release-keys/

**Comment by lss4** [comment]
+1 on this. If possible, the RRAA31.Q3-19-46 (Edge S Pro) version as well.

Don't know about the differences between the two variants in terms of kernel, though.

**Comment by Hasaber8** [comment]
> +1 on this. If possible, the RRAA31.Q3-19-46 (Edge S Pro) version as well.
> 
> Don't know about the differences between the two variants in terms of kernel, though.

@lss4 edge s pro and edge 20 pro are the same thing - codenamed pstar

**Comment by ilia3367** [comment]
> > +1 on this. If possible, the RRAA31.Q3-19-46 (Edge S Pro) version as well.
> > Don't know about the differences between the two variants in terms of kernel, though.
> 
> @lss4 edge s pro and edge 20 pro are the same thing - codenamed pstar

Yes, the codename is the same, but the firmware is different. And boot.img and vendor are different too.

**Comment by electimon** [comment]
Hello @chenyt9 its been 2 weeks

**Comment by Hasaber8** [comment]
> Hi, @electimon @SGCMarkus @Hasaber8 The release process of the version has been triggered and it may be need take about two weeks. We will release it as soon as possible, will include device tree gits. Please wait patiently, thanks!

Approaching 4 weeks😕

**Comment by Hasaber8** [comment]
> Hi, @electimon @SGCMarkus @Hasaber8
> The release process of the version has been triggered and it may be need take about two weeks. We will release it as soon as possible, will include device tree gits. Please wait patiently, thanks!

It been a month now -_- @chenyt9

**Comment by SGCMarkus** [comment]
Not like i have much time atm to work with this, but i agree with @Hasaber8 
Its been a loooong time since the launch of these devices, its time you provide proper sources...

**Comment by lss4** [comment]
By the way, has this device received any new OTA update recently?

EDIT: [Guess not...](https://mirrors.lolinet.com/firmware/moto/pstar/official/)

**Comment by electimon** [comment]
@chenyt9 :/

**Comment by electimon** [comment]
> Hi, @electimon @SGCMarkus @Hasaber8
> The release process of the version has been triggered and it may be need take about two weeks. We will release it as soon as possible, will include device tree gits. Please wait patiently, thanks!

It's been a whole month!!! At least can we get an explanation? Knowing why it can't be released is better than no communication at all.

**Comment by chenyt9** [comment]
Hi, @all , sorry for delay ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRA31.Q3-19-19
Thanks.

**Comment by kytoaq** [comment]
@chenyt9 Please I need you to answer the issue #353 the 10 months of waiting is exasperating :(

**Comment by error0x001** [comment]
Does it work? I tried to compile all of configs (depconfig, gki_depconfig, ranchu64_depconfig), but I had a lot of errors

```
../scripts/Makefile.build:338: recipe for target 'kernel/sched/fair.o' failed
/kernel/Makefile:1200: recipe for target 'arch/arm64/kernel' failed
../scripts/Makefile.build:338: recipe for target 'kernel/sched/fair.o' failed
../scripts/Makefile.build:642: recipe for target 'kernel/sched' failed
../scripts/Makefile.build:338: recipe for target 'mm/memory.o' failed
```

and so on
