### ISSUE TITLE
GPL | Source request for Motorola Moto G 5G Plus (nairo) RPN31.Q4U-39-27-5-20

### ISSUE THREAD

**Issue by dgigantino** [MotorolaMobilityLLC/kernel-msm#370]
Hi. Could you please release the kernel, kernel modules source and the dts for Android 11 on nairo Moto G 5G Plus?
This includes:

kernel-msm
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-4.19-techpack-camera
kernel-msm-4.19-techpack-display
kernel-msm-4.19-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn

**Comment by dgigantino** [comment]
Bump @awheeler-mmi @chenyt9 @mbissaromoto

**Comment by Vachounet** [comment]
Bump @awheeler-mmi @chenyt9 @mbissaromoto

**Comment by dgigantino** [comment]
The source code has been released at https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPN31.Q4U-39-27-5.
