### ISSUE TITLE
Please upload kernel sources for new lineup

### ISSUE THREAD

**Issue by J0SH1X** [MotorolaMobilityLLC/kernel-msm#371]
hey , i would like to rqeuest the upload of the kernel sources of the motorola edge s edge 20 and edge 20 pro.

it would be pretty nice if you could publish them as GPL does require it.

thx in advance

**Comment by chenyt9** [comment]
Hi,@J0SH1X ，
Here is version released for edge s，can it meet you need？
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRN31.Q1-20-52-3
for other product， could you please specify the version you need. Thank.

**Comment by Hasaber8** [comment]
> Hi,@J0SH1X ，
> Here is version released for edge s，can it meet you need？
> https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRN31.Q1-20-52-3
> for other product， could you please specify the version you need. Thank.

You guys forgot to push device trees for this release, please do that

**Comment by chenyt9** [comment]
@J0SH1X ， Pls use the device tree code first, I will check the code and repost the tag for MMI-RRN31.Q1-20-52-3 .
https://github.com/MotorolaMobilityLLC/kernel-display-devicetree/releases/tag/MMI-RRN31.Q2-12-14-7
https://github.com/MotorolaMobilityLLC/kernel-camera-devicetree/releases/tag/MMI-RRN31.Q2-12-14-7
https://github.com/MotorolaMobilityLLC/kernel-devicetree/releases/tag/MMI-RRN31.Q2-12-14-7
Thanks

**Comment by chenyt9** [comment]
Hi， @J0SH1X ，device trees is here
https://github.com/MotorolaMobilityLLC/kernel-display-devicetree/releases/tag/MMI-RRN31.Q1-20-52-3
https://github.com/MotorolaMobilityLLC/kernel-camera-devicetree/releases/tag/MMI-RRN31.Q1-20-52-3
https://github.com/MotorolaMobilityLLC/kernel-devicetree/releases/tag/MMI-RRN31.Q1-20-52-3
