### ISSUE TITLE
| GPL | [Request] | Moto G⁹ Plus | odessa_retail | RPAS31.Q2-59-17-3 |

### ISSUE THREAD

**Issue by kytoaq** [MotorolaMobilityLLC/kernel-msm#372]
Hi there. 

Please can you upload the version **RPA31.Q2-59-17** with all the relevant repositories. Thank you.

**Comment by YSpoof** [comment]
I'm waiting for it too :)

@chenyt9

Pls ??

**Comment by kytoaq** [comment]
Upload plz sir @ccfries @mbissaromoto

**Comment by vinimed** [comment]
Hello, @kytoaq and @YSpoof,

The version was released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPA31.Q2-59-17

Thanks for your patience.
BRs,
Vinicius Medeiros
