### ISSUE TITLE
GPL | Motorola Moto G Power (2021) Borneo QZBS30.Q4-43-120-5 Source release

### ISSUE THREAD

**Issue by MrNerd** [MotorolaMobilityLLC/kernel-msm#374]
Can you please release the kernel source for this phone?

Thank you

 Motorola Moto G Power (2021) Borneo QZBS30.Q4-43-120-5

**Comment by thebestofall007** [comment]
It would also be nice to release the device tree, too.

**Comment by MrNerd** [comment]
I think i have the Device tree. If you want i can send it to you and you can tell me if its correct.

**Comment by thebestofall007** [comment]
> I think i have the Device tree. If you want i can send it to you and you can tell me if its correct.

Yes, please do. How would I be able to tell if it's correct though? I have this phone. I'm new at this but I would love to try my hand at building a custom lineage ROM.

So it's just the kernel sources that are needed now?

**Comment by MrNerd** [comment]
I have no clue sir.. Im just as new as you. I found a tree generator script made in python and that's how I got it.

**Comment by thebestofall007** [comment]
> I have no clue sir.. Im just as new as you. I found a tree generator script made in python and that's how I got it.

That's OK. I'll still take the tree if you could send it please. If I don't find out if it's the right one myself, perhaps someone else can if I upload it to XDA Forums

**Comment by MrNerd** [comment]
https://github.com/MrNerd/MotoGPower_2020_DT

**Comment by chenyt9** [comment]
Hi，@MrNerd 
The release process of the version has been triggered and it may be need take about two weeks. We will release it as soon as possible，includes the device tree code. 
The released versions are:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QZB30.Q4-43-130
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QZBS30.Q4-43-43-2
I don’t know if we can meet your needs first. please wait patiently, thanks!

**Comment by MrNerd** [comment]
Thank you for the reply. Can you also tell me how to compile for Borneo because i dont see a Defconfig file for that phone

**Comment by arkansawdave74** [comment]
What's up guys. I just got this this phone too and i might be of some help. I'm not great at building roms, but I have several lolipop and several nougat builds on afh. Sometimes I get lucky. Would you be willing to share your tree with me as well, @MrNerd ?

**Comment by MrNerd** [comment]
Sure its on my Github

**Comment by chenyt9** [comment]
@MrNerd ,
For the config , pls refer to:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QZBS30.Q4-43-120-5.txt
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QZBS30.Q4-43-120-5
Thanks.
