### ISSUE TITLE
Edge 2021 RRM31.Q3-23-29-5 kernel source

### ISSUE THREAD

**Issue by Dabug123** [MotorolaMobilityLLC/kernel-msm#375]
Would love to see this available along with a tree for development

**Comment by chenyt9** [comment]
Hi, @Dabug123 
The release process of the version has been triggered and it may be need about two weeks. We will release it as soon as possible. Please wait patiently, thanks!

**Comment by Dabug123** [comment]
Thanks.There wasnt source on the previous ver or the device release ..

Thanks for your time

**Comment by Dabug123** [comment]
I hope we are working towards a release of a source soon following this repo it seems multiple devices are very behind ..Great device overall gonna be sad if development is hindered by lack of source

**Comment by Dabug123** [comment]
No offense guys buy not only are you not living up to your promise of bi monthly updates you are not pushing source.. Probably move back to pixel.. Enjoy the device but doesn't seem like you guys can keep up with development

**Comment by Dabug123** [comment]
> Hi, @Dabug123 The release process of the version has been triggered and it may be need about two weeks. We will release it as soon as possible. Please wait patiently, thanks!

Still nothing sadly moto is same

**Comment by chenyt9** [comment]
@Dabug123
Sorry for delay, Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRM31.Q3-23-29-5
Thanks.
