### ISSUE TITLE
[Request] Motorola Moto G30 (caprip) GPL sources (RRCS31.Q1-3-56-2)

### ISSUE THREAD

**Issue by mikeNG** [MotorolaMobilityLLC/kernel-msm#376]
Could you please release kernel sources for caprip 'RRCS31.Q1-3-56-2' build?

Includes the following repositories:

```
kernel-msm
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-4.19-techpack-camera
kernel-msm-4.19-techpack-display
kernel-msm-4.19-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-data-kernel
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn
vendor-qcom-opensource-wlan-qcacld-3.0
motorola-kernel-modules
```

**Comment by ghost** [comment]
bump @chenyt9 @awheeler-mmi

**Comment by Hasaber8** [comment]
> Could you please release kernel sources for caprip 'RRCS31.Q1-3-56-2' build?
> 
> Includes the following repositories:
> 
> ```
> kernel-msm
> kernel-devicetree
> kernel-camera-devicetree
> kernel-display-devicetree
> kernel-msm-4.19-techpack-camera
> kernel-msm-4.19-techpack-display
> kernel-msm-4.19-techpack-video
> vendor-qcom-opensource-audio-kernel
> vendor-qcom-opensource-data-kernel
> vendor-qcom-opensource-wlan-fw-api
> vendor-qcom-opensource-wlan-qca-wifi-host-cmn
> vendor-qcom-opensource-wlan-qcacld-3.0
> motorola-kernel-modules
> ```

https://github.com/MotorolaMobilityLLC/kernel-devicetree/releases/tag/MMI-RRCS31.Q1-3-34-1-4

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRCS31.Q1-3-34-1-4

I doubt there's anything new in the release you asked for, these should work perfectly fine

**Comment by chenyt9** [comment]
@ferhzzoma ,@Hasaber8 ,@mikeNG,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRCS31.Q1-3-56-2
Thanks.

**Comment by mikeNG** [comment]
> @ferhzzoma ,@Hasaber8 ,@mikeNG, Version released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRCS31.Q1-3-56-2 Thanks.

@chenyt9 just like https://github.com/MotorolaMobilityLLC/kernel-msm/issues/357#issuecomment-927304645 it seems you have not pushed the tag for `vendor-qcom-opensource-data-kernel`. Can you please upload it?
