### ISSUE TITLE
[Request] RRES31.Q2-11-66-3 denver sources

### ISSUE THREAD

**Issue by electimon** [MotorolaMobilityLLC/kernel-msm#377]
Please and thanks 👍

**Comment by Hasaber8** [comment]
Bump @chenyt9

**Comment by fembyfox** [comment]
30 days and still nothing, bumping

**Comment by chenyt9** [comment]
@electimon @Hasaber8 @fembyfox ,
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRES31.Q2-11-66-3
Thanks.
