### ISSUE TITLE
[Request] Moto Edge Plus (burton) XT2061-3 RPBS31.Q1-19-19-14-11 (RETAIL)

### ISSUE THREAD

**Issue by knuxyl** [MotorolaMobilityLLC/kernel-msm#378]
Can someone please release the kernel source/device tree for the model and version below? Thanks!
```
Moto Edge Plus (burton)
XT2061-3
RPBS31.Q1-19-19-14-11 (RETAIL)
```

And if possible, the VZW version as well
```
Moto Edge Plus (burton)
XT2061-1
RPBS31.Q1-19-58-26-2 (VZW)
```

**Comment by mbissaromoto** [comment]
Hi @knuxyl 
Retail is now released: https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-RPBS31.Q1-19-19-14-11

Verizon is on queue. I will reply here when it is done.

Att,
Marcelo / Vinicius

**Comment by mbissaromoto** [comment]
Hi @knuxyl 
VZW is now released as well: https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-RPBS31.Q1-19-58-26-2

Att,
Marcelo / Vinicius
