### ISSUE TITLE
[Request] Moto Edge 20 (berlin) RRG31.Q3-23-50

### ISSUE THREAD

**Issue by Vachounet** [MotorolaMobilityLLC/kernel-msm#379]
Hi,

Could you release sources for this tag please ?

Thanks

**Comment by chenyt9** [comment]
Hi, @Vachounet ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRG31.Q3-23-50
Thanks.
