### ISSUE TITLE
GPL | Request | Source for Motorola G 5G (kiev) (RZK31.Q3-25-15)

### ISSUE THREAD

**Issue by SyberHexen** [MotorolaMobilityLLC/kernel-msm#380]
Kindly requesting source for the following repos for this tag "RZK31.Q3-25-15"

kernel-msm
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-4.19-techpack-camera
kernel-msm-4.19-techpack-display
kernel-msm-4.19-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn
Thanks in advance!
~Andrew

**Comment by ghost** [comment]
bump @chenyt9

**Comment by mzohair-leed** [comment]
bump @SyberHexen

**Comment by SyberHexen** [comment]
Bump @awheeler-mmi @chenyt9 @mbissaromoto

**Comment by SyberHexen** [comment]
@mbissaromoto any updates on this one?

**Comment by mbissaromoto** [comment]
Hi @SyberHexen 
It is on our queue to be processed. Hope to have it by April's end

**Comment by mbissaromoto** [comment]
Hi @SyberHexen ,
It is now released: https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-RZK31.Q3-25-15

Att,
Marcelo / Vinicius
