### ISSUE TITLE
[Request] Device Tree, Kernal code and vendor for Moto g40 fusion

### ISSUE THREAD

**Issue by bhawesh2002** [MotorolaMobilityLLC/kernel-msm#381]

**Comment by kytoaq** [comment]
Version released:

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRI31.Q1-42-24-4

**Comment by ghost** [comment]
@kytoaq is that the kernel for the g40 fusion?

**Comment by kytoaq** [comment]
the user did not comment the Tag he needs, but this kernel is from hanoip which is the same device maybe it might work

**Comment by vinimed** [comment]
Hello @bhawesh2002, could you please inform us the version desired? Is it possible to use RRI31.Q1-42-24-4, as user @kytoaq commented?

**Comment by bhawesh2002** [comment]
@vinimed The version i want is RRI31.Q1-42-48.  It is released?

**Comment by bhawesh2002** [comment]
I am a complete noob so I need help to learn android development.

**Comment by chenyt9** [comment]
Hi, @bhawesh2002 ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRI31.Q1-42-48
Thanks.

**Comment by kytoaq** [comment]
@chenyt9 Please can upload the issue #353
