### ISSUE TITLE
[REQUEST] All device tree/DTS for Payton PPW29.69-40-4

### ISSUE THREAD

**Issue by blap** [MotorolaMobilityLLC/kernel-msm#382]
Kindly release the following sources (all device tree/dts) for payton (moto X4). Tag PPW29.69-40-4

Including:
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree 
Audio tree
WLAN tree
Storage/data tree
USB tree
GPU tree
Modem tree
Bluetooth tree
NFC tree
Fingerprint tree
Sensors tree
Vendor tree

Thanks

**Comment by FPSensor** [comment]
If with Vendor trees u mean full Vendor AND no dts dude
For all dts better ask for full kernel ig

**Comment by asbraga-motorola** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PPW29.69-39-2
