### ISSUE TITLE
[REQUEST] All device tree/DTS for athene OPJ28.111-22-1

### ISSUE THREAD

**Issue by blap** [MotorolaMobilityLLC/kernel-msm#383]
Kindly release the following sources (all device tree/dts) for athene (moto G4 Plus). Tag OPJ28.111-22-1

Including:
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
Audio tree
WLAN tree
Storage/data tree
USB tree
GPU tree
Modem tree
Bluetooth tree
Sensors tree
TV tree
Vendor tree

Thanks

**Comment by mbissaromoto** [comment]
Hi @blap 

It was already released here: https://github.com/MotorolaMobilityLLC/kernel-msm/issues/227

**Comment by blap** [comment]
It is just the kernel...
