### ISSUE TITLE
[REQUEST] Device Tree, kernel code and vendor for Motorola Edge 20 Fusion RRK31.Q3.19-54 (model : XT2139-2)

### ISSUE THREAD

**Issue by tapi2001** [MotorolaMobilityLLC/kernel-msm#384]
Please release Device Tree, kernel code and vendor for Motorola Edge 20 Fusion 

Including:
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
Audio tree
WLAN tree
Storage/data tree
USB tree
GPU tree
Modem tree
Bluetooth tree
Sensors tree
TV tree
Vendor tree

Thanks

**Comment by vinimed** [comment]
Hello @tapi2001,
There is a version already in our Github (MMI-RRN31.Q1-20-52-3). Is it fit your needs?
As request on https://github.com/MotorolaMobilityLLC/kernel-msm/issues/371

Best regards.

**Comment by tapi2001** [comment]
Is it for model no: XT2139-2. PLS CONFIRM

**Comment by tapi2001** [comment]
BUILD NUMBER RRK31.Q3.19-54 

KINDL CONFIRM

**Comment by chenyt9** [comment]
Hi，@tapi2001 
Does this version can meet your needs?
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRK31.Q3-19-97

**Comment by chenyt9** [comment]
Hi, @tapi2001 ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRK31.Q3-19-54
