### ISSUE TITLE
[REQUEST]: Android 12 - sofiap_sprout S0PRS32.44-11-10-2-10 Kernel Sources

### ISSUE THREAD

**Issue by kytoaq** [MotorolaMobilityLLC/kernel-msm#385]
Since Android 11 couldn't send the Android 11 kernel update (see #353), I am forced to ask for this tag. I'd appreciate it if you could upload it.

Excuse my desperation for requesting it, but quite a few releases of different devices have passed and it is a bit annoying to learn that this device cannot be released. We have been trying to get the source of this kernel for more than 10 months but the answer is negative. Please release the version as soon as possible, since Android 12 should not be a problem.

Thanks you :)

NO ANDROID 12, JUST ANDROID 11

**Comment by mbissaromoto** [comment]
Hi @kytoaq  

After you opened this request here, I've published the tag that was requested on #353. I will close this issue here, ok?
 
If you need a request for this or any other tag for Android 12, please update this issue accordingly.

Regards,
Marcelo

**Comment by kytoaq** [comment]
Hi!.

thanks for answering this issue. I would really appreciate if you could upload this Tag for the Trinket platform.

S0PRS32.44-11-10-2-10

Thanks you.

**Comment by asbraga-motorola** [comment]
Hi @kytoaq 
The version is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S0PRS32.44-11-10-2-10
