### ISSUE TITLE
[REQUEST] Device Tree, kernel code and vendor for Motorola One Fusion (astro) RPLS31.Q2-63-10-2-4 XT2073-2

### ISSUE THREAD

**Issue by cr3ativec0mmons** [MotorolaMobilityLLC/kernel-msm#386]
Including:
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
Audio tree
WLAN tree
Storage/data tree
USB tree
GPU tree
Modem tree
Bluetooth tree
Sensors tree
Vendor tree

Your faithfully, Skelebrawl.

**Comment by uotlaf** [comment]
Bump

**Comment by mbissaromoto** [comment]
Gonna be published using #390
