### ISSUE TITLE
Moto G Play (2021) [guamna] has decoding problems with 10-bit HEVC

### ISSUE THREAD

**Issue by Pentaphon** [MotorolaMobilityLLC/kernel-msm#388]
Steps: 
1) Download https://jell.yfish.us/media/jellyfish-10-mbps-hd-hevc-10bit.mkv
2) Play it on https://play.google.com/store/apps/details?id=com.brouken.player&hl=en_US&gl=US
3) Won't play, see screenshot below for error you get. 

![Screenshot_20211206-022642](https://user-images.githubusercontent.com/49374058/144830696-9443dcc1-5f4f-4c51-8fbf-1f2139c41cfc.png)

**Comment by nsherbina1999** [comment]
Are you sure it's not a SW decode problem?

**Comment by Pentaphon** [comment]
> Are you sure it's not a SW decode problem?

I'm not sure. I've been told by other video player devs on github that this device has buggy decoders. I'd love to help debug this with somebody and get a permanent fix for this.

**Comment by asbraga-motorola** [comment]
Hi @Pentaphon,
This forum is primarily for requesting open source code publication or questions related to it.
Please use the Moto Community Forum for all other questions:
https://forums.lenovo.com/t5/Motorola-Community/ct-p/MotorolaCommunity

**Comment by Pentaphon** [comment]
@asbraga-motorola can you please take my bug report to the people at Motorola who take bug reports? I don't need community support. I need a firmware bug fixed.
