### ISSUE TITLE
[Request] Motorola One Fusion+ (liber) - QPIS30.73-33-13 Kernel Sources

### ISSUE THREAD

**Issue by b4ckup007** [MotorolaMobilityLLC/kernel-msm#389]
Hi!
Can you release kernel sources for this version?
Thanks! :D

**Comment by b4ckup007** [comment]
send the last tag if possible (QPIS30.73-33-13)

**Comment by b4ckup007** [comment]
Bump @chenyt9 @awheeler-mmi

**Comment by mbissaromoto** [comment]
Hi @b4ckup007 

It is now released: https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-QPIS30.73-33-13

Att,
Marcelo Bissaro / Vinicius Medeiros
