### ISSUE TITLE
[GPL] [REQUEST] Motorola One Fusion (astro) RPLS31.Q2-63-10-2-4 Kernel Sources

### ISSUE THREAD

**Issue by Fraaxius** [MotorolaMobilityLLC/kernel-msm#390]
Hello Moto!

Could they release the kernel source code for Motorola One Fusion (astro) RPLS31.Q2-63-10-2-4?

Thanks and good day!

**Comment by Fraaxius** [comment]
Bump @chenyt9

**Comment by guilleastro** [comment]
Bump @Chenyt9

**Comment by cr3ativec0mmons** [comment]
Bump @Chenyt9

**Comment by syoker** [comment]
Bump @Chenyt9

**Comment by uotlaf** [comment]
Bump @chenyt9

**Comment by uotlaf** [comment]
Bump again @chenyt9

**Comment by vinimed** [comment]
Hi @Fraaxius and @uotlaf,
The version was released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPLS31.Q2-63-10-2-4

Best regards,
Vinicius

**Comment by uotlaf** [comment]
Thanks!

> Hi @Fraaxius and @uotlaf, The version was released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPLS31.Q2-63-10-2-4
> 
> Best regards, Vinicius
