### ISSUE TITLE
[Request] motorola edge X30 (XT2201-2) - SOSC32.16-29-12 sources/dts

### ISSUE THREAD

**Issue by 113afternoon** [MotorolaMobilityLLC/kernel-msm#391]
please include required source code and device trees for this release (SOSC32.16-29-12)

麻烦你了!

**Comment by chenyt9** [comment]
@113afternoon ，
this version is already in our process and will be released as soon as possible. Under normal circumstances, itusually takes two weeks. Thank you!

**Comment by chenyt9** [comment]
@113afternoon ,
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S0SC32.16-29-12
