### ISSUE TITLE
REQUEST: TONGA 11 RRQ31.Q3-68-16-2

### ISSUE THREAD

**Issue by ArtiicPanda** [MotorolaMobilityLLC/kernel-msm#392]

**Comment by chenyt9** [comment]
@ArtiicPanda ，this version is already in our process and will be released as soon as possible. Under normal circumstances, itusually takes two weeks. Thank you!

**Comment by chenyt9** [comment]
Hi， @ArtiicPanda ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRQ31.Q3-68-16-2R1
