### ISSUE TITLE
[Request] GPL | Motorola g31 Source release (Device Tree, Kernal code and vendor etc.)

### ISSUE THREAD

**Issue by harshzalavadiya** [MotorolaMobilityLLC/kernel-msm#393]

**Comment by vinimed** [comment]
Hello @harshzalavadiya ,

Can you please specify the release number you want? By having the release number we can focus on releasing the exact version you need.

Vinicius

**Comment by harshzalavadiya** [comment]
@vinimed thanks, it's RRWB31.Q3-46-64-2-2

**Comment by chenyt9** [comment]
@harshzalavadiya ，
this version is already in our process and will be released as soon as possible. Under normal circumstances, itusually takes two weeks. Thank you!

**Comment by chenyt9** [comment]
@harshzalavadiya ,
Verison released:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRWB31.Q3-46-64-2-2

**Comment by VTVishwanath** [comment]
Can we get the latest version? 

Also does it include Kernel + device tree + vendor tree/blobs or only kernel tree?

**Comment by harshzalavadiya** [comment]
@VTVISHWANATH I think it will be better to create new issue

**Comment by VTVishwanath** [comment]
@motorolamobility please upload source for below
GPL | Source request for Motorola Moto G31[retin] (XT2173-2) RRWBS31.Q3-46-85-7
https://github.com/MotorolaMobilityLLC/kernel-msm/issues/450
