### ISSUE TITLE
[REQUEST] Moto Edge S (nio) - RRN31.Q3-1-11-6 - all device tree/dts sources

### ISSUE THREAD

**Issue by moetayuko** [MotorolaMobilityLLC/kernel-msm#395]
The latest available tag is RRN31.Q2-12-14-7 so far and outdated for 3 OTA updates.

**Comment by chenyt9** [comment]
@MoetaYuko ，
This version is already in our process and will be released as soon as possible. Under normal circumstances, itusually takes two weeks. Thank you!

**Comment by chenyt9** [comment]
@MoetaYuko ，version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRN31.Q3-1-11-6
