### ISSUE TITLE
[REQUEST] Moto g20 (java) RTA31.68-29 sources

### ISSUE THREAD

**Issue by rodriguezbrunodaniel** [MotorolaMobilityLLC/kernel-msm#396]
Please take our request into consideration, a new kernel update has just come out if possible to source this thousands of users and devs will be grateful @awheeler-mmi @chenyt9 @mbissaromoto 🙏

**Comment by rodriguezbrunodaniel** [comment]
bump @awheeler-mmi @chenyt9 @mbissaromoto

**Comment by ghost** [comment]
aren't they legally forced to provide sources?

**Comment by SantiiAgoo5121** [comment]
@awheeler-mmi @chenyt9 @mbissaromoto 🙏🏻🙏🏻🙏🏻

**Comment by Claravallac** [comment]
BUILD ID: RTAS31.68-66-2

please release all GPL protected linux kernel source code for Moto G20 device

@chenyt9
@awheeler-mmi
@TinnoOSS
@asbraga-motorola
@mbissaromoto

As npjohnson said:
"This is getting bordererline absurd. Especially considering this looks like EOL for this device family - please push it."

**Comment by TinnoOSS** [comment]
@ALL,version released:
https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-RTA31.68-29

**Comment by Claravallac** [comment]
@asbraga-motorola  Source is incomplete.
