### ISSUE TITLE
[Request] GPL | Motorola g200 5G (S30) Source release (Device Tree, Kernal code and vendor etc.) 

### ISSUE THREAD

**Issue by MarcoXiao17** [MotorolaMobilityLLC/kernel-msm#397]

**Comment by wisecrick** [comment]
Seconded
I also want these

**Comment by betaxab** [comment]
me too.

**Comment by wisecrick** [comment]
Moto S30/G200 will upgrade to Android 12, I hope they release these resource of Android 12

**Comment by mbissaromoto** [comment]
Hi @MarcoXiao17 
Can you please specify the release number you want? By having the release number we can focus on releasing the exact version you need.

Att,
Marcelo

**Comment by betaxab** [comment]
@mbissaromoto RRXC31.Q3-45-54-5 is better. And RETAIL RRX31.Q3-59-42. thanks.

**Comment by chenyt9** [comment]
@betaxab ，
this version（RRXC31.Q3-45-54-5） is already in our process and will be released as soon as possible. Under normal circumstances, itusually takes two weeks. Thank you!

**Comment by wisecrick** [comment]
Moto S30 has already upgraded to Android 12

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRXC31.Q3-45-54-5

**Comment by asbraga-motorola** [comment]
Hi @betaxab,
RRX31.Q3-59-42 is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRX31.Q3-59-42
