### ISSUE TITLE
(GPL)(REQUEST) Kernel source release for RRUB31.Q3-71-32-1 (Moto G71) 

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#398]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack
CC: @chenyt9 @awheeler-mmi

**Comment by chenyt9** [comment]
@Hasaber8 ，
this version is already in our process and will be released as soon as possible. Under normal circumstances, itusually takes two weeks. Thank you!

**Comment by chenyt9** [comment]
@Hasaber8 ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRUB31.Q3-71-32-1R1
