### ISSUE TITLE
[REQUEST] All Unisoc chipset kernels

### ISSUE THREAD

**Issue by huntergregal** [MotorolaMobilityLLC/kernel-msm#399]

**Comment by huntergregal** [comment]
Any update? there seems to be no motorola unisoc/spreadtrum kernels anywhere that i can find.

**Comment by asbraga-motorola** [comment]
I am closing this issue as it does not specify a product.
If necessary, please open a new one informing the exact released version you want.
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.
