### ISSUE TITLE
[REQUEST] Moto G Play 2021 (guamna) RZAS31.Q2-146-14-1-1 Sources

### ISSUE THREAD

**Issue by electimon** [MotorolaMobilityLLC/kernel-msm#400]
Please and thanks!

**Comment by franciskafieh** [comment]
I would like this too! Tysm!

**Comment by franciskafieh** [comment]
Is there any ETA for this? Sorry to sound impatient

**Comment by vinimed** [comment]
Hello @franciskafieh ,
The version was released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RZAS31.Q2-146-14-1-1

Thank you.

Vinicius Medeiros / Marcelo Bissaro.
