### ISSUE TITLE
[QUESTION] Motorola edge 20 pro with Docker

### ISSUE THREAD

**Issue by error0x001** [MotorolaMobilityLLC/kernel-msm#401]
Hello there! 

The phone is awesome! It's really powerful, with high uptime and access to the internet. I tried to research information about how to use this power, and have found the [article](https://gist.github.com/FreddieOliveira/efe850df7ff3951cb62d74bd770dce27) about running docker on android natively. It's really good point for this smartphone. Also, we have [source code](https://github.com/MotorolaMobilityLLC/kernel-msm/issues/369) for the phone.

Could anyone help with building custom kernel with docker support? I have a lack of experience in this theme. Another case is getting a manual how-to compile with thes device, please.

**Comment by asbraga-motorola** [comment]
Hi @error0x001 
This forum is primarily for requesting open source code publication or questions related to it.
Please use the Moto Community Forum for all other questions:
https://forums.lenovo.com/t5/Motorola-Community/ct-p/MotorolaCommunity
