### ISSUE TITLE
[Request] Motorola G 71 5G (corfur) Kernel Sources (RRUB31.Q3-71-102-2)

### ISSUE THREAD

**Issue by Venkat3620** [MotorolaMobilityLLC/kernel-msm#402]
please publish kernel ,dts,techpack drivers for Motorola G 71 5G (corfur), @chenyt9 @awheeler-mmi @mbissaromoto

**Comment by chenyt9** [comment]
Hi,@Venkat3620 , could you please inform us the version number ?

**Comment by Venkat3620** [comment]
RRUB31.Q3-71-102-2

**Comment by Venkat3620** [comment]
@chenyt9 , there is version of MMI-RRUB31.Q3-71-32-1R1 for corfur published yesterday ,is there any chance of pushing the latest one i.e, RRUB31.Q3-71-102-2

**Comment by chenyt9** [comment]
@Venkat3620 ,sorry for miss the msg, will start to arrange the publish work for RRUB31.Q3-71-102-2

**Comment by Venkat3620** [comment]
@chenyt9 thanks for response, previous tag has kernel-display-devicetree,kernel-camera-devicetree missing so please add them with this version.

**Comment by Venkat3620** [comment]
@chenyt9 @awheeler-mmi @mbissaromoto can you please release the latest tag. RRUBS31.Q3-71-102-3

**Comment by chenyt9** [comment]
@Venkat3620 ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/RRUB31.Q3-71-102-2
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/RRUBS31.Q3-71-102-2-3
