### ISSUE TITLE
[Request]GPL | Motorola Edge S30 Source release (Device Tree, Kernal code and vendor etc.) 

### ISSUE THREAD

**Issue by 499906881** [MotorolaMobilityLLC/kernel-msm#403]
Android 12 S1RXC32.50-25-3
Android 11 RRXC31.Q3-45-54-5

**Comment by chenyt9** [comment]
@499906881 
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRXC31.Q3-45-54-5

**Comment by chengnan049** [comment]
So this issues should be closed now.
