### ISSUE TITLE
[Request] GPL | Motorola Moto E20 and E40 Source release (Device Tree, Kernel code and vendor, etc.) and unlockable bootloaders

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [MotorolaMobilityLLC/kernel-msm#404]
A lot more life and use could be squeezed out of these models if they were made more open and customizable. 

Furthermore, the E20's bootloader doesn't seem to be unlockable at all - it merely gives errors such as `FAILED (remote: unknown cmd.)`. Others report the same error on the E40:
https://forums.lenovo.com/t5/MOTOROLA-Android-Developer-Community/Moto-E20-Bootloader-Unlock/m-p/5136560
https://forum.xda-developers.com/t/failed-remote-unknown-command-trying-to-unlock-bootloader.3841588/post-86474265

**Comment by iFUCKINGHATEcomputers** [comment]
Related: #399

**Comment by asbraga-motorola** [comment]
Hi. We do not generally support unlocking bootloaders. Hope that other users can help you in the developer community forum.

**Comment by ThePedroo** [comment]
Hello. While the Moto E20 bootloader appears to be unlockable, like the author of this issue has stated, it would be beneficial to have its device tree, kernel source, vendor, among other components publicly available anyway, as required by GPL.

**Comment by asbraga-motorola** [comment]
Could you please open a new request with the exact build id you want?

**Comment by ThePedroo** [comment]
> Could you please open a new request with the exact build id you want?

Please follow in #673 issue.
