### ISSUE TITLE
[Request] Motorola One Fusion+ (liber) - RPIS31.Q2-42-25-1 Kernel Sources

### ISSUE THREAD

**Issue by menorziin** [MotorolaMobilityLLC/kernel-msm#408]
Hi, Could you release sources for this tag please ?

Thanks

**Comment by menorziin** [comment]
Bump @chenyt9

**Comment by menorziin** [comment]
Bump @chenyt9 @awheeler-mmi

**Comment by asbraga-motorola** [comment]
Hi @menorziin,
RPI31.Q2-42-25 is published to https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPI31.Q2-42-25

**Comment by asbraga-motorola** [comment]
RPIS31.Q2-42-25-1 is published to https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPIS31.Q2-42-25-1
