### ISSUE TITLE
[Request] Motorola G 30 (caprip) Kernel Sources (S0RCS32.41-10-9-2)

### ISSUE THREAD

**Issue by Venkat3620** [MotorolaMobilityLLC/kernel-msm#409]
please publish kernel ,dts,techpack drivers for Motorola G 30 (caprip) @chenyt9 @awheeler-mmi @mbissaromoto
tag- S0RCS32.41-10-9-2

**Comment by decaduto** [comment]
Sorry one question: what is the techpack? in my kernel there isn't anything similar

**Comment by Venkat3620** [comment]
@decaduto  techpack was introduced from 4.9 kernel it contains drivers for audio disp etc,if your kernel version is less than 4.9 then there is nothing tobe worried, if yes add those commits manully and check for moto repos and add them

**Comment by decaduto** [comment]
so techpack is a "pack" of various specific drivers for qualcomm chipset? why my kernel compiles without any problems using the .config file found in /proc/config.gz, even if the techpack folder did not exists? (my kernel is 5.4 )

**Comment by Venkat3620** [comment]
there is already defconfig present in ext_config dir add those lines to holi-perf_defconfig and compile and this isnt correct issue to be talked here i guess

**Comment by Venkat3620** [comment]
@chenyt9  @awheeler-mmi @mbissaromoto Sir any update?

**Comment by asbraga-motorola** [comment]
@Venkat3620 
Version is released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S0RCS32.41-10-9-2
