### ISSUE TITLE
Moto G (1st gen.) GPE 5.1 latest kernel source

### ISSUE THREAD

**Issue by fonz93** [MotorolaMobilityLLC/kernel-msm#41]
Hi, can you update the falcon gpe branch/release to the latest one? Thanks

LMY47M.M004
falcon_gpe-user 5.1 LMY47M.M004 9 release-keys
motorola/falcon_gpe/falcon_umts:5.1/LMY47M.M004/9:user/release-keys

**Comment by tags07** [comment]
Yes, its in the pipeline. We'll post it soon.

**Comment by charleseb** [comment]
Hi fonz93,

The version MMI-LMY47M.M004 has been released to Github.

Thanks,
Charles Barros

**Comment by luca020400** [comment]
LMY47M.M005 has been released a few days ago
Can you upload it ?
Thanks
