### ISSUE TITLE
[Request] Moto Edge Plus (burton) XT2061-3 MMI-S1PB32.41-10-17 (RETAIL)

### ISSUE THREAD

**Issue by AKoskovich** [MotorolaMobilityLLC/kernel-msm#410]
Hello, could the kernel sources + DTS for Android 12 be released for this device?

Thanks

**Comment by asbraga-motorola** [comment]
Hi @ZVNexus 
The version is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1PB32.41-10-17
