### ISSUE TITLE
Moto Edge 30 source code - S1RD32.55-33

### ISSUE THREAD

**Issue by switch-gott** [MotorolaMobilityLLC/kernel-msm#412]
Dir sir or madam,

please release kernel and vendor source code for device edge 30.

Realy thanks

Kind regards

**Comment by vinimed** [comment]
Hello @switch-gott,
Could you please specify the version you want?

Thank you.

**Comment by switch-gott** [comment]
Hi,
thanks for reply.
I meen for version motorola XT2203-1. (Motorola Edge 30)
Cant find also firmware for it.
Thanks

**Comment by diapolon** [comment]
+1 for this!

**Comment by mbissaromoto** [comment]
Hi @switch-gott 
We need to known the exact release tag you need (the one you find the System Config in the phone). Something like: RAB31.YY-ZZ-WW

**Comment by diapolon** [comment]
hi @mbissaromoto, is this S1RD32.55-33?

**Comment by mbissaromoto** [comment]
Ok, we will add to the queue.

**Comment by kailashrs** [comment]
Bump @mbissaromoto

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RD32.55-33
