### ISSUE TITLE
Moto G20 kernel source (java) XT2128-1 Tag RTAS31.68-34-2

### ISSUE THREAD

**Issue by SantiiAgoo5121** [MotorolaMobilityLLC/kernel-msm#413]
Please could you post the kernel source code? We need to work with this device.

**Comment by vinimed** [comment]
Hello @SantiiAgoo5121,

Could you please specify the version you want? The same as #412?

Thank you.

**Comment by SantiiAgoo5121** [comment]
@vinimed 
Yes bro, the same

**Comment by SantiiAgoo5121** [comment]
No Bro 

XT2128-1

RTA31.68-29

**Comment by SantiiAgoo5121** [comment]
@chenyt9 help

**Comment by SantiiAgoo5121** [comment]
@vinimed

**Comment by TinnoOSS** [comment]
@ALL,version released:
https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-RTAS31.68-34-2
