### ISSUE TITLE
[REQUEST] Moto G40 Fusion/Moto G60 (hanoip) RRIS31.Q1-42-51-12-4

### ISSUE THREAD

**Issue by pranayadmn** [MotorolaMobilityLLC/kernel-msm#415]
Hi, could you please release the kernel source along with all of the required external kernel modules for Moto G40 Fusion/Moto G60 (hanoip) running on software revision RRIS31.Q1-42-51-12-4? Thanks.

**Comment by chenyt9** [comment]
Hi,@pranaya2005 , 
will arrange the release for RRIS31.Q1-42-51-12-4. Thank you for your patience.

**Comment by chenyt9** [comment]
@pranaya2005 ，Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/RRIS31.Q1-42-51-12-4
Thanks.

**Comment by pranayadmn** [comment]
> @pranaya2005 ，Version released： https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/RRIS31.Q1-42-51-12-4 Thanks.

Appreciate it, thanks!
