### ISSUE TITLE
(GPL)(REQUEST) Kernel source release for S1RD32.55-33(Moto Edge 30)

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#416]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack
CC: @chenyt9 @awheeler-mmi

**Comment by sb6596** [comment]
@chenyt9 Waiting for sources to be released (including all drivers, device trees).

**Comment by Hasaber8** [comment]
Bump: @chenyt9

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RD32.55-33
