### ISSUE TITLE
Moto G20 (java)(XT2128-1) Kernel Sources RTA31.68-29

### ISSUE THREAD

**Issue by SantiiAgoo5121** [MotorolaMobilityLLC/kernel-msm#417]
Hello, could you provide us with the Sources kernel for this device? We want to work with this device

**Comment by Claravallac** [comment]
Bump it 

@chenyt9
@awheeler-mmi
@TinnoOSS
@asbraga-motorola
@mbissaromoto

**Comment by TinnoOSS** [comment]
@ALL,version released:
https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-RTA31.68-29
