### ISSUE TITLE
MSM8953 devices to 4.9

### ISSUE THREAD

**Issue by Ratatouilledummie** [MotorolaMobilityLLC/kernel-msm#418]
is possible to msm8953 devices be ported to 4.9 releases ?

**Comment by chenyt9** [comment]
Hi,@Ratatouilledummie ，
Are you asking for open source kernel code? If yes，could you please describe in detail what’s product you need and the corresponding version number. Thanks.

**Comment by FPSensor** [comment]
nno since Motorola only offers the kernel of the stock ROM and it is not convenient for them to port one but even so the community is lately porting them by hand, some examples are: Montana, Hannah, cedric (brokensensors) and Albus (charger broken)

**Comment by asbraga-motorola** [comment]
I'm closing this issue because it does not request the code of a specific product.
For generic questions, you may try the developer community:
https://forums.lenovo.com/t5/MOTOROLA-Android-Developer-Community/bd-p/230
