### ISSUE TITLE
(GPL)(REQUEST) Kernel Source Release for RRYA31.Q3-56-99-2(Moto G51)

### ISSUE THREAD

**Issue by 18712886438** [MotorolaMobilityLLC/kernel-msm#422]
hi, can u please release the kernel source for moto g51? thx :p

**Comment by chenyt9** [comment]
Hi, @18712886438 
The kernel source for moto g51 has been released：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRYA31.Q3-56-79-3
 And the version you requested are also in the process.Please be patient. Thanks.

**Comment by chenyt9** [comment]
Hi, @18712886438 ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRYA31.Q3-56-99-2
Thank you for your patience！

**Comment by 18712886438** [comment]
> Hi, @18712886438 ，
> Version released：
> https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRYA31.Q3-56-99-2
> Thank you for your patience！

thx.
