### ISSUE TITLE
GPL | Source request for  Motorola Edge 20 Pro (pstar) (S1RAS32.41-20-16-3)

### ISSUE THREAD

**Issue by SyberHexen** [MotorolaMobilityLLC/kernel-msm#424]
Kindly requesting source for the following repos for this tag "S1RAS32.41-20-16-3"

kernel-msm
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-4.19-techpack-camera
kernel-msm-4.19-techpack-display
kernel-msm-4.19-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn

Thanks in advance!
~Andrew

**Comment by asbraga-motorola** [comment]
Hi @SyberHexen,
The version is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RAS32.41-20-16-3
