### ISSUE TITLE
GPL | Source Request for Motorola Edge 20 (berlin) - S1RG32.53-18-11

### ISSUE THREAD

**Issue by npjohnson** [MotorolaMobilityLLC/kernel-msm#425]
Kindly requesting source for the listed device for this tag "S1RG32.53-18-11"

Need kernel + modules + device-tree repos as applicable.

Thanks in advance!

**Comment by npjohnson** [comment]
Following up on this. Would very much like to see this.

**Comment by npjohnson** [comment]
@awheeler-mmi CC

**Comment by asbraga-motorola** [comment]
Hi @npjohnson,
The version is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RG32.53-18-11
