### ISSUE TITLE
[REQUEST] S2RI32.32-20-7 Kernel Sources (hanoip)

### ISSUE THREAD

**Issue by kytoaq** [MotorolaMobilityLLC/kernel-msm#426]
Hi. Could push this tag with all relevant repositories complement.

Thanks you =)

@kytoaq

**Comment by DhineshCool** [comment]
@chenyt9

**Comment by asbraga-motorola** [comment]
HI @kytoaq,
The tag is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RI32.32-20-7
