### ISSUE TITLE
[REQUEST] Moto Edge S (nio) - S1RN32.55-16-2 - all device tree/dts sources

### ISSUE THREAD

**Issue by moetayuko** [MotorolaMobilityLLC/kernel-msm#427]
Build Fingerprint: motorola/nio_retcn/nio:12/S1RN32M.55-16-2/32b4dd:user/release-keys

**Comment by seba3567** [comment]
or S1RTS32.41-20-16-1-2 and  device tree

**Comment by gyfx** [comment]
bump @chenyt9  pls

**Comment by chenyt9** [comment]
@MoetaYuko , pls refer to:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RN32.55-16-2

**Comment by chenyt9** [comment]
@seba3567 
pls refer to:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RTS32.41-20-16-1-2

**Comment by moetayuko** [comment]
@chenyt9 S1RN32.55-16-2 for the following repos are missing, please upload them:

* https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-wlan-fw-api
* https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-data-kernel
* https://github.com/MotorolaMobilityLLC/kernel-devicetree
