### ISSUE TITLE
[REQUEST] Moto G Pro S0PR32.44-11-8 Kernel

### ISSUE THREAD

**Issue by electimon** [MotorolaMobilityLLC/kernel-msm#428]
Please and thanks!

**Comment by asbraga-motorola** [comment]
Hi @electimon 
Is this tag adequate for you? It's already published:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S0PRS32.44-11-10-2-10

**Comment by electimon** [comment]
Yes thanks
