### ISSUE TITLE
thea: LXB22.99-24.12 11

### ISSUE THREAD

**Issue by luca020400** [MotorolaMobilityLLC/kernel-msm#43]
System Version : 22.46.12.thea_retgb.retgball.en.GB
Build Number : LXB22.99-24.12
Kernel version: Linux version 3.4.42-gf18cb80 (hudsoncm@ilclbld73) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Tue Aug 18 18:36:04 CDT 2015

**Comment by charleseb** [comment]
Hi luca020400,

I'm working to release this version.

Thanks,
Charles

**Comment by luca020400** [comment]
Great thanks

**Comment by luca020400** [comment]
Thanks Charles :)

Just a cve , well better than nothing
