### ISSUE TITLE
[Request] Edge 30 Pro (XT2201-1) - S1SH32.55-8-8 sources/dts

### ISSUE THREAD

**Issue by kunver400** [MotorolaMobilityLLC/kernel-msm#430]
Hi,
please provide the sources for

`Motorola Edge 30 Pro (XT2201-1) - S1SH32.55-8-8`

Thanks,
Kunal

**Comment by chenyt9** [comment]
@kunver400 ,
The release process for this version has been triggered. Please be patient. Thanks!

**Comment by gabriel-hurtado** [comment]
Any update ?

**Comment by chenyt9** [comment]
Hi, @kunver400 ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SH32.55-8-8
Thank you for your patience！

**Comment by neobuddy89** [comment]
Typical corporate culture.
