### ISSUE TITLE
[REQUEST] Moto G100 (nio) - S1RTS32.41-20-16-1-2 - all device tree/dts and kernel sources

### ISSUE THREAD

**Issue by JarlPenguin** [MotorolaMobilityLLC/kernel-msm#432]

**Comment by asbraga-motorola** [comment]
Hi @JarlPenguin,
Version is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RTS32.41-20-16-1-2

**Comment by WINDROID-EMU** [comment]
Is there anyone with kernel experience who could backport ntsync to this nio kernel, if that's possible?
