### ISSUE TITLE
Moto G Stylus 2021 (minsk) RPCS31.Q2_109_16_17 sources

### ISSUE THREAD

**Issue by milesmccaleb** [MotorolaMobilityLLC/kernel-msm#433]
Requesting RPCS31.Q2_109_16_17 minsk source code

Please and Thank you so much!

**Comment by asbraga-motorola** [comment]
Hi @milesmccaleb,
Version is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPCS31.Q2-109-16-17
