### ISSUE TITLE
[REQUEST] Moto G82 5G S1SUS32.73-13-4-3 Sources, Kernel, Device Tree, etc.

### ISSUE THREAD

**Issue by XylenC4** [MotorolaMobilityLLC/kernel-msm#435]
Hello, could you please release the Sources, Kernel, Device Tree, etc. for the Moto G82 5G from S1SUS32.73-13-4-3?

**Comment by chenyt9** [comment]
@XylenC4 ，
The publishing process has been triggered, please be patient. Thank you!

**Comment by adammover** [comment]
Please release the kernel sources for moto g82 5g

**Comment by adammover** [comment]
> @XylenC4 ， The publishing process has been triggered, please be patient. Thank you!

There are 25 days since publishing process has started

**Comment by chenyt9** [comment]
@XylenC4  @adammover ,
Pls use this version first,
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SU32.73-41-2-4
We are preparing to release another version. Thanks.

**Comment by adammover** [comment]
> 

What about the trees?

**Comment by chenyt9** [comment]
Hi, @all,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/S1SUS32.73-13-4-3

@adammover , devicetree is in other repos
kernel-devicetree
kernel-*-devicetree

Thank you all.
