### ISSUE TITLE
Requesting for the 2nd time.

### ISSUE THREAD

**Issue by MelonMusk93** [MotorolaMobilityLLC/kernel-msm#436]
Request to please release Kernel tree, vendor tree , device sources for Moto E40 
There's already an issue raised it seems no one's interested or even have the courtesy to reply. Goodjob moto support team. There are multiple posts regarding Unisoc Chipset device sources release but no one bothers to look into user requests. 

https://github.com/MotorolaMobilityLLC/kernel-mtk/issues/67#issue-1316181056

**Comment by FuccDucc** [comment]
@chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

Motorola is violating the GPL laws

**Comment by asbraga-motorola** [comment]
The code is published in repo kernel-sprd: https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-ROQS31.166-42-1
