### ISSUE TITLE
[REQUEST] Moto G52 (India) (S1SR32.38-112) Sources, Kernel, Device Tree, etc

### ISSUE THREAD

**Issue by Ghosty-Gigabytes** [MotorolaMobilityLLC/kernel-msm#437]
Hello, could you please release the Sources, Kernel, Device Tree, etc. for the Moto G52 from (India) (S1SR32.38-112)

**Comment by chenyt9** [comment]
Hi，@Ghosty-Gigabytes ，
 we will arrange the work of release S1SR32.38-112. But before we release，does this version can meet your needs firstly？
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SR32.38-25
Thanks.

**Comment by chenyt9** [comment]
Hi，@Ghosty-Gigabytes ，
 we will arrange the work of release S1SR32.38-112. But before we release，does this version can meet your needs firstly？
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SR32.38-25
Thanks.

**Comment by Ghosty-Gigabytes** [comment]
Yep, it will surely meet the requirements, thanks for the release
