### ISSUE TITLE
RZBS31.Q2-143-27-13 release for Borneo.

### ISSUE THREAD

**Issue by thebestofall007** [MotorolaMobilityLLC/kernel-msm#438]
Hello, could you kindly release the kernel source for Borneo, release number RZBS31.Q2-143-27-13 please?

**Comment by asbraga-motorola** [comment]
Hi @thebestofall007 ,
Code is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RZBS31.Q2-143-27-13
