### ISSUE TITLE
[REQUEST] Moto Tab G62 (XT2261-2_S000012_220629_ROW) sources, Kernel, Device tree etc.

### ISSUE THREAD

**Issue by vvr3ddy** [MotorolaMobilityLLC/kernel-msm#440]
Hello, could you please release the Sources, Kernel, Device Tree, etc. for the Moto Tab G62 LTE version (XT2261-2_S000012_220629_ROW) along with unlocking the bootloader.
Looks like trying to get unlock data doesnt work on fastboot on this device. 
fastboot returns command failed.

Thanks

**Comment by omkarpatil29** [comment]
it seems moto have blocked the Bootloader unlocking for this tab. but people with International version of this tab able to unlock the BL.

https://forum.xda-developers.com/t/custom-rom-rooting-options-vor-tb-125fu-lenovo-tab-m10-plus-3rd-gen.4480023/#post-87530209
