### ISSUE TITLE
[Request] Moto Z3 (messi) Android Pie Kernel Source

### ISSUE THREAD

**Issue by michaelcrusso** [MotorolaMobilityLLC/kernel-msm#443]
It's old now, but could you still release the most recent kernel source for the Messi XT1929-17 devices (PDX29)? I can only find the one released for Oreo, XT1929-15 RETCN. Thanks!

**Comment by npjohnson** [comment]
agreed - this is still pending.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-PDX29.84-51-11-8
