### ISSUE TITLE
Req: guamp android 11 Kernel Sources (RPXS31.Q2-58-17-4-8)

### ISSUE THREAD

**Issue by FPSensor** [MotorolaMobilityLLC/kernel-msm#444]
for research reasons I require the android 11 kernel sources of Moto G9 Play guamp, I await your response.
Greetings.

**Comment by asbraga-motorola** [comment]
Hi @FPSensor,
Can you inform the exact released version you want?
You find it in the System Config in the phone. It is a group of letters and numbers, that look similar to these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2, ...

**Comment by FPSensor** [comment]
I need RPXS31.Q2-58-17-4-8

**Comment by FPSensor** [comment]
Well I made the request more than a month ago, I think it would be good to start knowing at least if they are working on it

**Comment by Joxquin** [comment]
Please releasw the kernel source of guamp RPXS31.Q2-58-17-4-8

**Comment by Fercho289** [comment]
Please releasw the kernel source of guamp RPXS31.Q2-58-17-4-8

**Comment by Emersoou78** [comment]
Please releasw the kernel source of guamp RPXS31.Q2-58-17-4-8

**Comment by kevios12** [comment]
Please releasw the kernel source of guamp RPXS31.Q2-58-17-4-8

**Comment by FranciscoAlefe** [comment]
Up

**Comment by pesejo69** [comment]
We need  RPXS31.Q2-58-17-4-8 please ;)

**Comment by pedroborraz** [comment]
Please realese the kernel source for guamp

**Comment by Royna2544** [comment]
You should release kernel sources like other OEMs do.

**Comment by asbraga-motorola** [comment]
We are working on it. I requested priority for this version.

**Comment by asbraga-motorola** [comment]
Version is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPXS31.Q2-58-17-4-8
