### ISSUE TITLE
[Request] Edge 30 Ultra (XT2241-2) - S3SQ32.16-16-28 Kernel Source

### ISSUE THREAD

**Issue by hinnie123** [MotorolaMobilityLLC/kernel-msm#445]
Hello,

I'm looking for the kernel sources for the Motorola Edge 30 Ultra (S3SQ32.16-16-28).

Thanks

**Comment by chenyt9** [comment]
Hi，@hinnie123 ，
The publishing process has been triggered, please be patient. Thank you!

**Comment by gabriel-hurtado** [comment]
Hello @chenyt9, any update on this one ?

**Comment by chenyt9** [comment]
@hinnie123 ，@gabriel-hurtado ，
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3SQ32.16-16-28

**Comment by SGCMarkus** [comment]
@chenyt9 there are a sadly few repositories missing as its split up even more than it was for 5.4 now:

kernel-audio-devicetree
kernel-cvp-devicetree
kernel-display-devicetree
kernel-mmrm-devicetree
kernel-video-devicetree
kernel-msm-5.10-techpack-camera
kernel-msm-5.10-techpack-cvp
kernel-msm-5.10-techpack-display
kernel-msm-5.10-techpack-eva
kernel-msm-5.10-techpack-mmrm
kernel-msm-5.10-techpack-sched
kernel-msm-5.10-techpack-video
vendor-qcom-opensource-dataipa

should be all missing ones.

Thanks in advance!
Markus

**Comment by electimon** [comment]
@chenyt9 please and thank you
