### ISSUE TITLE
device tree release - RZBS31.Q2-143-27-13

### ISSUE THREAD

**Issue by Rogerjr442200** [MotorolaMobilityLLC/kernel-msm#446]
if i could get a release of the actual device device tree that would be great .. please and thank you

**Comment by asbraga-motorola** [comment]
Hi @Rogerjr442200,
Can you inform the exact released version you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

**Comment by Rogerjr442200** [comment]
RZBS31.Q2-143-27-13 is that what you need?@https://github.com/asbraga-motorola

**Comment by Rogerjr442200** [comment]
?? @asbraga-motorola

**Comment by asbraga-motorola** [comment]
Yes, that's the version identification I need. Thanks.

**Comment by asbraga-motorola** [comment]
Duplicated: https://github.com/MotorolaMobilityLLC/kernel-msm/issues/438.
Code is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RZBS31.Q2-143-27-13
