### ISSUE TITLE
[REQUEST] Edge 20 Fusion, S2RK32.92-11-21

### ISSUE THREAD

**Issue by thenextgod** [MotorolaMobilityLLC/kernel-msm#447]
Where can I find the Device Tree, kernel code and vendor files for Motorola Edge 20 Fusion, Build number S2RK32.92-11-21 (Android 12).

**Comment by asbraga-motorola** [comment]
Hi @thenextgod,
The code you requested has been published in the repo kernel-mtk. 
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S2RK32.92-11-21
