### ISSUE TITLE
GPL | Source request for Motorola Razr 2020 (smith) (S2PS32.57-23-21)

### ISSUE THREAD

**Issue by SyberHexen** [MotorolaMobilityLLC/kernel-msm#449]
Kindly requesting source for the following repos for this tag "S2PS32.57-23-21"

kernel-msm
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-4.19-techpack-camera
kernel-msm-4.19-techpack-display
kernel-msm-4.19-techpack-video
vendor-cirrus-audio-dlkm
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn

Thanks in advance!
~Andrew

**Comment by asbraga-motorola** [comment]
Hi @SyberHexen,
The version is published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2PS32.57-23-21
