### ISSUE TITLE
victara 6.0 release source

### ISSUE THREAD

**Issue by invisiblek** [MotorolaMobilityLLC/kernel-msm#45]

**Comment by ramsudharsan** [comment]
+1

**Comment by notly** [comment]
+1

**Comment by justindriggers** [comment]
+1

**Comment by luca020400** [comment]
We're still waiting

**Comment by invisiblek** [comment]
you guys got beat by HTC to release kernel source

that's pretty pathetic

**Comment by tags07** [comment]
Closing.. No description!!!

**Comment by invisiblek** [comment]
Are you serious? i'll give you a fucking description.

This shit is GPL, you guys released a build and no source is available. When asked for source you're going to ignore the request?

Here's the ROM build: MPE24.49-18
Here's the kernel string: Linux localhost 3.4.42-ga9982b3-00002-g389e46b #1 SMP PREEMPT Tue Nov 3 16:12:18 CST 2015 armv7l

**Comment by invisiblek** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/issues/48

**Comment by tags07** [comment]
@invisiblek : Dude, in your original post, you never requested the source. There was no description. The title "victara 6.0 release source" was not clear to me if you are commenting on something or asking for the source. Please be clear on what you want and you'll get a decent response. What do you think we have a mind reading machine here that interprets your cryptic messages?

**Comment by u-ra** [comment]
That's a nice rant, but you forgot to acknowledge you got beat by _HTC_ to release the kernel source. That's pretty pathetic.

**Comment by kumajaya** [comment]
LOL :D

**Comment by charleseb** [comment]
Hi invisiblek,

The tag related to the version MMI-MPE24.49-18 has been released.

Thanks,
Charles
