### ISSUE TITLE
GPL | Source request for Motorola Moto G31[retin] (XT2173-2) RRWBS31.Q3-46-85-7

### ISSUE THREAD

**Issue by VTVishwanath** [MotorolaMobilityLLC/kernel-msm#450]
GPL | Source request for Motorola Moto G31[retin] (XT2173-2) RRWBS31.Q3-46-85-7 
Device Tree Blobs, Kernel Tree Blobs and Vendor Tree Blobs.

For the latest build number: RRWBS31.Q3-46-85-7
@motorolamobility

**Comment by VTVishwanath** [comment]
We have not received any update in Here @motorolamobility.

Kindly release it.

Thanks in advance.

**Comment by chenyt9** [comment]
@VTVISHWANATH ，
Sorry, I missed this message, this version is already on our release list, thank you very much for your patience. We will publish it as soon as possible.
Here is a release for Motorola G31：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRWB31.Q3-46-64-2-2
Can you please use this version first？

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-RRWBS31.Q3-46-85-7
