### ISSUE TITLE
GPL | Source request for Motorola Moto Edge (XT2143-1) RRG31.Q3-23-27

### ISSUE THREAD

**Issue by conradalf** [MotorolaMobilityLLC/kernel-msm#452]
Dir sir,
  Please release kernel source code for Motorola Edge (XT2143-1) RRG31.Q3-23-27 for android 11.
  Thanks a lot!!!

**Comment by SyberHexen** [comment]
This is moto edge 20 (Berlin)
Request wants...
kernel-msm
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-4.19-techpack-camera
kernel-msm-4.19-techpack-display
kernel-msm-4.19-techpack-video
vendor-cirrus-audio-dlkm
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn

**Comment by chenyt9** [comment]
@conradalf @SyberHexen , we will trigger the release of this version RRG31.Q3-23-27.
Here is a release for Motorola Edge：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRG31.Q3-23-85
Can you please use this version first？

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRG31.Q3-23-27
