### ISSUE TITLE
GPL | Source request for Motorola Moto Edge 30 Neo (Miami) S3SSM32.34-46-1-1 (XT22245-1)

### ISSUE THREAD

**Issue by marcost2** [MotorolaMobilityLLC/kernel-msm#457]
Kindly requesting source for the following repos for this tag "S3SSM32.34-46-1-1 "

kernel-msm
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-5.4-techpack-camera
kernel-msm-5.4-techpack-display
kernel-msm-5.4-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn

Thanks in advance!

**Comment by chenyt9** [comment]
Hi,@marcost2 , could you use this version first:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3SSM32.34-46-6
This version S3SSM32.34-46-1-1 will be released as soon as possible.

**Comment by chenyt9** [comment]
@marcost2 ,Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3SSMS32.34-46-1-1

**Comment by marcost2** [comment]
Thanks!
