### ISSUE TITLE
[Request]GPL | Motorola Edge 30 Pro Source release (Device Tree, Kernal code and vendor etc.)

### ISSUE THREAD

**Issue by Mohali2609** [MotorolaMobilityLLC/kernel-msm#458]
requesting source for the following repos:
 
- RETEU - S1SHS32.55-70-5-2
- RETEU - S3SH32.12-41-4

Thank you!

**Comment by chenyt9** [comment]
@Mohali2609 ， I did not find this version S3SH32.12-41-4, is the correct version number S3SH32.12-41-4R1? If yes, we will trigger the release of this version S3SH32.12-41-4R1 after getting the confirmation.
Here is a release for Motorola Edge 30 Pro：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SH32.55-8-8
Can you please use this version first？

**Comment by Mohali2609** [comment]
@chenyt9

The correct version number is S3SH32.12-41-4R1.

I will a look at the mentioned repo in the mean time.

Thanks in advance!

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3SH32.12-41-4R1

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SHS32.55-70-5-2
