### ISSUE TITLE
[Request]GPL | Motorola Moto G200 5G/Motorola Edge S30 (xpeng) Source release (Device Tree, Kernal code and vendor etc.) - S1RXS32.50-13-10

### ISSUE THREAD

**Issue by ZhiBeiZhe** [MotorolaMobilityLLC/kernel-msm#459]
RETEU S1RXS32.50-13-10

thanks

**Comment by ZhiBeiZhe** [comment]
@awheeler-mmi@chenyt9@mbissaromoto

**Comment by ThEMarD** [comment]
Heyyo @ZhiBeiZhe , whilst there isn't a direct source code release for xpeng, there is for tundra (Motorola Edge 30 Fusion/Motorola S30 Pro) which has the same SoC and the kernel source code contains the necessary parts for xpeng as well so in theory you should be able to use that tree.

Actually, even the source code release of dubai (Motorola Edge 30) has tundra and xpeng, so if you look at the LineageOS trees? You should even be able to adapt them for xpeng, albeit preferrably a newer source code release like tundra for the kernel to be used as there could be better camera drivers in there and maybe audio too.

You can see the initial tree adaptation I did here for tundra:

https://github.com/moto-sm7325/android_device_motorola_tundra/tree/lineage-20

https://github.com/moto-sm7325/android_device_motorola_sm7325-common/tree/tundra/lineage-20

https://github.com/moto-sm7325/android_kernel_motorola_sm7325/tree/tundra/lineage-20

https://gitlab.com/moto-sm7325/proprietary_vendor_motorola_tundra/-/tree/lineage-20

https://gitlab.com/moto-sm7325/proprietary_vendor_motorola_sm7325-common/-/tree/tundra/lineage-20

So you could fork those and modify them for xpeng to get started and then redo the blobs from the xpeng stock ROM to get your vendor blobs too.

The kernel probably also needs a few extra drivers setup to be buildable for Xpeng as well.

If you use Telegram? My username on there is ThE_MarD if you want to discuss this stuff further.

**Comment by rogers2602** [comment]
@chenyt9 could you give a focus on releasing source code three of s30 Edge and g200? xpeng... thank you

**Comment by dequadim** [comment]
Please, help us to give to our G200 a new life.
I strongly wish to give my help, but I'm a totally newbie and don't know where put my hands.

**Comment by asbraga-motorola** [comment]
Code is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RXS32.50-13-10

**Comment by ZhiBeiZhe** [comment]
> 嘿，雖然 xpeng 沒有直接的原始碼釋出，但 tundra（Motorola Edge 30 Fusion/Motorola S30 Pro）有，它有相同的 SoC，核心原始碼也包含 XPENG 所需的部分，理論上你應該能用那棵樹。
> 
> 其實，連 dubai 的原始碼版本（Motorola Edge 30）都有 tundra 和 xpeng，所以如果你看 LineageOS 的樹？你甚至可以把它們改編成 XPENG，雖然最好是像 Tundra 這種較新的原始碼來使用核心，因為裡面可能有更好的相機驅動程式，甚至可能還有音訊。
> 
> 你可以在這裡看到我為苔原做的初始樹狀調整：
> 
> https://github.com/moto-sm7325/android_device_motorola_tundra/tree/lineage-20
> 
> https://github.com/moto-sm7325/android_device_motorola_sm7325-common/tree/tundra/lineage-20
> 
> https://github.com/moto-sm7325/android_kernel_motorola_sm7325/tree/tundra/lineage-20
> 
> https://gitlab.com/moto-sm7325/proprietary_vendor_motorola_tundra/-/tree/lineage-20
> 
> https://gitlab.com/moto-sm7325/proprietary_vendor_motorola_sm7325-common/-/tree/tundra/lineage-20
> 
> 所以你可以fork那些模組，修改成xpeng開始，然後再從xpeng原廠ROM重做blobs，也能拿到你的供應商blob。
> 
> 核心可能還需要設定幾個額外的驅動程式，才能讓 Xpeng 能夠建置。
> 
> 如果你用 Telegram？如果你想進一步討論這些話題，我在那裡的用戶名是 ThE_MarD。

Thanks, man. I'm not a professional developer, just a build bot.
