### ISSUE TITLE
[Request] GPL | Source request for Motorola edge 2021 (berlna) (S1RM32.68-43-16-3 ) 

### ISSUE THREAD

**Issue by coderamen666** [MotorolaMobilityLLC/kernel-msm#461]
Can the entire corresponding source code be released for the Moto Edge 5g UW? I would also like the AOSP branch.

**Comment by asbraga-motorola** [comment]
Hi @jacobrogers256,
The code is released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RMS32.68-43-16-3
