### ISSUE TITLE
[REQUEST] Moto G60 (hanoip) [S2RIS32.32-20-7-5] Android 12  All Kernel tree ,device drivers.

### ISSUE THREAD

**Issue by TURING-V2** [MotorolaMobilityLLC/kernel-msm#462]

**Comment by fuyukihidekii** [comment]
bump, S2RIS32.32-20-7-7

**Comment by asbraga-motorola** [comment]
Hi @TURING-V2, @fuyukihidekii 
Code is published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RIS32.32-20-7-5
