### ISSUE TITLE
[Request] GPL | Source request for Motorola X40 (rtwo) XT2301-5 - T1TR33.4-30-10-2

### ISSUE THREAD

**Issue by leslieo2002** [MotorolaMobilityLLC/kernel-msm#463]

**Comment by asbraga-motorola** [comment]
Hi @hujunhao0311 
Can you inform the exact released version you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

**Comment by leslieo2002** [comment]
> Hi @hujunhao0311 
> Can you inform the exact released version you want?
> You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

Hi, it's here. T1TR33.4-15-15
Thanks!

**Comment by chenyt9** [comment]
@hujunhao0311 ，
This version is already in our release process and will be open-sourced next week, please wait patiently. Thanks.

**Comment by chenyt9** [comment]
@hujunhao0311 ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.4-30-10-2
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.4-15-15
