### ISSUE TITLE
[Request] GPL | Source request for Moto Tab G62 (XT2261-2 / XT2261-1)

### ISSUE THREAD

**Issue by Hadenix** [MotorolaMobilityLLC/kernel-msm#464]
Hello, could you please release the Sources, Kernel, Device Tree 4.19, etc. for the Moto Tab G62

released version: SKQ1.220119.001

release the DTS/DTSI files of Bengal platform/device please!

Kindly release it.

Thanks in advance.

**Comment by LamerDeath** [comment]
+1

**Comment by Xserxus** [comment]
+1

**Comment by mikewap83** [comment]
+1

**Comment by mrmawhita** [comment]
+1

**Comment by Alex500317** [comment]
+1
