### ISSUE TITLE
Moto G100 (nio) - S1RTS32.41-20-16-1-5 Kernel Sources

### ISSUE THREAD

**Issue by Vasant-1234** [MotorolaMobilityLLC/kernel-msm#465]
I see that you  have released tag MMI-S1RTS32.41-20-16-1-2 . However my latest Android 12 is running Build number: S1RTS32.41-20-16-1-5. Can you release the kernel for the latest build ?.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RTS32.41-20-16-1-5
