### ISSUE TITLE
[REQUEST] XT2225-2(rhodep-cn) S1SU32.73-112-22 kernel, dts, techpack, etc source codes

### ISSUE THREAD

**Issue by HorseLuke** [MotorolaMobilityLLC/kernel-msm#466]
Hello, could you release kernel, dts, techpack, etc source codes for which S1SU32.73-112-22 XT2225-2(rhodep-cn) used?

Now I found MMI-S1SU32.73-34-7, is that the same as S1SU32.73-112-22 ?

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SU32.73-34-7

Thanks!

**Comment by chenyt9** [comment]
@HorseLuke .
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SU32.73-112-22
