### ISSUE TITLE
Moto G200

### ISSUE THREAD

**Issue by dequadim** [MotorolaMobilityLLC/kernel-msm#467]
Need for Moto G200 device tree.
Can someone help?

**Comment by chenyt9** [comment]
Hi, @dequadim，
 Could you inform the exact released version you need?Thanks.

**Comment by dequadim** [comment]
S1RXS32.50-13-12

Mauro Comiotto
________________________________

**Comment by rogers2602** [comment]
@chenyt9 please release the sources reported above.

**Comment by metl-play** [comment]
I would like to have it too.

**Comment by ThEMarD** [comment]
Heyyo @dequadim @metl-play @asbraga-motorola please see my local manifest here.

I got xpeng working on LineageOS and in this repo is also a README with instructions on how to set it up, sync and build for xpeng.

I do not own an xpeng so I cannot go official with LineageOS though...

https://github.com/moto-sm7325/local_manifests

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RXS32.50-13-12
