### ISSUE TITLE
Release Moto g62 (rhodec) global version - S1SSS32.53-82-3

### ISSUE THREAD

**Issue by GabriLex** [MotorolaMobilityLLC/kernel-msm#468]

**Comment by asbraga-motorola** [comment]
Hi, @GabriLex 
Can you inform the exact released version you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

**Comment by GabriLex** [comment]
> Hi, @GabriLex 
> Can you inform the exact released version you want?
> You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

Hi
I have S1SSS32.53-82-3 and codename rhodec
( I am european)

**Comment by GabriLex** [comment]
> Hi, @GabriLex 
> Can you inform the exact released version you want?
> You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

Hi
I have S1SSS32.53-82-3 and codename rhodec
( I am european)

**Comment by chenyt9** [comment]
@GabriLex ，
I've triggered the release process for version S1SSS32.53-82-3,  please be patient. Thanks!

**Comment by chenyt9** [comment]
@GabriLex 
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SSS32.53-82-3
Thanks.
