### ISSUE TITLE
[Request] Moto G20 (java)(XT2128-1) Kernel Sources RTAS31.68-66-2

### ISSUE THREAD

**Issue by Claravallac** [MotorolaMobilityLLC/kernel-msm#469]
Please send the kernel source of this device

**Comment by Claravallac** [comment]
BUILD ID: RTAS31.68-66-2

please release all GPL protected linux kernel source code for Moto G20 device

@chenyt9
@awheeler-mmi
@TinnoOSS
@asbraga-motorola
@mbissaromoto

As npjohnson said:
"This is getting bordererline absurd. Especially considering this looks like EOL for this device family - please push it."

**Comment by TinnoOSS** [comment]
@ALL,version released:
https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-RTAS31.68-66-2
