### ISSUE TITLE
Latest source for Peregrine

### ISSUE THREAD

**Issue by amitbl** [MotorolaMobilityLLC/kernel-msm#47]
What is the release tag for this Peregrine build? does it even up yet?

3.4.42-gb4744cf
hudsoncm@ilclbld53 # 1
Tue Sep 15 12:06:04 CDT 2015

23.26.3.peregrine_retgb.retgball.en.GB retgb
LPB23.13-17.3

Thanks

**Comment by tags07** [comment]
All commits upto LPB23.13-57 are posted here: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-LPB23.13-57
