### ISSUE TITLE
GPL | Source request for Motorola Edge S Pro (pstar) (S1RAA32.54-37-4)

### ISSUE THREAD

**Issue by Nobooooody** [MotorolaMobilityLLC/kernel-msm#470]
Fingerprint : motorola/pstar_cmcc/pstar:12/S1RAA32.54-37-4/3e5e9d-be4f8:user/release-keys
Kindly requesting source for the following repos for this tag "S1RAA32.54-37-4"

kernel-msm
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-4.19-techpack-camera
kernel-msm-4.19-techpack-display
kernel-msm-4.19-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn

Thanks in advance!
~Andy

**Comment by chenyt9** [comment]
@Nobooooody 
Version is here：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RAA32.54-37-4
