### ISSUE TITLE
[REQUEST] XT2201-2 HIPHIC_RETCN_12_S3SC32.7-42-20 kernel source code, dts, techpack, device tree, etc

### ISSUE THREAD

**Issue by m-akc** [MotorolaMobilityLLC/kernel-msm#472]
Hi!
Please, release the source codes (kernel, dts, device tree, techpack)
for HIPHIC_RETCN_12_S3SC32.7-42-20

Thanks!!

**Comment by chenyt9** [comment]
Version is here：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3SC32.7-42-20
