### ISSUE TITLE
[Request] (moto g8 plus (XT2019-1)) QPIS30.28-Q3-28-26-4-1-7 

### ISSUE THREAD

**Issue by metl-play** [MotorolaMobilityLLC/kernel-msm#473]
Hello,
I want to Request some files which are, namely but not limited to: Kernel Source, Device-Tree, "Vendor-Blobs"
(moto g8 plus (XT2019-1)) QPIS30.28-Q3-28-26-4-1-7 
Of course, only if possible.

**Comment by metl-play** [comment]
Maybe, if existent, even unofficial updates to support Android 11 or newer.

**Comment by asbraga-motorola** [comment]
Hi @metl-play 
I included QPIS30.28-Q3-28-26-4-1-7 in the pipeline for publication.
There is an earlier version already published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPIS30.28-Q3-28-26-4-1-4
For official upgrades, you can check https://motorola-global-portal.custhelp.com/app/software-upgrade

**Comment by metl-play** [comment]
Thank you very much, and thanks for clarification about the already published version.

**Comment by asbraga-motorola** [comment]
Hi @metl-play,
Code is published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-QPIS30.28-Q3-28-26-4-1-7
