### ISSUE TITLE
Moto G20 (java)(XT2128-1) Kernel Sources RTAS31.68-66-2

### ISSUE THREAD

**Issue by Thiizi** [MotorolaMobilityLLC/kernel-msm#475]
pls source kernel moto g20

**Comment by Claravallac** [comment]
@chenyt9
@awheeler-mmi
@TinnoOSS
@asbraga-motorola
@mbissaromoto

**Comment by 99cvitor** [comment]
Up

**Comment by TinnoOSS** [comment]
@ALL,version released:
https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-RTAS31.68-66-2
