### ISSUE TITLE
(GPL)(REQUEST) Kernel source release for RHODE_G_S1SRS32.38-132-5(Moto G52)

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/kernel-msm#477]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack
CC: @chenyt9 @awheeler-mmi

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SRS32.38-132-5
