### ISSUE TITLE
Moto G20 (java)(XT2128-1) Kernel Sources RTAS31.68-66-2

### ISSUE THREAD

**Issue by 99cvitor** [MotorolaMobilityLLC/kernel-msm#478]
Please send to us Moto G20 kernel sources!!! We really need it.

**Comment by 99cvitor** [comment]
@chenyt9 
@awheeler-mmi 
@asbraga-motorola 
@mbissaromoto 
@TinnoOSS

**Comment by TinnoOSS** [comment]
@ALL,version released:
https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-RTAS31.68-66-2
