### ISSUE TITLE
Moto G20 (java)(XT2128-1) Kernel Sources RTAS31.68-66-2

### ISSUE THREAD

**Issue by Adriano2056** [MotorolaMobilityLLC/kernel-msm#482]
@@chenyt9
@awheeler-mmi
@TinnoOSS
@asbraga-motorola
@mbissaromoto

**Comment by TinnoOSS** [comment]
@ALL,version released:
https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-RTAS31.68-66-2

**Comment by Adriano2056** [comment]
Thank you very much, you are a great person and on top of that you still
like to help others. You have just opened new doors for our beloved G2 moto

Em seg., 20 de mar. de 2023 23:58, Tinno ***@***.***>
escreveu:

**Comment by TinnoOSS** [comment]
hi Adriano2056 ,
What is the problem? Can you describe it in more detail?
