### ISSUE TITLE
[REQUEST] Moto G60 (hanoip) [S2RIS32.32-20-7-7] Android 12 Source release (Device Tree, Kernel code and vendor etc.) 

### ISSUE THREAD

**Issue by M7T024** [MotorolaMobilityLLC/kernel-msm#486]

**Comment by M7T024** [comment]
@chenyt9
@awheeler-mmi
@TinnoOSS
@asbraga-motorola
@mbissaromoto

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RIS32.32-20-7-7
