### ISSUE TITLE
GPL | Source request for Motorola Edge 30 (dubai) S1RDS32.55-106-4

### ISSUE THREAD

**Issue by FuccDucc** [MotorolaMobilityLLC/kernel-msm#491]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 30 (dubai) version `S1RDS32.55-106-4`

cc @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=S1RDS32.55-106-4

**Comment by FuccDucc** [comment]
Hello @chenyt9 ?

Please respect GPL, i can see a lot of other requests with even more waiting time that are unanswerred, and barely activity to publish in recent times.

**Comment by ThEMarD** [comment]
@FuccDucc can you please close this source request? It's more important we get the Android 13 kernel source code that I already created a request for

**Comment by FuccDucc** [comment]
Replace with [https://github.com/MotorolaMobilityLLC/kernel-msm/issues/504](https://github.com/MotorolaMobilityLLC/kernel-msm/issues/504)

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RDS32.55-106-3
