### ISSUE TITLE
(GPL) Request for Moto stylus 5g 21 source 

### ISSUE THREAD

**Issue by Drunkmarcus** [MotorolaMobilityLLC/kernel-msm#494]
Request for Moto 5g 2021 kernel source xt2131-1
12 (s2res32.29-16-1-5-1-2)

**Comment by leo858** [comment]
second on this

**Comment by asbraga-motorola** [comment]
code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RES32.29-16-1-5-1-2

**Comment by Franklin199913** [comment]
> Código publicado: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RES32.29-16-1-5-1-2

Uno para el:

motorola/denver_global/denver:12/

S2RES32.29-16-1-5-1-2/08b17-de6a4:user/release-keys

**Comment by Franklin199913** [comment]
motorola/denver_global/denver:12/

S2RES32.29-16-1-5-1-2/08b17-de6a4:user/release-keys
