### ISSUE TITLE
GPL | Source request for Motorola Moto S30 Pro (Tundra) T1SJC33.51-19-7/T1SJ33.117-30-4 (XT2243-2/XT2243-1)

### ISSUE THREAD

**Issue by TadiT7** [MotorolaMobilityLLC/kernel-msm#495]
Kindly requesting source for the following repos of these tags: `T1SJC33.51-19-7`, `T1SJ33.117-30-4`. Prefix may be a little different, but `51-19-7` and `117-30-4` will confirm a match.

kernel-msm
kernel-modules
kernel-devicetree
kernel-camera-devicetree
kernel-display-devicetree
kernel-msm-5.4-techpack-camera
kernel-msm-5.4-techpack-display
kernel-msm-5.4-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn

Thanks!

**Comment by chenyt9** [comment]
Hi, TadiT7 ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SJC33.51-19-7
