### ISSUE TITLE
GPL | Source request for Motorola S30 Edge (xpeng) (S3RXC32.33-8-7)

### ISSUE THREAD

**Issue by rogers2602** [MotorolaMobilityLLC/kernel-msm#496]
kernel-msm
kernel-devicetree
kernel-audio-devicetree
kernel-camera-devicetree
kernel-cvp-devicetree
kernel-display-devicetree
kernel-mmrm-devicetree
kernel-video-devicetree
kernel-msm-5.4.180-techpack-camera
kernel-msm-5.4.180-techpack-cvp
kernel-msm-5.4.180-techpack-display
kernel-msm-5.4.180-techpack-eva
kernel-msm-5.4.180-techpack-mmrm
kernel-msm-5.4.180-techpack-sched
kernel-msm-5.4.180-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-dataipa
vendor-qcom-opensource-datarmnet
vendor-qcom-opensource-datarmnet-ext
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn
motorola-kernel-modules

and others if applicable.

**Comment by chenyt9** [comment]
@rogers2602 
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3RXC32.33-8-7
