### ISSUE TITLE
GPL | Device Tree and Kernel Source Code Request for Motorola Edge 20 Pro (pstar) T1RA33.55-15-10 (XT2153-1)

### ISSUE THREAD

**Issue by ericclose** [MotorolaMobilityLLC/kernel-msm#497]
We kindly request the source code for this tag: T1RA33.55-15-10 on Android 13

**Comment by Sato-goj** [comment]
@chenyt9 Kindly look into it and it would be heavily appreciated if you don't take a couple of months to release the sources as the trend has been so far.

**Comment by twlswan** [comment]
> @chenyt9 Kindly look into it and it would be heavily appreciated if you don't take a couple of months to release the sources as the trend has been so far.

what's with this almost aggressive tone? I know they are obliged to release the sources, but no one actually forces them to release source updates. a few years ago the manufacturers releasing updated sources could probably be counted on one hand. you should be thankful.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1RA33.55-15-10

**Comment by richard4O4** [comment]
> Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1RA33.55-15-10

@asbraga-motorola @chenyt9  Could you please share the instructions for how to build the [MMI-T1RA33.55-15-10](https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1RA33.55-15-10) kernel for pstar? We would be very appreciated if you can.

**Comment by chenyt9** [comment]
@all, Pls refer to:
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-T1RA33.55-15-10
Thanks.

**Comment by Sato-goj** [comment]
@chenyt9 Thank you very much.
 I really appreciate the dedication and hard work Motorola is showing in hearing out and fixing the requirements of the customer base.

**Comment by Sato-goj** [comment]
> > @chenyt9 Kindly look into it and it would be heavily appreciated if you don't take a couple of months to release the sources as the trend has been so far.
> 
> what's with this almost aggressive tone? I know they are obliged to release the sources, but no one actually forces them to release source updates. a few years ago the manufacturers releasing updated sources could probably be counted on one hand. you should be thankful.

ok dance then
