### ISSUE TITLE
Moto Edge 30 Pro (hiphi) Sources for Android 13 (T1SH33.35-23-20) (XT2201-1)

### ISSUE THREAD

**Issue by Anush02198** [MotorolaMobilityLLC/kernel-msm#498]
@asbraga-motorola @motorolamobility @jwylder1 @awheeler-mmi @ccfries @louiewang Please do realease full sources the asap

**Comment by Anush02198** [comment]
@chenyt9

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SH33.35-23-20

**Comment by YeYdi-YonY** [comment]
@Anush02198 Hopefully I can see customs roms soon and help with testing.
