### ISSUE TITLE
GDB support?

### ISSUE THREAD

**Issue by JulianVolodia** [MotorolaMobilityLLC/kernel-msm#50]
I saw that in readme:

>   gdb'ing a non-running kernel currently fails because gdb (wrongly)
>   disregards the starting offset for which the kernel is compiled.

Have you any idea what need to be fixed or "workarounded"?

Best regards.

**Comment by awheeler-mmi** [comment]
Old, w/rt an old kernel.

**Comment by JulianVolodia** [comment]
OK, best.
