### ISSUE TITLE
GPL | Source request for Motorola Edge 40 Pro (rtwo) XT2301-4 - T1TR33.43-20-15

### ISSUE THREAD

**Issue by FuccDucc** [MotorolaMobilityLLC/kernel-msm#500]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 40 Pro (rtwo) version `T1TR33.43-20-15`

Model number: `XT2301-4`
Codename: `rtwo`

cc @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=T1TR33.43-20-15

** If needed to find it, an example output of this version:
```
SW Version: rtwo_g-user 13 T1TR33.43-20-15 a7538-6cf6e release-keysM8550_DE30_30.2276.01.75.17R
Modem Version: M8550_DE30_30.2276.01.75.17R
FSG Version: FSG-8550-01.68.11
MBM Version: MBM-3.0-rtwo-a6b97da0-dirty-230218
Build Fingerprint: motorola/rtwo_g/rtwo:13/T1TR33.43-20-15/a7538-6cf6e:user/release-keys
```

It's the best if you release this together with newer version [T1TR33.43-20-28](https://github.com/MotorolaMobilityLLC/kernel-msm/issues/503) sources request

**Comment by FuccDucc** [comment]
I hope this isn't going to take months (or even lead to violating GPL laws, by indefinitely not being processed) as has seemingly been the trend over here. This is your newest device, it's good practise to release it off the bat, so development can begin during the moment of peak interest.

**Comment by FuccDucc** [comment]
@asbraga-motorola i see you are online now, please notice this!

**Comment by chenyt9** [comment]
@FuccDucc ，
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.43-20-15

**Comment by FuccDucc** [comment]
> @FuccDucc ， Version released： https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.43-20-15
@chenyt9 

Thanks, but please release the latest version too: `T1TR33.43-20-28`
[https://github.com/MotorolaMobilityLLC/kernel-msm/issues/503](https://github.com/MotorolaMobilityLLC/kernel-msm/issues/503) it was requested.
