### ISSUE TITLE
GPL | Source request for Motorola X40 (rtwo) XT2301-5 - T1TR33.4-30-62

### ISSUE THREAD

**Issue by zhaoyunjihao** [MotorolaMobilityLLC/kernel-msm#502]
Motorola X40 (rtwo) XT2301-5
T1TR33.4_30_62

**Comment by chenyt9** [comment]
Hi, @zhaoyunjihao ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.4-30-62
