### ISSUE TITLE
GPL | Source request for Motorola Edge 40 Pro (rtwo) XT2301-4 - T1TR33.43-20-28

### ISSUE THREAD

**Issue by FuccDucc** [MotorolaMobilityLLC/kernel-msm#503]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 40 Pro (rtwo) version `T1TR33.43-20-28`

Model number: `XT2301-4`
Codename: `rtwo`

cc @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=T1TR33.43-20-28

This is a different request than the other one for version [T1TR33.43-20-15](https://github.com/MotorolaMobilityLLC/kernel-msm/issues/500)
It is ok to handle the other one first

**Comment by ThEMarD** [comment]
Heyyo @FuccDucc , do you own an Edge 40 Pro? I am starting to work on LineageOS trees for it and if you can contribute I'd appreciate the help

https://github.com/moto-sm8550

tbh you can just close the previous source code request as having the latest version would be more important anyways

**Comment by ThEMarD** [comment]
@chenyt9 looking at MMI-T1TR33 kernel source code releases so far, they seem to be missing some repos unless these are unused on rtwo?

kernel-audio-devicetree 
kernel-mmrm-devicetree
kernel-msm-techpack-display
kernel-msm-techpack-video
kernel-msm-techpack-dataipa

can you please confirm about these repos and exactly which are needed to compile the full kernel source code for rtwo?

**Comment by ThEMarD** [comment]
@FuccDucc can you please close this request? SGCMarkus made a request that specifically mentions the repos we need. He will be maintaining LineageOS for rtwo

https://github.com/MotorolaMobilityLLC/kernel-msm/issues/516

**Comment by chenyt9** [comment]
@ThEMarD @FuccDucc 
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.43-20-28
