### ISSUE TITLE
GPL | Source request for Motorola Edge 30 (dubai) T1RD33.116-33-3

### ISSUE THREAD

**Issue by ThEMarD** [MotorolaMobilityLLC/kernel-msm#504]
Heyyo, I currently work on LineageOS for dubai and humbly request the kernel source code for Android 13 release of dubai T1RD33.116-33-3 so that I can also update my kernel.

I will need all necessary modules and drivers that go with this kernel source code as well, please.

**Comment by tattwamashi** [comment]
yes, please upload the source codes @chenyt9

**Comment by sb6596** [comment]
Please do the needful @chenyt9

**Comment by FuccDucc** [comment]
HELLO
@chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1RD33.116-33-3

**Comment by albayhani** [comment]
I am looking for a recovery twrp for this device
