### ISSUE TITLE
[REQUEST] Moto G32 LATAM (devon) [S2SNS32.34-60-6] Android 12 Sources release (Device Tree, Kernel code etc.) 

### ISSUE THREAD

**Issue by facufachin** [MotorolaMobilityLLC/kernel-msm#505]
Please release sources @asbraga-motorola @motorolamobility @jwylder1 @awheeler-mmi @ccfries @louiewang

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2SNS32.34-60-6
