### ISSUE TITLE
GPL | Source request | Motorola Edge 30 Pro / Motorola Edge Plus (2022) / Motorola Edge Plus 5G UW / Motorola Edge X30 / Motorola Edge X30: USC (hiphi/hiphic/hiphid)

### ISSUE THREAD

**Issue by 7Soldier** [MotorolaMobilityLLC/kernel-msm#506]
Dear Motorola Mobility, kindly requesting last sources for hiphi/hiphic/hiphid phones family:
- `T1SC33.52-8-6`
- `S3SHS32.12-41-4-5`
- `S3SF32.35-5-9`

Including opensource repositories:
- kernel-msm
- motorola-kernel-modules
- kernel-devicetree
- kernel-audio-devicetree
- kernel-camera-devicetree
- kernel-display-devicetree
- kernel-mmrm-devicetree
- kernel-video-devicetree
- vendor-qcom-opensource-audio-kernel
- vendor-qcom-opensource-camera-kernel
- vendor-qcom-opensource-datarmnet
- vendor-qcom-opensource-datarmnet-ext
- vendor-qcom-opensource-eva-kernel
- vendor-qcom-opensource-mmrm-driver
- vendor-qcom-opensource-wlan-fw-api
- vendor-qcom-opensource-wlan-qca-wifi-host-cmn
- vendor-qcom-opensource-qcacld-3.0
- kernel-msm-5.10-techpack-cvp
- kernel-msm-5.10-techpack-display
- kernel-msm-5.10-techpack-dataipa
- kernel-msm-5.10-techpack-video
- and others required for working stuff (device tree, all the necessary audio/video/display techpack, etc.)

Thanks in advice, waiting for respond!
Sincerely, 7Soldier

CC:
@chenyt9
@awheeler-mmi
@asbraga-motorola
@motorolamobility
@jwylder1
@mbissaromoto
@ccfries
@TinnoOSS

**Comment by s4704** [comment]
Please post the full source code.

**Comment by LucyfMorning** [comment]
Yeah..  release full code

**Comment by Anush02198** [comment]
Please Release Source code .. @motorolamobility @awheeler-mmi @asbraga-motorola

**Comment by 7Soldier** [comment]
Please, don't ignore our requests for sources.
We need all mentioned repositories source code at least for T1SH33.35-23-20.

Thanks in advice!

CC:
@chenyt9
@awheeler-mmi
@asbraga-motorola
@motorolamobility
@jwylder1
@mbissaromoto
@ccfries

**Comment by 7Soldier** [comment]
Upping issue.

CC:
@chenyt9
@awheeler-mmi
@asbraga-motorola
@motorolamobility
@jwylder1
@mbissaromoto
@ccfries
@TinnoOSS

**Comment by YeYdi-YonY** [comment]
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SH33.35-23-20
