### ISSUE TITLE
GPL | Source request for Motorola Moto G32 (Devon) [S2SNS32.34-72-12-2] Android 12 Sources release (Device Tree, Kernel code, etc.)

### ISSUE THREAD

**Issue by nesper8** [MotorolaMobilityLLC/kernel-msm#507]
Hello,
I want to Request some files which are, namely but not limited to: Kernel Source, Device-Tree, "Vendor-Blobs", etc... for Moto G32 (Devon) [S2SNS32.34-72-12-2] Android 12

@chenyt9 
@awheeler-mmi 
@asbraga-motorola 
@motorolamobility 
@jwylder1 
@mbissaromoto 
@ccfries 

Thank you

**Comment by nesper8** [comment]
Bumping for visibility

Thank you

**Comment by nesper8** [comment]
Bumping for visibility again 
Thank you

**Comment by chenyt9** [comment]
@nesper8 
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2SNS32.34-72-12-2

**Comment by nesper8** [comment]
Thank you very much
