### ISSUE TITLE
GPL | Source request for Motorola Moto G42 [XT2233-2] (Hawao) [S2SES32.28-67-7] 

### ISSUE THREAD

**Issue by MiniViper111** [MotorolaMobilityLLC/kernel-msm#508]
Hello,

Please release the kernel tree, vendor, device tree and all the necessary audio/video/display techpack for Motorola motog42

Model number: XT2233-2
Codename: Hawao
Build Number : S2SES32.28-67-7

CC: @chenyt9 @awheeler-mmi @TinnoOSS @asbraga-motorola @mbissaromoto

**Comment by MiniViper111** [comment]
Requesting again to release the device tree, source code.

**Comment by MiniViper111** [comment]
Requesting again to please release the kernel tree, vendor, device tree and all the necessary audio/video/display techpack for Motorola motog42

CC:
@chenyt9
@awheeler-mmi
@asbraga-motorola
@motorolamobility
@mbissaromoto
@TinnoOSS

**Comment by chenyt9** [comment]
@MiniViper111 
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2SES32.28-67-7
Sorry for delay.

**Comment by MiniViper111** [comment]
Thanks @chenyt9
