### ISSUE TITLE
GPL Source Request for DROID Turbo 2/Moto X Force

### ISSUE THREAD

**Issue by Rashed97** [MotorolaMobilityLLC/kernel-msm#51]
5.1.1. release for DROID Turbo 2:
- System version: 23.31.23.kinzie_verizon.verizon.en.US
- Build number: LCK23.130-23
- Kernel version: 3.10.49-perf-ge851b65

Thank you in advanced

**Comment by charleseb** [comment]
Hi Rashed,

I'm working to release this version, it will be available in a few days.

Thanks,
Charles

On Sun, Dec 6, 2015 at 4:54 AM, Rashed Abdel-Tawab <notifications@github.com

**Comment by Rashed97** [comment]
Hi Charles,

Thanks for the update, I really appreciate it

Have a great afternoon,
Rashed

**Comment by charleseb** [comment]
Hi Rashed,

The version MMI-LCK23.130-23 has been released to Github.

Thanks,
Charles
