### ISSUE TITLE
[REQUEST] kernel source code for moto g(40) / g(60) [S2RIS32.32-20-7-11]

### ISSUE THREAD

**Issue by fuyukihidekii** [MotorolaMobilityLLC/kernel-msm#511]
Android 12
BUILD ID: S2RIS32.32-20-7-11

hanoi/hanoip is EOL now.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RIS32.32-20-7-11

**Comment by fuyukihidekii** [comment]
Thank you!

**Comment by fuyukihidekii** [comment]
@asbraga-motorola Could you release the readme for this TAG as well?

**Comment by fuyukihidekii** [comment]
> @asbraga-motorola Could you release the readme for this TAG as well?

CC: @chenyt9
