### ISSUE TITLE
[REQUEST] Kernel source for codename astro RPLS31.Q2-63-10-2-9 (Motorola One Fusion)

### ISSUE THREAD

**Issue by notmaddock** [MotorolaMobilityLLC/kernel-msm#515]
Hello, the sources for RPLS31.Q2-63-10-2-4 have been released but the latest OEM update is RPLS31.Q2-63-10-2-9. The update is a security update but the sources might have changed and I have no real way to check if they did or not.

Thank you.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPLS31.Q2-63-10-2-9

**Comment by notmaddock** [comment]
Thank you!
