### ISSUE TITLE
GPL | Source request for Motorola Edge 40 Pro (rtwo) XT2301-4 - T1TR33.43-20-28

### ISSUE THREAD

**Issue by SGCMarkus** [MotorolaMobilityLLC/kernel-msm#516]
Hi,
could you please release the sources for the following devicetree repositories (based on current naming scheme)?
kernel-devicetree
kernel-audio-devicetree
kernel-bt-devicetree
kernel-camera-devicetree
kernel-data-devicetree
kernel-display-devicetree
kernel-eSE-devicetree
kernel-eva-devicetree
kernel-graphics-devicetree
kernel-mm-devicetree
kernel-mmrm-devicetree
kernel-nfc-devicetree
kernel-video-devicetree
kernel-wlan-devicetree

and the following kernel + module sources (using paths from CLO here) if they differ from the CLO release?
kernel/msm-5.15
platform/vendor/qcom/opensource/audio-kernel-ar
platform/vendor/opensource/camera-kernel
platform/vendor/opensource/display-drivers
platform/vendor/opensource/mm-drivers
platform/vendor/opensource/eva-kernel
platform/vendor/qcom/opensource/graphics-kernel
platform/vendor/opensource/mmrm-driver
platform/vendor/opensource/video-driver
platform/vendor/qcom-opensource/bt-kernel
platform/vendor/qcom/opensource/securemsm-kernel
platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn
platform/vendor/qcom-opensource/wlan/qcacld-3.0
platform/vendor/qcom-opensource/wlan/fw-api
platform/vendor/qcom-opensource/wlan/platform
platform/vendor/nxp/opensource/driver
platform/vendor/qcom/opensource/datarmnet
platform/vendor/qcom/opensource/datarmnet-ext
platform/vendor/opensource/dataipa

as well as:
motorola-kernel-modules

Thanks in advance

**Comment by FuccDucc** [comment]
You forgot to add to your list:

kernel-msm-techpack-display
kernel-msm-techpack-video
kernel-msm-techpack-dataipa

Like #509 had included

@SGCMarkus can edit it in, or else i request that who process this will take it along.

**Comment by FuccDucc** [comment]
For the entire issue:

cc @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

**Comment by SGCMarkus** [comment]
> You forgot to add to your list:
> 
> kernel-msm-techpack-display
> kernel-msm-techpack-video
> kernel-msm-techpack-dataipa


I included them though? (just in the CLO naming scheme of the repos, as we have so many new repos to keep track of):
platform/vendor/opensource/display-drivers
platform/vendor/opensource/video-driver
platform/vendor/opensource/dataipa

**Comment by chenyt9** [comment]
@SGCMarkus 
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.43-20-28
