### ISSUE TITLE
[REQUEST] Kernel Source for Motorola G52j 5G (cypfr) - S3RYBS32.168-19-5-3

### ISSUE THREAD

**Issue by Garry050** [MotorolaMobilityLLC/kernel-msm#517]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola G52j 5G (cypfr) version S3RYBS32.168-19-5-3

Model number: XT2219-1
Codename: cypfr

Remind: This is not Global model. only Japan retail model

CC: @chenyt9 @awheeler-mmi @TinnoOSS @asbraga-motorola @mbissaromoto

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3RYBS32.168-19-5-3
