### ISSUE TITLE
GPL | Source request for Motorola Edge+ (2023) (rtwo) XT2301-1 - T1TR33.43-48-21

### ISSUE THREAD

**Issue by FuccDucc** [MotorolaMobilityLLC/kernel-msm#520]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge+ (2023) version `T1TR33.43-48-21`

Model number: `XT2301-1`
Codename: `rtwo`
Version: `T1TR33.43-48-21`

While processing this request, please take extra care to also include all of the repositories mentioned in #516

cc @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=T1TR33.43-48-21

**Comment by chenyt9** [comment]
@FuccDucc ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.43-48-21
