### ISSUE TITLE
GPL | Source request | Motorola G Power (2021) (Borneo) XT2117-4 RZB31.Q2-143-27-11-12-3

### ISSUE THREAD

**Issue by iTrySmoke** [MotorolaMobilityLLC/kernel-msm#521]
Model Number: `XT2117-4`
Codename: `Borneo`
Version: `RZB31.Q2-143-27-11-12-3`
Requesting all available sources for this device described above.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RZB31.Q2-143-27-11-12-3

**Comment by teodororo** [comment]
ty, @asbraga-motorola
