### ISSUE TITLE
开源下Razr 40/Razr 40 Ultra的内核源码吧

### ISSUE THREAD

**Issue by Alpa7000** [MotorolaMobilityLLC/kernel-msm#523]
Razr 40 Ultra(zeekr)：T2TZ33.28-16-19
Razr 40(lynkco)：T2TV33.45-10-9

**Comment by Alpa7000** [comment]
全套内核源码，我可不想上圣经去骂人

**Comment by chenyt9** [comment]
@Alpa7000 ,你要的Moto Razr 40 代码是哪个地区的代码？ 中国区还是非中国区？

**Comment by chenyt9** [comment]
在您提供正确的区域版本要求之前，可以先参考这些版本：
Moto razr 40 中国版本：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T2TV33.45-10-17
Moto razr 40 海外版本：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T2TV33.45-10-20
Moto razr 40 Ultra中国版本：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T2TZ33.18-16-19
Moto razr 40 Ultra海外版本：https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TZ33.3-62-29
