### ISSUE TITLE
Moto G32 (devon) Kernel Sources S2SNS32.34-60-7

### ISSUE THREAD

**Issue by AndyBGD** [MotorolaMobilityLLC/kernel-msm#524]
@@chenyt9
@awheeler-mmi
@TinnoOSS
@asbraga-motorola
@mbissaromoto

**Comment by teodororo** [comment]
up

**Comment by facufachin** [comment]
@chenyt9
@awheeler-mmi
@TinnoOSS
@asbraga-motorola
@mbissaromoto

**Comment by mercedessosaa** [comment]
@chenyt9
@awheeler-mmi
@TinnoOSS
@asbraga-motorola
@mbissaromoto

**Comment by teodororo** [comment]
up

**Comment by chenyt9** [comment]
@facufachin ，
I didn't find S2SNS32.34-60-7 version in our database. Is this version officially released? I only found this version: S2SNS32.34-60-6, does it meet your needs? Thanks

**Comment by chenyt9** [comment]
@facufachin @AndyBGD 
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2SNS32.34-60-7
