### ISSUE TITLE
T1TZ33.3-62-25 source code

### ISSUE THREAD

**Issue by balika011** [MotorolaMobilityLLC/kernel-msm#526]
Dear Motorola,
I would like to modify compile the T1TZ33.3-62-25 kernel source.
Please provide that GPL source code.
Thank you,
Balázs Triszka

**Comment by chenyt9** [comment]
@balika011 ,
pls use this version first:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TZ33.3-62-29
And will release T1TZ33.3-62-25 soon.

**Comment by balika011** [comment]
Okay, thank you!

**Comment by balika011** [comment]
What is the name of the branch for this tag in kernel-devicetree repo?

**Comment by chenyt9** [comment]
@balika011 ,
version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TZ33.3-62-25
