### ISSUE TITLE
GPL | Source request | Moto G Stylus 5G 2023 (genevn) [T1TGNS33.60-55-3-1]

### ISSUE THREAD

**Issue by MilesBreslin** [MotorolaMobilityLLC/kernel-msm#527]
codename: `genevn`
version: `T1TGNS33.60-55-3-1`
sku: `XT2315-1`

```
genevn:/ $ uname -r
5.10.136-android12-9-00078-gccf5ed5e3e3a-ab9626999
```

Requesting all available sources for this device described above.

@chenyt9
@awheeler-mmi
@asbraga-motorola
@motorolamobility
@jwylder1
@mbissaromoto
@ccfries
@TinnoOSS

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TGNS33.60-55-3-1

**Comment by PizzaG** [comment]
I am unable to get the Ilitek touchscreen variant of the device working and has been an 8 month battle, need some help to get it working.
