### ISSUE TITLE
Moto g50 Android 12 Kernel Source Code - S1RFS32.27-25-12

### ISSUE THREAD

**Issue by robbins** [MotorolaMobilityLLC/kernel-msm#529]
Hi, I'd like to request the Android 12 kernel source code for the following device & version.

Codename `ibiza`
Version: `S1RFS32.27-25-12`
Model: `XT2137-1`

Thanks.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RFS32.27-25-12
