### ISSUE TITLE
Moto G LTE (Peregrine) latest sources

### ISSUE THREAD

**Issue by fonz93** [MotorolaMobilityLLC/kernel-msm#53]
Hi, can you release latest sources for this?

ro.build.id=LPB23.13-61
ro.build.description=peregrine_retus-user 5.1 LPB23.13-61 62 release-keys
ro.build.fingerprint=motorola/peregrine_retus/peregrine:5.1/LPB23.13-61/62:user/release-keys

the "WCNSS_qcom_wlan_nv.bin" firmware differs from 23-13.58, so i would like to know if there are changes to "vendor-qcom-opensource-wlan-prima" too, thank you.

**Comment by charleseb** [comment]
Hi fonz93,

I'm working to release this version. It will be available in a few days.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi fonz93,

This version has been released to Github.

Thanks,
Charles
