### ISSUE TITLE
Provide latest tag for capri moto g10 RRBS31.Q1-3-58-19

### ISSUE THREAD

**Issue by sultanahamer** [MotorolaMobilityLLC/kernel-msm#530]
Please provide latest tag(RRBS31.Q1-3-58-19) for capri(moto g10). The latest tag on this repository is MMI-RRB31.Q1-3-48-2  which is older

The touch screen driver isn't working for the new devices if we are using this tag to build.

**Comment by sultanahamer** [comment]
@chenyt9 bumping up

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RRBS31.Q1-3-58-19
