### ISSUE TITLE
[REQUEST] Kernel Release for RPXS31.Q2-58-17-7-3 guamp

### ISSUE THREAD

**Issue by DelightReza** [MotorolaMobilityLLC/kernel-msm#531]
RPXS31.Q2-58-17-7-3 has been published in September 2022, why kernel source not pushed yet?

@mbissaromoto

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPXS31.Q2-58-17-7-3

**Comment by DelightReza** [comment]
@asbraga-motorola other repos are not pushed device tree, kernel modules, techpack and all..

**Comment by asbraga-motorola** [comment]
I'll check why they are missing.

**Comment by asbraga-motorola** [comment]
The missing repos are published now. You may look for the tag MMI-RPXS31.Q2-58-17-7-3.

**Comment by gelomon** [comment]
Hello as per checking the tag it is still missing -- device tree, techpack, kernel modules and others

**Comment by asbraga-motorola** [comment]
The tag MMI-RPXS31.Q2-58-17-7-3 is applied to the repos

- kernel-camera-devicetree
- kernel-devicetree
- kernel-display-devicetree
- kernel-msm
- kernel-msm-techpack-camera
- kernel-msm-techpack-display
- kernel-msm-techpack-video
- vendor-cirrus-audio-dlkm
- vendor-qcom-opensource-audio-kernel
- vendor-qcom-opensource-data-kernel
- vendor-qcom-opensource-wlan-fw-api
- vendor-qcom-opensource-wlan-qca-wifi-host-cmn
- vendor-qcom-opensource-wlan-qcacld-3.0

and many others.
Could you please check again and specify which ones are missing?

**Comment by gelomon** [comment]
Thank you @asbraga-motorola. I have rechecked some of them and github is not showing them until I searched the whole tag. I will be verifying them.

Regards
