### ISSUE TITLE
GPL | Source request for Motorola Edge 30 Ultra (eqs) T1SQ33.15-11-137-10

### ISSUE THREAD

**Issue by FuccDucc** [MotorolaMobilityLLC/kernel-msm#532]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 30 Ultra version `T1SQ33.15-11-137-10`

Codename: `eqs`
Version: `T1SQ33.15-11-137-10` (Android 13 push)

While processing this request, please take care to also include all of the repositories, that are structured in a way like it's done for another device at #516

cc @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=T1SQ33.15-11-137-10

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SQ33.15-11-137-10
