### ISSUE TITLE
[REQUEST] Moto G Stylus 5g 2021 (denver) Android 12 Sources release

### ISSUE THREAD

**Issue by leo858** [MotorolaMobilityLLC/kernel-msm#533]
hello, could you please release the sources for this phone?
thanks

**Comment by asbraga-motorola** [comment]
@leo858,
Can you inform the exact released version you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2.

**Comment by leo858** [comment]
@asbraga-motorola you mean the build number? It is S2RES32.29-16-1-15-1-2

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RES32.29-16-1-15-1-2

**Comment by heavybluewoodpecker** [comment]
s2re32.29-16-1-5-18
