### ISSUE TITLE
[REQUEST] kernel source code for moto g(9) power - [RZCS31.Q2-57-12-14] 

### ISSUE THREAD

**Issue by fuyukihidekii** [MotorolaMobilityLLC/kernel-msm#534]
Asking for the code to pair with the latest available firmware

If possible, please release #510 also.

**Comment by fuyukihidekii** [comment]
Kindly, we have any update on this and #510 ?

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RZCS31.Q2-57-12-14
