### ISSUE TITLE
GPL | Source request | Motorola Edge 30 Neo (Miami) XT2245-1 T1SSM33.1-121-4

### ISSUE THREAD

**Issue by RozkolNFT** [MotorolaMobilityLLC/kernel-msm#535]
Model Number: XT2245-1
Codename: Miami
Version: T1SSM33.1-121-4
Requesting all available sources for this device described above.

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SSM33.1-121-4
