### ISSUE TITLE
[GPL Request] Kernel Source for Moto G51 5G

### ISSUE THREAD

**Issue by gooosedev** [MotorolaMobilityLLC/kernel-msm#540]
Hello,
Can you please release the Kernel Sources (along with the usual device-trees, techpacks, modules, ...) for the Motorola Moto G51 5G (cypfq).

build: S2RYA32.58-13-9 (from: ro.build.id)

thanks in advance.

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RYA32.58-13-9
