### ISSUE TITLE
(Request) Moto Edge 30 Fusion

### ISSUE THREAD

**Issue by RadioactivePlays** [MotorolaMobilityLLC/kernel-msm#541]
Hello Moto, I would like to request the triggering process to release the source code of the `Edge 30 Fusion (tundra)

Model number: XT2243-1
Codename: tundra
Variant: RETBR
Version: `latest - Android 13 - (T1SJS33.117-30-3-2)`

Thanks in advance.

Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 30 Fusion version T1SJS33.117-30-3-2

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in #516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SJS33.117-30-3-2

**Comment by RadioactivePlays** [comment]
TYSM
