### ISSUE TITLE
GPL | Source request for Motorola Edge+ (2023) (rtwo) - T1TR33.43-48-41

### ISSUE THREAD

**Issue by mxzqw** [MotorolaMobilityLLC/kernel-msm#543]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge+ (2023) version `T1TR33.43-48-41`

Model number: `XT2301-1`
Codename: `rtwo`
Version: `T1TR33.43-48-41` (October 2023)
Variant: `RETUS`

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in #516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

I am from the LineageOS project for rtwo [that you can see on XDA](https://xdaforums.com/t/rom-unofficial-lineageos-20-android-13-for-the-motorola-edge-40-pro-x40-edge-2023-rtwo.4613129/), fulfilling this request can help us get forwards on certain things and it would be appreciated if it can be expedited.

Notif: @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=T1TR33.43-48-41

*Edit (8th November 2023): GPL request changed from `T1TR33.43-48-35` to `T1TR33.43-48-41` because so much time passed for this request to be processed, that newer release already took place.

**Comment by FuccDucc** [comment]
@chenyt9 @asbraga-motorola Are you taking a vacation bro? Rarely activity in entire requests space..

**Comment by mxzqw** [comment]
> @chenyt9 @asbraga-motorola Are you taking a vacation bro? Rarely activity in entire requests space..

@FuccDucc Please don't make comments like that in any of my requests, i want us to remain civil (and not impatient). I see you made a habit out of it. Thanks for understanding

**Comment by mxzqw** [comment]
Hello, i am growing a little concerned now.. are there any status updates? The low speed of processing GPL releases has consequences for OSS projects like ours.

Please consider releasing this after 2+ months, @asbraga-motorola
I hope it gets released at all.. also, i updated the requested version number as the passing of time brought newer versions.

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.43-48-35
Thanks

**Comment by mxzqw** [comment]
> Version released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.43-48-35 Thanks

@chenyt9 @mbissaromoto
Thanks for the effort, but you didn't see the request was no longer about T1TR33.43-48-35 (which by now, is old) ?

Almost 2 weeks ago, i've changed it to `T1TR33.43-48-41`, please read the issue description again, and i would appreciate if you can still upload the newer version now that you're at it. Please release `T1TR33.43-48-41`

**Comment by ThEMarD** [comment]
Please make sure to also release updated kernel source code for this repo as well

https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-display-drivers

update: Oh, I just noticed instead of pushing the tag there, it was pushed to 5.4 kernel techpack display repo instead

https://github.com/MotorolaMobilityLLC/kernel-msm-5.4-techpack-display/tree/MMI-T1TR33.43-48-35

**Comment by mxzqw** [comment]
Closing in favour of https://github.com/MotorolaMobilityLLC/kernel-msm/issues/567 (retry to have you release the desired version). Because of the mistake in processing it in this one, it would be appreciated if you give it some priority regardless of switching to a new issue ID.

**Comment by asbraga-motorola** [comment]
Thank you.
It's really better to use one request per issue.
