### ISSUE TITLE
GPL | Source request for Motorola Moto X40 (rtwo) - T1TR33.4-30-77

### ISSUE THREAD

**Issue by mxzqw** [MotorolaMobilityLLC/kernel-msm#546]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Moto X40 version `T1TR33.4-30-77`

Model number: `XT2301-5`
Codename: `rtwo`
Version: `T1TR33.4-30-77`
Variant: `RETCN`

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in #516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

I am from the LineageOS project for rtwo [that you can see on XDA](https://xdaforums.com/t/rom-unofficial-lineageos-20-android-13-for-the-motorola-edge-40-pro-x40-edge-2023-rtwo.4613129/), fulfilling this request can help us get forwards on certain things and it would be appreciated if it can be expedited.

Notif: @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=T1TR33.4-30-77

*Edit (8th November 2023):
**NOTE:** If newer versions have been released for this device by the time this request is met, please push those as well. I couldn't find newer ones by manually searching the web, but i also dont speak Chinese to read any such version numbers from Chinese news posts, so yeah, i can't be sure.

**Comment by GreyElaina** [comment]
i noticed that new kernel version `5.15.104` appeared in a14 update.

**Comment by chenyt9** [comment]
Version released：

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TR33.4-30-77

Thanks.
