### ISSUE TITLE
[GPL] [REQUEST] kernel source code for motorola moto G(52) (rhode) - [S1SRS32.38-132-14]

### ISSUE THREAD

**Issue by ZeakiOFC** [MotorolaMobilityLLC/kernel-msm#547]
Hello Moto! 
If possible, could you provide the kernel source code for the July Security Update, along with any associated README documentation, if available?

Thank you for your attention.

**Comment by chenyt9** [comment]
@IsaacOfc ,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SRS32.38-132-14
