### ISSUE TITLE
Moto G53 5G (penang) sourcecode request (T1TP33.75-96-1) 

### ISSUE THREAD

**Issue by SavedByLight** [MotorolaMobilityLLC/kernel-msm#548]
Can you upload the kernel source code

Device: moto g53 5G
Codename: penang
Build Number: T1TP33.75-96-1
Model:XT2335-2
Variant: retgb

Please include every part of the source code, thank you

**Comment by MrFluffyOven** [comment]
T1TP33.75-96-1 update

**Comment by D4yvid** [comment]
Probably you can use this kernel source:
https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-T1TPC33.1-37-8
I don't know if it's the correct phone model, but i searched and it's XT2335-2, so probably it's the same kernel but on another Android release

**Comment by chenyt9** [comment]
@MrFluffyOven,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TP33.75-96-1
