### ISSUE TITLE
GPL Source Request for Moto X Force Chinese Version

### ISSUE THREAD

**Issue by DevriesL** [MotorolaMobilityLLC/kernel-msm#55]
Hi, I bought a Moto X Force Chinese version also called MOTO X 极 (Ji)
I want to make a custom kernel on these phone
Thank you in advanced

**Comment by tags07** [comment]
Could you post the Software Version/Build Version you have on the device under Settings->About Phone. I'll check if that's already posted or if its in our pipieline

**Comment by DevriesL** [comment]
Hi Palaniappan,
System version: 23.1.229.kinzie_retcn_ds.retcn.en.CN retcn
Build number: LPK23
Kernel version: 3.10.49-perf-g02cfaca

**Comment by tags07** [comment]
LPK23.145-5 is in our pipeline. We'll get to posting it soon.

**Comment by DevriesL** [comment]
Hi Palaniappan,
Sorry I have made a mistake
The System version: 23.11.1.kinzie_retcn_ds.retcn.en.CN retcn
Build number: LPK23.229
Kernel version: 3.10.49-perf-g02cfaca

**Comment by tags07** [comment]
@DevriesL I am checking if we shipped this version.We may have shipped it end of December 2015. If so, we will post the kernel sources for this release soon..

**Comment by DevriesL** [comment]
OK, Thank you, hope to get this kernel source :D

**Comment by DevriesL** [comment]
@tags07 It is been really a long time...

**Comment by charleseb** [comment]
Hi DevriesL,

I'm working to release this tag.
This version will be available in a few days.

Thanks,
Charles
Em 7 de fev de 2016 12:52 AM, "DevriesL" notifications@github.com
escreveu:

**Comment by charleseb** [comment]
Hi all,

The version MMI-LPK23.229 has been released to Github.

Thanks,
Charles
