### ISSUE TITLE
 [GPL] [REQUEST] kernel source code for motorola moto G(52) (rhode) - [S1SRS32.38-132-8]

### ISSUE THREAD

**Issue by enthusiastic2003** [MotorolaMobilityLLC/kernel-msm#551]

**Comment by enthusiastic2003** [comment]
Please release the kernel source with the relevent techpack/display/audio. 

CC: @chenyt9 @awheeler-mmi @asbraga-motorola @mbissaromoto

**Comment by chenyt9** [comment]
Hi, @enthusiastic2003 
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1SRS32.38-132-8
