### ISSUE TITLE
[Request] eqs-T1SQS33.15-11-137-10-5 kernel source

### ISSUE THREAD

**Issue by hingbong** [MotorolaMobilityLLC/kernel-msm#552]
eqs has source of version `MMI-T1SQ33.15-11-137-10` is released, but there is a system update to `T1SQS33.15-11-137-10-5`, if kernel source of them is same, ignore this

**Comment by hingbong** [comment]
and volume up key of MMI-T1SQ33.15-11-137-10 is unusable while I am using

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SQS33.15-11-137-10-5
