### ISSUE TITLE
Kernel source request T1TPN33.58-68-1-2-1

### ISSUE THREAD

**Issue by AsmoValroth** [MotorolaMobilityLLC/kernel-msm#554]
Can you please release the kernel source for  the Moto g 5g (2023) T1TPN33.58-68-1-2-1 along with the device tree please and thank you

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TPN33.58-68-1-2-1
