### ISSUE TITLE
[REQUEST] Latest Dubai kernel source

### ISSUE THREAD

**Issue by npjohnson** [MotorolaMobilityLLC/kernel-msm#555]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 30 Pro version DUBAI_RETAIL_13_T1RD33.116-33-12_subsidy-DEFAULT_regulatory-DEFAULT_cid50_CFC.xml.zip

Codename: dubai
Version: T1RD33.116-33-12
Variant: RETAIL

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in https://github.com/MotorolaMobilityLLC/kernel-msm/issues/516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

Notif: @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=T1RD33.116-33-12

**NOTE**: If newer tags have been released for this device by the time this request is met, please push those as well.

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1RD33.116-33-12
