### ISSUE TITLE
[REQUEST] Latest troika source code

### ISSUE THREAD

**Issue by npjohnson** [MotorolaMobilityLLC/kernel-msm#556]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 30 Pro version TROIKA_RETAIL_11_RSBS31.Q1-48-36-26_subsidy-DEFAULT_regulatory-DEFAULT_CFC.xml.zip

Codename: troika
Version: RSBS31.Q1-48-36-26
Variant: RETAIL

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in https://github.com/MotorolaMobilityLLC/kernel-msm/issues/516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

Notif: @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=RSBS31.Q1-48-36-26

**Comment by npjohnson** [comment]
Ping on this: @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

**Comment by npjohnson** [comment]
whoops, wrong kernel repo

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-slsi/releases/tag/MMI-RSBS31.Q1-48-36-26
