### ISSUE TITLE
GPL | Source request for Motorola Edge 40 XT2303-2

### ISSUE THREAD

**Issue by Ankk98** [MotorolaMobilityLLC/kernel-msm#558]
Please share the source of moto edge 40 sold in india.

Build number: T2TL33.3-62-3
model: motorola edge 40
model number sku: XT2303-2

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T2TL33.3-62-3
