### ISSUE TITLE
defconfig for Moto x style

### ISSUE THREAD

**Issue by feiyun2002gl** [MotorolaMobilityLLC/kernel-msm#56]
My kernel:3.10.84-gf6a6187
System version:24.11.18
Build number:MPH24.49-18
Android 6.0
I want to know my kernel deconfig,  please, thanks!

**Comment by tags07** [comment]
Update:
kernel/arch/arm64/configs/msm8994-perf_defconfig

Sorry my bad.. i was looking up MPE24.49-18 and had the wrong defconfig. The correct config for MPH24.49-18 is kernel/arch/arm64/configs/msm8994-perf_defconfig

**Comment by luca020400** [comment]
@tags07 kernel/arch/arm64/configs/msm8994_defconfig
msm8992 uses msm8994 defconfig

**Comment by tags07** [comment]
@luca020400 Thanks for the pointer.. i was looking at the wrong tag.
