### ISSUE TITLE
moto g73 

### ISSUE THREAD

**Issue by jignesh2023** [MotorolaMobilityLLC/kernel-msm#560]
Hello, could you please release the Sources, Kernel, Device Tree, etc.

**Comment by asbraga-motorola** [comment]
Can you inform the exact released version (Build ID) you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2, T2TZ33.28-16-19.
