### ISSUE TITLE
[Request] Which defconfig files needed to build kernel for moto g53 5G (XT2335-1; retbr; holi; penang)?

### ISSUE THREAD

**Issue by D4yvid** [MotorolaMobilityLLC/kernel-msm#561]
How i can build a kernel for the moto g53 5G? I found it's [kernel source tag](https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-T1TP33.1-47-2), but there is little to no information on which defconfigs i should use, nor how to build it correctly.

I tried building this kernel source tag, using this build tools:
LLVM toolchain: https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b
GCC/Binutils for aarch64: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
GCC/Binutils for arm32: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9

<details>
  <summary>Output<pre>d4y@moon:~/kernel-msm$ ./scripts/kconfig/merge_config.sh -m arch/arm64/configs/vendor/genericarmv8-64_defconfig arch/arm64/configs/vendor/holi_debug.config arch/arm64/configs/vendor/ext_config/debug-holi.config arch/arm64/configs/vendor/ext_config/debug-holi-penang.config</pre></summary>
  <pre>
Using arch/arm64/configs/vendor/genericarmv8-64_defconfig as base
Merging arch/arm64/configs/vendor/holi_debug.config
Value of CONFIG_DEBUG_PREEMPT is redefined by fragment arch/arm64/configs/vendor/holi_debug.config:
Previous value: # CONFIG_DEBUG_PREEMPT is not set
New value: CONFIG_DEBUG_PREEMPT=y

Merging arch/arm64/configs/vendor/ext_config/debug-holi.config
Value of CONFIG_EDAC_KRYO_ARM64_PANIC_ON_CE is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: CONFIG_EDAC_KRYO_ARM64_PANIC_ON_CE=y
New value: # CONFIG_EDAC_KRYO_ARM64_PANIC_ON_CE is not set

Value of CONFIG_SLUB_DEBUG_PANIC_ON is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: CONFIG_SLUB_DEBUG_PANIC_ON=y
New value: # CONFIG_SLUB_DEBUG_PANIC_ON is not set

Value of CONFIG_DEBUG_PAGEALLOC is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: CONFIG_DEBUG_PAGEALLOC=y
New value: # CONFIG_DEBUG_PAGEALLOC is not set # CONFIG_DEBUG_PAGEALLOC is not set

Value of CONFIG_DEBUG_PAGEALLOC_ENABLE_DEFAULT is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: CONFIG_DEBUG_PAGEALLOC_ENABLE_DEFAULT=y
New value: # CONFIG_DEBUG_PAGEALLOC_ENABLE_DEFAULT is not set # CONFIG_DEBUG_PAGEALLOC_ENABLE_DEFAULT is not set

Value of CONFIG_DEBUG_PANIC_ON_OOM is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: CONFIG_DEBUG_PANIC_ON_OOM=y
New value: # CONFIG_DEBUG_PANIC_ON_OOM is not set

Value of CONFIG_DEBUG_PREEMPT is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: CONFIG_DEBUG_PREEMPT=y
New value: # CONFIG_DEBUG_PREEMPT is not set

Value of CONFIG_TOUCHSCREEN_FTS is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: CONFIG_TOUCHSCREEN_FTS=y
New value: # CONFIG_TOUCHSCREEN_FTS is not set

Value of CONFIG_CORESIGHT_CTI_SAVE_DISABLE is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: # CONFIG_CORESIGHT_CTI_SAVE_DISABLE is not set
New value: CONFIG_CORESIGHT_CTI_SAVE_DISABLE=y

Value of CONFIG_DEBUG_SPINLOCK is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: CONFIG_DEBUG_SPINLOCK=y CONFIG_DEBUG_SPINLOCK=y
New value: CONFIG_DEBUG_SPINLOCK=y

Value of CONFIG_PREEMPT_TRACER is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: CONFIG_PREEMPT_TRACER=y
New value: # CONFIG_PREEMPT_TRACER is not set

Value of CONFIG_LOCK_STAT is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi.config:
Previous value: CONFIG_LOCK_STAT=y
New value: # CONFIG_LOCK_STAT is not set

Merging arch/arm64/configs/vendor/ext_config/debug-holi-penang.config
Value of CONFIG_CMA_ALLOW_WRITE_DEBUGFS is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi-penang.config:
Previous value: CONFIG_CMA_ALLOW_WRITE_DEBUGFS=y
New value: # CONFIG_CMA_ALLOW_WRITE_DEBUGFS is not set

Value of CONFIG_CMA_DEBUG is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi-penang.config:
Previous value: CONFIG_CMA_DEBUG=y
New value: # CONFIG_CMA_DEBUG is not set

Value of CONFIG_PREEMPTIRQ_EVENTS is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi-penang.config:
Previous value: CONFIG_PREEMPTIRQ_EVENTS=y
New value: # CONFIG_PREEMPTIRQ_EVENTS is not set

Value of CONFIG_RCU_TORTURE_TEST is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi-penang.config:
Previous value: CONFIG_RCU_TORTURE_TEST=m
New value: # CONFIG_RCU_TORTURE_TEST is not set

Value of CONFIG_TEST_USER_COPY is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi-penang.config:
Previous value: CONFIG_TEST_USER_COPY=m # CONFIG_TEST_USER_COPY is not set
New value: # CONFIG_TEST_USER_COPY is not set

Value of CONFIG_SLUB_DEBUG_ON is redefined by fragment arch/arm64/configs/vendor/ext_config/debug-holi-penang.config:
Previous value: CONFIG_SLUB_DEBUG_ON=y
New value: # CONFIG_SLUB_DEBUG_ON is not set

#
# merged configuration written to .config (needs make)
#
  </pre>
</details>
<pre>day@moon:~/kernel-msm$ mv .config arch/arm64/configs/penang_defconfig</pre>
<details>
  <summary>Output <pre>day@moon:~/kernel-msm$ make O=out ARCH=arm64 penang_defconfig</pre></summary>
  <pre>
make[1]: Entering directory '/home/day/kernel-msm/out'
  GEN     Makefile
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTLD  scripts/kconfig/conf
arch/arm64/configs/penang_defconfig:306:warning: override: reassigning to symbol LKDTM
arch/arm64/configs/penang_defconfig:345:warning: override: reassigning to symbol DETECT_HUNG_TASK
arch/arm64/configs/penang_defconfig:346:warning: override: reassigning to symbol RUNTIME_TESTING_MENU
arch/arm64/configs/penang_defconfig:348:warning: override: reassigning to symbol LKDTM
arch/arm64/configs/penang_defconfig:357:warning: override: reassigning to symbol ATOMIC64_SELFTEST
arch/arm64/configs/penang_defconfig:386:warning: override: reassigning to symbol MSM_REMOTEQDSS
arch/arm64/configs/penang_defconfig:387:warning: override: reassigning to symbol LKDTM
arch/arm64/configs/penang_defconfig:399:warning: override: reassigning to symbol PAGE_EXTENSION_PAGE_FREE
arch/arm64/configs/penang_defconfig:455:warning: override: reassigning to symbol CORESIGHT
arch/arm64/configs/penang_defconfig:468:warning: override: reassigning to symbol DEBUG_PAGEALLOC
arch/arm64/configs/penang_defconfig:469:warning: override: reassigning to symbol DEBUG_PAGEALLOC_ENABLE_DEFAULT
#
# configuration written to .config
#
make[1]: Leaving directory '/home/day/kernel-msm/out'
  </pre>
</details>
<details>
  <summary>Output (build error)<pre>day@moon:~/kernel-msm$ make -j$(nproc --all) O=out \
                               ARCH=arm64 \
                               CC=clang \
                               CLANG_TRIPLE=aarch64-linux-gnu- \
                               CROSS_COMPILE=aarch64-linux-android- \
                               CROSS_COMPILE_ARM32=arm-linux-androideabi-
</pre></summary>
<pre>
  [............ there was a lot of output ...............]
  CC      drivers/hwtracing/coresight/coresight-byte-cntr.o
  CC      drivers/hwtracing/coresight/coresight-funnel.o
  CC      drivers/hwtracing/coresight/coresight-replicator.o
  AR      drivers/iommu/built-in.a
  CC      drivers/hwtracing/coresight/coresight-etm4x.o
  CC      drivers/hwtracing/coresight/coresight-etm4x-sysfs.o
  CC      drivers/irqchip/irqchip.o
  AR      drivers/macintosh/built-in.a
  CC      drivers/mailbox/mailbox.o
  CC      drivers/md/dm-builtin.o
  CC      drivers/irqchip/irq-gic.o
  CC      drivers/irqchip/irq-gic-common.o
../drivers/hwtracing/coresight/coresight-byte-cntr.c:642:37: error: too few arguments to function call, expected 3, have 2
                usb_qdss_alloc_req(ch, USB_BUF_NUM);
                ~~~~~~~~~~~~~~~~~~                ^
../include/linux/usb/usb_qdss.h:71:19: note: 'usb_qdss_alloc_req' declared here
static inline int usb_qdss_alloc_req(struct usb_qdss_ch *c, int n_wr, int n_rd)
                  ^
1 error generated.
make[3]: *** [../scripts/Makefile.build:288: drivers/hwtracing/coresight/coresight-byte-cntr.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC      drivers/irqchip/irq-gic-v3.o
  CC      drivers/irqchip/irq-gic-v3-mbi.o
  AR      drivers/mailbox/built-in.a
  CC [M]  drivers/md/md.o
  CC [M]  drivers/md/md-bitmap.o
make[2]: *** [../scripts/Makefile.build:558: drivers/hwtracing/coresight] Error 2
make[2]: *** Waiting for unfinished jobs....
  CC [M]  drivers/md/dm.o
  CC      drivers/irqchip/irq-gic-v3-its.o
  CC      drivers/irqchip/irq-gic-v3-its-platform-msi.o
  CC [M]  drivers/md/dm-table.o
  CC      drivers/irqchip/irq-gic-v4.o
  CC      drivers/irqchip/irq-partition-percpu.o
  CC      drivers/irqchip/qcom-mpm.o
  CC      drivers/irqchip/qcom-mpm-holi.o
  CC      drivers/irqchip/qcom-mpm-sdxnightjar.o
  CC      drivers/irqchip/qcom-mpm-monaco.o
  CC [M]  drivers/md/dm-target.o
  CC [M]  drivers/md/dm-linear.o
  CC      drivers/irqchip/qcom-mpm-qcs405.o
  CC [M]  drivers/md/dm-stripe.o
  CC      drivers/irqchip/qcom-mpm-blair.o
  CC [M]  drivers/md/dm-ioctl.o
  CC [M]  drivers/md/dm-io.o
  CC [M]  drivers/md/dm-kcopyd.o
  AR      drivers/irqchip/built-in.a
  CC [M]  drivers/md/dm-sysfs.o
  CC [M]  drivers/md/dm-stats.o
  CC [M]  drivers/md/dm-rq.o
  CC [M]  drivers/md/dm-raid1.o
  CC [M]  drivers/md/dm-log.o
  CC [M]  drivers/md/dm-region-hash.o
  CC [M]  drivers/md/dm-zero.o
  AR      drivers/md/built-in.a
  LD [M]  drivers/md/dm-mod.o
  LD [M]  drivers/md/dm-mirror.o
  LD [M]  drivers/md/md-mod.o
make[1]: *** [/home/day/kernel-msm/Makefile:1845: drivers] Error 2
make[1]: Leaving directory '/home/day/kernel-msm/out'
make: *** [Makefile:183: sub-make] Error 2
</pre>
</details>

I really don't know which files i should use to build this, i did a lot of research on that but i wasn't able to solve this by myself.

**Comment by chankruze** [comment]
@D4yvid Can you share the AIDA64 report for XT2335-1 ?

**Comment by D4yvid** [comment]
> @D4yvid Can you share the AIDA64 report for XT2335-1 ?

Yeah! Here it is: https://pastebin.com/BnDiBS4U

**Comment by chankruze** [comment]
Which andorid version you are building ? I think your config is correct.

Found that thing in `usb_bypass_notifier` function [here](https://android.googlesource.com/kernel/msm.git/+/a7b4e9f4453bc9f6ec8b6ae702d963d3f35800ca/drivers/hwtracing/coresight/coresight-byte-cntr.c) it no longer exit in android 13 ([here](https://android.googlesource.com/kernel/msm.git/+/refs/tags/android-13.0.0_r0.130/drivers/hwtracing/coresight/coresight-byte-cntr.c)).

**Comment by D4yvid** [comment]
> Which andorid version you are building ? I think your config is correct.
> 
> Found that thing in `usb_bypass_notifier` function [here](https://android.googlesource.com/kernel/msm.git/+/a7b4e9f4453bc9f6ec8b6ae702d963d3f35800ca/drivers/hwtracing/coresight/coresight-byte-cntr.c) it no longer exit in android 13 ([here](https://android.googlesource.com/kernel/msm.git/+/refs/tags/android-13.0.0_r0.130/drivers/hwtracing/coresight/coresight-byte-cntr.c)).

I'm trying to build only the kernel, but the kernel is being built for Android 13

**Comment by D4yvid** [comment]
Also, my phone is rooted, so i got the kernel config file from /proc/config.gz (the builders forgot to disable it lol), i'll try to build this again when i get home using this config file from /proc

Thank you for helping me c:

**Comment by D4yvid** [comment]
@chankruze The kernel compiled successfully using the `/proc/config.gz` extracted directly from the device, thank you for helping me! I'll create a fork with this device config in my github in case someone need this to build.
