### ISSUE TITLE
[REQUEST] Moto g73 / DEVONF Sources, Kernel, Device Tree, etc. (T1TNS33.14-90-9-2)

### ISSUE THREAD

**Issue by santoshjogdand** [MotorolaMobilityLLC/kernel-msm#562]
Please release Sources, Kernel, Device Tree, etc.

**Comment by asbraga-motorola** [comment]
Can you inform the exact released version (Build ID) you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2, T2TZ33.28-16-19.

**Comment by santoshjogdand** [comment]
T1TNS33.14-90-9-2

**Comment by santoshjogdand** [comment]
N

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-T1TNS33.14-90-9-2
