### ISSUE TITLE
GPL - Source Request for Motorola g84 XT2347-2 (bangkk) - T3TC33.18-48-6

### ISSUE THREAD

**Issue by chankruze** [MotorolaMobilityLLC/kernel-msm#565]
Please release the kernel/device/vendor trees and all the necessary audio/video/display packages for Motorola Moto g84 version `T3TC33.18-48-6`

| Key             | Value                                                |
| :-------------- | :--------------------------------------------------- |
| Model           | XT2347-2                                             |
| Board           | bangkk                                               |
| Device          | bangkk                                               |
| Platform        | holi                                                 |
| Codename        | REL                                                  |
| Build ID        | T3TC33.18-48-6                                       |
| Variant         | retin                                                |
| Android Version | 13 (Tiramisu)                                        |
| API Level       | 33                                                   |
| Bootloader      | MBM-3.0-uefi-e8ce7c27e72-230928-T3TC33.18-48-6-5dba7 |

Can I use [MMI-T3TC33.18-12-3](https://github.com/MotorolaMobilityLLC/kernel-msm/tree/MMI-T3TC33.18-12-3) asking because the phone was shipped with `T3TC33.18-27-34`

Note: Please include all the dependent packages for example https://github.com/MotorolaMobilityLLC/kernel-msm/issues/516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T3TC33.18-48-6

**Comment by irtygo** [comment]
sorry, its old, can you reopen so i can get a not stale kernel

**Comment by asbraga-motorola** [comment]
you can just open a new issue requesting the Build ID you want.
