### ISSUE TITLE
Enable notification LED on Moto X Play

### ISSUE THREAD

**Issue by amandal1810** [MotorolaMobilityLLC/kernel-msm#57]
Kindly enable the notification LED which already exists on the Moto X Play (lux) but has been kept disabled.

**Comment by luk1337** [comment]
I don't think this is the right place. Also they keep it disabled for reason I guess.

**Comment by piratenpanda** [comment]
Didn't notice any problems by using it so far

**Comment by piratenpanda** [comment]
Is the any reason why the new sensor hub firmware disables the led?

**Comment by awheeler-mmi** [comment]
Hey all,

On Lynx/lux we replaced general LED notification support with Active Display. The sensorhub firmware that disabled LED support enabled our glance (face/attention detection) sensor.  After that update the LED is just used to indicate that the battery is extremely low, etc.  We can't roll out a new firmware that re-enables LED, but if reverting the firmware works then great.
