### ISSUE TITLE
[GPL Request] Kernel source for moto G32 devon_g T2SN33.73-22-3

### ISSUE THREAD

**Issue by mikeNG** [MotorolaMobilityLLC/kernel-msm#571]
Please release the kernel sources along with the usual device-trees, techpacks, modules, etc.
Thanks in advance

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T2SN33.73-22-3
