### ISSUE TITLE
[GPL Request] Kernel source for moto G42 hawao_g T2SE33.73-23-2

### ISSUE THREAD

**Issue by mikeNG** [MotorolaMobilityLLC/kernel-msm#572]
Please release the kernel sources along with the usual device-trees, techpacks, modules, etc.
Thanks in advance

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T2SE33.73-23-2

**Comment by mikeNG** [comment]
Hello @asbraga-motorola it looks like the new tag has not been published for the following repositories:
https://github.com/MotorolaMobilityLLC/kernel-camera-devicetree
https://github.com/MotorolaMobilityLLC/kernel-msm-techpack-camera

**Comment by asbraga-motorola** [comment]
Code for the remaining repositories:
https://github.com/MotorolaMobilityLLC/kernel-camera-devicetree/releases/tag/MMI-T2SE33.73-23-2
https://github.com/MotorolaMobilityLLC/kernel-msm-techpack-camera/releases/tag/MMI-T2SE33.73-23-2
