### ISSUE TITLE
[GPL Request] Kernel source for moto G52 rhode_g T2SR33.72-22-4

### ISSUE THREAD

**Issue by mikeNG** [MotorolaMobilityLLC/kernel-msm#573]
Please release the kernel sources along with the usual device-trees, techpacks, modules, etc.
Thanks in advance

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T2SRS33.72-22-4-1
