### ISSUE TITLE
GPL REQUEST | Source request for Motorola G62 5G India model | [T1SSIS33.1-75-7-1]

### ISSUE THREAD

**Issue by adarshkannada** [MotorolaMobilityLLC/kernel-msm#575]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola G62 5g INDIA model

Model number(SKU): XT2223-3

**Comment by asbraga-motorola** [comment]
Can you inform the exact released version (Build ID) you want?
You find it in the System Config in the phone. It is a group of letters and numbers that look like these: RRA31.Q3-19-19, S1RD32.55-33, S0RCS32.41-10-9-2, T2TZ33.28-16-19.

**Comment by adarshkannada** [comment]
Please find the build Number
T1SSIS33.1-75-7-1

**Comment by Llary02** [comment]
Yes , Please release that code i also want to look at it. **T1SSIS33.1-75-7-1**

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SSIS33.1-75-7-1

**Comment by firdosifahad** [comment]
can someone please list for XT2223-3 ( T1SSIS33.1-75-7-15 )

**Comment by asbraga-motorola** [comment]
@firdosifahad , please open a new request issue to get the code you want.
