### ISSUE TITLE
[GPL Request] Kernel source for motorola edge 30 fusion(tundra_g) T1SJS33.117-30-3-5

### ISSUE THREAD

**Issue by schqiushui** [MotorolaMobilityLLC/kernel-msm#577]
Please release the kernel sources along with the usual device-trees, techpacks, modules, etc.
Thanks in advance.
@asbraga-motorola @chenyt9

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SJS33.117-30-3-5

**Comment by schqiushui** [comment]
> Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SJS33.117-30-3-5

Thanks a lot.

**Comment by schqiushui** [comment]
> Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SJS33.117-30-3-5

Hi, I found out that missing some below, please help release these sources.
Thanks!

https://github.com/MotorolaMobilityLLC/vendor-cirrus-audio-dlkm
https://github.com/MotorolaMobilityLLC/kernel-devicetree
https://github.com/MotorolaMobilityLLC/kernel-msm-techpack-dataipa
https://github.com/MotorolaMobilityLLC/kernel-msm-5.4-techpack-camera
https://github.com/MotorolaMobilityLLC/kernel-msm-5.4-techpack-video

**Comment by asbraga-motorola** [comment]
Fixed. Now those repos have the tag for this release.

**Comment by schqiushui** [comment]
Thanks a lot.
