### ISSUE TITLE
GPL | Source request for Motorola Moto X40 (rtwo) - U1TR34.8-19-2

### ISSUE THREAD

**Issue by mxzqw** [MotorolaMobilityLLC/kernel-msm#579]
Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Moto X40 version `U1TR34.8-19-2` (early Android 14 build)

Model number: `XT2301-5`
Codename: `rtwo` / `rtwo_cn`
Version: `U1TR34.8-19-2` (Android 14)
Variant: `RETCN`

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in #516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

I am from the LineageOS project for rtwo [that you can see on XDA](https://xdaforums.com/t/rom-unofficial-lineageos-20-android-13-for-the-motorola-edge-40-pro-x40-edge-2023-rtwo.4613129/), fulfilling this request can help us get forwards on certain things and it would be appreciated if it can be expedited.

Given that currently only RETCN (Chinese rtwo variant) has seen the light of any Android 14 build, beta or not, we already can learn a lot from a GPL release when it comes to Motorola engineering changes that are required to get initial A14 readiness for our project.

Notif: @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=U1TR34.8-19-2

**Comment by chenyt9** [comment]
@mxzqw  pls use this version first:
Version here:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1TR34.8-19-11

**Comment by chenyt9** [comment]
Hi, @mxzqw ，
There is no U1TR34.8-19-2 shipped version in our database, please confirm the version.Thanks.

**Comment by 13riki** [comment]
Nececito canselar esta subscriccion
