### ISSUE TITLE
GPL | Source request for Motorola moto g(8) - RPJS31.Q4U-47-35-17

### ISSUE THREAD

**Issue by marceloalencar** [MotorolaMobilityLLC/kernel-msm#580]
Model: XT2045-1
TAG: RPJS31.Q4U-47-35-17

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPJS31.Q4U-47-35-17
