### ISSUE TITLE
"X" button in moto launcher is not accessible with keyboard.

### ISSUE THREAD

**Issue by msftedad** [MotorolaMobilityLLC/kernel-msm#582]
**Test Environment:**
Device: ThinkPhone by motorola
Android Version: 14
EW3 Build number: 2023.1020.6-oem

**Pre-requisites:**
Connect mobile device to the external display via wired connection.
Use only keyboard for navigation

**Repro steps:**

1. Connect an external display to your Thinkphone-Moto device using a wired connection.
2. Open Moto connect app observe the list of available apps on the external display
3. Try to navigate using tab or arrow keys on Moto ready for page
4. Observe "X" button is not keyboard focusable

**Actual behavior:**
"X" button in moto launcher, is not accessible with keyboard

**Expected behavior:**
All the interactive elements should be accessible with keyboard

**Attachments:**

https://github.com/MotorolaMobilityLLC/kernel-msm/assets/93735775/521ba35a-0dbd-4ae9-97d4-83f0245a39c6

**Comment by asbraga-motorola** [comment]
Hi @msftedad,
This forum is primarily for requesting open source code publication.
You may request suport directly in http://motorola.com/ or try the Moto Community Forum:
https://forums.lenovo.com/t5/Motorola-Community/ct-p/MotorolaCommunity
