### ISSUE TITLE
[GPL] [REQUEST] kernel source code for motorola moto G(52) (rhode) - [T2SRS33.72-22-4-1]

### ISSUE THREAD

**Issue by ZeakiOFC** [MotorolaMobilityLLC/kernel-msm#583]
Greetings, Moto team!
Thank you for your attention. Could you please provide the kernel source code for the November Security Update, along with any associated README documentation, if available?

I appreciate your collaboration in advance.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T2SRS33.72-22-4-1
