### ISSUE TITLE
GPL | Source request for Motorola Edge 20 (berlin) T1RGS33.135-109-9-7 (XT2143-1)

### ISSUE THREAD

**Issue by Shubhamkr4** [MotorolaMobilityLLC/kernel-msm#584]
Kindly requesting the kernel sources and device tree for the following device's latest update mentioned in the title

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1RGS33.135-109-9-7
