### ISSUE TITLE
[GPL Request] Updated Kernel Source for Moto G51 5G

### ISSUE THREAD

**Issue by gooosedev** [MotorolaMobilityLLC/kernel-msm#585]
Hello,

Can you please release the latest sources for the Kernel (and usual techpacks, modules, device trees, etc)
for the Motorola Moto G51 5G (cypfq).

the build number should  be the following S2RYAS32.58-13-12-5-1-4.

Thanks in advance.

**Comment by asbraga-motorola** [comment]
Code published: Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RYAS32.58-13-12-5-1-4
