### ISSUE TITLE
Kernel Source for Motorola FOGOS U1UG34.23-23-3

### ISSUE THREAD

**Issue by techyminati** [MotorolaMobilityLLC/kernel-msm#587]
### Build ID

U1UG34.23-23-3
motorola/fogos_cn/fogos:11/U1UG34.23-23-3/8dc27:user/release-keys

**Comment by chenyt9** [comment]
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1UG34.23-23-3

**Comment by techyminati** [comment]
Thanks
