### ISSUE TITLE
Kernel Source for Moto g53y 5G - T1TPJS33.75-105-1-3 

### ISSUE THREAD

**Issue by nattolecats** [MotorolaMobilityLLC/kernel-msm#588]
### Build ID

T1TPJS33.75-105-1-3 

* Moto g53y 5G - Y!mobile carrier variant

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TPJS33.75-105-1-3

**Comment by nattolecats** [comment]
Thank you very much
