### ISSUE TITLE
Correct Toolchain for Denver

### ISSUE THREAD

**Issue by pauldmurphy** [MotorolaMobilityLLC/kernel-msm#589]
### Build ID

S2RE32.29-16-1-5-19 

### Additional

I'm having a nightmare of a time identifying the correct toolchain to build this kernel. Can you please advise?

I'm using this as my source...

git clone --depth=1 https://github.com/MotorolaMobilityLLC/kernel-msm.git -b android-12-release-s2res32.29-16-1-15-1-2 ~/android/kernel-msm

Thank You!

--pm

**Comment by pauldmurphy** [comment]
i found it here 

https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/e532342f30eadb954c96d19ca6a0edf89a5c65bc/clang-r383902b1/

can confirm stock device config builds

**Comment by metl-play** [comment]
How did you find the correct toolchain? I want to compile the kernel for my Doha device, unfortunately I am completely new to it.

**Comment by pauldmurphy** [comment]
Here's how I found it.

This will work on almost all android devices. You will need root in order
to be able to perform these operations.

cp /proc/config.gz ~

gunzip ~/config.gz
or
gzip -d ~/config.gz

Rename that file to something more manageable. My version of that file had
a super long name. I renamed it to device_config

mv ~/[super long filename] ~/device_config

Open the file with your preferred editor. I'm keen on nano.

nano ~/device_config

The first couple of lines should point you into the right place for the
toolchain. The file itself is the .config file used to build the running
kernel.

The relevant lines in my file looked like this...

CONFIG_CC_VERSION_TEXT="Android (6877366 based on r383902b1) clang version 11.0.2 (https://android.googlesource.com/toolchain/llvm-project b397f81060ce6d701042b782172ed13bee898b79)"
CONFIG_GCC_VERSION=0
CONFIG_CC_IS_CLANG=y
CONFIG_LD_IS_LLD=y
CONFIG_CLANG_VERSION=110002
CONFIG_CC_CAN_LINK=y
CONFIG_CC_HAS_ASM_GOTO=y
CONFIG_IRQ_WORK=y
CONFIG_BUILDTIME_EXTABLE_SORT=y
CONFIG_THREAD_INFO_IN_TASK=y


HTH,
--pm

**Comment by metl-play** [comment]
So I need to reinstall the stock firmware and then root it, to get this information?

**Comment by juic3b0x** [comment]
> So I need to reinstall the stock firmware and then root it, to get this information?

or if you got boot.img just run:
`strings boot.img | grep "Linux version"`

And it'll show you the clang version also...

It's also in the kernel sources defconfig for your device .. at least should be ..

*quietly goes back to lurking*
