### ISSUE TITLE
MMI-MPI24.65-24 tag

### ISSUE THREAD

**Issue by Alberto97** [MotorolaMobilityLLC/kernel-msm#59]
@charleseb I see you've pushed MMI-MPI24.65-24 tag to vendor-qcom-opensource-wlan-prima, motorola-external-f2fs-tools and motorola-kernel. Could you push it here too?

**Comment by charleseb** [comment]
Hi Alberto,

I'm working to push it in a few hours.

Thanks,
Charles
Em 13 de jan de 2016 2:45 PM, "Alberto Pedron" notifications@github.com
escreveu:

**Comment by neobuddy89** [comment]
Must applaud moto's quick response. 
Kudos.

**Comment by Alberto97** [comment]
Thank you very much!
