### ISSUE TITLE
Kernel Source for U1SQ34.52-21-1 (eqs)

### ISSUE THREAD

**Issue by SGCMarkus** [MotorolaMobilityLLC/kernel-msm#590]
### Build ID

U1SQ34.52-21-1

### Additional

This will be used for LineageOS and other custom ROMs.

Please don't forget about the various kernel devicetrees and module repositories.

Thanks in advance.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1SQ34.52-21-1
