### ISSUE TITLE
Kernel Source for U1TR34.8-30-8 (rtwo, retus)

### ISSUE THREAD

**Issue by SGCMarkus** [MotorolaMobilityLLC/kernel-msm#591]
### Build ID

U1TR34.8-30-8

### Additional

This will be used for LineageOS and other custom ROMs.

Please don't forget about the various kernel devicetrees and module repositories.

Thanks in advance.

**Comment by ThEMarD** [comment]
I'd also like this kernel source code please

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1TR34.8-30-8R2
