### ISSUE TITLE
GPL | Source request for Motorola ThinkPhone XT2309-3 - T3TBS33.2-47-2-4

### ISSUE THREAD

**Issue by quantum77** [MotorolaMobilityLLC/kernel-msm#593]
### Build ID

T3TBS33.2-47-2-4

### Additional

Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola ThinkPhone

Model number: XT2309-3
Codename: bronco

cc @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

TAG=T3TBS33.2-47-2-4

**Comment by quantum77** [comment]
Is, anyone here?

**Comment by milesmccaleb** [comment]
Hi, i am also requesting sources for the XT2309-3

@asbraga-motorola

**Comment by mansonss** [comment]
Request number 3, please.

**Comment by chenyt9** [comment]
@all,
Version released:
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T3TBS33.2-47-2-4
