### ISSUE TITLE
Kernel Source for motorola edge 30 neo (miami) - T1SSMS33.1-121-4-8

### ISSUE THREAD

**Issue by Ev3rt** [MotorolaMobilityLLC/kernel-msm#594]
### Build ID

T1SSMS33.1-121-4-8

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SSMS33.1-121-4-8

**Comment by ghost** [comment]
> Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SSMS33.1-121-4-8

Can you upload device and vendor tree?

**Comment by asbraga-motorola** [comment]
Check for the tag MMI-T1SSMS33.1-121-4-8 in these repos:
kernel-msm-5.4-techpack-camera
kernel-msm-techpack-dataipa
kernel-msm-5.4-techpack-display
kernel-msm-5.4-techpack-video
motorola-kernel-modules
vendor-cirrus-audio-dlkm
vendor-qcom-opensource-datarmnet
vendor-qcom-opensource-datarmnet-ext
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn
vendor-qcom-opensource-wlan-qcacld-3.0
kernel-camera-devicetree
kernel-devicetree
kernel-display-devicetree

(edited: fixed tag)

**Comment by ghost** [comment]
I founded the tag MMI-T1SSMS33.1-121-4-8 in almost all repository, but in:
vendor-qcom-opensource-wlan-fw-api I found only MMI-T1SSMS33.1-121-4-5 or MMI-T1SSMS33.1-121-4. Wich is the correct one?

**Comment by asbraga-motorola** [comment]
It's there: https://github.com/MotorolaMobilityLLC/vendor-qcom-opensource-wlan-fw-api/releases/tag/MMI-T1SSMS33.1-121-4-8
