### ISSUE TITLE
GPL - Source Request for Motorola Moto g84 XT2347-1 (bangkk) - U1TC34.22-64-6

### ISSUE THREAD

**Issue by Samw662** [MotorolaMobilityLLC/kernel-msm#597]
### Additional

Hey! Please release the kernel/vendor/device trees and all the necessary audio/video/display packages for the moto g(84) 5g (bangkk) version ### U1TC34.22-64-6

Model number: XT2347-1
Codename: bangkk

cc @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

Greetings and thank you.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1TC34.22-64-6

**Comment by Alpmfim** [comment]
Existe kernel já copilado para moto g84 XT2347-1 (Bangkk) U1TC34.22-64-18  Android 14  alguém tem?
