### ISSUE TITLE
Kernel Source for U1TRS34.8-30-13-1

### ISSUE THREAD

**Issue by mxzqw** [MotorolaMobilityLLC/kernel-msm#598]
### Build ID

U1TRS34.8-30-13-1

### Additional

Hello,

Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 40 Pro version `U1TRS34.8-30-13-1`

Model number: `XT2301-4`
Codename: `rtwo`
Version: `U1TRS34.8-30-13-1` (March 2024)
Variant: `RETEU`

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in #516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

I am from the LineageOS project for rtwo [that you can see on XDA](https://xdaforums.com/t/rom-unofficial-lineageos-20-android-13-for-the-motorola-edge-40-pro-x40-edge-2023-rtwo.4613129/), fulfilling this request can help us get forwards on certain things and it would be appreciated if it can be expedited.

Notif: @asbraga-motorola @chenyt9 @awheeler-mmi @mbissaromoto @TinnoOSS

TAG=U1TRS34.8-30-13-1

**Comment by ThEMarD** [comment]
I would also like the kernel source code release to help us in continuing custom ROM support on rtwo

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1TRS34.8-30-13-1
