### ISSUE TITLE
Kernel Source for Motorola S30 Edge (xpeng) (S3RXC32.33-8-25)

### ISSUE THREAD

**Issue by yqxyz** [MotorolaMobilityLLC/kernel-msm#599]
### Build ID

S3RXC32.33-8-25

### Additional

S3RXC32.33-8-25

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3RXC32.33-8-25
