### ISSUE TITLE
When will you release lollipop kernel source?

### ISSUE THREAD

**Issue by dirttech** [MotorolaMobilityLLC/kernel-msm#6]
When will you release lollipop kernel source for moto g?

kernel version 3.4.42-gfdc8055
hudsoncm@ilclbld27

system version
22.11.6.titan_retuaws.retuaws.en.US.retin

build number
LXB22.39-6

**Comment by tags07** [comment]
Sources for Moto G, Moto E and Moto G(2nd Gen) are all posted on branch: lollipop—5.0.2-release and TAG : MMI-LXB22.46-28

Sources for Moto X(2nd Gen) is posted on branch: lollipop-5.0.2-release-victara
TAG: MMI-LXE22.46-25
