### ISSUE TITLE
hab check failed for custom compiled zImage - XT1097

### ISSUE THREAD

**Issue by glauberlima** [MotorolaMobilityLLC/kernel-msm#60]
Hi everyone.

I've an unlocked Moto X (2014) XT1097.

Despite being able to boot via "fastboot boot myCompiledKernel.img" I get this error message when I flash the boot image (fastboot flash boot myCompiledKernel.img):

_hab check failed for boot_

and the phone won't boot - it falls back to bootloader.

I've been using abootimg to put my compiled zImage inside the original untouched Moto boot.img.

I'm wondering what step I've been doing wrong....

Any help is appreciated.

**Comment by TalAloni** [comment]
A successful flash of a self compiled (read: invalid signature) kernel will always print "hab check failed for boot". (Tested with my XT1032).
Sounds like you flashed successfully and have an issue with your kernel.

**Comment by awheeler-mmi** [comment]
This one is pretty old, so I'll close it.
