### ISSUE TITLE
Kernel Source for Motorola Edge 50 Pro - U2UM34M.27-38-5

### ISSUE THREAD

**Issue by karthik1896** [MotorolaMobilityLLC/kernel-msm#600]
### Build ID

Build ID : U2UM34M.27-38-5
Hey! Please release the kernel/vendor/device trees and all the necessary audio/video/display packages for the Motorola Edge 50 Pro.

### Additional

Notif: @asbraga-motorola @chenyt9 @awheeler-mmi @mbissaromoto @TinnoOSS

**Comment by DhineshCool** [comment]
We need kernel source release for working on custom rom ,so please release all necessary packages for building

**Comment by bhargavpydimalla** [comment]
please release full kernel sources for working on custom rom ,so please release all necessary packages for building

@asbraga-motorola @chenyt9 @awheeler-mmi @mbissaromoto @TinnoOSS

**Comment by ak-ag** [comment]
Hey moto please release the kernel and trees for custom rom development

**Comment by FPSensor** [comment]
Please release the edge 50 pro kernel so we can study it, remember that it is protected by a GPL v2 license

**Comment by ccfries** [comment]
Me too!

**Comment by chenyt9** [comment]
Hi，@all，
Version here：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U2UM34.27-38-5
