### ISSUE TITLE
Kernel Source for U1TD34.94-12-7 (Moto G54 5G)

### ISSUE THREAD

**Issue by Velosh** [MotorolaMobilityLLC/kernel-msm#601]
### Build ID

U1TD34.94-12-7

### Additional

And please, together with: Kernel, Device & Vendor with Display, DTS, Video and Audio stuff. If necessary, add the rest in case I forgot, while processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in MotorolaMobilityLLC/kernel-msm#516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release).

Device: `Moto G54 5G`
Codename: `cancunf`
Region: `retbr`

**Comment by asbraga-motorola** [comment]
Code for U1TD34.94-12-7 is already published: https://github.com/MotorolaMobilityLLC/kernel-mtk/issues/113
