### ISSUE TITLE
Kernel Source for T3TFS33.66-37-3 (moto g play - 2024 / fogona / XT2413-2)

### ISSUE THREAD

**Issue by mikeNG** [MotorolaMobilityLLC/kernel-msm#602]
### Build ID

T3TFS33.66-37-3

### Additional

Please release the kernel sources along with the usual device-trees, techpacks, modules, etc.
It will be used for development of custom ROMs like LineageOS.

Thanks in advance

**Comment by lingsen92** [comment]
Version here：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T3TFS33.66-37-3
