### ISSUE TITLE
Kernel Source for T1SHS33.35-23-20-12, Android 13.

### ISSUE THREAD

**Issue by Vasant-1234** [MotorolaMobilityLLC/kernel-msm#603]
### Build ID

T1SHS33.35-23-20-12

### Additional

I want to build the kernel for Motorola Edge+ 2022. The currently released hiphi kernel is kernel-msm-MMI-T1SHS33.35-23-20-2.tar.gz which is kernel version 5.10.136 and the kernel version on my phone is 5.10.168-xxxxx. Looks like you have not released the latest kernel code.

**Comment by Vasant-1234** [comment]
Okay, looks like this is running a GKI kernel.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SHS33.35-23-20-12
