### ISSUE TITLE
GPL | Source request for Motorola g200 (xpeng) S1RXS32.50-13-25

### ISSUE THREAD

**Issue by rogers2602** [MotorolaMobilityLLC/kernel-msm#606]
Kindly requesting source for the following repos for this tag "S1RXS32.50-13-25"

kernel-msm
kernel-devicetree
kernel-audio-devicetree
kernel-camera-devicetree
kernel-cvp-devicetree
kernel-display-devicetree
kernel-mmrm-devicetree
kernel-video-devicetree
kernel-msm-5.4.233-techpack-camera
kernel-msm-5.4.233-techpack-cvp
kernel-msm-5.4.233-techpack-display
kernel-msm-5.4.233-techpack-eva
kernel-msm-5.4.233-techpack-mmrm
kernel-msm-5.4.233-techpack-sched
kernel-msm-5.4.233-techpack-video
vendor-qcom-opensource-audio-kernel
vendor-qcom-opensource-dataipa
vendor-qcom-opensource-datarmnet
vendor-qcom-opensource-datarmnet-ext
vendor-qcom-opensource-wlan-qcacld-3.0
vendor-qcom-opensource-wlan-fw-api
vendor-qcom-opensource-wlan-qca-wifi-host-cmn
motorola-kernel-modules

and others if applicable.

Thanks in advance!

**Comment by asbraga-motorola** [comment]
code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S1RXS32.50-13-25
