### ISSUE TITLE
GPL - Kernel Source Request for motorola moto g(30) XT2129-1 (caprip) - S0RCS32.41-10-19-14

### ISSUE THREAD

**Issue by Samw662** [MotorolaMobilityLLC/kernel-msm#607]
### Build ID

S0RCS32.41-10-19-14

### Additional

Hello there! 😁
Kindly provide the kernel/vendor/device trees and all the necessary audio/video/display packages for the moto g(30) (caprip) version ### S0RCS32.41-10-19-14

Codename: caprip
Release: S0RCS32.41-10-19-14
Model: XT2129-1

Notif: @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

Greetings. Thank you 🫶🏻

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S0RCS32.41-10-19-14
