### ISSUE TITLE
Kernel Source for Motorola Edge 50 Pro - U2UM34M.27-38-1

### ISSUE THREAD

**Issue by raajeshmani** [MotorolaMobilityLLC/kernel-msm#608]
### U2UM34M.27-38-1
**Build ID** : U2UM34M.27-38-1
Hey! Please release the kernel/vendor/device trees and all the necessary audio/video/display packages for the Motorola Edge 50 Pro.

@asbraga-motorola @chenyt9 @awheeler-mmi @mbissaromoto @TinnoOSS

**Comment by DhineshCool** [comment]
Duplicate issue 
Already opened here
https://github.com/MotorolaMobilityLLC/kernel-msm/issues/600
 pls close this one
