### ISSUE TITLE
How to disable system update on T1SSMS33.1-121-4-8

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#609]
Hello,
Is there any way to disable Android 13 updates?
I've a Moto Edge 30 neo, with the build T1SSMS33.1-121-4-8;
I used a firewall app to block the update packages, but it need to be started each time you boot the phone, and one time I forgot it.. So now it keep asking me to update to Android 14 U1SSM34.31-64-4 and I don't want to upgrade( I know for sure that some important apps that I use for job are NOT compatible and have iusses with Android 14).. The notification is very annoying, it keep to appear over the apps every few seconds. 
Any advice to solve please?

**Comment by asbraga-motorola** [comment]
Hi, @AMT-Cheif 
This forum is primarily for requesting open source code publication or questions related to it.
You may try the Moto Community Forum (https://forums.lenovo.com/t5/Motorola-Community/ct-p/MotorolaCommunity) or the support (www.motorola.com)
