### ISSUE TITLE
[GPL - Kernel Source Request] for motorola moto g(84) 5g XT2347-1 (bangkk) - U1TCS34.22-64-6-1

### ISSUE THREAD

**Issue by Samw662** [MotorolaMobilityLLC/kernel-msm#610]
### Build ID

U1TCS34.22-64-6-1

### Additional

Hello there!
Could you kindly provide the kernel sources along with the usual vendor/device trees and all the necessary audio/video/display packages for the moto g(84) 5g (bangkk) version ### U1TCS34.22-64-6-1

While processing this request, please take care to include all of the things mentioned.

Codename: bangkk
Release: U1TCS34.22-64-6-1
Model Number (SKU): XT2347-1

Greetings, moto-team!
I really appreciate what you do

Notif: @chenyt9 @awheeler-mmi @mbissaromoto @asbraga-motorola @TinnoOSS

**Comment by asbraga-motorola** [comment]
Code released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1TCS34.22-64-6-1
