### ISSUE TITLE
Kernel Source for U1TPS34.29-37-2-3

### ISSUE THREAD

**Issue by john4554** [MotorolaMobilityLLC/kernel-msm#611]
### Build ID

U1TPS34.29-37-2-3

### Additional

Hello there!
Could you kindly provide the kernel sources along with the usual vendor/device trees and all the necessary audio/video/display packages for the moto g53 5G (penang)?

Please include some instructions for building the kernel, including the defconfig I should be using.

While processing this request, please take care to include all of the things mentioned.

Thank you.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1TPS34.29-37-2-3
