### ISSUE TITLE
Kernel Source for T1RDS33.116-33-13-5

### ISSUE THREAD

**Issue by mxzqw** [MotorolaMobilityLLC/kernel-msm#612]
### Build ID

T1RDS33.116.33.13.5

### Additional

Hello,

Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Edge 30 (dubai) version `T1RDS33.116.33.13.5`

Model number: `XT2203-1`
Codename: `dubai`
Version: `T1RDS33.116.33.13.5` (April 2024 security update; latest version as of writing)
Variant: `RETEU`

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in #516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

The source code will be used for open-source purposes, in LineageOS ROM development on this device (see it here: https://xdaforums.com/t/rom-official-lineageos-21-android-14-for-the-motorola-edge-30-dubai.4653563/)

Notif: @asbraga-motorola @chenyt9 @awheeler-mmi @mbissaromoto @TinnoOSS

TAG=T1RDS33.116.33.13.5

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1RDS33.116-33-13-5
