### ISSUE TITLE
Kernel Source for Moto Edge 50 Fusion <U2UUI34.40-24-6>

### ISSUE THREAD

**Issue by Rakhshan7070** [MotorolaMobilityLLC/kernel-msm#613]
### Build ID

U2UUI34.40-24-6

### Additional

Please provide device tree too
This is for kernel tweaking to get most out of it and for custom rom development projects.

**Comment by parasy787898** [comment]
please release full kernel sources for working on custom rom ,so please release all necessary packages for building

**Comment by Darshil-154** [comment]
please release full kernel source for custom rom development for moto edge 50 fusion please

**Comment by Darshil-154** [comment]
please release full kernel source for custom rom development for moto edge 50 fusion please

**Comment by DhineshCool** [comment]
Kindly update with new tag 

Build ID : U2UUI34.40-64-1
Hey! Please release the kernel/vendor/device trees and all the necessary audio/video/display packages for the Motorola Edge 50 fusion

Notif: @asbraga-motorola @chenyt9

**Comment by lingsen92** [comment]
code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U2UUI34.40-24-6

**Comment by lingsen92** [comment]
version released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U2UUI34.40-64-1

**Comment by stylemanik** [comment]
@DhineshCool 
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U2UUI34.40-64-1
