### ISSUE TITLE
Kernel Source for U1SSMS34.31-64-4-4

### ISSUE THREAD

**Issue by Claymore1297** [MotorolaMobilityLLC/kernel-msm#615]
### Build ID

U1SSMS34M.31-64-4-4

### Additional

Hello,
please release the kernel tree, device tree and all the necessary audio/video/display techpack mentioned above or latest A14 MIAMI kernel source. Want to build kernel inline in A14 rom.

thank you & kind regards

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1SSMS34.31-64-4-4

**Comment by marcost2** [comment]
We are missing the rmnet/rmnet-ext techpacks for this tag. Any chace on publishing those?
