### ISSUE TITLE
[HELP] How to merge moto g34 5g (fogos) defconfig?

### ISSUE THREAD

**Issue by UlekBR** [MotorolaMobilityLLC/kernel-msm#616]
### Build ID: android-14-release-u1u g34 .23-28-2

Of all the attempts I made, one was successful:

```
./scripts/kconfig/merge_config.sh -m \
    arch/arm64/configs/vendor/genericarmv8-64_defconfig \
    arch/arm64/configs/vendor/moto-consolidate.config \
    arch/arm64/configs/vendor/ext_config/moto-holi.config \
    arch/arm64/configs/vendor/ext_config/moto-holi-fogos.config
```

but it didn't start, I received bootloop

I tried other combinations, with other files, but in all the other attempts I made, the kernel does not compile, to be more specific, it gives an error most of the time when compiling the drivers.

I hope someone can help me

**Comment by SantoshKumarOjha** [comment]
Are you developing kernel for fogos?

**Comment by SantoshKumarOjha** [comment]
https://github.com/AnandSuresh02
He is actively working on this device's kernel. You can speak with him.
