### ISSUE TITLE
Kernel Source for RPJS31.Q1-53-12-17 (moto g fast)

### ISSUE THREAD

**Issue by AstroSquared** [MotorolaMobilityLLC/kernel-msm#618]
### Build ID

RPJS31.Q1-53-12-17

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-RPJS31.Q1-53-12-17

**Comment by AstroSquared** [comment]
Thank you so much!
