### ISSUE TITLE
Kernel Source for T1SJS33.117-30-3-9

### ISSUE THREAD

**Issue by ThEMarD** [MotorolaMobilityLLC/kernel-msm#619]
### Build ID

MMI-T1SJS33.117-30-3-9

For tundra

### Additional

I will use this kernel source code to keep the kernel we use for Motorola sm7325 / sm8350 common kernel devices on LineageOS which is based upon AOSP

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1SJS33.117-30-3-9
