### ISSUE TITLE
Titan: MPB24.65-34

### ISSUE THREAD

**Issue by luk1337** [MotorolaMobilityLLC/kernel-msm#62]
System Version: 24.41.34.titan_retaildsds.retaildsdsall.en.03
Build Number: MPB24.65-34
Kernel version: Linux version 3.4.42-gef77327 (hudsoncm@ilclbld53) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Wed Jan 6 12:29:54 CST 2016

**Comment by luca020400** [comment]
Bump
This build has been officially released in India

**Comment by luk1337** [comment]
@tags07 @charleseb ;_;

**Comment by tags07** [comment]
@luk1337 : Yes, looks like we got approval to ship this mid Jan 2016. I need to check if we completed the rollout to all regions. We have this in our pipeline. We'll get to it soon.

**Comment by luca020400** [comment]
Only India as of now ....

**Comment by luk1337** [comment]
yeah, XT1068 and XT1079 got it already...

**Comment by luca020400** [comment]
@tags07 as far as I know thea received same build as titan ( MPB24.65-34 )
When MPB24.65-20 has been released ?
Thanks

**Comment by charleseb** [comment]
Hi Luca,

I just released MMI-MPB24.65-20 to github.

Thanks,
Charles

**Comment by luca020400** [comment]
What about -34 ? :p

**Comment by tags07** [comment]
@luca020400 we'll post that soon.. we have a huge backlog and Charles is multi tasking with other priorities. I'll sync up with him and prioritize posting all commits till the latest tags we shipped.

**Comment by luca020400** [comment]
Great thank you both :)

**Comment by archon810** [comment]
@charleseb @tags07 Can you confirm that this update has started rolling out in US now please? We got a report from a user who isn't in the soak test and is using a US model.

Thanks.

**Comment by luca020400** [comment]
@archon810: as far as I know XT1064 ( us ) didn't receive it yet
Only XT1068 ( India )

**Comment by archon810** [comment]
@luca020400 Got 2 reports already in the last few hours of the US version.

**Comment by luca020400** [comment]
Oh nice, we're still waiting in EU ..

**Comment by luca020400** [comment]
@tags07 @charleseb Since this issue has been bumped . Any news on this release ? Thanks

**Comment by tags07** [comment]
@luca020400  I am slacking behind a bit on the list of releases to post. I'll check and add it to the pipeline.

**Comment by charleseb** [comment]
Hi @luca020400,

I'm working to release this version. It will be available in a few days.

Thanks,
Charles

**Comment by luca020400** [comment]
@charleseb thanks :)
@archon810 Looks like EU received some M love too ;) ( XT1072 reteu - moto g 2014 lte ) Where's my retgb ......

**Comment by luca020400** [comment]
@charleseb thanks

**Comment by charleseb** [comment]
Hi  @luca020400,

The version MMI-MPB24.65-34 has been released to Github.

Thanks,
Charles

**Comment by luca020400** [comment]
@charleseb Just for curiosity, did you ever ship -20 ?
I couldn't find a device using it

**Comment by tags07** [comment]
@luca020400 How do you know we didnt ship?

**Comment by luca020400** [comment]
@tags07 I checked every titan and thea 6.0 release :P

**Comment by tags07** [comment]
@luca020400 Do you work for Lenovo/Motorola? If not, I'd like access to that database you are checking..sometimes its a pain internally to see what we shipped ;-)

**Comment by luk1337** [comment]
@tags07
No, he doesn't work for Moto/Lenovo but there's like filefactory folder of guy posting like all factory images for the whole G series xD

**Comment by luca020400** [comment]
@tags07: http://www.filefactory.com/folder/c6cdedc45a775d27/?sort=created&order=DESC&show=100&page=1
Enjoy downloading at 40 kb/s ...
Just to let you know all these firmware are signed with moto key ( flashable on locked bootloader) 
I don't know from where all the images came from but they are really useful for some users
( well there were an osprey firmware even before it was announced too ;) )
