### ISSUE TITLE
Kernel Source for T1TPN33.58-94

### ISSUE THREAD

**Issue by AsmoValroth** [MotorolaMobilityLLC/kernel-msm#620]
### Build ID

T1TPN33.58-94

### Additional

Hello,

Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola moto g 5g (pnangn) version T1TPN33.58-94

Model number: XT2313-6
Codename: pnangn
Version: T1TPN33.58-94 (October 1 2023 security update)
Variant: RETCA

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in #516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

The source code will be used for open-source purposes, in LineageOS ROM development on this device

**Comment by chenyt9** [comment]
Version released：
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TPN33.58-94R1
