### ISSUE TITLE
Looking for the latest MotoG32 (Devon) kernel. [T2SNS33.73-22-3-6]

### ISSUE THREAD

**Issue by Aurtikent** [MotorolaMobilityLLC/kernel-msm#621]
Info:
Build Number: T2SNS33.73-22-3-6

Please release the kernel sources along with   device-trees, kernel modules, etc.

thank you for your help.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T2SNS33.73-22-3-6
