### ISSUE TITLE
Kernel Source for U1TGN34.42-86 genevn

### ISSUE THREAD

**Issue by damnthefall** [MotorolaMobilityLLC/kernel-msm#625]
### Build ID

U1TGN34.42-86

### Additional

Requesting kernel source, techpacks, and anything else required to build the latest Android 14 kernel for genevn. Thanks in advance for your assistance.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1TGN34.42-86

**Comment by damnthefall** [comment]
@asbraga-motorola  thank you
