### ISSUE TITLE
Kernel Source for S3RV32.128-36-6

### ISSUE THREAD

**Issue by SyberHexen** [MotorolaMobilityLLC/kernel-msm#627]
### Build ID

S3RV32.128-36-6

### Additional

Hello,

Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola One 5G UW Ace(kievv) version: S3RV32.128-36-6

Model number: XT2113-1
Codename: KIEVV
Android: 12
Version: S3RV32.128-36-6 (latest version as of writing)
Variant: VZW

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in https://github.com/MotorolaMobilityLLC/kernel-msm/issues/516 (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S3RV32.128-36-6
