### ISSUE TITLE
Kernel Source for U3UOC34.49-29-1

### ISSUE THREAD

**Issue by AnandSuresh02** [MotorolaMobilityLLC/kernel-msm#629]
### Build ID

U3UOC34.49-29-1

### Additional

Hello,

Please release the kernel tree, device tree and all the necessary audio/video/display techpack for Motorola Moto g85 5G(malmo) version: U3UOC34.49-29-1

Model number: XT2427-4
Codename: malmo
Android: 14
Version: U3UOC34.49-29-1 (latest version as of writing)

While processing this request, please take care to include all of the repositories that correspond to ones such as mentioned in [#516](https://github.com/MotorolaMobilityLLC/kernel-msm/issues/516) (referenced just as example of what sort of repo's from the tree appear to be easy to miss during a GPL release)

**Comment by lingsen92** [comment]
version released: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U3UOC34.49-29-1

**Comment by Shagunk99** [comment]
shagun@9PM7OMM0:~/kernel-msm-MMI-U3UOC34.49-29-1/kernel-msm-MMI-U3UOC34.49-29-1$ ls arch
Kconfig  alpha  arc  arm

**Comment by tmhakim** [comment]
Where is the git history for this kernel source?!

**Comment by AnandSuresh02** [comment]
> Where is the git history for this kernel source?!

Check the tags instead of the release package
