### ISSUE TITLE
Source request for Lux (Moto x Play)

### ISSUE THREAD

**Issue by viinicius** [MotorolaMobilityLLC/kernel-msm#63]
Hello, can you please release the sources for MPD24.65-18 ?

**Comment by charleseb** [comment]
Hi viinicius,

This tag is in our pipeline.
We'll post that tag soon.

Thanks,
Charles

**Comment by piratenpanda** [comment]
btw, you should talk more to your support people it seems.. https://twitter.com/piratenpanda/status/686228467793412096

**Comment by piratenpanda** [comment]
How soon is soon? ;)

**Comment by charleseb** [comment]
Hi piratenpanda,

I think I can release it in a few days.

Thanks,
Charles
Em 5 de fev de 2016 5:25 AM, "piratenpanda" notifications@github.com
escreveu:

**Comment by charleseb** [comment]
Hi all,

The tag MMI-MPD24.65-25.1 has been released to GitHub.

Thanks,
Charles

**Comment by piratenpanda** [comment]
So this is the same as osprey?
