### ISSUE TITLE
Kernel Source for Astro RPLS31.Q2-63-10-2-9

### ISSUE THREAD

**Issue by Fraaxius** [MotorolaMobilityLLC/kernel-msm#632]
### Build ID

RPLS31.Q2-63-10-2-9

### Additional

Hello, Moto Team.

Could you please release the latest sources for the Kernel (and usual techpacks, modules, device trees, etc)
for the Motorola One Fusion (astro / XT2073-2)? Thanks in advance.

**Comment by asbraga-motorola** [comment]
Code for RPLS31.Q2-63-10-2-9 is already released, please see https://github.com/MotorolaMobilityLLC/kernel-msm/issues/515

For other releases, could you please open a new issue with the exact build id you want?
