### ISSUE TITLE
[GPL Request] Kernel Source for Moto G51 5G [S2RYA32.58-13-12-5-9]

### ISSUE THREAD

**Issue by Temhur** [MotorolaMobilityLLC/kernel-msm#633]
### Build ID

Can you please release the latest source for the Kernel for Motorola Moto G51 5G [cypfq].
The build id: **S2RYA32.58-13-12-5-9**

Thanks

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RYA32.58-13-12-5-9
