### ISSUE TITLE
Kernel Source for U1TPNS34.26-78-6-1

### ISSUE THREAD

**Issue by aldo-mcs** [MotorolaMobilityLLC/kernel-msm#634]
### Build ID

U1TPNS34.26-78-6-1

### Additional

Please provide the Kernel, Device, Vendor, and similar trees as well as driver packages that would be used in the development for building LineageOS 21. 

Variant: RETUS
Phone: Motorola Moto G 5G 2023
Carrier: Boost Mobile
Build: U1TPNS34.26-78-6-1 
Android Vers: 14

**Comment by JuanDavid006** [comment]
Android 13 version of this same device: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T1TPN33.58-68-1-2-1

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1TPNS34.26-78-6-1

**Comment by JuanDavid006** [comment]
Thank you so much. By the way, any reason why my build is only 24Mb and not 46Mb like the original? I might not be getting the proper defconfig or I'm doing something wrong...
