### ISSUE TITLE
Device Tree Source for Moto Edge 50 Fusion (U2UUI34.40-14-1)

### ISSUE THREAD

**Issue by themayankraut** [MotorolaMobilityLLC/kernel-msm#635]
### Build ID

U2UUI34.40-14-1

### Additional

Need device tree for building custom rom for the device.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U2UUI34.40-14-1
