### ISSUE TITLE
Kernel Modules and Device Tree Source for U3UX34.56-29-2

### ISSUE THREAD

**Issue by Kendrenogen** [MotorolaMobilityLLC/kernel-msm#636]
### Build ID

U3UX34.56-29-2

### Additional

I noticed that the main kernel source code for arcfox (Motorola RAZR 50 Ultra) build U3UX34.56-29-2 and for some of the modules are uploaded. Can you do the same for the modules that do not have the source code as well as the device tree source code? I will be using it to build custom kernels and ROMs for this device. Thank you.

**Comment by chenyt9** [comment]
@Kendrenogen ,
you can refer to devicetree repo:
filter on dashboard:
https://github.com/MotorolaMobilityLLC?q=devicetree&type=all&language=&sort=
https://github.com/orgs/MotorolaMobilityLLC/repositories?language=&q=kernel&sort=&type=all
and find each repo:
Like: https://github.com/MotorolaMobilityLLC/kernel-devicetree/releases/tag/MMI-U3UX34.56-29-2
