### ISSUE TITLE
Kernel Source for S2RYAS32.58-13-12-5-1-7

### ISSUE THREAD

**Issue by 734j** [MotorolaMobilityLLC/kernel-msm#638]
### Build ID

S2RYAS32.58-13-12-5-1-7

Thanks

### Additional
Please release the kernel sources along with device-trees, kernel modules, etc.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RYAS32.58-13-12-5-1-7
