### ISSUE TITLE
Source request for Merlin (Moto G Turbo Edition)

### ISSUE THREAD

**Issue by omerjerk** [MotorolaMobilityLLC/kernel-msm#64]
Hi,
I plan to develop on Moto G Turbo Edition.
By when can we expect the kernel source for this device to be available ?

**Comment by luca020400** [comment]
I think the kernel tree for merlin is MMI-MPI24.65-24 tag ( marshmallow ) ( msm8916 and msm8939 shares the same kernel tree )
@tags07

**Comment by omerjerk** [comment]
So which exactly which defconfig should I use ?

**Comment by luca020400** [comment]
I couldn't find a proper config for marlin
Probably they have to release it yet

EDIT: nvm :)

**Comment by tags07** [comment]
MPI24.65-24:  msm8916-perf_defconfig

If you tell me what tag you are looking for, I can tell you the defconfig
or if the tag is still in our pipeline..

**Comment by omerjerk** [comment]
@tags07 
So just reconfirming, I should use `msm8916-perf_defconfig` at the tag `MPI24.65-24` for building the kernel for Moto G Turbo Edition ?

**Comment by luca020400** [comment]
If you are running MPI24.65-24 build yes
Otherwise provide your build version

**Comment by tags07** [comment]
MPI24.65-24 is for osprey and you can use msm8916-perf_defconfig  for
defconfig. If you are looking for merlin, I am checking..we may have posted
Lollipop release but Android M may be in pipeline..

**Comment by omerjerk** [comment]
I think this should do. :)
Thanks for the help.
P.S. My build version is MPD24.65-22
