### ISSUE TITLE
Kernel Source for Motorola Edge 30 (dubai) - U1RD34.80-40

### ISSUE THREAD

**Issue by Fraaxius** [MotorolaMobilityLLC/kernel-msm#641]
### Request

Hello! :)

Could you please release the latest sources for the Kernel (and usual techpacks, modules, device trees, etc) for the Motorola Edge 30 5G (dubai / XT2203-1)? Thanks in advance.

**Comment by ThEMarD** [comment]
I would also like this kernel source code release please as we would be using it for AOSP on LineageOS custom ROM

**Comment by Fraaxius** [comment]
Bump @asbraga-motorola @mbissaromoto

**Comment by npjohnson** [comment]
Tagging in here I need this as well!

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1RD34.80-40
