### ISSUE TITLE
Update Kernel Source for Cypfq S2RYAS32.58-13-12-5-1-7

### ISSUE THREAD

**Issue by gooosedev** [MotorolaMobilityLLC/kernel-msm#642]
### Build ID

build id : S2RYAS32.58-13-12-5-1-7

can you publish as well the usual device-trees, techpacks, modules, ...

### Additional

can you also please publish the builds instructions as per:
MotorolaMobilityLLC/readme#64

Also does this device supports the user-settable root of trust  (as described here https://source.android.com/docs/security/features/verifiedboot/device-state#user-settable-root-of-trust) ?

Thanks in advance.

**Comment by gooosedev** [comment]
Bump

**Comment by asbraga-motorola** [comment]
The code is already published (https://github.com/MotorolaMobilityLLC/kernel-msm/issues/638) in https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-S2RYAS32.58-13-12-5-1-7

Regarding the other question, this forum is primarily for requesting open source code publication. Maybe you can find the information you need in other Moto forums:
https://forums.lenovo.com/t5/Motorola-Community/ct-p/MotorolaCommunity
https://forums.lenovo.com/t5/MOTOROLA-Android-Developer-Community/bd-p/230
