### ISSUE TITLE
Kernel Source for ULA34.89-100-7 (Moto G04)

### ISSUE THREAD

**Issue by InverseAxle** [MotorolaMobilityLLC/kernel-msm#645]
### Build ID

Build ID: ULA34.89-100-7

Device: Moto G04 (XT2421-2)

Please publish all pertinent source code, device tree, and modules

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-sprd/releases/tag/MMI-ULA34.89-100-7
