### ISSUE TITLE
Kernel Devicetree for QPIS30.28-Q3-28-26-4-1-7

### ISSUE THREAD

**Issue by qaotyk** [MotorolaMobilityLLC/kernel-msm#647]
### Build ID

Need kernel devicetree source for QPIS30.28-Q3-28-26-4-1-7. Include relevant missing source tag.

Need repo kernel_devicetree

### Additional

I need this kernel devicetree for update kernel source.

**Comment by asbraga-motorola** [comment]
Code already published. See #473

For devicetrees, look for the tag MMI-QPIS30.28-Q3-28-26-4-1-7 in the other repos under https://github.com/MotorolaMobilityLLC, such as:

- motorola-kernel-modules
- vendor-cirrus-audio-dlkm
- vendor-fci-dtvdriver
- vendor-qcom-opensource-audio-kernel
- vendor-qcom-opensource-data-kernel
- vendor-qcom-opensource-wlan-fw-api
- vendor-qcom-opensource-wlan-qca-wifi-host-cmn
- vendor-qcom-opensource-wlan-qcacld-3.0

**Comment by qaotyk** [comment]
I need tag for kernel_devicetree.

https://github.com/MotorolaMobilityLLC/kernel-devicetree/releases/tag/MMI-QPIS30.28-Q3-28-26-4-1-7 was missing.

Need dts source files for QPIS30.28-Q3-28-26-4-1-7. There is not tag related to sm6125 chipset (such as sofia, sofiar, sofiap, sofiap_sprout, rav, doha).
