### ISSUE TITLE
Kernel Source for S3RWS32.138-29-5-9

### ISSUE THREAD

**Issue by c3l3si4n** [MotorolaMobilityLLC/kernel-msm#649]
### Build ID

S3RWS32.138-29-5-9

### Additional

Looking forward to manually compile KernelSU into it

**Comment by asbraga-motorola** [comment]
This code is for a more recent publication:
https://github.com/MotorolaMobilityLLC/kernel-mtk/releases/tag/MMI-S3RWS32.138-29-5-11
(https://github.com/MotorolaMobilityLLC/kernel-mtk/issues/133)
