### ISSUE TITLE
disregard

### ISSUE THREAD

**Issue by louisrousseau** [MotorolaMobilityLLC/kernel-msm#65]
Something isn't quite right with that branch... Missing commits on what was pushed?

**Comment by charleseb** [comment]
Hi Louis,

I'm responsible for this release. I'm checking what is going on.

Thanks,
Charles
Em 13 de fev de 2016 8:39 PM, "Louis Rousseau" notifications@github.com
escreveu:

**Comment by louisrousseau** [comment]
That was a PEBKAC: a rebased commit shows the original commit date as last update on GitHub's "main" repo page. Made it look like the last update was from late 2012 instead of last November which can be seen on the "commits" page.

**Comment by charleseb** [comment]
Hi Louis,

Thank you for checking.

Charles.
