### ISSUE TITLE
Kernel Source for U1UGS34.23-110-2-1(Motorola g45 5G)

### ISSUE THREAD

**Issue by quickfixdemon** [MotorolaMobilityLLC/kernel-msm#650]
### Build ID

Build ID: U1UGS34.23-110-2-1
Please publish all related source code, device tree source(dts), and modules

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1UGS34.23-110-2-1
