### ISSUE TITLE
Kernel Source for U1SJ34.2-92-10 (Motorola Edge 30 Fusion / tundra)

### ISSUE THREAD

**Issue by ThEMarD** [MotorolaMobilityLLC/kernel-msm#653]
### Build ID

U1SJ34.2-92-10

### Additional

We will be using this for the AOSP known as LineageOS as we already support berlin, berlna, dubai and xpeng and are thinking of adding tundra to that list too

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U1SJ34.2-92-10

**Comment by yetanotherguyx2** [comment]
I was trying to compile this kernel several times and it always says it's the source tree is not clean. I ran 'make mrproper' several times.
It always returns the same error that the source is not clean

Anyhelp be friendly, I'm a noob.

**Comment by ThEMarD** [comment]
> I was trying to compile this kernel several times and it always says it's the source tree is not clean. I ran 'make mrproper' several times. It always returns the same error that the source is not clean
> 
> Anyhelp be friendly, I'm a noob.

Please check the readme repo. If there isn't a readme for tundra you can do a new issue there to request it

https://github.com/MotorolaMobilityLLC/readme
