### ISSUE TITLE
Kernel Source for U3UW34.67-65

### ISSUE THREAD

**Issue by aviskumar** [MotorolaMobilityLLC/kernel-msm#654]
### Build ID

U3UW34.67-65

**Comment by aviskumar** [comment]
Can you release the kernel source as well as all  the device tree sources, kernel modules, and any other sources that is used by this build?

Can you also release the source of the kernel_platform script and build tools as well like some other OEMs?

**Comment by aviskumar** [comment]
There has been an update so it would be good if the sources are latest. build id = U3UWS34.67-65-1

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-U3UWS34.67-65-1
