### ISSUE TITLE
Kernel Source for T2SDS33.75-38-1-3-18

### ISSUE THREAD

**Issue by VenusIsJaded** [MotorolaMobilityLLC/kernel-msm#656]
### Build ID

T2SDS33.75-38-1-3-18

### Additional

Please release the kernel sources along with device-trees, kernel modules, etc.

**Comment by asbraga-motorola** [comment]
Code published: https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-T2SDS33.75-38-1-3-18
