### ISSUE TITLE
Kernel source request for Moto X Pure/Style February security update  (MPHS24.49-18-3)

### ISSUE THREAD

**Issue by HashBang173** [MotorolaMobilityLLC/kernel-msm#66]
This version has rolled out to many devices now, but no kernel source is available yet

**Comment by charleseb** [comment]
Hi @HashBang173,

This version is in our pipeline and it will be released in a few days.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi @HashBang173,

The version MMI-MPHS24.49-18-3 has been released to Github.

Thanks,
Charles
