### ISSUE TITLE
Kernel source request for Moto E 2015 (surnia) - MPI24.65-39

### ISSUE THREAD

**Issue by ramsudharsan** [MotorolaMobilityLLC/kernel-msm#67]
This version has rolled out to many devices now, but no kernel source is available yet.

**Comment by charleseb** [comment]
Hi Ramsudharsan,

This version is in our pipeline and I'll release this tag in a few days.

Thanks,
Charles
Em 28 de fev de 2016 12:41 PM, "Ramsudharsan" notifications@github.com
escreveu:

**Comment by charleseb** [comment]
Hi Ramsudharsan,

The version MMI-MPI24.65-39 has been released to github.

Thanks,
Charles

**Comment by ramsudharsan** [comment]
Thanks a lot! :v:
