### ISSUE TITLE
Provide Camera API v2 support for lux

### ISSUE THREAD

**Issue by piratenpanda** [MotorolaMobilityLLC/kernel-msm#69]
Don't know if this is the right place but it'd be very nice if lux could capture raw images etc.

**Comment by awheeler-mmi** [comment]
Hey, ping the product support pages [here](https://mobilesupport.lenovo.com/us/en/).  Thanks!

**Comment by piratenpanda** [comment]
A simple no would have been sufficient. Product support pages, well..
