### ISSUE TITLE
Firmware and kernel source for my moto g (2014)

### ISSUE THREAD

**Issue by dirttech** [MotorolaMobilityLLC/kernel-msm#7]
Can anyone please suggest me kernel source link with relative firmware link and def config file to compile that kernel? I have tried various combinations but get mismatched partition size error while flashing kernel. However kernel works fine if i load it in the memory and boot from there using - 
fastboot boot myboot.img

**Comment by savoca** [comment]
cat arch/arm/configs/ext_config/titan-defconfig.config >> arch/arm/configs/msm8226_defconfig

**Comment by dirttech** [comment]
@savoca Can you please suggest me kernel source and firmware to use? I am confused about co-relation between them.

**Comment by rabih** [comment]
For what device?

**Comment by dirttech** [comment]
@somcom3x For 2nd Gen Moto G

**Comment by dirttech** [comment]
@savoca The thing is - I want to add usb serial FTDI driver to it. And defconfig file you suggested don't let me do it. IS there any solution?

**Comment by rabih** [comment]
@dirttech 
The latest release for the titan is under the kitkat-4.4.4-release-titan branch name in the kernel-msm project.

**Comment by dirttech** [comment]
@somcom3x  Actually i used that. But while flashing kernel it throws "mismatch partition size" error. I used msm8226_defconfig file for compiling. Can you suggest me the Firmware to use with this version? I used RETAILSDSDALL_XT1068-4.4.4-KXB21.85-14_cid7_CFC_SVC.xml.

**Comment by luca020400** [comment]
"mismatch partition size" error isn't an important error as this is caused by the different size of the image
Probably they used a different flag and the size of the kernel is less than your build

**Comment by pirpi** [comment]
Even I have downloaded kernel-msm-MMI-KXB21.85-24.tar.gz for moto G 2014. Then I have build that kernel after adding usb serial driver. But size is coming lesser than required. Anyhow I managed to run the newly created boot.img. But now my sound is not working. No sound at all from the device. It is showing following error when I check with dmesg. 

" failed to instantiate card msm8226-tapan9302-snd-card : -22 " and " failed to init SLIMBUS_0_RX  : -22 "

Could you please help me with this?

Thanks 
pirpi
