### ISSUE TITLE
Marshmallow Kernel source for titan

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#70]
I can't find a defconfig in the Kernel source. Please be Patient. I am new to this.

**Comment by luca020400** [comment]
@tags07 You might add a readme with the guide to build the kernel for titan aswell
@cmd1084 the main defconfig is arch/arm/configs/msm8226_defconfig and the extconfig is arch/arm/configs/ext_config/titan-defconfig.config. Combine them with
cat arch/arm/configs/ext_config/titan-defconfig.config >> arch/arm/configs/msm8226_defconfig
make msm8226_defconfig
make

**Comment by ghost** [comment]
Thank you luca

**Comment by tags07** [comment]
We are working on generating a standalone build instruction with each posting. Stay tuned. That should simplify things.

**Comment by luca020400** [comment]
@tags07 nice idea, it will help a lot of users
