### ISSUE TITLE
How do I compile moto x style?

### ISSUE THREAD

**Issue by Janer1** [MotorolaMobilityLLC/kernel-msm#71]
It's giving me error makefile 803 multiple targets error when I try to use the make command

**Comment by charleseb** [comment]
Hi Janer1,

I'll work to release it in a few hours.

Thanks,
Charles

**Comment by Janer1** [comment]
Work to release what ?

**Comment by charleseb** [comment]
Hi Janer1,

I'll release the readme file with the kernel compile instructions.

Thanks,
Charles
Em 20 de mai de 2016 12:58 PM, "Janer1" notifications@github.com escreveu:

**Comment by charleseb** [comment]
Hi Janer1,

Please check the instructions at
https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-MPH24.49-20.txt

Thanks,
Charles

**Comment by Janer1** [comment]
Thank you
