### ISSUE TITLE
Kernel source request for Moto MAXX (quark) MM

### ISSUE THREAD

**Issue by 18712886438** [MotorolaMobilityLLC/kernel-msm#72]
Looking forward to the MM kernel source of quark. Thx. :+1:

**Comment by tags07** [comment]
Could you post the System Version and Build Number of the sources you are looking for?

**Comment by 18712886438** [comment]
@tags07 MPG24.107-70.1  android 6.0

**Comment by tags07** [comment]
Currently all commits leading upto MPG24.107-70.2 is in our pipeline. We'll
start rolling them out in the coming weeks.

**Comment by 18712886438** [comment]
@tags07  thanks :)

**Comment by 18712886438** [comment]
@tags07    any update？

**Comment by charleseb** [comment]
Hi CallMESuper,

I'm still working on this tag. It will be released soon.

Thanks,
Charles

**Comment by 18712886438** [comment]
@charleseb  Thx  :+1:

**Comment by charleseb** [comment]
Hi CallMESuper,

The version MMI-MPG24.107-70.2 is released to Github.

https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-MPG24.107-70.2

Thanks,
Charles
