### ISSUE TITLE
Kernel source code for Moto G4 Plus

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/kernel-msm#73]
Please release the kernel source code for Motorola G4 Plus(Athene).

**Comment by tags07** [comment]
Please post the System Version/Build Number of the device SW and we'll post the source soon.

**Comment by ghost** [comment]
@tags07 
Build Number : MPJ24.139-23.1
Android Version : 6.0.1
Codename : Athene

**Comment by tags07** [comment]
Thankyou, currently posting all commits leading up to MPJ24.139-23.4 is in the works. Stay tuned.

**Comment by ghost** [comment]
@tags07 Thanks :) We are waiting

**Comment by ghost** [comment]
@tags07 Any update on this item?

**Comment by charleseb** [comment]
Hi Yeshwanth,

I'm working to release this version and it will be available in a few days.

Thanks,
Charles
Em 31 de mai de 2016 6:38 AM, "Yeshwanth V Shenoy" notifications@github.com
escreveu:

**Comment by ghost** [comment]
@charleseb thanks :+1:

**Comment by pranav01** [comment]
@tags07  Any update with release?

**Comment by charleseb** [comment]
Hi Pranav,

I'm still working on this version. It will be released soon.

Thanks,
Charles

**Comment by ghost** [comment]
Thanks. Closing the issue now.

**Comment by ghost** [comment]
@charleseb Could you please point out which defconfig is used for compiling the stock kernel? Is it msm8916_defconfig or msm_defconfig? There seems to be commits related to msm8952 under msm_defconfig.

**Comment by charleseb** [comment]
Hi Yeshwanth,

I'm working to release the readme file with the compile process related to
this tag. It will be released soon.

Thanks,
Charles

**Comment by ghost** [comment]
@charleseb Thanks! I tried to compile my own kernel but it ended up in bootloops and stuck on moto boot logo. Could be great if you can provide a README for this! Thanks!

**Comment by ramsudharsan** [comment]
@charleseb @tags07 Is this the right way to handle? 
https://github.com/ramsudharsan/android_kernel_motorola_msm8952/commit/91242f4c18799ab73d5031fcd75d06bf1f6e8ef7

**Comment by C-Aniruddh** [comment]
@yeshwanthvshenoy you could pull the kernel config from a running device.

`adb pull /proc/config.gz`

**Comment by HelllGuest** [comment]
@yeshwanthvshenoy  unpack stock boot image and use extract-ikconfig (from kernel_dir/scripts) to get stock defconfig. eg: ./extract-ikconfig zImage > stock_defconfig . rename stock_defconfig to .config and compile.
