### ISSUE TITLE
Kernel source for Motorola Moto G4 Plus (athene)

### ISSUE THREAD

**Issue by C-Aniruddh** [MotorolaMobilityLLC/kernel-msm#74]
Kindly push the kernel source code corresponding to Moto G4 Plus (athene) (sd617, msm8952).
@charleseb

**Comment by tags07** [comment]
Please post the System Version/Build Number of the device and we'll post the sources soon.

**Comment by C-Aniruddh** [comment]
The build ID is : MPJ24.139-23.1 @tags07

**Comment by tags07** [comment]
Thankyou, currently posting all commits leading up to MPJ24.139-23.4 is in the works. Stay tuned.

**Comment by C-Aniruddh** [comment]
I'm glad! :)

**Comment by rajeshdubey293** [comment]
Kindly push the kernel source code corresponding to Moto G4 Plus (athene) (sd617, msm8952,build id NPJS25.93-14-4)
