### ISSUE TITLE
kernel mm 6.0.1  kinzie 

### ISSUE THREAD

**Issue by thomisus** [MotorolaMobilityLLC/kernel-msm#76]
Hi, could you push kernel for kinzie xt1580 mm 6.0.1

build: MPK24.107-54
mm: 6.0.1

I read last year there should be a kernel-build how to guide. How is going?

ty very much

**Comment by charleseb** [comment]
Hi thomisus,

I'm working to release this tag and the how to build readme file. It will
be available in a few days.

Thanks,
Charles

**Comment by thomisus** [comment]
Ty very much

**Comment by charleseb** [comment]
Hi @thomisus,

Please see this version at [MMI-MPK24.107-54](https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-MPK24.107-54)
