### ISSUE TITLE
MM 6.0.1 for clark

### ISSUE THREAD

**Issue by dirty-hank** [MotorolaMobilityLLC/kernel-msm#77]
Hi there

Would you please push the latest kernel source for clark (MM 6.0.1)?

Thank you!

**Comment by chrmhoffmann** [comment]
Yes, please release this.

Chris

**Comment by chrmhoffmann** [comment]
Any news?

Chris

**Comment by charleseb** [comment]
Hi Chris,

Could you inform the version you want, please?

Thanks,
Charles

Em 28 de ago de 2016 3:09 PM, "chrmhoffmann" notifications@github.com
escreveu:

**Comment by chrmhoffmann** [comment]
Charles,

That would be
MM 6.0.1 firmware - MPHS 24.107-58 - RETEU

Chris

**Comment by charleseb** [comment]
Hi chrmhoffmann,

I'm working to release this version. It will be released in a few days.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi @chrmhoffmann,

The version [MMI-MPH27.107-58](https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-MPH24.107-58) has been released to Github.
