### ISSUE TITLE
falcon GPE 5.1 latest kernel source

### ISSUE THREAD

**Issue by TalAloni** [MotorolaMobilityLLC/kernel-msm#78]
Hi, can you update the falcon gpe release to the latest one (LMY47M.M005)?
Thanks

**Comment by charleseb** [comment]
Hi @TalAloni,

The version LMY47M.M005 has been released to Github
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-LMY47M.M005

Thanks,
Charles
