### ISSUE TITLE
Source built zImage (or) DT fails to boot (Athene)

### ISSUE THREAD

**Issue by ashwinr64** [MotorolaMobilityLLC/kernel-msm#80]
Using prebuilt DT and Zimage built out of 'marshmallow-6.0.1-release-athene' branch , it fails to boot the stock ROM which has the release number 'MPJ24.139-13.1' . It was built with GCC 4.9 . 
Also,
While using a combination of prebuilt ZImage and Source built DT , phone stays at Moto Logo.
Source to dtbtool: https://github.com/CyanogenMod/android_device_qcom_common/tree/cm-13.0/dtbtool
I tried diffing the prebuilt DT image and my source built dt image ,They both are extremely different.I wonder if you were using a dtbtool slightly deviated from CodeAurora .If so, kindly share the code.

P.S: I'm not able to log anything.Kindly help.

@charleseb @tags07

**Comment by luca020400** [comment]
cat arch/arm/configs/ext_config/moto-msm8916.config >> arch/arm/configs/msm8916-perf_defconfig  
make msm8916-perf_defconfig
make dtbs
I just created dt.img locally and it's exactly the same as the one shipped in moto boot.img ( apparently)

**Comment by ghost** [comment]
@luca020400 I tried what you mentioned but I ended up with something else when doing the make msm8916-perf_defconfig itself. Here is what happened : http://pastebin.com/8R4X33R0

**Comment by luca020400** [comment]
You need to clone motorola-kernel in $kernel_tree_path/../.

**Comment by ghost** [comment]
Ahhh okay, I guess we missed that. Cool! Thanks! :)

**Comment by ashwinr64** [comment]
F2fs code in motorola-kernel has been imported to the kernel, so motorola-kernel is not needed in my case.

**Comment by luca020400** [comment]
@tags07 @charleseb can you release the dtbTool used in official athene builds? 
@ashwinr64 athene isn't using a standard dt.img format, there is a extra field ( hence the the /wrong/ 259 version )

**Comment by ashwinr64** [comment]
That's what I was precisely saying. Kindly update us, Motorola developers ....

**Comment by charleseb** [comment]
Hi Ashwin, Luca and all

You can reach the prebuilt dtbTool related to version MMI-MPJ24.139-23.4 at
https://github.com/MotorolaMobilityLLC/readme/tree/master/dtbtool_MMI-MPJ24.139-23.4

Thanks,
Charles

**Comment by luca020400** [comment]
@charleseb any plan to release the source code? The difference between caf and moto is relatively small, I don't think there is any reason to share it as prebuilt

**Comment by charleseb** [comment]
Hi Luca,

As a temporary solution I've pushed the prebuilt version so you can get
back to hacking.
I'm still working on the process to release the source code, once I get it
concluded I'll push to github.

Thanks,
Charles

**Comment by ashwinr64** [comment]
Thanks for the hospitality @charleseb !

**Comment by ashwinr64** [comment]
Is this still on @charleseb ?

**Comment by charleseb** [comment]
Hi Ashwin,

I'm still working to release this code. I'll update in a few days.

Thanks,
Charles

**Comment by ashwinr64** [comment]
That's nice to hear @charlesb . Waiting for the same.

**Comment by Vachounet** [comment]
Does the new N release needs an update dtbtool ?

Builded a fresh boot : 
    -If i try to flash it with fastboot, error : Too many links
    -If i try to boot it with fastboot, stuck at Moto logo
    -If a try to use dd, it just soft brick my device.

Something i missed here ?


**Edit:** as @ashwinr64 tells me, it tried with 6.0.1 dt image, and it worked. I mean, i can flash and boot.

**Comment by rahulsnair** [comment]
i have checked too. Gets the same error.

**Comment by charleseb** [comment]
Hi all,

You can use this prebuilt dtbTool at https://github.com/MotorolaMobilityLLC/readme/tree/master/dtbtool_MMI-NPJ25.93-11

Thanks,
Charles

**Comment by Vachounet** [comment]
Thanks @charleseb
