### ISSUE TITLE
Droid X/ Verizon griffin source

### ISSUE THREAD

**Issue by CunningLogic** [MotorolaMobilityLLC/kernel-msm#82]
Can someone push the relevant branch for this device please

Linux localhost 3.18.24-perf-g4f3d148-00001-g2c82a6a #1 SMP PREEMPT Fri Jun 10 20:55:29 CDT 2016 aarch64

**Comment by luk1337** [comment]
You likely want to post build description / fingerprint too. Otherwise someone will reply to this after 2 weeks asking you to do so...

**Comment by CunningLogic** [comment]
thanks
ro.bootimage.build.fingerprint motorola/griffin_verizon/griffin:6.0.1/MCL24.203-22/24:user/release-keys
ro.build.description griffin_verizon-user 6.0.1 MCL24.203-22 24 release-keys
ro.build.fingerprint motorola/griffin_verizon/griffin:6.0.1/MCL24.203-22/24:user/release-keys

**Comment by CunningLogic** [comment]
dup

**Comment by charleseb** [comment]
Hi all,

Version MMI-MCL24.203-22 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-MCL24.203-22
