### ISSUE TITLE
Marshmallow kernel souce of moto z 

### ISSUE THREAD

**Issue by 18712886438** [MotorolaMobilityLLC/kernel-msm#84]
Hello, I am looking forward to the kernel source of moto z .
griffin_retcn-userdebug 6.0.1 mcc24.223 1122 intcfg

Thx  :)

**Comment by charleseb** [comment]
HI CallMESuper,

I'm working to release this version. It will be available in a few days.

Thanks,
Charles

**Comment by 18712886438** [comment]
HI Charles
how about the source of griffin now
:p

**Comment by charleseb** [comment]
Hi CallMESuper,

The process to release that version is almost concluded. I'll release the
code soon.

Thanks,
Charles

Em 19 de set de 2016 10:47 PM, "CallMESuper" notifications@github.com
escreveu:

**Comment by charleseb** [comment]
Hi all,

The version MMI-MCC24.246-37 has been released to Github.

Thanks,
Charles
