### ISSUE TITLE
when release kernel source for Moto z play?

### ISSUE THREAD

**Issue by wzsx150** [MotorolaMobilityLLC/kernel-msm#87]
hi,
would you release the kernel source for Moto z play?
the version is motorola/addison_retcn/addison:6.0.1/MCN24.104-35.2/1:user/release-keys

thank you very much!

**Comment by charleseb** [comment]
Hi @wzsx150,

I've just released https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-MPN24.104-44.
We are working to release MCN24.104-35.2 
I'll push such version in a few days.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi @wzsx150,

This version is in our pipeline to be released.
I'll release this version in a few days.

---

Thanks,
Charles

**Comment by wzsx150** [comment]
@charleseb thanks.

**Comment by charleseb** [comment]
Hi @wzsx150,

The version MCN24.104-35.2 has been released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-MCN24.104-35.2

Thanks,
Charles
