### ISSUE TITLE
Build number naming scheme

### ISSUE THREAD

**Issue by shawnwahi** [MotorolaMobilityLLC/kernel-msm#88]
@charleseb Can you please explain the build number naming scheme for Motorola/Moto firmwares.

For example the Moto Z's build number is MCC24.246-37. How was that number formed? What does each part mean.

Thanks,
Shawn

**Comment by awheeler-mmi** [comment]
Hey Shawn,

They are mostly meaningless letters and numbers outside of Motorola.  M
stands for marshmallow, while CC represents the internal baseline/build
permutation. 24.246-37 is the major.minor-build version number.

-andrew

**Comment by shawnwahi** [comment]
Thank you :)
