### ISSUE TITLE
Release kernel source code for Clark nougat

### ISSUE THREAD

**Issue by larmyv** [MotorolaMobilityLLC/kernel-msm#89]
Hello, when will you release the kernel source code for Clark nougat?

Thanks

**Comment by invisiblek** [comment]
You imply clark has a nougat release....

**Comment by larmyv** [comment]
Yes, is there a nougat release coming? If so, will you release the kernel source code?
On Oct 26, 2016 3:34 PM, Dan Pasanen notifications@github.com wrote:You imply clark has a nougat release....

**Comment by shawnwahi** [comment]
Nougat hasn't been officially released for any Motorola device. As far as I know the only devices which even have a soak test are the Moto G4 Plus and Moto Z. Plus Motorola has already confirmed the only devices to get Nougat officially before the end of 2016 are the Moto G4 and Moto Z series.

**Comment by larmyv** [comment]
OK thank you for replying.
