### ISSUE TITLE
Motorola ringtone

### ISSUE THREAD

**Issue by Subinsmani** [MotorolaMobilityLLC/kernel-msm#91]
Hai i want motorola flashable ringtone... Plaese will u give me...

**Comment by Subinsmani** [comment]
hello?????

**Comment by luca020400** [comment]
What about you download the stock rom and extract it by yourself?
No one is here to upload a file for you unless it's related to the OSS  motorola software

**Comment by DevriesL** [comment]
THIS IS GITHUB, NOT YOUR MOTHER NOR YOUR TEACHER.
USE GOOGLE FOR THIS KIND OF QUESTIONS, DO NO BE LIKE A CHILD.

**Comment by neobuddy89** [comment]
@motorolamobility Please close this request.
