### ISSUE TITLE
Share the source code of VoLTE Of Moto G 2015 (Osprey)

### ISSUE THREAD

**Issue by iankitkulkarni** [MotorolaMobilityLLC/kernel-msm#92]
Hi, 
Please share the source code of VoLTE Of Moto G 2015 (osprey) to implement enhanced 4G ( calls over LTE network).. Enhanced 4G (calls over LTE) is needed because of the new service provider JIO.. It works perfectly fine on Stock Android, but doens't work on Custom ROMs like Cyanogenmod.. I asked the maintainer to get implemented VoLTE in Cyanogenmod rom.. but the source code is not shared by Motorola with us to implement VoLTE in custom roms.. please share and help us..

**Comment by luca020400** [comment]
Come on ... Not again ...

**Comment by iankitkulkarni** [comment]
This is the most wanted feature for us..

**Comment by iankitkulkarni** [comment]
Ok.. tell me the technical difficulties.. we will sort out..

**Comment by luca020400** [comment]
Or maybe just check the other issues about VOLTE? #90 for example

**Comment by iankitkulkarni** [comment]
Who can implement VoLTE feature in custom rom? Rom mainter or Motorola?

**Comment by luca020400** [comment]
Stock supports volte > yes it can be implemented in custom roms ( maybe, it doesn't always work )
Stock doesn't support volte > you can't

**Comment by iankitkulkarni** [comment]
Stock supports volte > yes it can be implemented in custom roms ( maybe, it doesn't always work )

Then why devs are not working on it?

**Comment by luca020400** [comment]
Maybe they tried and it didn't work? Motorola may be using custom libs/apks that aren't compatible with the open source Android framework
Or maybe it doesn't just work?

If you really want volte try to add it by yourself

**Comment by iankitkulkarni** [comment]
I don't know how to add it.. I need someone who knows it..

**Comment by luca020400** [comment]
What if they tried and failed? We "devs" aren't magically able to fix everything

**Comment by iankitkulkarni** [comment]
They should troubleshoot the issue as it is the most important topic in India..

**Comment by luca020400** [comment]
You know that we don't work for you?
We work on custom roms in our free time as a hobby

Anyway close this issue

**Comment by rabih** [comment]
I guess GitHub is no longer our safe haven...

**Comment by iankitkulkarni** [comment]
I know and I respect all devs who work for us.. But the issue is also important.. please understand it.. anyways I am closing this issue now..

**Comment by luca020400** [comment]
@somcom3x sadly, it isn't anymore :(
