### ISSUE TITLE
GPL source request for Moto Z Droid

### ISSUE THREAD

**Issue by HashBang173** [MotorolaMobilityLLC/kernel-msm#94]
There is currently no GPL source available for the Moto Z Droid, for version NCL25.86-11

**Comment by shawnwahi** [comment]
I second that @charleseb

**Comment by charleseb** [comment]
Hi Shawn, HashBang173,

I’m starting the process to release this version. It will be released in a few days.

----
Thanks,
Charles

**Comment by charleseb** [comment]
Hi all,

Version MMI-NCL25.86-11 released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-NCL25.86-11

Thanks,
Charles
