### ISSUE TITLE
rst_cmdbuff pointer initialized after being used if LOWPOWER_ALLOWED == 1

### ISSUE THREAD

**Issue by jmartinesp** [MotorolaMobilityLLC/kernel-msm#95]
Hello, I was playing a bit with my Moto X Force trying to make IR sensors work when screen off to wake the device, and I thought the `LOWPOWER_ALLOWED` constant might be related to wake IRQs.

Anyway, when I set it to `1`, the phone just got stuck in a bootloop, so I decided to take a look at the last kernel log and I found something related to a null pointer. After taking a good look, I found [this](https://github.com/MotorolaMobilityLLC/kernel-msm/blob/marshmallow-6.0.1-release-kinzie/drivers/misc/moto-sensorhub/motosh_reset.c#L128):

```
unsigned char *rst_cmdbuff; // <--- Pointer declared
int mutex_locked = 0;

dev_dbg(&motosh_misc_data->client->dev,
	 "motosh_reset_and_init %d\n", (int)mode);
pdata = motosh_misc_data->pdata;
motosh_misc_data->in_reset_and_init = true;
wake_lock(&motosh_misc_data->reset_wakelock);

if (mode == START_RESET) {
	/* Mode will transition to NORMALMODE after
	   hub reports its init is complete */
	motosh_misc_data->mode = UNINITIALIZED;
	motosh_reset(pdata, rst_cmdbuff); // <--- Pointer used
	wake_unlock(&motosh_misc_data->reset_wakelock);
	return ret_err;
}

/* INIT */
rst_cmdbuff = kmalloc(512, GFP_KERNEL); // <--- Pointer actually allocated

if (rst_cmdbuff == NULL) {
	wake_unlock(&motosh_misc_data->reset_wakelock);
	return -ENOMEM;
}
```

And that would crash [here](https://github.com/MotorolaMobilityLLC/kernel-msm/blob/marshmallow-6.0.1-release-kinzie/drivers/misc/moto-sensorhub/motosh_core.c#L419):

```
cmdbuff[0] = LOWPOWER_REG;
```

Or in one of the several lines where that pointer is accessed.

**Comment by awheeler-mmi** [comment]
Thanks!  I opened an internal bug about this.
