### ISSUE TITLE
Kernel Relseased request for latest Quark Verizon Motorola Droid Turbo (MCG24.251-5)

### ISSUE THREAD

**Issue by fgl27** [MotorolaMobilityLLC/kernel-msm#97]
Please released the source for latest Marshmallow ROM for the Verizon Motorola Droid Turbo (MCG24.251-5)

	ro.build.id=MCG24.251-5
	ro.build.description=quark_verizon-user 6.0.1 MCG24.251-5 9 release-keys
	ro.build.fingerprint=motorola/quark_verizon/quark:6.0.1/MCG24.251-5/9:user/release-keys
	ro.build.version.full=Blur_Version.24.81.5.quark_verizon.verizon.en.US

If need any other ROM description let me know, thanks.

**Comment by charleseb** [comment]
Hi @bhb27,

The version MMI-MCG24.251-5 has been released.
https://github.com/MotorolaMobilityLLC/kernel-msm/releases/tag/MMI-MCG24.251-5

Thanks,
Charles
